// Words for the lawyers' hub. Six languages, like every public page on the site.
export default {
  en: {
    purchase_costs_t: 'Buying costs by region',
    purchase_costs_d: 'Transfer tax, IVA or IGIC and stamp duty for any region, taxed slice by slice where the region uses bands, with a buyer handout in seven languages.',
    purchase_costs_cta: 'Work out the taxes',
    poa_planner_t: 'Power of attorney planner',
    poa_planner_d: 'For a client who cannot come to sign: consulate or local notary with apostille, the steps in order, the powers to name, and a client letter.',
    poa_planner_cta: 'Plan the power',
    s_estate: 'Inheritance',
    s_estate_d: 'Which law governs the estate, which tax rules non-resident heirs can choose, and what to file by when.',
    inheritance_roadmap_t: 'Inheritance roadmap',
    inheritance_roadmap_d: 'EU choice of law, the regional option for non-resident heirs, deadlines as real dates, the document list and a letter to the heirs.',
    inheritance_roadmap_cta: 'Build the roadmap',
    up_lau: 'A rental contract checker: deposits, minimum terms and who pays the agency fee',
    eyebrow: 'For lawyers in Spain',
    h1: 'Sourced answers your international clients can check',
    body: 'Free tools on the taxes, deadlines and rights foreign owners ask about most. Send them to clients in their own language, and use the branded checklist on live transactions.',
    bueno_body: 'These tools are built with Bueno, the platform that looks after Spanish accounts, payments and paperwork for foreign property owners.',
    bueno_referral: 'Using the tools never passes your client to anyone. If you ever want to introduce a client to Bueno, you decide when, and any arrangement is agreed with you in writing first.',
    note: 'Practical guidance for property professionals. Not legal or tax advice.',

    s_deal: 'Transactions',
    s_deal_d: 'A branded checklist for a live sale, and the seller’s tax position with every date calculated from completion.',
    s_tax: 'Tax, deadlines and stays',
    s_tax_d: 'Non-resident returns, late filing and the 90 day rule, each figure linked to the provision it comes from.',
    s_rights: 'Disputes and rights',
    s_rights_d: 'Limitation periods, insurance cover and defects, for clients who need to know where they stand before they call you.',

    deal_checklist_t: 'Sale readiness checklist',
    deal_checklist_d: 'Answer a few questions about a live sale. Get the tasks, who owns each one, the dates that follow from completion, and a letter for your client.',
    deal_checklist_cta: 'Build a checklist',

    upcoming_t: 'Planned next for lawyers',
    upcoming_d: 'These are the next tools on the list for this section.',
    up_nota: 'Reading a nota simple with a foreign client',
  },
  no: {
    purchase_costs_t: 'Kjøpskostnader per region',
    purchase_costs_d: 'Dokumentavgift, IVA eller IGIC og stempelavgift for alle regioner, trinn for trinn der regionen har trinnskala, med et ark til kjøperen på sju språk.',
    purchase_costs_cta: 'Regn ut skattene',
    poa_planner_t: 'Planlegger for fullmakt',
    poa_planner_d: 'For kunder som ikke kan komme og signere: konsulat eller lokal notar med apostille, stegene i rekkefølge, fullmaktene som bør nevnes og et brev til kunden.',
    poa_planner_cta: 'Planlegg fullmakten',
    s_estate: 'Arv',
    s_estate_d: 'Hvilken lov som gjelder arven, hvilke skatteregler arvinger i utlandet kan velge, og hva som må leveres når.',
    inheritance_roadmap_t: 'Veikart for arv',
    inheritance_roadmap_d: 'EUs lovvalg, regionvalget for arvinger i utlandet, frister som faktiske datoer, dokumentlisten og et brev til arvingene.',
    inheritance_roadmap_cta: 'Lag veikartet',
    up_lau: 'Kontroll av leiekontrakter: depositum, minste leietid og hvem som betaler meglerhonoraret',
    eyebrow: 'For advokater i Spania',
    h1: 'Svar med kilder som dine internasjonale klienter kan sjekke',
    body: 'Gratis verktøy om skattene, fristene og rettighetene utenlandske eiere spør mest om. Send dem til klienter på deres eget språk, og bruk sjekklisten med ditt brevhode på pågående transaksjoner.',
    bueno_body: 'Verktøyene er laget sammen med Bueno, plattformen som tar seg av spanske konti, betalinger og papirarbeid for utenlandske boligeiere.',
    bueno_referral: 'Når du bruker verktøyene, gis klienten din aldri videre til noen. Vil du en dag introdusere en klient for Bueno, bestemmer du når, og en eventuell avtale inngås skriftlig med deg først.',
    note: 'Praktisk veiledning for eiendomsprofesjonelle. Ikke juridisk rådgivning eller skatterådgivning.',

    s_deal: 'Transaksjoner',
    s_deal_d: 'En sjekkliste med ditt brevhode for et pågående salg, og selgerens skatteposisjon med hver dato regnet fra overtakelsen.',
    s_tax: 'Skatt, frister og opphold',
    s_tax_d: 'Skattemeldinger for ikke-residenter, sen levering og 90-dagersregelen, med hvert tall knyttet til bestemmelsen det kommer fra.',
    s_rights: 'Konflikter og rettigheter',
    s_rights_d: 'Foreldelsesfrister, forsikringsdekning og mangler, for klienter som vil vite hvor de står før de ringer deg.',

    deal_checklist_t: 'Sjekkliste for salget',
    deal_checklist_d: 'Svar på noen spørsmål om et pågående salg. Få oppgavene, hvem som eier hver av dem, datoene som følger av overtakelsen og et brev til klienten.',
    deal_checklist_cta: 'Lag en sjekkliste',

    upcoming_t: 'Neste verktøy for advokater',
    upcoming_d: 'Dette er de neste verktøyene på listen for denne delen.',
    up_nota: 'Å lese en nota simple sammen med en utenlandsk klient',
  },
  sv: {
    purchase_costs_t: 'Köpkostnader per region',
    purchase_costs_d: 'Överlåtelseskatt, IVA eller IGIC och stämpelskatt för alla regioner, steg för steg där regionen har trappsteg, med ett blad till köparen på sju språk.',
    purchase_costs_cta: 'Räkna ut skatterna',
    poa_planner_t: 'Planerare för fullmakt',
    poa_planner_d: 'För kunder som inte kan komma och skriva under: konsulat eller lokal notarie med apostille, stegen i ordning, befogenheterna att nämna och ett brev till kunden.',
    poa_planner_cta: 'Planera fullmakten',
    s_estate: 'Arv',
    s_estate_d: 'Vilken lag som gäller arvet, vilka skatteregler arvingar utomlands kan välja och vad som ska lämnas in när.',
    inheritance_roadmap_t: 'Färdplan för arv',
    inheritance_roadmap_d: 'EU:s lagval, regionvalet för arvingar utomlands, frister som verkliga datum, dokumentlistan och ett brev till arvingarna.',
    inheritance_roadmap_cta: 'Skapa färdplanen',
    up_lau: 'Granskning av hyresavtal: deposition, minsta hyrestid och vem som betalar mäklararvodet',
    eyebrow: 'För advokater i Spanien',
    h1: 'Svar med källor som dina internationella klienter kan kontrollera',
    body: 'Gratis verktyg om de skatter, frister och rättigheter utländska ägare frågar mest om. Skicka dem till klienter på deras eget språk och använd checklistan med ditt brevhuvud i pågående affärer.',
    bueno_body: 'Verktygen är byggda tillsammans med Bueno, plattformen som sköter spanska konton, betalningar och pappersarbete för utländska fastighetsägare.',
    bueno_referral: 'När du använder verktygen lämnas din klient aldrig vidare till någon. Vill du någon gång presentera en klient för Bueno bestämmer du när, och en eventuell överenskommelse görs skriftligt med dig först.',
    note: 'Praktisk vägledning för fastighetsproffs. Inte juridisk rådgivning eller skatterådgivning.',

    s_deal: 'Affärer',
    s_deal_d: 'En checklista med ditt brevhuvud för en pågående försäljning, och säljarens skatteläge med varje datum räknat från tillträdet.',
    s_tax: 'Skatt, frister och vistelser',
    s_tax_d: 'Deklarationer för icke-residenter, sen inlämning och 90-dagarsregeln, med varje siffra kopplad till bestämmelsen den kommer från.',
    s_rights: 'Konflikter och rättigheter',
    s_rights_d: 'Preskriptionstider, försäkringsskydd och fel i fastigheten, för klienter som vill veta var de står innan de ringer dig.',

    deal_checklist_t: 'Checklista inför tillträdet',
    deal_checklist_d: 'Svara på några frågor om en pågående affär. Få uppgifterna, vem som äger varje uppgift, datumen som följer av tillträdet och ett brev till klienten.',
    deal_checklist_cta: 'Skapa en checklista',

    upcoming_t: 'Nästa verktyg för advokater',
    upcoming_d: 'Det här är nästa verktyg på listan för den här delen.',
    up_nota: 'Att läsa en nota simple tillsammans med en utländsk klient',
  },
  de: {
    purchase_costs_t: 'Kaufnebenkosten nach Region',
    purchase_costs_d: 'Grunderwerbsteuer, IVA oder IGIC und Urkundensteuer für jede Region, bei Stufentarifen Stufe für Stufe berechnet, mit einem Käufer-Merkblatt in sieben Sprachen.',
    purchase_costs_cta: 'Steuern berechnen',
    poa_planner_t: 'Vollmacht-Planer',
    poa_planner_d: 'Für Kunden, die nicht zur Unterschrift kommen können: Konsulat oder örtlicher Notar mit Apostille, die Schritte in Reihenfolge, die Befugnisse und ein Kundenbrief.',
    poa_planner_cta: 'Vollmacht planen',
    s_estate: 'Erbschaft',
    s_estate_d: 'Welches Recht für den Nachlass gilt, welche Steuerregeln nicht ansässige Erben wählen können und was bis wann einzureichen ist.',
    inheritance_roadmap_t: 'Fahrplan für den Nachlass',
    inheritance_roadmap_d: 'EU-Rechtswahl, die Regionaloption für nicht ansässige Erben, Fristen als echte Daten, die Dokumentenliste und ein Brief an die Erben.',
    inheritance_roadmap_cta: 'Fahrplan erstellen',
    up_lau: 'Mietvertrags-Check: Kaution, Mindestlaufzeit und wer die Maklerprovision zahlt',
    eyebrow: 'Für Anwälte in Spanien',
    h1: 'Belegte Antworten, die Ihre internationalen Mandanten prüfen können',
    body: 'Kostenlose Tools zu den Steuern, Fristen und Rechten, nach denen ausländische Eigentümer am häufigsten fragen. Senden Sie sie Mandanten in deren Sprache und nutzen Sie die Checkliste mit Ihrem Briefkopf bei laufenden Transaktionen.',
    bueno_body: 'Die Tools entstehen zusammen mit Bueno, der Plattform, die spanische Konten, Zahlungen und Formalitäten für ausländische Eigentümer übernimmt.',
    bueno_referral: 'Die Nutzung der Tools gibt Ihren Mandanten an niemanden weiter. Wenn Sie einen Mandanten an Bueno vermitteln möchten, entscheiden Sie wann, und jede Vereinbarung wird vorher schriftlich mit Ihnen getroffen.',
    note: 'Praktische Orientierung für Immobilienprofis. Keine Rechts- oder Steuerberatung.',

    s_deal: 'Transaktionen',
    s_deal_d: 'Eine Checkliste mit Ihrem Briefkopf für einen laufenden Verkauf und die Steuerlage des Verkäufers mit allen Fristen ab der Beurkundung.',
    s_tax: 'Steuern, Fristen und Aufenthalte',
    s_tax_d: 'Erklärungen für Nicht-Residenten, verspätete Abgabe und die 90-Tage-Regel, jede Zahl mit der Vorschrift, aus der sie stammt.',
    s_rights: 'Streitfälle und Rechte',
    s_rights_d: 'Verjährungsfristen, Versicherungsschutz und Mängel, für Mandanten, die wissen möchten, wo sie stehen, bevor sie Sie anrufen.',

    deal_checklist_t: 'Checkliste bis zur Beurkundung',
    deal_checklist_d: 'Beantworten Sie einige Fragen zu einem laufenden Verkauf. Sie erhalten die Aufgaben, die Zuständigkeiten, die Fristen ab der Beurkundung und einen Brief an Ihren Mandanten.',
    deal_checklist_cta: 'Checkliste erstellen',

    upcoming_t: 'Als Nächstes für Anwälte geplant',
    upcoming_d: 'Diese Tools stehen als Nächstes auf der Liste für diesen Bereich.',
    up_nota: 'Eine Nota simple gemeinsam mit einem ausländischen Mandanten lesen',
  },
  fr: {
    purchase_costs_t: 'Frais d’achat par région',
    purchase_costs_d: 'Droits de mutation, IVA ou IGIC et droit de timbre pour chaque région, calculés tranche par tranche si la région applique un barème, avec une fiche acheteur en sept langues.',
    purchase_costs_cta: 'Calculer les impôts',
    poa_planner_t: 'Planificateur de procuration',
    poa_planner_d: 'Pour le client qui ne peut pas venir signer : consulat ou notaire local avec apostille, les étapes dans l’ordre, les pouvoirs à citer et une lettre au client.',
    poa_planner_cta: 'Préparer la procuration',
    s_estate: 'Successions',
    s_estate_d: 'Quelle loi régit la succession, quelles règles fiscales les héritiers non résidents peuvent choisir, et quoi déposer avant quand.',
    inheritance_roadmap_t: 'Feuille de route de succession',
    inheritance_roadmap_d: 'Choix de loi européen, option régionale des héritiers non résidents, délais en dates réelles, liste des documents et lettre aux héritiers.',
    inheritance_roadmap_cta: 'Créer la feuille de route',
    up_lau: 'Un contrôle des baux : dépôt de garantie, durée minimale et qui paie les honoraires d’agence',
    eyebrow: 'Pour les avocats en Espagne',
    h1: 'Des réponses sourcées que vos clients étrangers peuvent vérifier',
    body: 'Des outils gratuits sur les impôts, les délais et les droits qui préoccupent le plus les propriétaires étrangers. Envoyez-les à vos clients dans leur langue et utilisez la check-list à votre en-tête sur les dossiers en cours.',
    bueno_body: 'Ces outils sont conçus avec Bueno, la plateforme qui prend en charge les comptes, les paiements et les démarches espagnoles des propriétaires étrangers.',
    bueno_referral: "Utiliser ces outils ne transmet jamais votre client à qui que ce soit. Si vous souhaitez un jour présenter un client à Bueno, c'est vous qui décidez du moment, et tout accord est d'abord conclu par écrit avec vous.",
    note: 'Repères pratiques pour les professionnels de l’immobilier. Pas un conseil juridique ou fiscal.',

    s_deal: 'Transactions',
    s_deal_d: 'Une check-list à votre en-tête pour une vente en cours, et la situation fiscale du vendeur avec chaque date calculée depuis la signature.',
    s_tax: 'Impôts, délais et séjours',
    s_tax_d: 'Déclarations des non-résidents, dépôt tardif et règle des 90 jours, chaque chiffre relié au texte dont il provient.',
    s_rights: 'Litiges et droits',
    s_rights_d: 'Délais de prescription, garanties d’assurance et vices, pour les clients qui veulent savoir où ils en sont avant de vous appeler.',

    deal_checklist_t: 'Check-list avant la signature',
    deal_checklist_d: 'Répondez à quelques questions sur une vente en cours. Obtenez les tâches, le responsable de chacune, les dates qui découlent de la signature et une lettre pour votre client.',
    deal_checklist_cta: 'Créer une check-list',

    upcoming_t: 'Prochains outils pour les avocats',
    upcoming_d: 'Voici les prochains outils prévus pour cette section.',
    up_nota: 'Lire une nota simple avec un client étranger',
  },
  nl: {
    purchase_costs_t: 'Aankoopkosten per regio',
    purchase_costs_d: 'Overdrachtsbelasting, IVA of IGIC en zegelrecht voor elke regio, per schijf berekend waar de regio schijven heeft, met een overzicht voor de koper in zeven talen.',
    purchase_costs_cta: 'Bereken de belastingen',
    poa_planner_t: 'Planner voor een volmacht',
    poa_planner_d: 'Voor een klant die niet kan komen tekenen: consulaat of lokale notaris met apostille, de stappen op volgorde, de bevoegdheden en een brief aan de klant.',
    poa_planner_cta: 'Volmacht plannen',
    s_estate: 'Erfenissen',
    s_estate_d: 'Welk recht de nalatenschap beheerst, welke belastingregels erfgenamen in het buitenland kunnen kiezen en wat wanneer ingediend moet zijn.',
    inheritance_roadmap_t: 'Stappenplan nalatenschap',
    inheritance_roadmap_d: 'Europese rechtskeuze, de regiokeuze voor erfgenamen in het buitenland, termijnen als echte data, de documentenlijst en een brief aan de erfgenamen.',
    inheritance_roadmap_cta: 'Stappenplan maken',
    up_lau: 'Een huurcontractcheck: borg, minimale duur en wie de makelaarscourtage betaalt',
    eyebrow: 'Voor advocaten in Spanje',
    h1: 'Onderbouwde antwoorden die uw internationale cliënten kunnen controleren',
    body: 'Gratis tools over de belastingen, termijnen en rechten waar buitenlandse eigenaren het vaakst naar vragen. Stuur ze naar cliënten in hun eigen taal en gebruik de checklist met uw briefhoofd bij lopende transacties.',
    bueno_body: 'Deze tools zijn gebouwd met Bueno, het platform dat Spaanse rekeningen, betalingen en papierwerk regelt voor buitenlandse eigenaren.',
    bueno_referral: 'Het gebruik van de tools draagt uw cliënt nooit aan iemand over. Wilt u ooit een cliënt aan Bueno voorstellen, dan bepaalt u wanneer, en elke afspraak wordt eerst schriftelijk met u gemaakt.',
    note: 'Praktische informatie voor vastgoedprofessionals. Geen juridisch of fiscaal advies.',

    s_deal: 'Transacties',
    s_deal_d: 'Een checklist met uw briefhoofd voor een lopende verkoop, en de fiscale positie van de verkoper met elke datum gerekend vanaf de overdracht.',
    s_tax: 'Belasting, termijnen en verblijf',
    s_tax_d: 'Aangiften voor niet-residenten, te late aangifte en de 90-dagenregel, elk bedrag gekoppeld aan de bepaling waar het vandaan komt.',
    s_rights: 'Geschillen en rechten',
    s_rights_d: 'Verjaringstermijnen, verzekeringsdekking en gebreken, voor cliënten die willen weten waar ze staan voordat ze u bellen.',

    deal_checklist_t: 'Checklist tot de overdracht',
    deal_checklist_d: 'Beantwoord een paar vragen over een lopende verkoop. U krijgt de taken, wie waarvoor verantwoordelijk is, de data die uit de overdracht volgen en een brief voor uw cliënt.',
    deal_checklist_cta: 'Checklist maken',

    upcoming_t: 'Hierna gepland voor advocaten',
    upcoming_d: 'Dit zijn de volgende tools op de lijst voor dit onderdeel.',
    up_nota: 'Een nota simple lezen met een buitenlandse cliënt',
  },
};
