// Screen text for the power of attorney planner, in the site's six languages. The plan is
// in plan.js (English and Spanish), the client letter in seven languages.
const C = (o) => o;
export default {
  en: C({
    title: 'Power of attorney planner', note: 'Guidance for property professionals. Not legal advice.',
    eyebrow: 'For lawyers and agents', headline: 'Signing from abroad without a wasted month',
    body: 'Where the client lives, what the power is for, and whether they can reach a Spanish consulate. You get the route to take, each step in order, the powers the document should name, and a letter to the client in their language.',
    points: ['Consulate or local notary with apostille, compared for the client’s country', 'The powers to include for each purpose', 'A client letter in seven languages'],
    cta: 'Plan the power', minutes: 'About a minute',
    q_country: 'Where will the client sign?', q_purposes: 'What is the power for?', q_purposes_hint: 'Tick everything it must cover.',
    q_consulate: 'Can the client get to a Spanish consulate?', c_yes: 'Yes', c_no: 'No', c_unsure: 'Not sure',
    q_language: 'In which language will the document be?', l_spanish: 'Spanish', l_bilingual: 'Bilingual, with Spanish', l_other: 'Another language only',
    purpose_buy: 'Buying a property', purpose_sell: 'Selling a property', purpose_inherit: 'An inheritance', purpose_mortgage: 'A mortgage', purpose_nie: 'Getting an NIE', purpose_bank: 'Bank accounts', purpose_taxes: 'Taxes',
    f_client: 'Client name (optional)', f_doclang: 'Plan language', f_letterlang: 'Letter language',
    country_other: 'Another country',
    countries: { Norway: 'Norway', Sweden: 'Sweden', Germany: 'Germany', France: 'France', Netherlands: 'Netherlands', 'United Kingdom': 'United Kingdom', Belgium: 'Belgium', Denmark: 'Denmark', Finland: 'Finland', Ireland: 'Ireland', Switzerland: 'Switzerland', 'United States': 'United States', Italy: 'Italy', Poland: 'Poland' },
    preferred: 'Recommended', print: 'Print or save as PDF', copy_letter: 'Copy the letter', copied: 'Copied',
    letter_t: 'Letter to the client', sources_t: 'Where the rules come from',
    need: 'Choose the country and at least one purpose.',
  }),
  no: C({
    title: 'Planlegger for fullmakt', note: 'Veiledning for eiendomsprofesjonelle. Ikke juridisk rådgivning.',
    eyebrow: 'For advokater og meglere', headline: 'Signering fra utlandet uten en bortkastet måned',
    body: 'Hvor kunden bor, hva fullmakten gjelder, og om kunden kan komme til et spansk konsulat. Du får ruten, hvert steg i rekkefølge, fullmaktene dokumentet bør nevne og et brev til kunden på kundens språk.',
    points: ['Konsulat eller lokal notar med apostille, sammenlignet for kundens land', 'Fullmaktene som bør med for hvert formål', 'Et brev til kunden på sju språk'],
    cta: 'Planlegg fullmakten', minutes: 'Omtrent ett minutt',
    q_country: 'Hvor skal kunden signere?', q_purposes: 'Hva gjelder fullmakten?', q_purposes_hint: 'Kryss av for alt den må dekke.',
    q_consulate: 'Kan kunden komme seg til et spansk konsulat?', c_yes: 'Ja', c_no: 'Nei', c_unsure: 'Usikker',
    q_language: 'På hvilket språk blir dokumentet?', l_spanish: 'Spansk', l_bilingual: 'Tospråklig, med spansk', l_other: 'Bare et annet språk',
    purpose_buy: 'Kjøp av bolig', purpose_sell: 'Salg av bolig', purpose_inherit: 'Arv', purpose_mortgage: 'Boliglån', purpose_nie: 'NIE-nummer', purpose_bank: 'Bankkonti', purpose_taxes: 'Skatt',
    f_client: 'Kundens navn (valgfritt)', f_doclang: 'Språk for planen', f_letterlang: 'Språk for brevet',
    country_other: 'Et annet land',
    countries: { Norway: 'Norge', Sweden: 'Sverige', Germany: 'Tyskland', France: 'Frankrike', Netherlands: 'Nederland', 'United Kingdom': 'Storbritannia', Belgium: 'Belgia', Denmark: 'Danmark', Finland: 'Finland', Ireland: 'Irland', Switzerland: 'Sveits', 'United States': 'USA', Italy: 'Italia', Poland: 'Polen' },
    preferred: 'Anbefalt', print: 'Skriv ut eller lagre som PDF', copy_letter: 'Kopier brevet', copied: 'Kopiert',
    letter_t: 'Brev til kunden', sources_t: 'Hvor reglene kommer fra',
    need: 'Velg land og minst ett formål.',
  }),
  sv: C({
    title: 'Planerare för fullmakt', note: 'Vägledning för fastighetsproffs. Inte juridisk rådgivning.',
    eyebrow: 'För advokater och mäklare', headline: 'Underteckna från utlandet utan en förlorad månad',
    body: 'Var kunden bor, vad fullmakten gäller och om kunden kan ta sig till ett spanskt konsulat. Du får vägen att välja, varje steg i ordning, befogenheterna dokumentet bör nämna och ett brev till kunden på kundens språk.',
    points: ['Konsulat eller lokal notarie med apostille, jämfört för kundens land', 'Befogenheterna som behövs för varje syfte', 'Ett brev till kunden på sju språk'],
    cta: 'Planera fullmakten', minutes: 'Ungefär en minut',
    q_country: 'Var ska kunden skriva under?', q_purposes: 'Vad gäller fullmakten?', q_purposes_hint: 'Kryssa i allt den måste täcka.',
    q_consulate: 'Kan kunden ta sig till ett spanskt konsulat?', c_yes: 'Ja', c_no: 'Nej', c_unsure: 'Osäker',
    q_language: 'På vilket språk blir dokumentet?', l_spanish: 'Spanska', l_bilingual: 'Tvåspråkigt, med spanska', l_other: 'Bara ett annat språk',
    purpose_buy: 'Köp av bostad', purpose_sell: 'Försäljning av bostad', purpose_inherit: 'Arv', purpose_mortgage: 'Bolån', purpose_nie: 'NIE-nummer', purpose_bank: 'Bankkonton', purpose_taxes: 'Skatter',
    f_client: 'Kundens namn (valfritt)', f_doclang: 'Planens språk', f_letterlang: 'Brevets språk',
    country_other: 'Ett annat land',
    countries: { Norway: 'Norge', Sweden: 'Sverige', Germany: 'Tyskland', France: 'Frankrike', Netherlands: 'Nederländerna', 'United Kingdom': 'Storbritannien', Belgium: 'Belgien', Denmark: 'Danmark', Finland: 'Finland', Ireland: 'Irland', Switzerland: 'Schweiz', 'United States': 'USA', Italy: 'Italien', Poland: 'Polen' },
    preferred: 'Rekommenderas', print: 'Skriv ut eller spara som PDF', copy_letter: 'Kopiera brevet', copied: 'Kopierat',
    letter_t: 'Brev till kunden', sources_t: 'Var reglerna kommer ifrån',
    need: 'Välj land och minst ett syfte.',
  }),
  de: C({
    title: 'Vollmacht-Planer', note: 'Orientierung für Immobilienprofis. Keine Rechtsberatung.',
    eyebrow: 'Für Anwälte und Makler', headline: 'Aus dem Ausland unterschreiben, ohne einen Monat zu verlieren',
    body: 'Wo der Kunde lebt, wofür die Vollmacht ist und ob er ein spanisches Konsulat erreicht. Sie erhalten den Weg, jeden Schritt in Reihenfolge, die Befugnisse, die das Dokument nennen sollte, und einen Brief an den Kunden in seiner Sprache.',
    points: ['Konsulat oder örtlicher Notar mit Apostille, verglichen für das Land des Kunden', 'Die Befugnisse für jeden Zweck', 'Ein Kundenbrief in sieben Sprachen'],
    cta: 'Vollmacht planen', minutes: 'Etwa eine Minute',
    q_country: 'Wo unterschreibt der Kunde?', q_purposes: 'Wofür ist die Vollmacht?', q_purposes_hint: 'Kreuzen Sie alles an, was sie abdecken muss.',
    q_consulate: 'Kann der Kunde ein spanisches Konsulat erreichen?', c_yes: 'Ja', c_no: 'Nein', c_unsure: 'Unklar',
    q_language: 'In welcher Sprache wird das Dokument sein?', l_spanish: 'Spanisch', l_bilingual: 'Zweisprachig, mit Spanisch', l_other: 'Nur eine andere Sprache',
    purpose_buy: 'Kauf einer Immobilie', purpose_sell: 'Verkauf einer Immobilie', purpose_inherit: 'Eine Erbschaft', purpose_mortgage: 'Eine Hypothek', purpose_nie: 'NIE beantragen', purpose_bank: 'Bankkonten', purpose_taxes: 'Steuern',
    f_client: 'Name des Kunden (optional)', f_doclang: 'Sprache des Plans', f_letterlang: 'Sprache des Briefs',
    country_other: 'Ein anderes Land',
    countries: { Norway: 'Norwegen', Sweden: 'Schweden', Germany: 'Deutschland', France: 'Frankreich', Netherlands: 'Niederlande', 'United Kingdom': 'Vereinigtes Königreich', Belgium: 'Belgien', Denmark: 'Dänemark', Finland: 'Finnland', Ireland: 'Irland', Switzerland: 'Schweiz', 'United States': 'Vereinigte Staaten', Italy: 'Italien', Poland: 'Polen' },
    preferred: 'Empfohlen', print: 'Drucken oder als PDF speichern', copy_letter: 'Brief kopieren', copied: 'Kopiert',
    letter_t: 'Brief an den Kunden', sources_t: 'Woher die Regeln stammen',
    need: 'Wählen Sie das Land und mindestens einen Zweck.',
  }),
  fr: C({
    title: 'Planificateur de procuration', note: 'Repères pour les professionnels de l’immobilier. Pas un conseil juridique.',
    eyebrow: 'Pour les avocats et les agents', headline: 'Signer depuis l’étranger sans perdre un mois',
    body: 'Où vit le client, à quoi sert la procuration et s’il peut se rendre dans un consulat d’Espagne. Vous obtenez la voie à suivre, chaque étape dans l’ordre, les pouvoirs à mentionner et une lettre au client dans sa langue.',
    points: ['Consulat ou notaire local avec apostille, comparés pour le pays du client', 'Les pouvoirs à inclure pour chaque objet', 'Une lettre client en sept langues'],
    cta: 'Préparer la procuration', minutes: 'Environ une minute',
    q_country: 'Où le client signera-t-il ?', q_purposes: 'À quoi sert la procuration ?', q_purposes_hint: 'Cochez tout ce qu’elle doit couvrir.',
    q_consulate: 'Le client peut-il se rendre dans un consulat d’Espagne ?', c_yes: 'Oui', c_no: 'Non', c_unsure: 'Pas sûr',
    q_language: 'Dans quelle langue sera le document ?', l_spanish: 'Espagnol', l_bilingual: 'Bilingue, avec l’espagnol', l_other: 'Une autre langue seulement',
    purpose_buy: 'Achat d’un bien', purpose_sell: 'Vente d’un bien', purpose_inherit: 'Une succession', purpose_mortgage: 'Un prêt immobilier', purpose_nie: 'Obtenir un NIE', purpose_bank: 'Comptes bancaires', purpose_taxes: 'Impôts',
    f_client: 'Nom du client (facultatif)', f_doclang: 'Langue du plan', f_letterlang: 'Langue de la lettre',
    country_other: 'Un autre pays',
    countries: { Norway: 'Norvège', Sweden: 'Suède', Germany: 'Allemagne', France: 'France', Netherlands: 'Pays-Bas', 'United Kingdom': 'Royaume-Uni', Belgium: 'Belgique', Denmark: 'Danemark', Finland: 'Finlande', Ireland: 'Irlande', Switzerland: 'Suisse', 'United States': 'États-Unis', Italy: 'Italie', Poland: 'Pologne' },
    preferred: 'Recommandé', print: 'Imprimer ou enregistrer en PDF', copy_letter: 'Copier la lettre', copied: 'Copié',
    letter_t: 'Lettre au client', sources_t: 'D’où viennent les règles',
    need: 'Choisissez le pays et au moins un objet.',
  }),
  nl: C({
    title: 'Planner voor een volmacht', note: 'Informatie voor vastgoedprofessionals. Geen juridisch advies.',
    eyebrow: 'Voor advocaten en makelaars', headline: 'Tekenen vanuit het buitenland zonder een verloren maand',
    body: 'Waar de klant woont, waarvoor de volmacht is en of de klant een Spaans consulaat kan bereiken. U krijgt de te volgen route, elke stap op volgorde, de bevoegdheden die het document moet noemen en een brief aan de klant in diens taal.',
    points: ['Consulaat of lokale notaris met apostille, vergeleken voor het land van de klant', 'De bevoegdheden voor elk doel', 'Een klantbrief in zeven talen'],
    cta: 'Volmacht plannen', minutes: 'Ongeveer een minuut',
    q_country: 'Waar tekent de klant?', q_purposes: 'Waarvoor is de volmacht?', q_purposes_hint: 'Vink alles aan wat erin moet.',
    q_consulate: 'Kan de klant een Spaans consulaat bereiken?', c_yes: 'Ja', c_no: 'Nee', c_unsure: 'Weet niet',
    q_language: 'In welke taal wordt het document?', l_spanish: 'Spaans', l_bilingual: 'Tweetalig, met Spaans', l_other: 'Alleen een andere taal',
    purpose_buy: 'Aankoop van een woning', purpose_sell: 'Verkoop van een woning', purpose_inherit: 'Een erfenis', purpose_mortgage: 'Een hypotheek', purpose_nie: 'Een NIE aanvragen', purpose_bank: 'Bankrekeningen', purpose_taxes: 'Belastingen',
    f_client: 'Naam van de klant (optioneel)', f_doclang: 'Taal van het plan', f_letterlang: 'Taal van de brief',
    country_other: 'Een ander land',
    countries: { Norway: 'Noorwegen', Sweden: 'Zweden', Germany: 'Duitsland', France: 'Frankrijk', Netherlands: 'Nederland', 'United Kingdom': 'Verenigd Koninkrijk', Belgium: 'België', Denmark: 'Denemarken', Finland: 'Finland', Ireland: 'Ierland', Switzerland: 'Zwitserland', 'United States': 'Verenigde Staten', Italy: 'Italië', Poland: 'Polen' },
    preferred: 'Aanbevolen', print: 'Afdrukken of als pdf opslaan', copy_letter: 'Brief kopiëren', copied: 'Gekopieerd',
    letter_t: 'Brief aan de klant', sources_t: 'Waar de regels vandaan komen',
    need: 'Kies het land en minstens één doel.',
  }),
};
