// All user-facing framing text for the utility setup planner. Item text and the "why"
// behind each item live in steps.js, next to the logic that decides whether the item
// applies at all. Same dot-path API as useT. Other locales fall back to en.
export default {
  en: {
    eyebrow: 'Free tool',
    headline: 'Get the utilities on, in the order they have to happen',
    body: 'Power, water, gas, internet and the council charge are five separate processes with five different counters, and two of them cannot start until something else is finished. This puts your six answers in order and tells you what each one needs.',
    points: [
      'Six questions, then an ordered list you can print',
      'Shows what is blocked, and by what',
      'The document pack, the contact, and the bill each one creates',
    ],
    cta: 'Build my order of play',
    minutes: 'About a minute',

    q_stage: 'Where are you with the property?',
    q_stage_hint: 'The work is the same either way. The order changes, and so does who you can still ask for documents.',
    stage_buying: 'I am buying, or I have just completed',
    stage_buying_d: 'The supplies are still in the seller name, or just moved',
    stage_owner: 'I already own it',
    stage_owner_d: 'Something is already set up and I am changing or fixing it',

    q_supply: 'What is the state of the supplies today?',
    q_supply_hint: 'If nobody has been to the property recently, say so. Guessing here is what produces a wasted month.',
    supply_live: 'Connected and working',
    supply_live_d: 'There is power and water at the property now',
    supply_dormant: 'Connected, but the property has been empty a long time',
    supply_dormant_d: 'The meters are there. Whether the supply is still live is the question.',
    supply_off: 'Cut off, or never connected',
    supply_off_d: 'Nothing at the meter, or no meter at all',
    supply_unknown: 'I do not know yet',
    supply_unknown_d: 'Nobody has been to check',

    q_nie: 'Do you have your NIE?',
    q_nie_hint: 'The NIE is the Spanish foreigner identity number. It is the number a supply contract is issued against, so it decides how much of this list you can start.',
    nie_have: 'Yes, I have the certificate',
    nie_applied: 'Applied for, still waiting',
    nie_none: 'Not yet',

    q_account: 'Do you have a Spanish account for the bills?',
    q_account_hint: 'Almost everything here is paid by direct debit, and several providers offer no other method.',
    account_spanish: 'Yes, a Spanish account in my name',
    account_foreign: 'I have a euro account, but not a Spanish one',
    account_foreign_d: 'A euro IBAN issued outside Spain',
    account_none: 'No, not yet',

    q_type: 'What kind of property is it?',
    q_type_hint: 'It changes who you talk to, and whether some of these are yours to contract at all.',
    type_apartment: 'Apartment',
    type_apartment_d: 'In a block, with a community of owners',
    type_villa: 'House or villa',
    type_villa_d: 'On its own plot, in or near a town',
    type_rural: 'Rural or isolated',
    type_rural_d: 'Outside the village network, or in the campo',

    q_plan: 'Take over what is there, or switch supplier?',
    q_plan_hint: 'There is a right order to this, and doing it the other way round is how people lose the supply.',
    plan_takeover: 'Take over what is already there',
    plan_takeover_d: 'Fastest, and the supply stays live',
    plan_switch: 'I want to switch supplier',
    plan_switch_d: 'Better tariff, or a provider who deals with me in my language',
    plan_unsure: 'I have not decided',

    result_nie: 'Start with the NIE. Everything below waits on it.',
    result_nie_sub: 'Electricity, water and gas contracts are issued to a named person with a Spanish identity number, and the ayuntamiento will not register a change of ownership without one. You can still gather documents and book an installer today. You cannot put anything in your name.',
    result_installer: 'Book the electrical installer first. The rest can be done from a phone.',
    result_installer_sub: 'A supply that has been off cannot be energised on a certificate nobody has issued yet, and the installer has to visit to issue one. That is the longest lead time on this page, so it goes first even though it is not the first thing anyone thinks of.',
    result_account: 'You can contract the supplies. Paying for them is the part that is not ready.',
    result_account_sub: 'Nothing here is blocked, but the direct debits are, and a supply contract with no working direct debit behind it is the version of this that fails three months from now while you are in another country.',
    result_clear: 'Nothing is blocking you. Here is the order.',
    result_clear_sub: 'You have the two things that gate the rest, so this is now a sequence rather than a wait. Work down it. The lead times are at the top and the things you can do from a phone are lower.',

    restart: 'Change my answers',

    who_title: 'Who you actually deal with',
    gates_title: 'What is blocked, and by what',

    g_gates: 'First. What everything else is waiting for',
    g_gates_note: 'None of these are utility jobs. They are the reason utility jobs fail.',
    g_folder: 'The folder you will be asked for, every single time',
    g_folder_note: 'Every supplier and the ayuntamiento ask for the same four things. Scan them once, and keep them somewhere you can reach from abroad.',
    g_elec: 'Electricity',
    g_elec_note: 'You choose the supplier and you contact them directly, by phone or online.',
    g_water: 'Water',
    g_water_note: 'The one utility you do not choose. Start at the ayuntamiento, which either bills you itself or names the company holding the concession for your street.',
    g_gas: 'Gas',
    g_gas_note: 'Only some towns have a mains supply. Where there is none, gas is a delivery contract with a local depot, not a connection.',
    g_net: 'Internet and phone',
    g_net_note: 'Nothing legal turns on this one, which is why it is down here. It is also the one with an engineer appointment, so book it around a visit.',
    g_council: 'The ayuntamiento: refuse, and everything else billed to the property',
    g_council_note: 'Nobody sends a welcome letter for this. The charge exists whether or not anyone has told you about it.',
    g_dd: 'Direct debits. This is the part that actually breaks',
    g_dd_note: 'Everything here takes minutes now and is genuinely hard to fix from another country. A returned direct debit for power is how supply gets cut off while the owner is abroad.',
    g_ongoing: 'What each of these commits you to, from now on',
    g_ongoing_note: 'Setting a supply up is a day. Keeping it is a calendar.',
  },
};
