// Screen text for the anti-money-laundering client file, in the site's six languages. The
// printed record is in aml.js, in English or Spanish.
export default {
  en: {
    title: 'Client due diligence file', note: 'A record for estate agents. Not legal advice, and not a substitute for the agency’s own procedures.',
    eyebrow: 'For estate agents', headline: 'The anti-money-laundering file, done before the deposit changes hands',
    body: 'Agents who intermediate property sales are obliged subjects under Spanish anti-money-laundering law. Answer the questions for one client and print a dated record for the file. Nothing you enter leaves this browser.',
    points: ['Tells you whether the operation is in scope', 'Flags what stops the operation and what needs enhanced checks', 'A signed record in English or Spanish'],
    cta: 'Open a file', minutes: 'About three minutes',
    s_op: 'The operation', s_client: 'The client', s_funds: 'The money', s_flags: 'Anything unusual?', s_record: 'The record',
    f_op: 'Type of operation', op_sale: 'Sale', op_lease: 'Lease',
    f_rent: 'Monthly rent in euros', f_side: 'Your client is', side_buyer: 'The buyer or tenant', side_seller: 'The seller or landlord', side_both: 'Both parties',
    f_client: 'Client name', f_property: 'Property reference or address',
    f_type: 'The client is', t_person: 'An individual', t_company: 'A company or other legal entity',
    f_id: 'Have you checked the client’s identity against a valid official document and kept a copy?',
    f_bo: 'Have you identified every person who owns more than {bo} percent of the company, or otherwise controls it?',
    f_pep: 'Is the client, a close family member or a close associate a politically exposed person?',
    yes: 'Yes', no: 'No', not_checked: 'Not checked yet',
    f_funds: 'Where does the money come from?',
    funds_mortgage: 'Mortgage', funds_savings: 'Savings', funds_sale: 'Sale of another property', funds_inheritance: 'Inheritance', funds_business: 'Business income', funds_other: 'Other',
    f_evidence: 'Have you seen evidence of that source?',
    f_payment: 'How will the price be paid?',
    pay_es_bank: 'From a Spanish account in the client’s name', pay_foreign_bank: 'From a foreign account in the client’s name', pay_cash: 'In cash', pay_third_party: 'By someone else', pay_unknown: 'Not known yet',
    flags_hint: 'Tick any that apply. These are common warning signs, not an official list.',
    flag_price_mismatch: 'Price well above or below the market without a clear reason', flag_quick_resale: 'Bought and resold within a short time', flag_reluctant: 'Reluctant to give information or documents', flag_structure: 'Complex ownership or intermediaries with no clear purpose', flag_urgency: 'Unusual urgency or indifference to price', flag_third_party: 'A third party pays or gives instructions', flag_cash: 'Cash offered for part of the price', flag_country: 'Linked to a high-risk jurisdiction',
    f_by: 'Checked by', f_doclang: 'Record language',
    print: 'Print or save as PDF', sources_t: 'Where the duties come from',
    scope_out: 'Below the rent at which agents are obliged subjects.',
    v_standard: 'Standard checks', v_enhanced: 'Enhanced review needed', v_stop: 'Do not proceed yet', v_out_of_scope: 'Outside the obligation',
  },
  no: {
    title: 'Hvitvaskingsmappe for kunden', note: 'En oversikt for eiendomsmeglere. Ikke juridisk rådgivning, og ingen erstatning for foretakets egne rutiner.',
    eyebrow: 'For eiendomsmeglere', headline: 'Hvitvaskingskontrollen, gjort før depositumet betales',
    body: 'Meglere som formidler boligsalg har plikter etter spansk hvitvaskingslov. Svar på spørsmålene for én kunde og skriv ut en datert oversikt til mappen. Ingenting du skriver forlater denne nettleseren.',
    points: ['Viser om transaksjonen omfattes', 'Viser hva som stopper saken og hva som krever skjerpede tiltak', 'En signert oversikt på engelsk eller spansk'],
    cta: 'Åpne en mappe', minutes: 'Omtrent tre minutter',
    s_op: 'Transaksjonen', s_client: 'Kunden', s_funds: 'Pengene', s_flags: 'Noe uvanlig?', s_record: 'Oversikten',
    f_op: 'Type transaksjon', op_sale: 'Salg', op_lease: 'Utleie',
    f_rent: 'Månedsleie i euro', f_side: 'Kunden din er', side_buyer: 'Kjøper eller leietaker', side_seller: 'Selger eller utleier', side_both: 'Begge parter',
    f_client: 'Kundens navn', f_property: 'Boligreferanse eller adresse',
    f_type: 'Kunden er', t_person: 'En privatperson', t_company: 'Et selskap eller annen juridisk person',
    f_id: 'Har du kontrollert kundens identitet mot gyldig offisielt dokument og tatt kopi?',
    f_bo: 'Har du identifisert alle som eier mer enn {bo} prosent av selskapet, eller kontrollerer det på annen måte?',
    f_pep: 'Er kunden, et nært familiemedlem eller en nær medarbeider en politisk eksponert person?',
    yes: 'Ja', no: 'Nei', not_checked: 'Ikke kontrollert ennå',
    f_funds: 'Hvor kommer pengene fra?',
    funds_mortgage: 'Boliglån', funds_savings: 'Sparepenger', funds_sale: 'Salg av annen eiendom', funds_inheritance: 'Arv', funds_business: 'Næringsinntekt', funds_other: 'Annet',
    f_evidence: 'Har du sett dokumentasjon på den kilden?',
    f_payment: 'Hvordan betales prisen?',
    pay_es_bank: 'Fra spansk konto i kundens navn', pay_foreign_bank: 'Fra utenlandsk konto i kundens navn', pay_cash: 'Kontant', pay_third_party: 'Av noen andre', pay_unknown: 'Ikke kjent ennå',
    flags_hint: 'Kryss av for det som passer. Dette er vanlige faresignaler, ikke en offisiell liste.',
    flag_price_mismatch: 'Pris langt over eller under markedet uten klar grunn', flag_quick_resale: 'Kjøpt og solgt igjen på kort tid', flag_reluctant: 'Uvillig til å gi opplysninger eller dokumenter', flag_structure: 'Komplisert eierskap eller mellommenn uten klart formål', flag_urgency: 'Uvanlig hastverk eller likegyldighet til pris', flag_third_party: 'En tredjepart betaler eller gir instruksjoner', flag_cash: 'Kontanter tilbudt for en del av prisen', flag_country: 'Knyttet til en høyrisikojurisdiksjon',
    f_by: 'Kontrollert av', f_doclang: 'Språk for oversikten',
    print: 'Skriv ut eller lagre som PDF', sources_t: 'Hvor pliktene kommer fra',
    scope_out: 'Under leienivået der meglere får plikter.',
    v_standard: 'Vanlige kontroller', v_enhanced: 'Skjerpet gjennomgang nødvendig', v_stop: 'Ikke gå videre ennå', v_out_of_scope: 'Utenfor plikten',
  },
  sv: {
    title: 'Penningtvättsakt för kunden', note: 'En dokumentation för fastighetsmäklare. Inte juridisk rådgivning och ingen ersättning för byråns egna rutiner.',
    eyebrow: 'För fastighetsmäklare', headline: 'Penningtvättskontrollen, klar innan handpenningen betalas',
    body: 'Mäklare som förmedlar bostadsförsäljningar har skyldigheter enligt spansk penningtvättslag. Svara på frågorna för en kund och skriv ut en daterad dokumentation till akten. Inget du skriver lämnar den här webbläsaren.',
    points: ['Visar om affären omfattas', 'Visar vad som stoppar affären och vad som kräver skärpta åtgärder', 'En signerad dokumentation på engelska eller spanska'],
    cta: 'Öppna en akt', minutes: 'Ungefär tre minuter',
    s_op: 'Affären', s_client: 'Kunden', s_funds: 'Pengarna', s_flags: 'Något ovanligt?', s_record: 'Dokumentationen',
    f_op: 'Typ av affär', op_sale: 'Försäljning', op_lease: 'Uthyrning',
    f_rent: 'Månadshyra i euro', f_side: 'Din kund är', side_buyer: 'Köpare eller hyresgäst', side_seller: 'Säljare eller hyresvärd', side_both: 'Båda parter',
    f_client: 'Kundens namn', f_property: 'Objektreferens eller adress',
    f_type: 'Kunden är', t_person: 'En privatperson', t_company: 'Ett bolag eller annan juridisk person',
    f_id: 'Har du kontrollerat kundens identitet mot en giltig officiell handling och sparat en kopia?',
    f_bo: 'Har du identifierat alla som äger mer än {bo} procent av bolaget eller på annat sätt kontrollerar det?',
    f_pep: 'Är kunden, en nära familjemedlem eller en nära medarbetare en person i politiskt utsatt ställning?',
    yes: 'Ja', no: 'Nej', not_checked: 'Inte kontrollerat än',
    f_funds: 'Var kommer pengarna ifrån?',
    funds_mortgage: 'Bolån', funds_savings: 'Sparande', funds_sale: 'Försäljning av annan fastighet', funds_inheritance: 'Arv', funds_business: 'Näringsinkomst', funds_other: 'Annat',
    f_evidence: 'Har du sett underlag för den källan?',
    f_payment: 'Hur betalas priset?',
    pay_es_bank: 'Från spanskt konto i kundens namn', pay_foreign_bank: 'Från utländskt konto i kundens namn', pay_cash: 'Kontant', pay_third_party: 'Av någon annan', pay_unknown: 'Inte känt än',
    flags_hint: 'Kryssa i det som stämmer. Det här är vanliga varningssignaler, inte en officiell lista.',
    flag_price_mismatch: 'Pris långt över eller under marknaden utan tydligt skäl', flag_quick_resale: 'Köpt och sålt igen på kort tid', flag_reluctant: 'Ovillig att lämna uppgifter eller handlingar', flag_structure: 'Komplicerat ägande eller mellanhänder utan tydligt syfte', flag_urgency: 'Ovanlig brådska eller likgiltighet för priset', flag_third_party: 'En tredje part betalar eller ger instruktioner', flag_cash: 'Kontanter erbjuds för en del av priset', flag_country: 'Kopplat till en högriskjurisdiktion',
    f_by: 'Kontrollerat av', f_doclang: 'Dokumentationens språk',
    print: 'Skriv ut eller spara som PDF', sources_t: 'Var skyldigheterna kommer ifrån',
    scope_out: 'Under den hyresnivå där mäklare får skyldigheter.',
    v_standard: 'Normala kontroller', v_enhanced: 'Skärpt granskning krävs', v_stop: 'Gå inte vidare än', v_out_of_scope: 'Utanför skyldigheten',
  },
  de: {
    title: 'Geldwäsche-Akte zum Kunden', note: 'Eine Dokumentation für Immobilienmakler. Keine Rechtsberatung und kein Ersatz für die internen Verfahren des Büros.',
    eyebrow: 'Für Immobilienmakler', headline: 'Die Geldwäscheprüfung, erledigt bevor die Anzahlung fließt',
    body: 'Makler, die Immobilienverkäufe vermitteln, sind nach spanischem Geldwäscherecht Verpflichtete. Beantworten Sie die Fragen zu einem Kunden und drucken Sie eine datierte Dokumentation für die Akte. Nichts, was Sie eingeben, verlässt diesen Browser.',
    points: ['Zeigt, ob der Vorgang erfasst ist', 'Zeigt, was den Vorgang stoppt und was verstärkte Prüfung braucht', 'Eine unterschriebene Dokumentation auf Englisch oder Spanisch'],
    cta: 'Akte anlegen', minutes: 'Etwa drei Minuten',
    s_op: 'Der Vorgang', s_client: 'Der Kunde', s_funds: 'Das Geld', s_flags: 'Etwas Ungewöhnliches?', s_record: 'Die Dokumentation',
    f_op: 'Art des Vorgangs', op_sale: 'Verkauf', op_lease: 'Vermietung',
    f_rent: 'Monatsmiete in Euro', f_side: 'Ihr Kunde ist', side_buyer: 'Käufer oder Mieter', side_seller: 'Verkäufer oder Vermieter', side_both: 'Beide Parteien',
    f_client: 'Name des Kunden', f_property: 'Objektreferenz oder Adresse',
    f_type: 'Der Kunde ist', t_person: 'Eine Privatperson', t_company: 'Eine Gesellschaft oder andere juristische Person',
    f_id: 'Haben Sie die Identität anhand eines gültigen amtlichen Dokuments geprüft und eine Kopie aufbewahrt?',
    f_bo: 'Haben Sie alle Personen identifiziert, die mehr als {bo} Prozent der Gesellschaft halten oder sie anderweitig kontrollieren?',
    f_pep: 'Ist der Kunde, ein naher Angehöriger oder eine nahestehende Person politisch exponiert?',
    yes: 'Ja', no: 'Nein', not_checked: 'Noch nicht geprüft',
    f_funds: 'Woher stammt das Geld?',
    funds_mortgage: 'Hypothek', funds_savings: 'Ersparnisse', funds_sale: 'Verkauf einer anderen Immobilie', funds_inheritance: 'Erbschaft', funds_business: 'Geschäftseinkünfte', funds_other: 'Sonstiges',
    f_evidence: 'Haben Sie Nachweise für diese Herkunft gesehen?',
    f_payment: 'Wie wird der Preis bezahlt?',
    pay_es_bank: 'Von einem spanischen Konto des Kunden', pay_foreign_bank: 'Von einem ausländischen Konto des Kunden', pay_cash: 'In bar', pay_third_party: 'Von jemand anderem', pay_unknown: 'Noch nicht bekannt',
    flags_hint: 'Kreuzen Sie Zutreffendes an. Das sind übliche Warnsignale, keine amtliche Liste.',
    flag_price_mismatch: 'Preis deutlich über oder unter dem Markt ohne klaren Grund', flag_quick_resale: 'Kurz nach dem Kauf wieder verkauft', flag_reluctant: 'Zögert, Angaben oder Unterlagen zu liefern', flag_structure: 'Komplexe Eigentumsstruktur oder Mittelsleute ohne klaren Zweck', flag_urgency: 'Ungewöhnliche Eile oder Gleichgültigkeit beim Preis', flag_third_party: 'Ein Dritter zahlt oder gibt Anweisungen', flag_cash: 'Bargeld für einen Teil des Preises angeboten', flag_country: 'Bezug zu einem Hochrisikoland',
    f_by: 'Geprüft von', f_doclang: 'Sprache der Dokumentation',
    print: 'Drucken oder als PDF speichern', sources_t: 'Woher die Pflichten stammen',
    scope_out: 'Unter der Miethöhe, ab der Makler Verpflichtete sind.',
    v_standard: 'Normale Prüfung', v_enhanced: 'Verstärkte Prüfung nötig', v_stop: 'Noch nicht fortfahren', v_out_of_scope: 'Außerhalb der Pflicht',
  },
  fr: {
    title: 'Dossier LCB du client', note: 'Un registre pour les agents immobiliers. Pas un conseil juridique, et ne remplace pas les procédures internes de l’agence.',
    eyebrow: 'Pour les agents immobiliers', headline: 'Le contrôle anti-blanchiment, fait avant le versement de l’acompte',
    body: 'Les agents qui interviennent dans des ventes immobilières sont assujettis à la loi espagnole contre le blanchiment. Répondez aux questions pour un client et imprimez un registre daté pour le dossier. Rien de ce que vous saisissez ne quitte ce navigateur.',
    points: ['Indique si l’opération est concernée', 'Signale ce qui bloque l’opération et ce qui exige des mesures renforcées', 'Un registre signé en anglais ou en espagnol'],
    cta: 'Ouvrir un dossier', minutes: 'Environ trois minutes',
    s_op: 'L’opération', s_client: 'Le client', s_funds: 'Les fonds', s_flags: 'Quelque chose d’inhabituel ?', s_record: 'Le registre',
    f_op: 'Type d’opération', op_sale: 'Vente', op_lease: 'Location',
    f_rent: 'Loyer mensuel en euros', f_side: 'Votre client est', side_buyer: 'L’acheteur ou le locataire', side_seller: 'Le vendeur ou le bailleur', side_both: 'Les deux parties',
    f_client: 'Nom du client', f_property: 'Référence ou adresse du bien',
    f_type: 'Le client est', t_person: 'Une personne physique', t_company: 'Une société ou autre personne morale',
    f_id: 'Avez-vous vérifié l’identité du client sur un document officiel valide et conservé une copie ?',
    f_bo: 'Avez-vous identifié toute personne détenant plus de {bo} pour cent de la société ou la contrôlant autrement ?',
    f_pep: 'Le client, un proche parent ou un proche associé est-il une personne politiquement exposée ?',
    yes: 'Oui', no: 'Non', not_checked: 'Pas encore vérifié',
    f_funds: 'D’où vient l’argent ?',
    funds_mortgage: 'Prêt immobilier', funds_savings: 'Épargne', funds_sale: 'Vente d’un autre bien', funds_inheritance: 'Héritage', funds_business: 'Revenus professionnels', funds_other: 'Autre',
    f_evidence: 'Avez-vous vu un justificatif de cette origine ?',
    f_payment: 'Comment le prix sera-t-il payé ?',
    pay_es_bank: 'Depuis un compte espagnol au nom du client', pay_foreign_bank: 'Depuis un compte étranger au nom du client', pay_cash: 'En espèces', pay_third_party: 'Par une autre personne', pay_unknown: 'Pas encore connu',
    flags_hint: 'Cochez ce qui s’applique. Ce sont des signaux d’alerte courants, pas une liste officielle.',
    flag_price_mismatch: 'Prix très au-dessus ou au-dessous du marché sans raison claire', flag_quick_resale: 'Acheté et revendu en peu de temps', flag_reluctant: 'Réticent à fournir informations ou documents', flag_structure: 'Détention complexe ou intermédiaires sans but clair', flag_urgency: 'Urgence inhabituelle ou indifférence au prix', flag_third_party: 'Un tiers paie ou donne des instructions', flag_cash: 'Espèces proposées pour une partie du prix', flag_country: 'Lien avec une juridiction à haut risque',
    f_by: 'Vérifié par', f_doclang: 'Langue du registre',
    print: 'Imprimer ou enregistrer en PDF', sources_t: 'D’où viennent les obligations',
    scope_out: 'Sous le loyer à partir duquel l’agent est assujetti.',
    v_standard: 'Contrôles normaux', v_enhanced: 'Examen renforcé nécessaire', v_stop: 'Ne pas continuer pour l’instant', v_out_of_scope: 'Hors obligation',
  },
  nl: {
    title: 'Witwasdossier van de klant', note: 'Een vastlegging voor makelaars. Geen juridisch advies en geen vervanging van de eigen procedures van het kantoor.',
    eyebrow: 'Voor makelaars', headline: 'Het witwasonderzoek, klaar voordat de aanbetaling wordt gedaan',
    body: 'Makelaars die bemiddelen bij woningverkoop hebben verplichtingen onder de Spaanse witwaswet. Beantwoord de vragen voor één klant en druk een gedateerde vastlegging af voor het dossier. Niets van wat u invult verlaat deze browser.',
    points: ['Laat zien of de transactie onder de plicht valt', 'Laat zien wat de transactie tegenhoudt en wat verscherpt onderzoek vraagt', 'Een ondertekende vastlegging in het Engels of Spaans'],
    cta: 'Dossier openen', minutes: 'Ongeveer drie minuten',
    s_op: 'De transactie', s_client: 'De klant', s_funds: 'Het geld', s_flags: 'Iets ongewoons?', s_record: 'De vastlegging',
    f_op: 'Soort transactie', op_sale: 'Verkoop', op_lease: 'Verhuur',
    f_rent: 'Maandhuur in euro', f_side: 'Uw klant is', side_buyer: 'De koper of huurder', side_seller: 'De verkoper of verhuurder', side_both: 'Beide partijen',
    f_client: 'Naam van de klant', f_property: 'Referentie of adres van de woning',
    f_type: 'De klant is', t_person: 'Een natuurlijk persoon', t_company: 'Een vennootschap of andere rechtspersoon',
    f_id: 'Heeft u de identiteit gecontroleerd aan de hand van een geldig officieel document en een kopie bewaard?',
    f_bo: 'Heeft u iedereen geïdentificeerd die meer dan {bo} procent van de vennootschap bezit of die op een andere manier zeggenschap heeft?',
    f_pep: 'Is de klant, een naast familielid of een naaste geassocieerde een politiek prominent persoon?',
    yes: 'Ja', no: 'Nee', not_checked: 'Nog niet gecontroleerd',
    f_funds: 'Waar komt het geld vandaan?',
    funds_mortgage: 'Hypotheek', funds_savings: 'Spaargeld', funds_sale: 'Verkoop van een andere woning', funds_inheritance: 'Erfenis', funds_business: 'Bedrijfsinkomsten', funds_other: 'Anders',
    f_evidence: 'Heeft u bewijs van die herkomst gezien?',
    f_payment: 'Hoe wordt de prijs betaald?',
    pay_es_bank: 'Vanaf een Spaanse rekening op naam van de klant', pay_foreign_bank: 'Vanaf een buitenlandse rekening op naam van de klant', pay_cash: 'Contant', pay_third_party: 'Door iemand anders', pay_unknown: 'Nog niet bekend',
    flags_hint: 'Vink aan wat van toepassing is. Dit zijn gangbare signalen, geen officiële lijst.',
    flag_price_mismatch: 'Prijs ver boven of onder de markt zonder duidelijke reden', flag_quick_resale: 'Kort na aankoop weer verkocht', flag_reluctant: 'Terughoudend met informatie of documenten', flag_structure: 'Complexe eigendomsstructuur of tussenpersonen zonder duidelijk doel', flag_urgency: 'Ongewone haast of onverschilligheid over de prijs', flag_third_party: 'Een derde betaalt of geeft instructies', flag_cash: 'Contant geld aangeboden voor een deel van de prijs', flag_country: 'Verbonden met een hoogrisicojurisdictie',
    f_by: 'Gecontroleerd door', f_doclang: 'Taal van de vastlegging',
    print: 'Afdrukken of als pdf opslaan', sources_t: 'Waar de plichten vandaan komen',
    scope_out: 'Onder de huur waarboven makelaars verplichtingen hebben.',
    v_standard: 'Normale controles', v_enhanced: 'Verscherpt onderzoek nodig', v_stop: 'Nog niet doorgaan', v_out_of_scope: 'Buiten de verplichting',
  },
};
