// Screen text for the inheritance roadmap, in the site's six languages. The roadmap itself
// is in roadmap.js (English and Spanish) and the letter to heirs in letter.js (seven).
export default {
  en: {
    title: 'Inheritance roadmap', note: 'Guidance for property professionals. Not legal or tax advice.',
    eyebrow: 'For lawyers and families', headline: 'Which law, which tax rules, and what to file by when',
    body: 'A few questions about the deceased and the heirs. You get the succession law that governs the estate, the inheritance tax rules non-resident heirs can choose, the deadlines as real dates, the documents to gather, and a letter to the heirs in their language.',
    points: ['EU choice-of-law rules applied in the right order', 'The regional option for non-resident heirs', 'Every rule shown with its source and date'],
    cta: 'Start the roadmap', minutes: 'About two minutes',
    q_residence: 'Where did the deceased habitually live at the time of death?', q_residence_hint: 'Habitual residence, not nationality and not where the holiday home is.',
    res_spain: 'In Spain', res_abroad: 'Outside Spain',
    q_deceased_region: 'In which Spanish region did the deceased live?',
    q_nationality: 'What was the deceased’s nationality?', nat_spanish: 'Spanish', nat_other: 'Another nationality',
    q_choice: 'Did a will choose the law of the deceased’s nationality?', q_choice_hint: 'Look for a clause saying the succession is governed by the law of their country. Spanish forced heirship depends on it.',
    ch_yes: 'Yes, the will chooses it', ch_no: 'No, there is a will without that choice', ch_nowill: 'There is no will', ch_unsure: 'Not sure yet',
    q_heirs: 'Where do the heirs live?', heirs_spain: 'All in Spain', heirs_abroad: 'All outside Spain', heirs_mixed: 'Some in Spain, some abroad',
    q_assets_region: 'In which region is the most valuable Spanish asset?', q_assets_region_hint: 'Usually the property. It decides which regional tax rules non-resident heirs can choose.',
    q_married: 'Was the deceased married at death?', yes: 'Yes', no: 'No',
    q_details: 'Details for the documents', q_details_hint: 'All optional. They stay in this browser.',
    f_death: 'Date of death', f_client: 'Name of the heir the letter is for', f_doclang: 'Roadmap language', f_letterlang: 'Letter language',
    region_ph: 'Choose a region', build: 'Build the roadmap',
    result_headline: 'The estate, step by step', result_sub: 'Law first, then tax, then paperwork. Each answer depends on the one before it.',
    print: 'Print or save as PDF', copy_letter: 'Copy the letter', copied: 'Copied', letter_t: 'Letter to the heirs', letter_hint: 'Copy it into an email or print it with your letterhead.',
    sources_t: 'Where the rules come from', restart: 'Change my answers',
    no_profile: 'Add your details on the lawyers page and your letterhead will print at the top.',
  },
  no: {
    title: 'Veikart for arv', note: 'Veiledning for eiendomsprofesjonelle. Ikke juridisk rådgivning eller skatterådgivning.',
    eyebrow: 'For advokater og familier', headline: 'Hvilken lov, hvilke skatteregler, og hva som må leveres når',
    body: 'Noen spørsmål om avdøde og arvingene. Du får arveloven som gjelder, skattereglene arvinger bosatt i utlandet kan velge, fristene som faktiske datoer, dokumentene som må samles og et brev til arvingene på deres språk.',
    points: ['EUs lovvalgsregler brukt i riktig rekkefølge', 'Regionvalget for arvinger bosatt i utlandet', 'Hver regel vist med kilde og dato'],
    cta: 'Start veikartet', minutes: 'Omtrent to minutter',
    q_residence: 'Hvor hadde avdøde fast bosted ved dødsfallet?', q_residence_hint: 'Fast bosted, ikke statsborgerskap og ikke hvor feriehuset ligger.',
    res_spain: 'I Spania', res_abroad: 'Utenfor Spania',
    q_deceased_region: 'I hvilken spansk region bodde avdøde?',
    q_nationality: 'Hvilket statsborgerskap hadde avdøde?', nat_spanish: 'Spansk', nat_other: 'Et annet',
    q_choice: 'Valgte et testament loven i avdødes statsborgerland?', q_choice_hint: 'Se etter en klausul om at arven skal følge loven i hjemlandet. Spansk pliktdelsarv avhenger av det.',
    ch_yes: 'Ja, testamentet velger den', ch_no: 'Nei, det finnes et testament uten det valget', ch_nowill: 'Det finnes ikke noe testament', ch_unsure: 'Usikker ennå',
    q_heirs: 'Hvor bor arvingene?', heirs_spain: 'Alle i Spania', heirs_abroad: 'Alle utenfor Spania', heirs_mixed: 'Noen i Spania, noen i utlandet',
    q_assets_region: 'I hvilken region ligger den mest verdifulle spanske eiendelen?', q_assets_region_hint: 'Som regel boligen. Den avgjør hvilke regionale skatteregler arvinger i utlandet kan velge.',
    q_married: 'Var avdøde gift ved dødsfallet?', yes: 'Ja', no: 'Nei',
    q_details: 'Detaljer til dokumentene', q_details_hint: 'Alt er valgfritt. Det blir i denne nettleseren.',
    f_death: 'Dødsdato', f_client: 'Navn på arvingen brevet er til', f_doclang: 'Språk for veikartet', f_letterlang: 'Språk for brevet',
    region_ph: 'Velg region', build: 'Lag veikartet',
    result_headline: 'Arven, steg for steg', result_sub: 'Først loven, så skatten, så papirene. Hvert svar bygger på det forrige.',
    print: 'Skriv ut eller lagre som PDF', copy_letter: 'Kopier brevet', copied: 'Kopiert', letter_t: 'Brev til arvingene', letter_hint: 'Kopier det inn i en e-post, eller skriv det ut med ditt brevhode.',
    sources_t: 'Hvor reglene kommer fra', restart: 'Endre svarene',
    no_profile: 'Legg inn detaljene dine på advokatsiden, så skrives brevhodet ut øverst.',
  },
  sv: {
    title: 'Färdplan för arv', note: 'Vägledning för fastighetsproffs. Inte juridisk rådgivning eller skatterådgivning.',
    eyebrow: 'För advokater och familjer', headline: 'Vilken lag, vilka skatteregler och vad som ska lämnas in när',
    body: 'Några frågor om den avlidne och arvingarna. Du får arvslagen som gäller, de skatteregler som arvingar bosatta utomlands kan välja, tidsfristerna som verkliga datum, dokumenten som ska samlas in och ett brev till arvingarna på deras språk.',
    points: ['EU:s lagvalsregler i rätt ordning', 'Regionvalet för arvingar bosatta utomlands', 'Varje regel med källa och datum'],
    cta: 'Starta färdplanen', minutes: 'Ungefär två minuter',
    q_residence: 'Var hade den avlidne sin hemvist vid dödsfallet?', q_residence_hint: 'Hemvist, inte medborgarskap och inte var fritidshuset ligger.',
    res_spain: 'I Spanien', res_abroad: 'Utanför Spanien',
    q_deceased_region: 'I vilken spansk region bodde den avlidne?',
    q_nationality: 'Vilket medborgarskap hade den avlidne?', nat_spanish: 'Spanskt', nat_other: 'Ett annat',
    q_choice: 'Valde ett testamente lagen i den avlidnes medborgarskapsland?', q_choice_hint: 'Leta efter en klausul om att arvet ska följa hemlandets lag. Den spanska laglotten avgörs av det.',
    ch_yes: 'Ja, testamentet väljer den', ch_no: 'Nej, det finns ett testamente utan det valet', ch_nowill: 'Det finns inget testamente', ch_unsure: 'Inte säkert än',
    q_heirs: 'Var bor arvingarna?', heirs_spain: 'Alla i Spanien', heirs_abroad: 'Alla utanför Spanien', heirs_mixed: 'Några i Spanien, några utomlands',
    q_assets_region: 'I vilken region finns den mest värdefulla spanska tillgången?', q_assets_region_hint: 'Oftast bostaden. Den avgör vilka regionala skatteregler arvingar utomlands kan välja.',
    q_married: 'Var den avlidne gift vid dödsfallet?', yes: 'Ja', no: 'Nej',
    q_details: 'Uppgifter till dokumenten', q_details_hint: 'Allt är frivilligt. Det stannar i den här webbläsaren.',
    f_death: 'Dödsdatum', f_client: 'Namn på arvingen brevet gäller', f_doclang: 'Färdplanens språk', f_letterlang: 'Brevets språk',
    region_ph: 'Välj region', build: 'Skapa färdplanen',
    result_headline: 'Arvet, steg för steg', result_sub: 'Först lagen, sedan skatten, sedan papperen. Varje svar bygger på det förra.',
    print: 'Skriv ut eller spara som PDF', copy_letter: 'Kopiera brevet', copied: 'Kopierat', letter_t: 'Brev till arvingarna', letter_hint: 'Kopiera det till ett mejl eller skriv ut det med ditt brevhuvud.',
    sources_t: 'Var reglerna kommer ifrån', restart: 'Ändra mina svar',
    no_profile: 'Fyll i dina uppgifter på advokatsidan så skrivs ditt brevhuvud ut överst.',
  },
  de: {
    title: 'Fahrplan für den Nachlass', note: 'Orientierung für Immobilienprofis. Keine Rechts- oder Steuerberatung.',
    eyebrow: 'Für Anwälte und Familien', headline: 'Welches Recht, welche Steuerregeln und was bis wann einzureichen ist',
    body: 'Einige Fragen zum Erblasser und zu den Erben. Sie erhalten das maßgebliche Erbrecht, die Steuerregeln, die nicht ansässige Erben wählen können, die Fristen als echte Daten, die nötigen Unterlagen und einen Brief an die Erben in ihrer Sprache.',
    points: ['EU-Rechtswahlregeln in der richtigen Reihenfolge', 'Die Regionaloption für nicht ansässige Erben', 'Jede Regel mit Quelle und Datum'],
    cta: 'Fahrplan starten', minutes: 'Etwa zwei Minuten',
    q_residence: 'Wo hatte der Erblasser beim Tod seinen gewöhnlichen Aufenthalt?', q_residence_hint: 'Gewöhnlicher Aufenthalt, nicht Staatsangehörigkeit und nicht der Ort des Ferienhauses.',
    res_spain: 'In Spanien', res_abroad: 'Außerhalb Spaniens',
    q_deceased_region: 'In welcher spanischen Region lebte der Erblasser?',
    q_nationality: 'Welche Staatsangehörigkeit hatte der Erblasser?', nat_spanish: 'Spanisch', nat_other: 'Eine andere',
    q_choice: 'Hat ein Testament das Recht der Staatsangehörigkeit gewählt?', q_choice_hint: 'Suchen Sie nach einer Klausel, dass der Nachlass dem Recht des Heimatlandes unterliegt. Das spanische Pflichtteilsrecht hängt davon ab.',
    ch_yes: 'Ja, das Testament wählt es', ch_no: 'Nein, es gibt ein Testament ohne diese Wahl', ch_nowill: 'Es gibt kein Testament', ch_unsure: 'Noch unklar',
    q_heirs: 'Wo leben die Erben?', heirs_spain: 'Alle in Spanien', heirs_abroad: 'Alle außerhalb Spaniens', heirs_mixed: 'Einige in Spanien, einige im Ausland',
    q_assets_region: 'In welcher Region liegt der wertvollste spanische Vermögenswert?', q_assets_region_hint: 'Meist die Immobilie. Sie entscheidet, welche regionalen Steuerregeln nicht ansässige Erben wählen können.',
    q_married: 'War der Erblasser beim Tod verheiratet?', yes: 'Ja', no: 'Nein',
    q_details: 'Angaben für die Dokumente', q_details_hint: 'Alles freiwillig. Die Angaben bleiben in diesem Browser.',
    f_death: 'Todestag', f_client: 'Name des Erben, an den der Brief geht', f_doclang: 'Sprache des Fahrplans', f_letterlang: 'Sprache des Briefs',
    region_ph: 'Region wählen', build: 'Fahrplan erstellen',
    result_headline: 'Der Nachlass, Schritt für Schritt', result_sub: 'Erst das Recht, dann die Steuer, dann die Unterlagen. Jede Antwort baut auf der vorigen auf.',
    print: 'Drucken oder als PDF speichern', copy_letter: 'Brief kopieren', copied: 'Kopiert', letter_t: 'Brief an die Erben', letter_hint: 'Kopieren Sie ihn in eine E-Mail oder drucken Sie ihn mit Ihrem Briefkopf.',
    sources_t: 'Woher die Regeln stammen', restart: 'Antworten ändern',
    no_profile: 'Hinterlegen Sie Ihre Angaben auf der Anwaltsseite, dann erscheint Ihr Briefkopf oben.',
  },
  fr: {
    title: 'Feuille de route de succession', note: 'Repères pour les professionnels de l’immobilier. Pas un conseil juridique ou fiscal.',
    eyebrow: 'Pour les avocats et les familles', headline: 'Quelle loi, quelles règles fiscales, et quoi déposer avant quand',
    body: 'Quelques questions sur le défunt et les héritiers. Vous obtenez la loi successorale applicable, les règles fiscales que les héritiers non résidents peuvent choisir, les délais en dates réelles, les documents à réunir et une lettre aux héritiers dans leur langue.',
    points: ['Les règles européennes de choix de loi, dans le bon ordre', 'L’option régionale des héritiers non résidents', 'Chaque règle avec sa source et sa date'],
    cta: 'Commencer la feuille de route', minutes: 'Environ deux minutes',
    q_residence: 'Où le défunt avait-il sa résidence habituelle au décès ?', q_residence_hint: 'La résidence habituelle, ni la nationalité ni le lieu de la maison de vacances.',
    res_spain: 'En Espagne', res_abroad: 'Hors d’Espagne',
    q_deceased_region: 'Dans quelle région espagnole vivait le défunt ?',
    q_nationality: 'Quelle était la nationalité du défunt ?', nat_spanish: 'Espagnole', nat_other: 'Une autre',
    q_choice: 'Un testament a-t-il choisi la loi de la nationalité du défunt ?', q_choice_hint: 'Cherchez une clause soumettant la succession à la loi du pays d’origine. La réserve héréditaire espagnole en dépend.',
    ch_yes: 'Oui, le testament la choisit', ch_no: 'Non, il y a un testament sans ce choix', ch_nowill: 'Il n’y a pas de testament', ch_unsure: 'Pas encore certain',
    q_heirs: 'Où vivent les héritiers ?', heirs_spain: 'Tous en Espagne', heirs_abroad: 'Tous hors d’Espagne', heirs_mixed: 'Certains en Espagne, d’autres à l’étranger',
    q_assets_region: 'Dans quelle région se trouve le bien espagnol le plus important ?', q_assets_region_hint: 'Souvent le logement. Il détermine les règles régionales que les héritiers non résidents peuvent choisir.',
    q_married: 'Le défunt était-il marié au décès ?', yes: 'Oui', no: 'Non',
    q_details: 'Informations pour les documents', q_details_hint: 'Tout est facultatif. Rien ne quitte ce navigateur.',
    f_death: 'Date du décès', f_client: 'Nom de l’héritier destinataire de la lettre', f_doclang: 'Langue de la feuille de route', f_letterlang: 'Langue de la lettre',
    region_ph: 'Choisir une région', build: 'Créer la feuille de route',
    result_headline: 'La succession, étape par étape', result_sub: 'D’abord la loi, puis l’impôt, puis les formalités. Chaque réponse dépend de la précédente.',
    print: 'Imprimer ou enregistrer en PDF', copy_letter: 'Copier la lettre', copied: 'Copié', letter_t: 'Lettre aux héritiers', letter_hint: 'Copiez-la dans un e-mail ou imprimez-la à votre en-tête.',
    sources_t: 'D’où viennent les règles', restart: 'Modifier mes réponses',
    no_profile: 'Ajoutez vos coordonnées sur la page des avocats et votre en-tête s’imprimera en haut.',
  },
  nl: {
    title: 'Stappenplan nalatenschap', note: 'Informatie voor vastgoedprofessionals. Geen juridisch of fiscaal advies.',
    eyebrow: 'Voor advocaten en families', headline: 'Welk recht, welke belastingregels en wat wanneer ingediend moet zijn',
    body: 'Een paar vragen over de overledene en de erfgenamen. U krijgt het erfrecht dat van toepassing is, de belastingregels waaruit erfgenamen in het buitenland kunnen kiezen, de termijnen als echte data, de benodigde documenten en een brief aan de erfgenamen in hun taal.',
    points: ['Europese rechtskeuzeregels in de juiste volgorde', 'De regiokeuze voor erfgenamen in het buitenland', 'Elke regel met bron en datum'],
    cta: 'Stappenplan starten', minutes: 'Ongeveer twee minuten',
    q_residence: 'Waar had de overledene bij overlijden zijn gewone verblijfplaats?', q_residence_hint: 'De gewone verblijfplaats, niet de nationaliteit en niet de plek van het vakantiehuis.',
    res_spain: 'In Spanje', res_abroad: 'Buiten Spanje',
    q_deceased_region: 'In welke Spaanse regio woonde de overledene?',
    q_nationality: 'Welke nationaliteit had de overledene?', nat_spanish: 'Spaans', nat_other: 'Een andere',
    q_choice: 'Koos een testament voor het recht van de nationaliteit van de overledene?', q_choice_hint: 'Zoek een clausule dat de nalatenschap onder het recht van het thuisland valt. Het Spaanse wettelijke erfdeel hangt ervan af.',
    ch_yes: 'Ja, het testament kiest ervoor', ch_no: 'Nee, er is een testament zonder die keuze', ch_nowill: 'Er is geen testament', ch_unsure: 'Nog niet zeker',
    q_heirs: 'Waar wonen de erfgenamen?', heirs_spain: 'Allemaal in Spanje', heirs_abroad: 'Allemaal buiten Spanje', heirs_mixed: 'Sommigen in Spanje, sommigen in het buitenland',
    q_assets_region: 'In welke regio ligt het waardevolste Spaanse bezit?', q_assets_region_hint: 'Meestal de woning. Die bepaalt welke regionale belastingregels erfgenamen in het buitenland kunnen kiezen.',
    q_married: 'Was de overledene bij overlijden getrouwd?', yes: 'Ja', no: 'Nee',
    q_details: 'Gegevens voor de documenten', q_details_hint: 'Alles is optioneel. Het blijft in deze browser.',
    f_death: 'Datum van overlijden', f_client: 'Naam van de erfgenaam voor wie de brief is', f_doclang: 'Taal van het stappenplan', f_letterlang: 'Taal van de brief',
    region_ph: 'Kies een regio', build: 'Stappenplan maken',
    result_headline: 'De nalatenschap, stap voor stap', result_sub: 'Eerst het recht, dan de belasting, dan de papieren. Elk antwoord bouwt voort op het vorige.',
    print: 'Afdrukken of als pdf opslaan', copy_letter: 'Brief kopiëren', copied: 'Gekopieerd', letter_t: 'Brief aan de erfgenamen', letter_hint: 'Kopieer hem in een e-mail of druk hem af met uw briefhoofd.',
    sources_t: 'Waar de regels vandaan komen', restart: 'Antwoorden wijzigen',
    no_profile: 'Vul uw gegevens in op de advocatenpagina, dan staat uw briefhoofd bovenaan.',
  },
};
