// Screen text for the sale readiness checklist, in the site's six languages.
// The checklist itself is in list.js (English and Spanish) and the client letter in
// letter.js (seven languages).
export default {
  en: {
    note: 'Practical guidance for property professionals. Not legal or tax advice.',
    title: 'Sale readiness checklist',
    eyebrow: 'For agents and lawyers',
    headline: 'Know what is missing before the notary does',
    body: 'Answer a few questions about a live sale. You get the tasks in order, who owns each one, the dates that follow from completion, and a letter your client can read in their own language.',
    points: ['Every rate and deadline comes from a dated, linked source', 'Your letterhead on the printout', 'Nothing you type leaves this browser'],
    cta: 'Start the checklist', minutes: 'About two minutes',

    q_side: 'Who are you acting for?',
    side_buyer: 'The buyer', side_seller: 'The seller', side_both: 'Both sides', side_both_d: 'You are handling the whole sale',
    q_seller: 'Is the seller tax resident in Spain?',
    q_seller_hint: 'This decides whether the buyer must hold back part of the price. Tax residency, not nationality or where they spend the summer.',
    q_buyer: 'Will the buyer be tax resident in Spain?',
    q_buyer_hint: 'It does not change the price. It changes what the buyer files every year afterwards.',
    res_resident: 'Yes, tax resident in Spain', res_nonresident: 'No, tax resident elsewhere', res_unsure: 'Not sure yet',
    q_property: 'What is being sold?',
    prop_resale: 'A resale home', prop_newbuild: 'A new home from the developer',
    q_region: 'Where is the new home?',
    q_region_hint: 'The Canary Islands have their own indirect tax instead of IVA.',
    region_mainland: 'Mainland Spain or the Balearics', region_canarias: 'The Canary Islands',
    q_finance: 'How is the buyer paying?',
    fin_cash: 'Cash, with no mortgage', fin_mortgage: 'With a Spanish mortgage', fin_undecided: 'Not decided yet',
    q_papers: 'What does the buyer already have?',
    q_papers_hint: 'Missing paperwork is the most common reason a completion date slips.',
    papers_nie: 'An NIE', papers_account: 'A Spanish account or a way to pay in euros',
    yes: 'Yes', no: 'No', unsure: 'Not sure',
    q_signing: 'How will the parties sign?',
    sign_person: 'Everyone in person at the notary', sign_poa: 'At least one by power of attorney', sign_undecided: 'Not decided yet',
    q_details: 'Details for the documents',
    q_details_hint: 'All optional. They stay in this browser.',
    f_client: "Client's name", f_property: 'Property reference or address',
    f_date: 'Planned completion date', f_date_hint: 'With a date, every deadline comes out as a real date.',
    f_doclang: 'Checklist language', f_letterlang: "Client letter language", f_recipient: 'Who is the letter for?',
    rec_buyer: 'The buyer', rec_seller: 'The seller',
    build: 'Build the checklist',

    result_headline: 'Your sale, step by step',
    result_sub: 'Work down the list. Each task says whose move it is.',
    missing_t: 'Still to confirm', missing_none: 'Nothing obvious is missing from what you told us.',
    dates_t: 'Dates from completion',
    d_completion: 'Completion', d_211: 'Buyer pays the retention (Modelo 211) by', d_210: 'Seller files the gain return (Modelo 210)', d_pv: 'Plusvalía deadline, no earlier than',
    d_pv_note: 'Holidays are not counted, so the real plusvalía deadline can fall later. Confirm it with the town hall.',
    d_between: '{a} to {b}',
    checklist_t: 'The checklist', letter_t: 'Letter for your client', letter_hint: 'Copy it into an email, or print it with your letterhead.',
    copy_letter: 'Copy the letter', copied: 'Copied', print: 'Print or save as PDF',
    no_profile: 'Add your details on the agents or lawyers page and they will appear at the top of the printout.',
    restart: 'Change my answers', sources_t: 'Where the figures come from',
    disclaimer: 'This is a working checklist based on the published rules on the dates shown. It is not legal or tax advice, and it does not replace the checks the notary, the lawyer or the agency must carry out.',
  },
  no: {
    note: 'Praktisk veiledning for eiendomsprofesjonelle. Ikke juridisk rådgivning eller skatterådgivning.',
    title: 'Sjekkliste for salget',
    eyebrow: 'For meglere og advokater',
    headline: 'Vit hva som mangler før notaren gjør det',
    body: 'Svar på noen spørsmål om et pågående salg. Du får oppgavene i rekkefølge, hvem som eier hver av dem, datoene som følger av overtakelsen, og et brev kunden kan lese på sitt eget språk.',
    points: ['Hver sats og frist kommer fra en datert kilde med lenke', 'Ditt brevhode på utskriften', 'Ingenting du skriver forlater denne nettleseren'],
    cta: 'Start sjekklisten', minutes: 'Omtrent to minutter',

    q_side: 'Hvem representerer du?',
    side_buyer: 'Kjøperen', side_seller: 'Selgeren', side_both: 'Begge parter', side_both_d: 'Du håndterer hele salget',
    q_seller: 'Er selgeren skattemessig bosatt i Spania?',
    q_seller_hint: 'Dette avgjør om kjøperen må holde tilbake en del av prisen. Det gjelder skattemessig bosted, ikke statsborgerskap eller hvor de er om sommeren.',
    q_buyer: 'Blir kjøperen skattemessig bosatt i Spania?',
    q_buyer_hint: 'Det endrer ikke prisen. Det endrer hva kjøperen må levere hvert år etterpå.',
    res_resident: 'Ja, bosatt i Spania', res_nonresident: 'Nei, bosatt et annet sted', res_unsure: 'Usikker ennå',
    q_property: 'Hva selges?',
    prop_resale: 'En brukt bolig', prop_newbuild: 'En ny bolig fra utbyggeren',
    q_region: 'Hvor ligger den nye boligen?',
    q_region_hint: 'Kanariøyene har sin egen avgift i stedet for IVA.',
    region_mainland: 'Fastlands-Spania eller Balearene', region_canarias: 'Kanariøyene',
    q_finance: 'Hvordan betaler kjøperen?',
    fin_cash: 'Kontant, uten lån', fin_mortgage: 'Med spansk boliglån', fin_undecided: 'Ikke bestemt ennå',
    q_papers: 'Hva har kjøperen allerede?',
    q_papers_hint: 'Manglende papirer er den vanligste grunnen til at overtakelsen blir forskjøvet.',
    papers_nie: 'Et NIE', papers_account: 'En spansk konto eller en måte å betale i euro',
    yes: 'Ja', no: 'Nei', unsure: 'Usikker',
    q_signing: 'Hvordan skal partene signere?',
    sign_person: 'Alle personlig hos notaren', sign_poa: 'Minst én med fullmakt', sign_undecided: 'Ikke bestemt ennå',
    q_details: 'Detaljer til dokumentene',
    q_details_hint: 'Alt er valgfritt. Det blir i denne nettleseren.',
    f_client: 'Kundens navn', f_property: 'Boligreferanse eller adresse',
    f_date: 'Planlagt overtakelse', f_date_hint: 'Med en dato kommer hver frist ut som en faktisk dato.',
    f_doclang: 'Språk for sjekklisten', f_letterlang: 'Språk for brevet til kunden', f_recipient: 'Hvem er brevet til?',
    rec_buyer: 'Kjøperen', rec_seller: 'Selgeren',
    build: 'Lag sjekklisten',

    result_headline: 'Salget ditt, steg for steg',
    result_sub: 'Jobb deg nedover listen. Hver oppgave viser hvem som har ballen.',
    missing_t: 'Må fortsatt bekreftes', missing_none: 'Ut fra svarene dine mangler ingenting åpenbart.',
    dates_t: 'Datoer fra overtakelsen',
    d_completion: 'Overtakelse', d_211: 'Kjøperen betaler tilbakeholdet (Modelo 211) innen', d_210: 'Selgeren leverer gevinstmeldingen (Modelo 210)', d_pv: 'Frist for plusvalía, tidligst',
    d_pv_note: 'Helligdager er ikke regnet med, så den reelle fristen for plusvalía kan komme senere. Bekreft den med kommunen.',
    d_between: '{a} til {b}',
    checklist_t: 'Sjekklisten', letter_t: 'Brev til kunden', letter_hint: 'Kopier det inn i en e-post, eller skriv det ut med ditt brevhode.',
    copy_letter: 'Kopier brevet', copied: 'Kopiert', print: 'Skriv ut eller lagre som PDF',
    no_profile: 'Legg inn detaljene dine på siden for meglere eller advokater, så vises de øverst på utskriften.',
    restart: 'Endre svarene', sources_t: 'Hvor tallene kommer fra',
    disclaimer: 'Dette er en arbeidssjekkliste basert på publiserte regler på datoene som vises. Det er ikke juridisk rådgivning eller skatterådgivning, og det erstatter ikke kontrollene notaren, advokaten eller meglerforetaket skal gjøre.',
  },
  sv: {
    note: 'Praktisk vägledning för fastighetsproffs. Inte juridisk rådgivning eller skatterådgivning.',
    title: 'Checklista inför tillträdet',
    eyebrow: 'För mäklare och advokater',
    headline: 'Vet vad som saknas innan notarien gör det',
    body: 'Svara på några frågor om en pågående affär. Du får uppgifterna i ordning, vem som äger varje uppgift, datumen som följer av tillträdet och ett brev som kunden kan läsa på sitt eget språk.',
    points: ['Varje sats och frist kommer från en daterad källa med länk', 'Ditt brevhuvud på utskriften', 'Inget du skriver lämnar den här webbläsaren'],
    cta: 'Starta checklistan', minutes: 'Ungefär två minuter',

    q_side: 'Vem företräder du?',
    side_buyer: 'Köparen', side_seller: 'Säljaren', side_both: 'Båda parter', side_both_d: 'Du sköter hela affären',
    q_seller: 'Har säljaren skatterättslig hemvist i Spanien?',
    q_seller_hint: 'Det avgör om köparen måste hålla inne en del av priset. Det gäller skatterättslig hemvist, inte medborgarskap eller var de bor på sommaren.',
    q_buyer: 'Kommer köparen att ha skatterättslig hemvist i Spanien?',
    q_buyer_hint: 'Det ändrar inte priset. Det ändrar vad köparen ska deklarera varje år efteråt.',
    res_resident: 'Ja, hemvist i Spanien', res_nonresident: 'Nej, hemvist någon annanstans', res_unsure: 'Inte säkert än',
    q_property: 'Vad säljs?',
    prop_resale: 'En begagnad bostad', prop_newbuild: 'En nyproducerad bostad från byggherren',
    q_region: 'Var ligger den nya bostaden?',
    q_region_hint: 'Kanarieöarna har en egen skatt i stället för IVA.',
    region_mainland: 'Spanska fastlandet eller Balearerna', region_canarias: 'Kanarieöarna',
    q_finance: 'Hur betalar köparen?',
    fin_cash: 'Kontant, utan lån', fin_mortgage: 'Med spanskt bolån', fin_undecided: 'Inte bestämt än',
    q_papers: 'Vad har köparen redan?',
    q_papers_hint: 'Saknade papper är den vanligaste orsaken till att tillträdet skjuts upp.',
    papers_nie: 'Ett NIE', papers_account: 'Ett spanskt konto eller ett sätt att betala i euro',
    yes: 'Ja', no: 'Nej', unsure: 'Osäker',
    q_signing: 'Hur ska parterna skriva under?',
    sign_person: 'Alla på plats hos notarien', sign_poa: 'Minst en genom fullmakt', sign_undecided: 'Inte bestämt än',
    q_details: 'Uppgifter till dokumenten',
    q_details_hint: 'Allt är frivilligt. Det stannar i den här webbläsaren.',
    f_client: 'Kundens namn', f_property: 'Objektreferens eller adress',
    f_date: 'Planerat tillträde', f_date_hint: 'Med ett datum kommer varje frist ut som ett verkligt datum.',
    f_doclang: 'Språk för checklistan', f_letterlang: 'Språk för brevet till kunden', f_recipient: 'Vem är brevet till?',
    rec_buyer: 'Köparen', rec_seller: 'Säljaren',
    build: 'Skapa checklistan',

    result_headline: 'Din affär, steg för steg',
    result_sub: 'Arbeta dig nedåt i listan. Varje uppgift visar vems tur det är.',
    missing_t: 'Behöver fortfarande bekräftas', missing_none: 'Utifrån dina svar saknas inget uppenbart.',
    dates_t: 'Datum från tillträdet',
    d_completion: 'Tillträde', d_211: 'Köparen betalar in innehållandet (Modelo 211) senast', d_210: 'Säljaren lämnar vinstdeklarationen (Modelo 210)', d_pv: 'Frist för plusvalía, tidigast',
    d_pv_note: 'Helgdagar är inte medräknade, så den verkliga fristen för plusvalía kan infalla senare. Bekräfta den med kommunen.',
    d_between: '{a} till {b}',
    checklist_t: 'Checklistan', letter_t: 'Brev till kunden', letter_hint: 'Kopiera det till ett mejl, eller skriv ut det med ditt brevhuvud.',
    copy_letter: 'Kopiera brevet', copied: 'Kopierat', print: 'Skriv ut eller spara som PDF',
    no_profile: 'Lägg till dina uppgifter på sidan för mäklare eller advokater så visas de överst på utskriften.',
    restart: 'Ändra mina svar', sources_t: 'Var siffrorna kommer ifrån',
    disclaimer: 'Det här är en arbetschecklista baserad på publicerade regler de datum som visas. Den är inte juridisk rådgivning eller skatterådgivning och ersätter inte de kontroller som notarien, advokaten eller mäklarföretaget ska göra.',
  },
  de: {
    note: 'Praktische Orientierung für Immobilienprofis. Keine Rechts- oder Steuerberatung.',
    title: 'Checkliste bis zur Beurkundung',
    eyebrow: 'Für Makler und Anwälte',
    headline: 'Wissen, was fehlt, bevor der Notar es merkt',
    body: 'Beantworten Sie einige Fragen zu einem laufenden Verkauf. Sie erhalten die Aufgaben in der richtigen Reihenfolge, die Zuständigkeiten, die Fristen ab der Beurkundung und einen Brief, den Ihr Kunde in seiner Sprache lesen kann.',
    points: ['Jeder Satz und jede Frist stammt aus einer datierten, verlinkten Quelle', 'Ihr Briefkopf auf dem Ausdruck', 'Nichts, was Sie eingeben, verlässt diesen Browser'],
    cta: 'Checkliste starten', minutes: 'Etwa zwei Minuten',

    q_side: 'Für wen sind Sie tätig?',
    side_buyer: 'Für den Käufer', side_seller: 'Für den Verkäufer', side_both: 'Für beide Seiten', side_both_d: 'Sie betreuen den gesamten Verkauf',
    q_seller: 'Ist der Verkäufer in Spanien steuerlich ansässig?',
    q_seller_hint: 'Davon hängt ab, ob der Käufer einen Teil des Preises einbehalten muss. Es geht um den steuerlichen Wohnsitz, nicht um die Staatsangehörigkeit.',
    q_buyer: 'Wird der Käufer in Spanien steuerlich ansässig sein?',
    q_buyer_hint: 'Das ändert nicht den Preis. Es ändert, was der Käufer danach jedes Jahr erklären muss.',
    res_resident: 'Ja, in Spanien ansässig', res_nonresident: 'Nein, anderswo ansässig', res_unsure: 'Noch unklar',
    q_property: 'Was wird verkauft?',
    prop_resale: 'Eine Bestandsimmobilie', prop_newbuild: 'Ein Neubau vom Bauträger',
    q_region: 'Wo liegt der Neubau?',
    q_region_hint: 'Auf den Kanarischen Inseln gilt eine eigene Steuer statt der IVA.',
    region_mainland: 'Spanisches Festland oder Balearen', region_canarias: 'Kanarische Inseln',
    q_finance: 'Wie bezahlt der Käufer?',
    fin_cash: 'Bar, ohne Finanzierung', fin_mortgage: 'Mit spanischer Hypothek', fin_undecided: 'Noch nicht entschieden',
    q_papers: 'Was hat der Käufer bereits?',
    q_papers_hint: 'Fehlende Unterlagen sind der häufigste Grund, warum sich ein Beurkundungstermin verschiebt.',
    papers_nie: 'Eine NIE', papers_account: 'Ein spanisches Konto oder eine Möglichkeit, in Euro zu zahlen',
    yes: 'Ja', no: 'Nein', unsure: 'Unklar',
    q_signing: 'Wie unterschreiben die Parteien?',
    sign_person: 'Alle persönlich beim Notar', sign_poa: 'Mindestens eine Partei per Vollmacht', sign_undecided: 'Noch nicht entschieden',
    q_details: 'Angaben für die Dokumente',
    q_details_hint: 'Alles freiwillig. Die Angaben bleiben in diesem Browser.',
    f_client: 'Name des Kunden', f_property: 'Objektreferenz oder Adresse',
    f_date: 'Geplanter Beurkundungstermin', f_date_hint: 'Mit einem Datum wird jede Frist als echtes Datum ausgegeben.',
    f_doclang: 'Sprache der Checkliste', f_letterlang: 'Sprache des Kundenbriefs', f_recipient: 'An wen geht der Brief?',
    rec_buyer: 'An den Käufer', rec_seller: 'An den Verkäufer',
    build: 'Checkliste erstellen',

    result_headline: 'Ihr Verkauf, Schritt für Schritt',
    result_sub: 'Arbeiten Sie die Liste von oben nach unten ab. Jede Aufgabe zeigt, wer am Zug ist.',
    missing_t: 'Noch zu klären', missing_none: 'Nach Ihren Angaben fehlt nichts Offensichtliches.',
    dates_t: 'Fristen ab der Beurkundung',
    d_completion: 'Beurkundung', d_211: 'Käufer führt den Einbehalt ab (Modelo 211) bis', d_210: 'Verkäufer gibt die Gewinnerklärung ab (Modelo 210)', d_pv: 'Frist für die Plusvalía, frühestens am',
    d_pv_note: 'Feiertage sind nicht berücksichtigt, die tatsächliche Frist für die Plusvalía kann also später liegen. Bitte bei der Gemeinde bestätigen.',
    d_between: '{a} bis {b}',
    checklist_t: 'Die Checkliste', letter_t: 'Brief an Ihren Kunden', letter_hint: 'Kopieren Sie ihn in eine E-Mail oder drucken Sie ihn mit Ihrem Briefkopf.',
    copy_letter: 'Brief kopieren', copied: 'Kopiert', print: 'Drucken oder als PDF speichern',
    no_profile: 'Hinterlegen Sie Ihre Angaben auf der Seite für Makler oder Anwälte, dann erscheinen sie oben auf dem Ausdruck.',
    restart: 'Antworten ändern', sources_t: 'Woher die Zahlen stammen',
    disclaimer: 'Dies ist eine Arbeitscheckliste auf Grundlage der veröffentlichten Regeln zu den angegebenen Daten. Sie ist keine Rechts- oder Steuerberatung und ersetzt nicht die Prüfungen, die Notar, Anwalt oder Makler vornehmen müssen.',
  },
  fr: {
    note: 'Repères pratiques pour les professionnels de l’immobilier. Pas un conseil juridique ou fiscal.',
    title: 'Check-list avant la signature',
    eyebrow: 'Pour les agents et les avocats',
    headline: 'Savoir ce qui manque avant le notaire',
    body: "Répondez à quelques questions sur une vente en cours. Vous obtenez les tâches dans l'ordre, le responsable de chacune, les dates qui découlent de la signature et une lettre que votre client peut lire dans sa langue.",
    points: ['Chaque taux et chaque délai vient d’une source datée et liée', 'Votre en-tête sur l’impression', 'Rien de ce que vous saisissez ne quitte ce navigateur'],
    cta: 'Commencer la check-list', minutes: 'Environ deux minutes',

    q_side: 'Pour qui intervenez-vous ?',
    side_buyer: "Pour l'acheteur", side_seller: 'Pour le vendeur', side_both: 'Pour les deux parties', side_both_d: 'Vous gérez toute la vente',
    q_seller: 'Le vendeur est-il résident fiscal en Espagne ?',
    q_seller_hint: "Cela décide si l'acheteur doit retenir une partie du prix. On parle de résidence fiscale, pas de nationalité.",
    q_buyer: "L'acheteur sera-t-il résident fiscal en Espagne ?",
    q_buyer_hint: "Cela ne change pas le prix. Cela change ce que l'acheteur déclare chaque année ensuite.",
    res_resident: 'Oui, résident en Espagne', res_nonresident: 'Non, résident ailleurs', res_unsure: 'Pas encore certain',
    q_property: "Qu'est-ce qui est vendu ?",
    prop_resale: 'Un logement ancien', prop_newbuild: 'Un logement neuf du promoteur',
    q_region: 'Où se trouve le logement neuf ?',
    q_region_hint: "Les Canaries appliquent leur propre taxe à la place de l'IVA.",
    region_mainland: 'Espagne continentale ou Baléares', region_canarias: 'Îles Canaries',
    q_finance: "Comment l'acheteur paie-t-il ?",
    fin_cash: 'Comptant, sans prêt', fin_mortgage: 'Avec un prêt immobilier espagnol', fin_undecided: 'Pas encore décidé',
    q_papers: "Que possède déjà l'acheteur ?",
    q_papers_hint: 'Les papiers manquants sont la première raison pour laquelle une date de signature glisse.',
    papers_nie: 'Un NIE', papers_account: 'Un compte espagnol ou un moyen de payer en euros',
    yes: 'Oui', no: 'Non', unsure: 'Pas sûr',
    q_signing: 'Comment les parties signeront-elles ?',
    sign_person: 'Tout le monde en personne chez le notaire', sign_poa: 'Au moins une partie par procuration', sign_undecided: 'Pas encore décidé',
    q_details: 'Informations pour les documents',
    q_details_hint: 'Tout est facultatif. Rien ne quitte ce navigateur.',
    f_client: 'Nom du client', f_property: 'Référence ou adresse du bien',
    f_date: 'Date de signature prévue', f_date_hint: 'Avec une date, chaque délai devient une date réelle.',
    f_doclang: 'Langue de la check-list', f_letterlang: 'Langue de la lettre au client', f_recipient: 'À qui est destinée la lettre ?',
    rec_buyer: "À l'acheteur", rec_seller: 'Au vendeur',
    build: 'Créer la check-list',

    result_headline: 'Votre vente, étape par étape',
    result_sub: 'Suivez la liste de haut en bas. Chaque tâche indique qui doit agir.',
    missing_t: 'Reste à confirmer', missing_none: "D'après vos réponses, rien d'évident ne manque.",
    dates_t: 'Dates à partir de la signature',
    d_completion: 'Signature', d_211: "L'acheteur verse la retenue (Modelo 211) au plus tard le", d_210: 'Le vendeur dépose la déclaration de plus-value (Modelo 210)', d_pv: 'Délai de la plusvalía, au plus tôt le',
    d_pv_note: "Les jours fériés ne sont pas comptés, le vrai délai de la plusvalía peut donc tomber plus tard. Vérifiez-le auprès de la mairie.",
    d_between: 'du {a} au {b}',
    checklist_t: 'La check-list', letter_t: 'Lettre pour votre client', letter_hint: 'Copiez-la dans un e-mail, ou imprimez-la avec votre en-tête.',
    copy_letter: 'Copier la lettre', copied: 'Copié', print: 'Imprimer ou enregistrer en PDF',
    no_profile: "Ajoutez vos coordonnées sur la page des agents ou des avocats et elles apparaîtront en haut de l'impression.",
    restart: 'Modifier mes réponses', sources_t: "D'où viennent les chiffres",
    disclaimer: "Il s'agit d'une check-list de travail fondée sur les règles publiées aux dates indiquées. Ce n'est pas un conseil juridique ou fiscal, et elle ne remplace pas les vérifications que le notaire, l'avocat ou l'agence doivent effectuer.",
  },
  nl: {
    note: 'Praktische informatie voor vastgoedprofessionals. Geen juridisch of fiscaal advies.',
    title: 'Checklist tot de overdracht',
    eyebrow: 'Voor makelaars en advocaten',
    headline: 'Weet wat er ontbreekt voordat de notaris het ziet',
    body: 'Beantwoord een paar vragen over een lopende verkoop. U krijgt de taken op volgorde, wie waarvoor verantwoordelijk is, de data die uit de overdracht volgen en een brief die uw klant in zijn eigen taal kan lezen.',
    points: ['Elk tarief en elke termijn komt uit een gedateerde bron met link', 'Uw briefhoofd op de afdruk', 'Niets van wat u invult verlaat deze browser'],
    cta: 'Checklist starten', minutes: 'Ongeveer twee minuten',

    q_side: 'Voor wie treedt u op?',
    side_buyer: 'De koper', side_seller: 'De verkoper', side_both: 'Beide partijen', side_both_d: 'U begeleidt de hele verkoop',
    q_seller: 'Woont de verkoper fiscaal in Spanje?',
    q_seller_hint: 'Dit bepaalt of de koper een deel van de prijs moet inhouden. Het gaat om de fiscale woonplaats, niet om nationaliteit.',
    q_buyer: 'Gaat de koper fiscaal in Spanje wonen?',
    q_buyer_hint: 'Het verandert de prijs niet. Het verandert wat de koper daarna elk jaar moet aangeven.',
    res_resident: 'Ja, fiscaal in Spanje', res_nonresident: 'Nee, fiscaal elders', res_unsure: 'Nog niet zeker',
    q_property: 'Wat wordt er verkocht?',
    prop_resale: 'Een bestaande woning', prop_newbuild: 'Een nieuwbouwwoning van de ontwikkelaar',
    q_region: 'Waar ligt de nieuwbouwwoning?',
    q_region_hint: 'De Canarische Eilanden hebben een eigen belasting in plaats van IVA.',
    region_mainland: 'Het Spaanse vasteland of de Balearen', region_canarias: 'De Canarische Eilanden',
    q_finance: 'Hoe betaalt de koper?',
    fin_cash: 'Contant, zonder hypotheek', fin_mortgage: 'Met een Spaanse hypotheek', fin_undecided: 'Nog niet besloten',
    q_papers: 'Wat heeft de koper al?',
    q_papers_hint: 'Ontbrekende papieren zijn de meest voorkomende reden dat een overdrachtsdatum verschuift.',
    papers_nie: 'Een NIE', papers_account: 'Een Spaanse rekening of een manier om in euro te betalen',
    yes: 'Ja', no: 'Nee', unsure: 'Weet niet',
    q_signing: 'Hoe tekenen de partijen?',
    sign_person: 'Iedereen persoonlijk bij de notaris', sign_poa: 'Minstens één partij met een volmacht', sign_undecided: 'Nog niet besloten',
    q_details: 'Gegevens voor de documenten',
    q_details_hint: 'Alles is optioneel. Het blijft in deze browser.',
    f_client: 'Naam van de klant', f_property: 'Referentie of adres van de woning',
    f_date: 'Geplande overdrachtsdatum', f_date_hint: 'Met een datum komt elke termijn uit als een echte datum.',
    f_doclang: 'Taal van de checklist', f_letterlang: 'Taal van de brief aan de klant', f_recipient: 'Voor wie is de brief?',
    rec_buyer: 'De koper', rec_seller: 'De verkoper',
    build: 'Checklist maken',

    result_headline: 'Uw verkoop, stap voor stap',
    result_sub: 'Werk de lijst van boven naar beneden af. Elke taak laat zien wie aan zet is.',
    missing_t: 'Nog te bevestigen', missing_none: 'Op basis van uw antwoorden ontbreekt er niets opvallends.',
    dates_t: 'Data vanaf de overdracht',
    d_completion: 'Overdracht', d_211: 'Koper draagt de inhouding af (Modelo 211) uiterlijk', d_210: 'Verkoper dient de winstaangifte in (Modelo 210)', d_pv: 'Termijn plusvalía, niet eerder dan',
    d_pv_note: 'Feestdagen zijn niet meegeteld, dus de echte termijn voor de plusvalía kan later vallen. Controleer die bij de gemeente.',
    d_between: '{a} tot {b}',
    checklist_t: 'De checklist', letter_t: 'Brief voor uw klant', letter_hint: 'Kopieer hem in een e-mail, of druk hem af met uw briefhoofd.',
    copy_letter: 'Brief kopiëren', copied: 'Gekopieerd', print: 'Afdrukken of als pdf opslaan',
    no_profile: 'Vul uw gegevens in op de pagina voor makelaars of advocaten, dan staan ze bovenaan de afdruk.',
    restart: 'Antwoorden wijzigen', sources_t: 'Waar de cijfers vandaan komen',
    disclaimer: 'Dit is een werkchecklist op basis van de gepubliceerde regels op de getoonde data. Het is geen juridisch of fiscaal advies en vervangt niet de controles die de notaris, de advocaat of het makelaarskantoor moeten uitvoeren.',
  },
};
