// All user-facing framing text for the quote checker. The questions to put back to the
// contractor, in English and Spanish, live in flags.js next to the logic that decides
// which of them you need. Same dot-path API as useT. Other locales fall back to en.
export default {
  en: {
    eyebrow: 'Free tool',
    headline: 'Check a builder quote before you sign it',
    body: 'Most bad building jobs in Spain are visible in the quote, and most of them are visible as something missing rather than as something wrong. Twelve questions, then a red flag count and the exact words to put back to the contractor.',
    points: [
      'Twelve questions about the quote in front of you',
      'Every unresolved item comes with the question to ask, in English and in Spanish',
      'What changes if the job is obra mayor rather than obra menor',
    ],
    cta: 'Check my quote',
    minutes: 'About two minutes',

    q_written: 'Is the quote in writing?',
    q_written_hint: 'A presupuesto is the normal Spanish word for it. Look for the company trading name, address and CIF on the document.',
    written_formal: 'Yes, a written presupuesto with the company details on it',
    written_informal: 'Written, but it is a message with a total in it',
    written_informal_d: 'An email or a WhatsApp with a number and no company details',
    written_verbal: 'No, we agreed it verbally',

    q_itemised: 'Is the price broken down?',
    q_itemised_hint: 'Partidas is the word for the line items. You are looking for trades and materials separated, not one figure at the bottom.',
    itemised_full: 'Yes, line by line, with materials and labour separate',
    itemised_partial: 'A few headings, but most of it is grouped',
    itemised_total: 'No, it is one total',

    q_iva: 'Does it say whether IVA is included?',
    q_iva_hint: 'This is the single most common surprise on a Spanish renovation bill. It should be a line on the quote, not a conversation.',
    iva_stated: 'Yes, it says either way',
    iva_silent: 'No, it does not mention IVA',
    iva_unsure: 'I am not sure',

    q_fixed: 'Is it a closed price or an estimate?',
    q_fixed_hint: 'Precio cerrado means the price is fixed. An estimate is perfectly normal on an old property. Silence about which one you are holding is not.',
    fixed_closed: 'It says the price is closed',
    fixed_variable: 'It says the price can move, and why',
    fixed_silent: 'It does not say either way',

    q_registered: 'Have you seen proof the business is registered?',
    q_registered_hint: 'A CIF for a company, or an autonomo registration for a sole trader, plus a certificate that they are up to date with tax and social security. Asking for these is routine here and is not an accusation.',
    registered_seen: 'Yes, I have seen the documents',
    registered_told: 'No, I have been told they are registered',
    registered_unsure: 'I do not know what I should be asking for',

    q_insurance: 'Have you seen their liability insurance?',
    q_insurance_hint: 'Responsabilidad civil. It covers the damage the work does to someone else, which for an apartment usually means the flat below.',
    insurance_seen: 'Yes, I have seen the policy and the dates',
    insurance_told: 'No, I have been told they have it',
    insurance_unsure: 'It has not come up',

    q_licence: 'Does the work need a town hall licence, and who is applying?',
    q_licence_hint: 'Almost all building work in Spain needs either a licence or a declaration to the ayuntamiento, including work that feels minor. The question is who is doing it.',
    licence_contractor: 'It needs one, and the contractor is applying',
    licence_contractor_d: 'And that is written down somewhere',
    licence_owner: 'It needs one, and I am applying',
    licence_none_needed: 'The contractor says no licence is needed',
    licence_unsure: 'Nobody has said',

    q_deposit: 'How much is being asked for up front?',
    q_deposit_hint: 'Some money before materials are ordered is normal. What matters is what it buys and whether the rest is tied to work you can see.',
    deposit_none: 'Nothing before work starts',
    deposit_small: 'A modest amount for materials, with an invoice',
    deposit_half: 'About half the total',
    deposit_most: 'Most or all of it, before anything starts',
    deposit_unsure: 'It has not been discussed yet',

    q_cash: 'Has cash, or payment without an invoice, been suggested?',
    q_cash_hint: 'Sin factura is the phrase. It usually arrives as an offer of a lower price, which is what makes it tempting.',
    cash_no: 'No, everything is invoiced',
    cash_part: 'Part of it in cash, or part without an invoice',
    cash_all: 'The whole job, cash, no invoice',

    q_dates: 'Are there start and completion dates in writing?',
    q_dates_hint: 'Renovations here do run over and a good contractor will say so. A written date is not a punishment, it is something to talk about from abroad.',
    dates_written: 'Yes, both are written down',
    dates_verbal: 'We discussed dates, nothing is written',
    dates_none: 'No dates at all',

    q_price: 'How does the price compare with your other quotes?',
    q_price_hint: 'For this to mean anything the quotes have to be for the same written specification. If they are not, that is the thing to fix first.',
    price_inline: 'It is in line with the others',
    price_below: 'It is far below the others',
    price_only: 'It is the only quote I have',

    q_bank: 'How did you get the bank details?',
    q_bank_hint: 'This is the question that protects the largest amount of money on the page, and it takes one phone call to answer.',
    bank_verified: 'Confirmed by voice, on a number I already had',
    bank_email: 'They came by email or message and I have not checked them',
    bank_changed: 'The details changed at some point',
    bank_none_yet: 'No money has been discussed yet',

    result_stop: 'Do not sign this yet',
    result_stop_sub: 'One of your answers is the kind that costs owners the whole job rather than part of it. That does not make this contractor dishonest, and it does not mean walking away. It means the thing gets fixed before any money moves, and everything below tells you how to say so.',
    result_rework: 'Not ready to sign, but nothing here is fatal',
    result_rework_sub: 'There are enough gaps that you would be signing on trust rather than on a document. Every one of them is answerable, and a contractor who answers them well is the one you want. Work down the red list first.',
    result_fixable: 'Close. A few things to put right first',
    result_fixable_sub: 'Nothing here suggests you are being taken advantage of. There are gaps in the paperwork, and paperwork gaps are what turn an ordinary disagreement into an expensive one. Ask for these before you sign.',
    result_confirm: 'Nothing is wrong. Some things are unconfirmed',
    result_confirm_sub: 'You have no red flags, which is genuinely uncommon at this stage. What is left is a short list of things nobody has said either way, and each of them is one question.',
    result_clear: 'This quote stands up',
    result_clear_sub: 'Everything a Spanish quote should carry is on it. That is a good sign about how the job will run as well as about the paperwork. The questions below are still worth putting, because they are the ones a scorecard cannot answer for you.',

    restart: 'Change my answers',
    score_title: 'Your score',
    score_red: 'Red flags',
    score_amber: 'Unconfirmed',
    score_clear: 'Checks out',
    score_total: 'Questions asked',

    g_critical: 'Fix these before any money moves',
    g_critical_note: 'Each of these on its own is enough to stop a signature. Not because the contractor is dishonest, but because if it does go wrong here, it goes wrong for the whole amount.',
    g_red: 'Resolve these before you sign',
    g_red_note: 'One line each, in words you can send as they are. The Spanish version is there to be copied into a message.',
    g_amber: 'Confirm these',
    g_amber_note: 'Not warnings. Things nobody has said either way, which is a different problem and an easier one.',
    g_always: 'Ask these whatever the answers were',
    g_always_note: 'The questions no scorecard can settle for you.',
    g_clear: 'What already checks out',
    g_clear_note: 'Worth knowing what you have, not only what is missing.',
  },
};
