// Every locality the directory covers, shared by the front end (the town menu) and the
// API (the centre point of the Google Places search).
//
// GENERATED FILE. Rebuilt by outputs/build_localities.py from two GitHub datasets: the
// GeoNames cities15000 tier (every Spanish municipality above roughly 15,000 people, the
// point below which a town rarely has a tradesperson carrying enough reviews to rank),
// joined to GeoNames coordinates and province codes.
//
// Hand-added entries are marked "curated" in the generator and are kept verbatim on every
// rebuild. Those are the resort towns that matter to a foreign owner but sit well under
// 15,000 people: Moraira, Sotogrande, Empuriabrava, Playa Blanca, Orihuela Costa and the
// rest. Losing them to a population rule would gut the tool.
//
// SLUGS ARE LOAD BEARING. They appear in live URLs (?town=javea) and they are the cache
// keys for the stored Google results in Supabase Storage. Never renumber or rename one:
// it breaks shared links and orphans a cell someone already paid an API call for.
//
// Coverage does not drive cost. Google bills per lookup, not per listed town, one lookup
// covers a town and trade for 30 days, and DIRECTORY_DAILY_BUDGET in api/directory.js is a
// hard ceiling on lookups per day. So this list can grow without the bill moving.
//
// Coordinates are the town centre. The API searches a radius around the point rather than
// trusting a text match on the name, because these names repeat across Spain.

export const REGIONS = {
  a_coruna: 'A Coruña',
  alava: 'Álava',
  albacete: 'Albacete',
  alicante: 'Alicante',
  almeria: 'Almería',
  asturias: 'Asturias',
  avila: 'Ávila',
  badajoz: 'Badajoz',
  baleares: 'Baleares',
  barcelona: 'Barcelona',
  burgos: 'Burgos',
  caceres: 'Cáceres',
  cadiz: 'Cádiz',
  cantabria: 'Cantabria',
  castellon: 'Castellón',
  ceuta: 'Ceuta',
  ciudad_real: 'Ciudad Real',
  cordoba: 'Córdoba',
  cuenca: 'Cuenca',
  girona: 'Girona',
  granada: 'Granada',
  guadalajara: 'Guadalajara',
  guipuzcoa: 'Guipúzcoa',
  huelva: 'Huelva',
  huesca: 'Huesca',
  jaen: 'Jaén',
  la_rioja: 'La Rioja',
  las_palmas: 'Las Palmas',
  leon: 'León',
  lleida: 'Lleida',
  lugo: 'Lugo',
  madrid: 'Madrid',
  malaga: 'Málaga',
  melilla: 'Melilla',
  murcia: 'Murcia',
  navarra: 'Navarra',
  ourense: 'Ourense',
  palencia: 'Palencia',
  pontevedra: 'Pontevedra',
  salamanca: 'Salamanca',
  santa_cruz_de_tenerife: 'Santa Cruz de Tenerife',
  segovia: 'Segovia',
  sevilla: 'Sevilla',
  soria: 'Soria',
  tarragona: 'Tarragona',
  teruel: 'Teruel',
  toledo: 'Toledo',
  valencia: 'Valencia',
  valladolid: 'Valladolid',
  vizcaya: 'Vizcaya',
  zamora: 'Zamora',
  zaragoza: 'Zaragoza',
};

export const LOCALITIES = [
  // A Coruña
  { slug: 'a-coruna', name: 'A Coruña', province: 'A Coruña', region: 'a_coruna', lat: 43.3713, lng: -8.3960 },
  { slug: 'arteixo', name: 'Arteixo', province: 'A Coruña', region: 'a_coruna', lat: 43.3048, lng: -8.5075 },
  { slug: 'boiro', name: 'Boiro', province: 'A Coruña', region: 'a_coruna', lat: 42.6472, lng: -8.8846 },
  { slug: 'cambre', name: 'Cambre', province: 'A Coruña', region: 'a_coruna', lat: 43.2944, lng: -8.3474 },
  { slug: 'carballo', name: 'Carballo', province: 'A Coruña', region: 'a_coruna', lat: 43.2130, lng: -8.6910 },
  { slug: 'culleredo', name: 'Culleredo', province: 'A Coruña', region: 'a_coruna', lat: 43.2879, lng: -8.3886 },
  { slug: 'ferrol', name: 'Ferrol', province: 'A Coruña', region: 'a_coruna', lat: 43.4845, lng: -8.2329 },
  { slug: 'naron', name: 'Narón', province: 'A Coruña', region: 'a_coruna', lat: 43.5018, lng: -8.1908 },
  { slug: 'oleiros', name: 'Oleiros', province: 'A Coruña', region: 'a_coruna', lat: 43.3333, lng: -8.3167 },
  { slug: 'santa-uxia-de-ribeira', name: 'Santa Uxía de Ribeira', province: 'A Coruña', region: 'a_coruna', lat: 42.5535, lng: -8.9909 },
  { slug: 'santiago-de-compostela', name: 'Santiago de Compostela', province: 'A Coruña', region: 'a_coruna', lat: 42.8805, lng: -8.5457 },
  { slug: 'teo', name: 'Teo', province: 'A Coruña', region: 'a_coruna', lat: 42.7950, lng: -8.5480 },

  // Álava
  { slug: 'gasteiz-vitoria', name: 'Gasteiz / Vitoria', province: 'Álava', region: 'alava', lat: 42.8500, lng: -2.6727 },
  { slug: 'laudio-llodio', name: 'Laudio / Llodio', province: 'Álava', region: 'alava', lat: 43.1432, lng: -2.9620 },

  // Albacete
  { slug: 'albacete', name: 'Albacete', province: 'Albacete', region: 'albacete', lat: 38.9942, lng: -1.8564 },
  { slug: 'almansa', name: 'Almansa', province: 'Albacete', region: 'albacete', lat: 38.8692, lng: -1.0971 },
  { slug: 'hellin', name: 'Hellín', province: 'Albacete', region: 'albacete', lat: 38.5106, lng: -1.7010 },
  { slug: 'la-roda', name: 'La Roda', province: 'Albacete', region: 'albacete', lat: 39.2073, lng: -2.1572 },
  { slug: 'villarrobledo', name: 'Villarrobledo', province: 'Albacete', region: 'albacete', lat: 39.2699, lng: -2.6012 },

  // Alicante
  { slug: 'alcoy', name: 'Alcoy', province: 'Alicante', region: 'alicante', lat: 38.7054, lng: -0.4743 },
  { slug: 'alicante', name: 'Alicante', province: 'Alicante', region: 'alicante', lat: 38.3452, lng: -0.4810 },
  { slug: 'almoradi', name: 'Almoradí', province: 'Alicante', region: 'alicante', lat: 38.1088, lng: -0.7920 },
  { slug: 'altea', name: 'Altea', province: 'Alicante', region: 'alicante', lat: 38.5989, lng: -0.0517 },
  { slug: 'aspe', name: 'Aspe', province: 'Alicante', region: 'alicante', lat: 38.3451, lng: -0.7672 },
  { slug: 'benidorm', name: 'Benidorm', province: 'Alicante', region: 'alicante', lat: 38.5342, lng: -0.1314 },
  { slug: 'benissa', name: 'Benissa', province: 'Alicante', region: 'alicante', lat: 38.7150, lng: 0.0483 },
  { slug: 'callosa-de-segura', name: 'Callosa de Segura', province: 'Alicante', region: 'alicante', lat: 38.1250, lng: -0.8782 },
  { slug: 'calpe', name: 'Calpe (Calp)', province: 'Alicante', region: 'alicante', lat: 38.6446, lng: 0.0450 },
  { slug: 'ciudad-quesada', name: 'Ciudad Quesada (Rojales)', province: 'Alicante', region: 'alicante', lat: 38.0872, lng: -0.7239 },
  { slug: 'crevillente', name: 'Crevillente', province: 'Alicante', region: 'alicante', lat: 38.2499, lng: -0.8097 },
  { slug: 'denia', name: 'Dénia', province: 'Alicante', region: 'alicante', lat: 38.8407, lng: 0.1057 },
  { slug: 'el-campello', name: 'El Campello', province: 'Alicante', region: 'alicante', lat: 38.4288, lng: -0.3977 },
  { slug: 'elche', name: 'Elche (Elx)', province: 'Alicante', region: 'alicante', lat: 38.2669, lng: -0.6983 },
  { slug: 'elda', name: 'Elda', province: 'Alicante', region: 'alicante', lat: 38.4778, lng: -0.7916 },
  { slug: 'finestrat', name: 'Finestrat', province: 'Alicante', region: 'alicante', lat: 38.5678, lng: -0.2094 },
  { slug: 'guardamar', name: 'Guardamar del Segura', province: 'Alicante', region: 'alicante', lat: 38.0886, lng: -0.6519 },
  { slug: 'ibi', name: 'Ibi', province: 'Alicante', region: 'alicante', lat: 38.6253, lng: -0.5723 },
  { slug: 'javea', name: 'Jávea (Xàbia)', province: 'Alicante', region: 'alicante', lat: 38.7891, lng: 0.1662 },
  { slug: 'alfaz-del-pi', name: "L'Alfàs del Pi", province: 'Alicante', region: 'alicante', lat: 38.5786, lng: -0.1017 },
  { slug: 'moraira', name: 'Moraira', province: 'Alicante', region: 'alicante', lat: 38.6870, lng: 0.1420 },
  { slug: 'mutxamel', name: 'Mutxamel', province: 'Alicante', region: 'alicante', lat: 38.4158, lng: -0.4453 },
  { slug: 'novelda', name: 'Novelda', province: 'Alicante', region: 'alicante', lat: 38.3848, lng: -0.7677 },
  { slug: 'orihuela', name: 'Orihuela', province: 'Alicante', region: 'alicante', lat: 38.0848, lng: -0.9440 },
  { slug: 'orihuela-costa', name: 'Orihuela Costa', province: 'Alicante', region: 'alicante', lat: 37.9260, lng: -0.7580 },
  { slug: 'pilar-de-la-horadada', name: 'Pilar de la Horadada', province: 'Alicante', region: 'alicante', lat: 37.8672, lng: -0.7897 },
  { slug: 'polop', name: 'Polop', province: 'Alicante', region: 'alicante', lat: 38.6197, lng: -0.1281 },
  { slug: 'san-miguel-de-salinas', name: 'San Miguel de Salinas', province: 'Alicante', region: 'alicante', lat: 37.9767, lng: -0.7889 },
  { slug: 'san-vicent-del-raspeig', name: 'San Vicent del Raspeig', province: 'Alicante', region: 'alicante', lat: 38.3964, lng: -0.5255 },
  { slug: 'sant-joan-d-alacant', name: "Sant Joan d'Alacant", province: 'Alicante', region: 'alicante', lat: 38.4015, lng: -0.4362 },
  { slug: 'santa-pola', name: 'Santa Pola', province: 'Alicante', region: 'alicante', lat: 38.1938, lng: -0.5619 },
  { slug: 'torrevieja', name: 'Torrevieja', province: 'Alicante', region: 'alicante', lat: 37.9787, lng: -0.6822 },
  { slug: 'villajoyosa', name: 'Villajoyosa', province: 'Alicante', region: 'alicante', lat: 38.5058, lng: -0.2331 },
  { slug: 'villena', name: 'Villena', province: 'Alicante', region: 'alicante', lat: 38.6373, lng: -0.8657 },

  // Almería
  { slug: 'adra', name: 'Adra', province: 'Almería', region: 'almeria', lat: 36.7483, lng: -3.0208 },
  { slug: 'almeria', name: 'Almería', province: 'Almería', region: 'almeria', lat: 36.8340, lng: -2.4637 },
  { slug: 'berja', name: 'Berja', province: 'Almería', region: 'almeria', lat: 36.8469, lng: -2.9497 },
  { slug: 'el-ejido', name: 'El Ejido', province: 'Almería', region: 'almeria', lat: 36.7763, lng: -2.8146 },
  { slug: 'huercal-overa', name: 'Huercal-Overa', province: 'Almería', region: 'almeria', lat: 37.3892, lng: -1.9430 },
  { slug: 'mojacar', name: 'Mojácar', province: 'Almería', region: 'almeria', lat: 37.1394, lng: -1.8511 },
  { slug: 'nijar', name: 'Níjar', province: 'Almería', region: 'almeria', lat: 36.9665, lng: -2.2060 },
  { slug: 'oria', name: 'Oria', province: 'Almería', region: 'almeria', lat: 37.4853, lng: -2.2929 },
  { slug: 'roquetas-de-mar', name: 'Roquetas de Mar', province: 'Almería', region: 'almeria', lat: 36.7642, lng: -2.6147 },
  { slug: 'vera', name: 'Vera', province: 'Almería', region: 'almeria', lat: 37.2469, lng: -1.8672 },
  { slug: 'vicar', name: 'Vícar', province: 'Almería', region: 'almeria', lat: 36.8316, lng: -2.6427 },

  // Asturias
  { slug: 'aviles', name: 'Avilés', province: 'Asturias', region: 'asturias', lat: 43.5547, lng: -5.9248 },
  { slug: 'corvera-de-asturias', name: 'Corvera de Asturias', province: 'Asturias', region: 'asturias', lat: 43.5355, lng: -5.8889 },
  { slug: 'gijon', name: 'Gijón', province: 'Asturias', region: 'asturias', lat: 43.5357, lng: -5.6615 },
  { slug: 'la-felguera', name: 'La Felguera', province: 'Asturias', region: 'asturias', lat: 43.3075, lng: -5.6909 },
  { slug: 'mieres', name: 'Mieres', province: 'Asturias', region: 'asturias', lat: 43.2500, lng: -5.7667 },
  { slug: 'natahoyo', name: 'Natahoyo', province: 'Asturias', region: 'asturias', lat: 43.5403, lng: -5.6823 },
  { slug: 'oviedo', name: 'Oviedo', province: 'Asturias', region: 'asturias', lat: 43.3603, lng: -5.8448 },
  { slug: 'sama', name: 'Sama', province: 'Asturias', region: 'asturias', lat: 43.2957, lng: -5.6842 },

  // Ávila
  { slug: 'avila', name: 'Ávila', province: 'Ávila', region: 'avila', lat: 40.6572, lng: -4.6995 },
  { slug: 'san-pascual', name: 'San Pascual', province: 'Ávila', region: 'avila', lat: 40.8814, lng: -4.7561 },

  // Badajoz
  { slug: 'almendralejo', name: 'Almendralejo', province: 'Badajoz', region: 'badajoz', lat: 38.6832, lng: -6.4075 },
  { slug: 'badajoz', name: 'Badajoz', province: 'Badajoz', region: 'badajoz', lat: 38.8779, lng: -6.9706 },
  { slug: 'don-benito', name: 'Don Benito', province: 'Badajoz', region: 'badajoz', lat: 38.9563, lng: -5.8616 },
  { slug: 'merida', name: 'Mérida', province: 'Badajoz', region: 'badajoz', lat: 38.9180, lng: -6.3429 },
  { slug: 'montijo', name: 'Montijo', province: 'Badajoz', region: 'badajoz', lat: 38.9084, lng: -6.6178 },
  { slug: 'villanueva-de-la-serena', name: 'Villanueva de la Serena', province: 'Badajoz', region: 'badajoz', lat: 38.9766, lng: -5.7974 },
  { slug: 'zafra', name: 'Zafra', province: 'Badajoz', region: 'badajoz', lat: 38.4254, lng: -6.4173 },

  // Baleares
  { slug: 'alcudia', name: 'Alcúdia', province: 'Baleares', region: 'baleares', lat: 39.8531, lng: 3.1219 },
  { slug: 'andratx', name: 'Andratx', province: 'Baleares', region: 'baleares', lat: 39.5747, lng: 2.4211 },
  { slug: 'calvia', name: 'Calvià', province: 'Baleares', region: 'baleares', lat: 39.5658, lng: 2.5064 },
  { slug: 'ciutadella', name: 'Ciutadella de Menorca', province: 'Baleares', region: 'baleares', lat: 40.0000, lng: 3.8383 },
  { slug: 'felanitx', name: 'Felanitx', province: 'Baleares', region: 'baleares', lat: 39.4696, lng: 3.1483 },
  { slug: 'ibiza', name: 'Ibiza (Eivissa)', province: 'Baleares', region: 'baleares', lat: 38.9089, lng: 1.4328 },
  { slug: 'inca', name: 'Inca', province: 'Baleares', region: 'baleares', lat: 39.7211, lng: 2.9109 },
  { slug: 'llucmajor', name: 'Llucmajor', province: 'Baleares', region: 'baleares', lat: 39.4909, lng: 2.8911 },
  { slug: 'mahon', name: 'Mahón (Maó)', province: 'Baleares', region: 'baleares', lat: 39.8885, lng: 4.2658 },
  { slug: 'manacor', name: 'Manacor', province: 'Baleares', region: 'baleares', lat: 39.5697, lng: 3.2089 },
  { slug: 'marratxi', name: 'Marratxí', province: 'Baleares', region: 'baleares', lat: 39.6214, lng: 2.7253 },
  { slug: 'palma', name: 'Palma de Mallorca', province: 'Baleares', region: 'baleares', lat: 39.5696, lng: 2.6502 },
  { slug: 'pollenca', name: 'Pollença', province: 'Baleares', region: 'baleares', lat: 39.8767, lng: 3.0164 },
  { slug: 'sant-agusti', name: 'Sant Agustí', province: 'Baleares', region: 'baleares', lat: 39.5506, lng: 2.5974 },
  { slug: 'sant-antoni-de-portmany', name: 'Sant Antoni de Portmany', province: 'Baleares', region: 'baleares', lat: 38.9807, lng: 1.3036 },
  { slug: 'santa-eularia', name: 'Santa Eulària des Riu', province: 'Baleares', region: 'baleares', lat: 38.9847, lng: 1.5347 },
  { slug: 'santanyi', name: 'Santanyí', province: 'Baleares', region: 'baleares', lat: 39.3547, lng: 3.1289 },
  { slug: 'soller', name: 'Sóller', province: 'Baleares', region: 'baleares', lat: 39.7658, lng: 2.7156 },

  // Barcelona
  { slug: 'arenys-de-mar', name: 'Arenys de Mar', province: 'Barcelona', region: 'barcelona', lat: 41.5819, lng: 2.5494 },
  { slug: 'badalona', name: 'Badalona', province: 'Barcelona', region: 'barcelona', lat: 41.4500, lng: 2.2474 },
  { slug: 'barbera-del-valles', name: 'Barberà del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.5159, lng: 2.1246 },
  { slug: 'barcelona', name: 'Barcelona', province: 'Barcelona', region: 'barcelona', lat: 41.3874, lng: 2.1686 },
  { slug: 'barri-de-sant-andreu', name: 'Barri de Sant Andreu', province: 'Barcelona', region: 'barcelona', lat: 41.4369, lng: 2.1902 },
  { slug: 'berga', name: 'Berga', province: 'Barcelona', region: 'barcelona', lat: 42.1043, lng: 1.8463 },
  { slug: 'caldes-de-montbui', name: 'Caldes de Montbui', province: 'Barcelona', region: 'barcelona', lat: 41.6333, lng: 2.1667 },
  { slug: 'calella', name: 'Calella', province: 'Barcelona', region: 'barcelona', lat: 41.6138, lng: 2.6542 },
  { slug: 'canovelles', name: 'Canovelles', province: 'Barcelona', region: 'barcelona', lat: 41.6167, lng: 2.2833 },
  { slug: 'cardedeu', name: 'Cardedeu', province: 'Barcelona', region: 'barcelona', lat: 41.6398, lng: 2.3574 },
  { slug: 'castellar-del-valles', name: 'Castellar del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.6167, lng: 2.0833 },
  { slug: 'castelldefels', name: 'Castelldefels', province: 'Barcelona', region: 'barcelona', lat: 41.2779, lng: 1.9703 },
  { slug: 'cerdanyola-del-valles', name: 'Cerdanyola del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.4911, lng: 2.1408 },
  { slug: 'cornella-de-llobregat', name: 'Cornellà de Llobregat', province: 'Barcelona', region: 'barcelona', lat: 41.3500, lng: 2.0833 },
  { slug: 'el-besos-i-el-maresme', name: 'el Besòs i el Maresme', province: 'Barcelona', region: 'barcelona', lat: 41.4131, lng: 2.2174 },
  { slug: 'el-masnou', name: 'El Masnou', province: 'Barcelona', region: 'barcelona', lat: 41.4798, lng: 2.3188 },
  { slug: 'el-prat-de-llobregat', name: 'El Prat de Llobregat', province: 'Barcelona', region: 'barcelona', lat: 41.3278, lng: 2.0947 },
  { slug: 'el-turo-de-la-peira', name: 'el Turó de la Peira', province: 'Barcelona', region: 'barcelona', lat: 41.4323, lng: 2.1690 },
  { slug: 'esparreguera', name: 'Esparreguera', province: 'Barcelona', region: 'barcelona', lat: 41.5381, lng: 1.8702 },
  { slug: 'esplugues-de-llobregat', name: 'Esplugues de Llobregat', province: 'Barcelona', region: 'barcelona', lat: 41.3773, lng: 2.0881 },
  { slug: 'gava', name: 'Gavà', province: 'Barcelona', region: 'barcelona', lat: 41.3060, lng: 2.0012 },
  { slug: 'granollers', name: 'Granollers', province: 'Barcelona', region: 'barcelona', lat: 41.6080, lng: 2.2877 },
  { slug: 'horta', name: 'Horta', province: 'Barcelona', region: 'barcelona', lat: 41.4363, lng: 2.1572 },
  { slug: 'igualada', name: 'Igualada', province: 'Barcelona', region: 'barcelona', lat: 41.5810, lng: 1.6172 },
  { slug: 'l-hospitalet-de-llobregat', name: "L'Hospitalet de Llobregat", province: 'Barcelona', region: 'barcelona', lat: 41.3597, lng: 2.1003 },
  { slug: 'la-guineueta', name: 'la Guineueta', province: 'Barcelona', region: 'barcelona', lat: 41.4388, lng: 2.1689 },
  { slug: 'la-maternitat-i-sant-ramon', name: 'la Maternitat i Sant Ramon', province: 'Barcelona', region: 'barcelona', lat: 41.3813, lng: 2.1174 },
  { slug: 'la-prosperitat', name: 'la Prosperitat', province: 'Barcelona', region: 'barcelona', lat: 41.4427, lng: 2.1820 },
  { slug: 'la-sagrera', name: 'La Sagrera', province: 'Barcelona', region: 'barcelona', lat: 41.4227, lng: 2.1859 },
  { slug: 'la-verneda-i-la-pau', name: 'la Verneda i la Pau', province: 'Barcelona', region: 'barcelona', lat: 41.4240, lng: 2.2030 },
  { slug: 'les-roquetes', name: 'les Roquetes', province: 'Barcelona', region: 'barcelona', lat: 41.4481, lng: 2.1752 },
  { slug: 'llefia', name: 'Llefià', province: 'Barcelona', region: 'barcelona', lat: 41.4381, lng: 2.2195 },
  { slug: 'malgrat-de-mar', name: 'Malgrat de Mar', province: 'Barcelona', region: 'barcelona', lat: 41.6466, lng: 2.7414 },
  { slug: 'manlleu', name: 'Manlleu', province: 'Barcelona', region: 'barcelona', lat: 42.0023, lng: 2.2848 },
  { slug: 'manresa', name: 'Manresa', province: 'Barcelona', region: 'barcelona', lat: 41.7281, lng: 1.8240 },
  { slug: 'martorell', name: 'Martorell', province: 'Barcelona', region: 'barcelona', lat: 41.4740, lng: 1.9306 },
  { slug: 'mataro', name: 'Mataró', province: 'Barcelona', region: 'barcelona', lat: 41.5421, lng: 2.4445 },
  { slug: 'molins-de-rei', name: 'Molins de Rei', province: 'Barcelona', region: 'barcelona', lat: 41.4167, lng: 2.0167 },
  { slug: 'mollet-del-valles', name: 'Mollet del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.5403, lng: 2.2131 },
  { slug: 'montcada-i-reixac', name: 'Montcada i Reixac', province: 'Barcelona', region: 'barcelona', lat: 41.4833, lng: 2.1833 },
  { slug: 'montornes-del-valles', name: 'Montornès del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.5421, lng: 2.2675 },
  { slug: 'nou-barris', name: 'Nou Barris', province: 'Barcelona', region: 'barcelona', lat: 41.4416, lng: 2.1773 },
  { slug: 'olesa-de-montserrat', name: 'Olesa de Montserrat', province: 'Barcelona', region: 'barcelona', lat: 41.5437, lng: 1.8941 },
  { slug: 'parets-del-valles', name: 'Parets del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.5748, lng: 2.2331 },
  { slug: 'piera', name: 'Piera', province: 'Barcelona', region: 'barcelona', lat: 41.5223, lng: 1.7508 },
  { slug: 'pineda-de-mar', name: 'Pineda de Mar', province: 'Barcelona', region: 'barcelona', lat: 41.6276, lng: 2.6889 },
  { slug: 'porta', name: 'Porta', province: 'Barcelona', region: 'barcelona', lat: 41.4349, lng: 2.1788 },
  { slug: 'premia-de-mar', name: 'Premià de Mar', province: 'Barcelona', region: 'barcelona', lat: 41.4921, lng: 2.3652 },
  { slug: 'ripollet', name: 'Ripollet', province: 'Barcelona', region: 'barcelona', lat: 41.4969, lng: 2.1574 },
  { slug: 'rubi', name: 'Rubí', province: 'Barcelona', region: 'barcelona', lat: 41.4923, lng: 2.0330 },
  { slug: 'sabadell', name: 'Sabadell', province: 'Barcelona', region: 'barcelona', lat: 41.5433, lng: 2.1094 },
  { slug: 'sant-adria-de-besos', name: 'Sant Adrià de Besòs', province: 'Barcelona', region: 'barcelona', lat: 41.4307, lng: 2.2186 },
  { slug: 'sant-andreu', name: 'Sant Andreu', province: 'Barcelona', region: 'barcelona', lat: 41.4354, lng: 2.1898 },
  { slug: 'sant-andreu-de-la-barca', name: 'Sant Andreu de la Barca', province: 'Barcelona', region: 'barcelona', lat: 41.4466, lng: 1.9719 },
  { slug: 'sant-boi-de-llobregat', name: 'Sant Boi de Llobregat', province: 'Barcelona', region: 'barcelona', lat: 41.3436, lng: 2.0366 },
  { slug: 'sant-celoni', name: 'Sant Celoni', province: 'Barcelona', region: 'barcelona', lat: 41.6892, lng: 2.4897 },
  { slug: 'sant-cugat-del-valles', name: 'Sant Cugat del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.4706, lng: 2.0861 },
  { slug: 'sant-feliu-de-llobregat', name: 'Sant Feliu de Llobregat', province: 'Barcelona', region: 'barcelona', lat: 41.3833, lng: 2.0500 },
  { slug: 'sant-joan-despi', name: 'Sant Joan Despí', province: 'Barcelona', region: 'barcelona', lat: 41.3672, lng: 2.0574 },
  { slug: 'sant-just-desvern', name: 'Sant Just Desvern', province: 'Barcelona', region: 'barcelona', lat: 41.3839, lng: 2.0676 },
  { slug: 'sant-marti', name: 'Sant Martí', province: 'Barcelona', region: 'barcelona', lat: 41.4181, lng: 2.1993 },
  { slug: 'sant-marti-de-provencals', name: 'Sant Martí de Provençals', province: 'Barcelona', region: 'barcelona', lat: 41.4202, lng: 2.1963 },
  { slug: 'sant-quirze-del-valles', name: 'Sant Quirze del Vallès', province: 'Barcelona', region: 'barcelona', lat: 41.5333, lng: 2.0833 },
  { slug: 'sant-vicenc-dels-horts', name: 'Sant Vicenç dels Horts', province: 'Barcelona', region: 'barcelona', lat: 41.3932, lng: 2.0069 },
  { slug: 'santa-coloma-de-gramenet', name: 'Santa Coloma de Gramenet', province: 'Barcelona', region: 'barcelona', lat: 41.4515, lng: 2.2081 },
  { slug: 'santa-perpetua-de-mogoda', name: 'Santa Perpètua de Mogoda', province: 'Barcelona', region: 'barcelona', lat: 41.5333, lng: 2.1833 },
  { slug: 'sarria', name: 'Sarrià', province: 'Barcelona', region: 'barcelona', lat: 41.4027, lng: 2.1162 },
  { slug: 'sitges', name: 'Sitges', province: 'Barcelona', region: 'barcelona', lat: 41.2371, lng: 1.8055 },
  { slug: 'terrassa', name: 'Terrassa', province: 'Barcelona', region: 'barcelona', lat: 41.5667, lng: 2.0167 },
  { slug: 'tordera', name: 'Tordera', province: 'Barcelona', region: 'barcelona', lat: 41.6991, lng: 2.7189 },
  { slug: 'vic', name: 'Vic', province: 'Barcelona', region: 'barcelona', lat: 41.9301, lng: 2.2549 },
  { slug: 'viladecans', name: 'Viladecans', province: 'Barcelona', region: 'barcelona', lat: 41.3141, lng: 2.0143 },
  { slug: 'vilafranca-del-penedes', name: 'Vilafranca del Penedès', province: 'Barcelona', region: 'barcelona', lat: 41.3462, lng: 1.6971 },
  { slug: 'vilanova-i-la-geltru', name: 'Vilanova i la Geltrú', province: 'Barcelona', region: 'barcelona', lat: 41.2239, lng: 1.7251 },
  { slug: 'vilapicina-i-la-torre-llobeta', name: 'Vilapicina i la Torre Llobeta', province: 'Barcelona', region: 'barcelona', lat: 41.4286, lng: 2.1741 },
  { slug: 'vilaseca', name: 'Vilaseca', province: 'Barcelona', region: 'barcelona', lat: 42.0617, lng: 2.2553 },
  { slug: 'vilassar-de-mar', name: 'Vilassar de Mar', province: 'Barcelona', region: 'barcelona', lat: 41.5051, lng: 2.3923 },

  // Burgos
  { slug: 'aranda-de-duero', name: 'Aranda de Duero', province: 'Burgos', region: 'burgos', lat: 41.6704, lng: -3.6892 },
  { slug: 'arcos', name: 'Arcos', province: 'Burgos', region: 'burgos', lat: 42.2666, lng: -3.7546 },
  { slug: 'burgos', name: 'Burgos', province: 'Burgos', region: 'burgos', lat: 42.3411, lng: -3.7018 },
  { slug: 'gamonal', name: 'Gamonal', province: 'Burgos', region: 'burgos', lat: 42.3566, lng: -3.6732 },
  { slug: 'miranda-de-ebro', name: 'Miranda de Ebro', province: 'Burgos', region: 'burgos', lat: 42.6865, lng: -2.9470 },

  // Cáceres
  { slug: 'caceres', name: 'Cáceres', province: 'Cáceres', region: 'caceres', lat: 39.4765, lng: -6.3722 },
  { slug: 'navalmoral-de-la-mata', name: 'Navalmoral de la Mata', province: 'Cáceres', region: 'caceres', lat: 39.8916, lng: -5.5406 },
  { slug: 'plasencia', name: 'Plasencia', province: 'Cáceres', region: 'caceres', lat: 40.0312, lng: -6.0884 },
  { slug: 'valdefuentes', name: 'Valdefuentes', province: 'Cáceres', region: 'caceres', lat: 39.2743, lng: -6.1218 },

  // Cádiz
  { slug: 'algeciras', name: 'Algeciras', province: 'Cádiz', region: 'cadiz', lat: 36.1333, lng: -5.4505 },
  { slug: 'arcos-de-la-frontera', name: 'Arcos de la Frontera', province: 'Cádiz', region: 'cadiz', lat: 36.7507, lng: -5.8106 },
  { slug: 'barbate', name: 'Barbate', province: 'Cádiz', region: 'cadiz', lat: 36.1924, lng: -5.9219 },
  { slug: 'cadiz', name: 'Cádiz', province: 'Cádiz', region: 'cadiz', lat: 36.5271, lng: -6.2886 },
  { slug: 'chiclana', name: 'Chiclana de la Frontera', province: 'Cádiz', region: 'cadiz', lat: 36.4194, lng: -6.1467 },
  { slug: 'chipiona', name: 'Chipiona', province: 'Cádiz', region: 'cadiz', lat: 36.7366, lng: -6.4370 },
  { slug: 'conil-de-la-frontera', name: 'Conil de la Frontera', province: 'Cádiz', region: 'cadiz', lat: 36.2772, lng: -6.0885 },
  { slug: 'el-puerto-de-santa-maria', name: 'El Puerto de Santa María', province: 'Cádiz', region: 'cadiz', lat: 36.5939, lng: -6.2330 },
  { slug: 'jerez-de-la-frontera', name: 'Jerez de la Frontera', province: 'Cádiz', region: 'cadiz', lat: 36.6865, lng: -6.1361 },
  { slug: 'la-linea-de-la-concepcion', name: 'La Línea de la Concepción', province: 'Cádiz', region: 'cadiz', lat: 36.1681, lng: -5.3478 },
  { slug: 'los-barrios', name: 'Los Barrios', province: 'Cádiz', region: 'cadiz', lat: 36.1848, lng: -5.4921 },
  { slug: 'puerto-real', name: 'Puerto Real', province: 'Cádiz', region: 'cadiz', lat: 36.5282, lng: -6.1901 },
  { slug: 'rota', name: 'Rota', province: 'Cádiz', region: 'cadiz', lat: 36.6236, lng: -6.3600 },
  { slug: 'san-fernando', name: 'San Fernando', province: 'Cádiz', region: 'cadiz', lat: 36.4759, lng: -6.1982 },
  { slug: 'san-roque', name: 'San Roque', province: 'Cádiz', region: 'cadiz', lat: 36.2098, lng: -5.3845 },
  { slug: 'sanlucar-de-barrameda', name: 'Sanlúcar de Barrameda', province: 'Cádiz', region: 'cadiz', lat: 36.7781, lng: -6.3515 },
  { slug: 'sotogrande', name: 'Sotogrande', province: 'Cádiz', region: 'cadiz', lat: 36.2870, lng: -5.2810 },
  { slug: 'tarifa', name: 'Tarifa', province: 'Cádiz', region: 'cadiz', lat: 36.0143, lng: -5.6044 },
  { slug: 'ubrique', name: 'Ubrique', province: 'Cádiz', region: 'cadiz', lat: 36.6778, lng: -5.4460 },

  // Cantabria
  { slug: 'camargo', name: 'Camargo', province: 'Cantabria', region: 'cantabria', lat: 43.4074, lng: -3.8850 },
  { slug: 'castro-urdiales', name: 'Castro-Urdiales', province: 'Cantabria', region: 'cantabria', lat: 43.3828, lng: -3.2204 },
  { slug: 'comillas', name: 'Comillas', province: 'Cantabria', region: 'cantabria', lat: 43.3860, lng: -4.2916 },
  { slug: 'el-astillero', name: 'El Astillero', province: 'Cantabria', region: 'cantabria', lat: 43.4009, lng: -3.8205 },
  { slug: 'santander', name: 'Santander', province: 'Cantabria', region: 'cantabria', lat: 43.4659, lng: -3.8049 },
  { slug: 'torrelavega', name: 'Torrelavega', province: 'Cantabria', region: 'cantabria', lat: 43.3494, lng: -4.0479 },

  // Castellón
  { slug: 'almassora', name: 'Almassora', province: 'Castellón', region: 'castellon', lat: 39.9473, lng: -0.0631 },
  { slug: 'almenara', name: 'Almenara', province: 'Castellón', region: 'castellon', lat: 39.7500, lng: -0.2167 },
  { slug: 'benicarlo', name: 'Benicarló', province: 'Castellón', region: 'castellon', lat: 40.4165, lng: 0.4271 },
  { slug: 'benicassim', name: 'Benicàssim', province: 'Castellón', region: 'castellon', lat: 40.0500, lng: 0.0667 },
  { slug: 'burriana', name: 'Burriana', province: 'Castellón', region: 'castellon', lat: 39.8890, lng: -0.0850 },
  { slug: 'castello-de-la-plana', name: 'Castelló de la Plana', province: 'Castellón', region: 'castellon', lat: 39.9857, lng: -0.0493 },
  { slug: 'el-grao', name: 'El Grao', province: 'Castellón', region: 'castellon', lat: 39.9736, lng: 0.0128 },
  { slug: 'onda', name: 'Onda', province: 'Castellón', region: 'castellon', lat: 39.9650, lng: -0.2604 },
  { slug: 'vila-real', name: 'Vila-real', province: 'Castellón', region: 'castellon', lat: 39.9383, lng: -0.1009 },
  { slug: 'vinaros', name: 'Vinaròs', province: 'Castellón', region: 'castellon', lat: 40.4703, lng: 0.4756 },

  // Ceuta
  { slug: 'ceuta', name: 'Ceuta', province: 'Ceuta', region: 'ceuta', lat: 35.8892, lng: -5.3204 },

  // Ciudad Real
  { slug: 'alcazar-de-san-juan', name: 'Alcázar de San Juan', province: 'Ciudad Real', region: 'ciudad_real', lat: 39.3901, lng: -3.2083 },
  { slug: 'almagro', name: 'Almagro', province: 'Ciudad Real', region: 'ciudad_real', lat: 38.8894, lng: -3.7113 },
  { slug: 'campo-de-criptana', name: 'Campo de Criptana', province: 'Ciudad Real', region: 'ciudad_real', lat: 39.4046, lng: -3.1249 },
  { slug: 'ciudad-real', name: 'Ciudad Real', province: 'Ciudad Real', region: 'ciudad_real', lat: 38.9863, lng: -3.9291 },
  { slug: 'daimiel', name: 'Daimiel', province: 'Ciudad Real', region: 'ciudad_real', lat: 39.0700, lng: -3.6150 },
  { slug: 'la-solana', name: 'La Solana', province: 'Ciudad Real', region: 'ciudad_real', lat: 38.9442, lng: -3.2381 },
  { slug: 'manzanares', name: 'Manzanares', province: 'Ciudad Real', region: 'ciudad_real', lat: 38.9992, lng: -3.3699 },
  { slug: 'miguelturra', name: 'Miguelturra', province: 'Ciudad Real', region: 'ciudad_real', lat: 38.9644, lng: -3.8905 },
  { slug: 'puertollano', name: 'Puertollano', province: 'Ciudad Real', region: 'ciudad_real', lat: 38.6871, lng: -4.1073 },
  { slug: 'tomelloso', name: 'Tomelloso', province: 'Ciudad Real', region: 'ciudad_real', lat: 39.1576, lng: -3.0216 },
  { slug: 'valdepenas', name: 'Valdepeñas', province: 'Ciudad Real', region: 'ciudad_real', lat: 38.7621, lng: -3.3848 },

  // Córdoba
  { slug: 'baena', name: 'Baena', province: 'Córdoba', region: 'cordoba', lat: 37.6167, lng: -4.3224 },
  { slug: 'cabra', name: 'Cabra', province: 'Córdoba', region: 'cordoba', lat: 37.4725, lng: -4.4421 },
  { slug: 'cordoba', name: 'Córdoba', province: 'Córdoba', region: 'cordoba', lat: 37.8916, lng: -4.7728 },
  { slug: 'el-viso', name: 'El Viso', province: 'Córdoba', region: 'cordoba', lat: 38.4833, lng: -4.9500 },
  { slug: 'lucena', name: 'Lucena', province: 'Córdoba', region: 'cordoba', lat: 37.4088, lng: -4.4852 },
  { slug: 'montilla', name: 'Montilla', province: 'Córdoba', region: 'cordoba', lat: 37.5863, lng: -4.6380 },
  { slug: 'palma-del-rio', name: 'Palma del Río', province: 'Córdoba', region: 'cordoba', lat: 37.7002, lng: -5.2812 },
  { slug: 'pozoblanco', name: 'Pozoblanco', province: 'Córdoba', region: 'cordoba', lat: 38.3791, lng: -4.8483 },
  { slug: 'priego-de-cordoba', name: 'Priego de Córdoba', province: 'Córdoba', region: 'cordoba', lat: 37.4381, lng: -4.1952 },
  { slug: 'puente-genil', name: 'Puente-Genil', province: 'Córdoba', region: 'cordoba', lat: 37.3894, lng: -4.7669 },

  // Cuenca
  { slug: 'cuenca', name: 'Cuenca', province: 'Cuenca', region: 'cuenca', lat: 40.0667, lng: -2.1333 },
  { slug: 'tarancon', name: 'Tarancón', province: 'Cuenca', region: 'cuenca', lat: 40.0085, lng: -3.0073 },

  // Girona
  { slug: 'banyoles', name: 'Banyoles', province: 'Girona', region: 'girona', lat: 42.1167, lng: 2.7667 },
  { slug: 'blanes', name: 'Blanes', province: 'Girona', region: 'girona', lat: 41.6748, lng: 2.7908 },
  { slug: 'empuriabrava', name: 'Empuriabrava', province: 'Girona', region: 'girona', lat: 42.2472, lng: 3.1219 },
  { slug: 'figueres', name: 'Figueres', province: 'Girona', region: 'girona', lat: 42.2664, lng: 2.9616 },
  { slug: 'girona', name: 'Girona', province: 'Girona', region: 'girona', lat: 41.9794, lng: 2.8214 },
  { slug: 'lescala', name: "L'Escala", province: 'Girona', region: 'girona', lat: 42.1236, lng: 3.1319 },
  { slug: 'lloret-de-mar', name: 'Lloret de Mar', province: 'Girona', region: 'girona', lat: 41.7005, lng: 2.8455 },
  { slug: 'olot', name: 'Olot', province: 'Girona', region: 'girona', lat: 42.1810, lng: 2.4901 },
  { slug: 'palafrugell', name: 'Palafrugell', province: 'Girona', region: 'girona', lat: 41.9175, lng: 3.1631 },
  { slug: 'palamos', name: 'Palamós', province: 'Girona', region: 'girona', lat: 41.8484, lng: 3.1291 },
  { slug: 'platja-daro', name: "Platja d'Aro", province: 'Girona', region: 'girona', lat: 41.8175, lng: 3.0656 },
  { slug: 'roses', name: 'Roses', province: 'Girona', region: 'girona', lat: 42.2622, lng: 3.1764 },
  { slug: 'sant-feliu-de-guixols', name: 'Sant Feliu de Guíxols', province: 'Girona', region: 'girona', lat: 41.7833, lng: 3.0333 },

  // Granada
  { slug: 'albolote', name: 'Albolote', province: 'Granada', region: 'granada', lat: 37.2309, lng: -3.6551 },
  { slug: 'almunecar', name: 'Almuñécar', province: 'Granada', region: 'granada', lat: 36.7325, lng: -3.6917 },
  { slug: 'armilla', name: 'Armilla', province: 'Granada', region: 'granada', lat: 37.1439, lng: -3.6253 },
  { slug: 'atarfe', name: 'Atarfe', province: 'Granada', region: 'granada', lat: 37.2248, lng: -3.6869 },
  { slug: 'baza', name: 'Baza', province: 'Granada', region: 'granada', lat: 37.4907, lng: -2.7726 },
  { slug: 'granada', name: 'Granada', province: 'Granada', region: 'granada', lat: 37.1882, lng: -3.6067 },
  { slug: 'guadix', name: 'Guadix', province: 'Granada', region: 'granada', lat: 37.2993, lng: -3.1392 },
  { slug: 'las-gabias', name: 'Las Gabias', province: 'Granada', region: 'granada', lat: 37.1355, lng: -3.6703 },
  { slug: 'loja', name: 'Loja', province: 'Granada', region: 'granada', lat: 37.1689, lng: -4.1513 },
  { slug: 'maracena', name: 'Maracena', province: 'Granada', region: 'granada', lat: 37.2076, lng: -3.6349 },
  { slug: 'motril', name: 'Motril', province: 'Granada', region: 'granada', lat: 36.7507, lng: -3.5179 },
  { slug: 'santafe', name: 'Santafé', province: 'Granada', region: 'granada', lat: 37.1886, lng: -3.7189 },
  { slug: 'zubia', name: 'Zubia', province: 'Granada', region: 'granada', lat: 37.1191, lng: -3.5840 },

  // Guadalajara
  { slug: 'azuqueca-de-henares', name: 'Azuqueca de Henares', province: 'Guadalajara', region: 'guadalajara', lat: 40.5657, lng: -3.2675 },
  { slug: 'guadalajara', name: 'Guadalajara', province: 'Guadalajara', region: 'guadalajara', lat: 40.6286, lng: -3.1618 },

  // Guipúzcoa
  { slug: 'arrasate-mondragon', name: 'Arrasate / Mondragón', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.0644, lng: -2.4898 },
  { slug: 'donostia-san-sebastian', name: 'Donostia / San Sebastián', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.3128, lng: -1.9750 },
  { slug: 'eibar', name: 'Eibar', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.1849, lng: -2.4716 },
  { slug: 'errenteria', name: 'Errenteria', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.3120, lng: -1.9023 },
  { slug: 'hernani', name: 'Hernani', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.2662, lng: -1.9762 },
  { slug: 'hondarribia', name: 'Hondarribia', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.3686, lng: -1.7962 },
  { slug: 'irun', name: 'Irun', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.3390, lng: -1.7894 },
  { slug: 'lasarte', name: 'Lasarte', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.2677, lng: -2.0217 },
  { slug: 'legazpi', name: 'Legazpi', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.0532, lng: -2.3369 },
  { slug: 'pasaia', name: 'Pasaia', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.3253, lng: -1.9271 },
  { slug: 'tolosa', name: 'Tolosa', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.1348, lng: -2.0780 },
  { slug: 'zarautz', name: 'Zarautz', province: 'Guipúzcoa', region: 'guipuzcoa', lat: 43.2844, lng: -2.1699 },

  // Huelva
  { slug: 'aljaraque', name: 'Aljaraque', province: 'Huelva', region: 'huelva', lat: 37.2699, lng: -7.0231 },
  { slug: 'almonte', name: 'Almonte', province: 'Huelva', region: 'huelva', lat: 37.2647, lng: -6.5167 },
  { slug: 'ayamonte', name: 'Ayamonte', province: 'Huelva', region: 'huelva', lat: 37.2133, lng: -7.4081 },
  { slug: 'cartaya', name: 'Cartaya', province: 'Huelva', region: 'huelva', lat: 37.2811, lng: -7.1507 },
  { slug: 'huelva', name: 'Huelva', province: 'Huelva', region: 'huelva', lat: 37.2664, lng: -6.9400 },
  { slug: 'isla-cristina', name: 'Isla Cristina', province: 'Huelva', region: 'huelva', lat: 37.2000, lng: -7.3167 },
  { slug: 'lepe', name: 'Lepe', province: 'Huelva', region: 'huelva', lat: 37.2548, lng: -7.2043 },
  { slug: 'moguer', name: 'Moguer', province: 'Huelva', region: 'huelva', lat: 37.2756, lng: -6.8385 },

  // Huesca
  { slug: 'barbastro', name: 'Barbastro', province: 'Huesca', region: 'huesca', lat: 42.0356, lng: 0.1269 },
  { slug: 'huesca', name: 'Huesca', province: 'Huesca', region: 'huesca', lat: 42.1362, lng: -0.4087 },
  { slug: 'monzon', name: 'Monzón', province: 'Huesca', region: 'huesca', lat: 41.9108, lng: 0.1941 },

  // Jaén
  { slug: 'alcala-la-real', name: 'Alcalá la Real', province: 'Jaén', region: 'jaen', lat: 37.4614, lng: -3.9230 },
  { slug: 'andujar', name: 'Andújar', province: 'Jaén', region: 'jaen', lat: 38.0392, lng: -4.0508 },
  { slug: 'baeza', name: 'Baeza', province: 'Jaén', region: 'jaen', lat: 37.9938, lng: -3.4710 },
  { slug: 'bailen', name: 'Bailén', province: 'Jaén', region: 'jaen', lat: 38.0964, lng: -3.7779 },
  { slug: 'campina', name: 'Campiña', province: 'Jaén', region: 'jaen', lat: 38.2190, lng: -2.9807 },
  { slug: 'jaen', name: 'Jaén', province: 'Jaén', region: 'jaen', lat: 37.7692, lng: -3.7903 },
  { slug: 'la-carolina', name: 'La Carolina', province: 'Jaén', region: 'jaen', lat: 38.2756, lng: -3.6153 },
  { slug: 'linares', name: 'Linares', province: 'Jaén', region: 'jaen', lat: 38.0952, lng: -3.6360 },
  { slug: 'martos', name: 'Martos', province: 'Jaén', region: 'jaen', lat: 37.7211, lng: -3.9726 },
  { slug: 'ubeda', name: 'Úbeda', province: 'Jaén', region: 'jaen', lat: 38.0133, lng: -3.3705 },

  // La Rioja
  { slug: 'calahorra', name: 'Calahorra', province: 'La Rioja', region: 'la_rioja', lat: 42.3051, lng: -1.9652 },
  { slug: 'logrono', name: 'Logroño', province: 'La Rioja', region: 'la_rioja', lat: 42.4661, lng: -2.4512 },

  // Las Palmas
  { slug: 'aguimes', name: 'Agüimes', province: 'Las Palmas', region: 'las_palmas', lat: 27.9054, lng: -15.4461 },
  { slug: 'arrecife', name: 'Arrecife', province: 'Las Palmas', region: 'las_palmas', lat: 28.9630, lng: -13.5477 },
  { slug: 'arucas', name: 'Arucas', province: 'Las Palmas', region: 'las_palmas', lat: 28.1198, lng: -15.5233 },
  { slug: 'caleta-de-fuste', name: 'Caleta de Fuste (Antigua)', province: 'Las Palmas', region: 'las_palmas', lat: 28.3944, lng: -13.8608 },
  { slug: 'carrizal', name: 'Carrizal', province: 'Las Palmas', region: 'las_palmas', lat: 27.9116, lng: -15.4056 },
  { slug: 'corralejo', name: 'Corralejo (La Oliva)', province: 'Las Palmas', region: 'las_palmas', lat: 28.7397, lng: -13.8672 },
  { slug: 'galdar', name: 'Gáldar', province: 'Las Palmas', region: 'las_palmas', lat: 28.1470, lng: -15.6502 },
  { slug: 'ingenio', name: 'Ingenio', province: 'Las Palmas', region: 'las_palmas', lat: 27.9185, lng: -15.4343 },
  { slug: 'las-palmas', name: 'Las Palmas de Gran Canaria', province: 'Las Palmas', region: 'las_palmas', lat: 28.1235, lng: -15.4363 },
  { slug: 'maspalomas', name: 'Maspalomas', province: 'Las Palmas', region: 'las_palmas', lat: 27.7606, lng: -15.5860 },
  { slug: 'pajara', name: 'Pájara', province: 'Las Palmas', region: 'las_palmas', lat: 28.3504, lng: -14.1076 },
  { slug: 'playa-blanca', name: 'Playa Blanca (Yaiza)', province: 'Las Palmas', region: 'las_palmas', lat: 28.8617, lng: -13.8244 },
  { slug: 'puerto-del-carmen', name: 'Puerto del Carmen (Tías)', province: 'Las Palmas', region: 'las_palmas', lat: 28.9236, lng: -13.6647 },
  { slug: 'puerto-del-rosario', name: 'Puerto del Rosario', province: 'Las Palmas', region: 'las_palmas', lat: 28.5004, lng: -13.8627 },
  { slug: 'puerto-rico-mogan', name: 'Puerto Rico (Mogán)', province: 'Las Palmas', region: 'las_palmas', lat: 27.7897, lng: -15.7089 },
  { slug: 'san-bartolome', name: 'San Bartolomé', province: 'Las Palmas', region: 'las_palmas', lat: 29.0009, lng: -13.6130 },
  { slug: 'san-bartolome-de-tirajana', name: 'San Bartolomé de Tirajana', province: 'Las Palmas', region: 'las_palmas', lat: 27.9248, lng: -15.5733 },
  { slug: 'santa-brigida', name: 'Santa Brígida', province: 'Las Palmas', region: 'las_palmas', lat: 28.0320, lng: -15.5043 },
  { slug: 'santa-lucia', name: 'Santa Lucía', province: 'Las Palmas', region: 'las_palmas', lat: 27.9117, lng: -15.5407 },
  { slug: 'teguise', name: 'Teguise', province: 'Las Palmas', region: 'las_palmas', lat: 29.0605, lng: -13.5640 },
  { slug: 'telde', name: 'Telde', province: 'Las Palmas', region: 'las_palmas', lat: 27.9924, lng: -15.4192 },

  // León
  { slug: 'carmenes', name: 'Cármenes', province: 'León', region: 'leon', lat: 42.9586, lng: -5.5735 },
  { slug: 'leon', name: 'León', province: 'León', region: 'leon', lat: 42.6000, lng: -5.5703 },
  { slug: 'ponferrada', name: 'Ponferrada', province: 'León', region: 'leon', lat: 42.5466, lng: -6.5962 },
  { slug: 'san-andres-del-rabanedo', name: 'San Andrés del Rabanedo', province: 'León', region: 'leon', lat: 42.6117, lng: -5.6167 },
  { slug: 'villaquilambre', name: 'Villaquilambre', province: 'León', region: 'leon', lat: 42.6469, lng: -5.5583 },

  // Lleida
  { slug: 'balaguer', name: 'Balaguer', province: 'Lleida', region: 'lleida', lat: 41.7912, lng: 0.8109 },
  { slug: 'lleida', name: 'Lleida', province: 'Lleida', region: 'lleida', lat: 41.6167, lng: 0.6222 },
  { slug: 'tarrega', name: 'Tàrrega', province: 'Lleida', region: 'lleida', lat: 41.6470, lng: 1.1396 },

  // Lugo
  { slug: 'lugo', name: 'Lugo', province: 'Lugo', region: 'lugo', lat: 43.0099, lng: -7.5560 },
  { slug: 'monforte-de-lemos', name: 'Monforte de Lemos', province: 'Lugo', region: 'lugo', lat: 42.5217, lng: -7.5142 },
  { slug: 'viveiro', name: 'Viveiro', province: 'Lugo', region: 'lugo', lat: 43.6623, lng: -7.5934 },

  // Madrid
  { slug: 'abrantes', name: 'Abrantes', province: 'Madrid', region: 'madrid', lat: 40.3790, lng: -3.7262 },
  { slug: 'alameda-de-osuna', name: 'Alameda de Osuna', province: 'Madrid', region: 'madrid', lat: 40.4518, lng: -3.5867 },
  { slug: 'alcala-de-henares', name: 'Alcalá de Henares', province: 'Madrid', region: 'madrid', lat: 40.4821, lng: -3.3600 },
  { slug: 'alcobendas', name: 'Alcobendas', province: 'Madrid', region: 'madrid', lat: 40.5475, lng: -3.6420 },
  { slug: 'alcorcon', name: 'Alcorcón', province: 'Madrid', region: 'madrid', lat: 40.3458, lng: -3.8249 },
  { slug: 'algete', name: 'Algete', province: 'Madrid', region: 'madrid', lat: 40.5971, lng: -3.4974 },
  { slug: 'aluche', name: 'Aluche', province: 'Madrid', region: 'madrid', lat: 40.3919, lng: -3.7567 },
  { slug: 'apostol-santiago', name: 'Apostol Santiago', province: 'Madrid', region: 'madrid', lat: 40.4764, lng: -3.6594 },
  { slug: 'aranjuez', name: 'Aranjuez', province: 'Madrid', region: 'madrid', lat: 40.0311, lng: -3.6025 },
  { slug: 'aravaca', name: 'Aravaca', province: 'Madrid', region: 'madrid', lat: 40.4577, lng: -3.7828 },
  { slug: 'arganda', name: 'Arganda', province: 'Madrid', region: 'madrid', lat: 40.3008, lng: -3.4372 },
  { slug: 'arroyomolinos', name: 'Arroyomolinos', province: 'Madrid', region: 'madrid', lat: 40.2695, lng: -3.9195 },
  { slug: 'barajas-de-madrid', name: 'Barajas de Madrid', province: 'Madrid', region: 'madrid', lat: 40.4737, lng: -3.5778 },
  { slug: 'berruguete', name: 'Berruguete', province: 'Madrid', region: 'madrid', lat: 40.4596, lng: -3.7050 },
  { slug: 'boadilla-del-monte', name: 'Boadilla del Monte', province: 'Madrid', region: 'madrid', lat: 40.4050, lng: -3.8784 },
  { slug: 'butarque', name: 'Butarque', province: 'Madrid', region: 'madrid', lat: 40.3372, lng: -3.6763 },
  { slug: 'campamento', name: 'Campamento', province: 'Madrid', region: 'madrid', lat: 40.3864, lng: -3.7982 },
  { slug: 'canillas', name: 'Canillas', province: 'Madrid', region: 'madrid', lat: 40.4640, lng: -3.6362 },
  { slug: 'canillejas', name: 'Canillejas', province: 'Madrid', region: 'madrid', lat: 40.4484, lng: -3.6085 },
  { slug: 'casco-historico-de-vallecas', name: 'Casco Histórico de Vallecas', province: 'Madrid', region: 'madrid', lat: 40.3485, lng: -3.6162 },
  { slug: 'casco-historico-de-vicalvaro', name: 'Casco Histórico de Vicálvaro', province: 'Madrid', region: 'madrid', lat: 40.3924, lng: -3.5701 },
  { slug: 'castilla', name: 'Castilla', province: 'Madrid', region: 'madrid', lat: 40.4743, lng: -3.6797 },
  { slug: 'castillejos', name: 'Castillejos', province: 'Madrid', region: 'madrid', lat: 40.4604, lng: -3.6941 },
  { slug: 'chamartin', name: 'Chamartín', province: 'Madrid', region: 'madrid', lat: 40.4621, lng: -3.6766 },
  { slug: 'ciempozuelos', name: 'Ciempozuelos', province: 'Madrid', region: 'madrid', lat: 40.1591, lng: -3.6210 },
  { slug: 'ciudad-jardin', name: 'Ciudad Jardín', province: 'Madrid', region: 'madrid', lat: 40.4483, lng: -3.6730 },
  { slug: 'ciudad-lineal', name: 'Ciudad Lineal', province: 'Madrid', region: 'madrid', lat: 40.4451, lng: -3.6513 },
  { slug: 'ciudad-universitaria', name: 'Ciudad Universitaria', province: 'Madrid', region: 'madrid', lat: 40.4560, lng: -3.7384 },
  { slug: 'collado-villalba', name: 'Collado-Villalba', province: 'Madrid', region: 'madrid', lat: 40.6351, lng: -4.0049 },
  { slug: 'colmenar-viejo', name: 'Colmenar Viejo', province: 'Madrid', region: 'madrid', lat: 40.6591, lng: -3.7676 },
  { slug: 'concepcion', name: 'Concepción', province: 'Madrid', region: 'madrid', lat: 40.4393, lng: -3.6493 },
  { slug: 'coslada', name: 'Coslada', province: 'Madrid', region: 'madrid', lat: 40.4238, lng: -3.5613 },
  { slug: 'costillares', name: 'Costillares', province: 'Madrid', region: 'madrid', lat: 40.4766, lng: -3.6685 },
  { slug: 'el-escorial', name: 'El Escorial', province: 'Madrid', region: 'madrid', lat: 40.5825, lng: -4.1285 },
  { slug: 'el-goloso', name: 'El Goloso', province: 'Madrid', region: 'madrid', lat: 40.5534, lng: -3.6997 },
  { slug: 'entrevias', name: 'Entrevías', province: 'Madrid', region: 'madrid', lat: 40.3785, lng: -3.6739 },
  { slug: 'fontarron', name: 'Fontarrón', province: 'Madrid', region: 'madrid', lat: 40.4014, lng: -3.6468 },
  { slug: 'fuencarral', name: 'Fuencarral', province: 'Madrid', region: 'madrid', lat: 40.5000, lng: -3.6833 },
  { slug: 'fuencarral-el-pardo', name: 'Fuencarral-El Pardo', province: 'Madrid', region: 'madrid', lat: 40.4984, lng: -3.7314 },
  { slug: 'fuenlabrada', name: 'Fuenlabrada', province: 'Madrid', region: 'madrid', lat: 40.2842, lng: -3.7942 },
  { slug: 'galapagar', name: 'Galapagar', province: 'Madrid', region: 'madrid', lat: 40.5783, lng: -4.0043 },
  { slug: 'getafe', name: 'Getafe', province: 'Madrid', region: 'madrid', lat: 40.3057, lng: -3.7330 },
  { slug: 'hispanoamerica', name: 'Hispanoamérica', province: 'Madrid', region: 'madrid', lat: 40.4554, lng: -3.6771 },
  { slug: 'hortaleza', name: 'Hortaleza', province: 'Madrid', region: 'madrid', lat: 40.4744, lng: -3.6411 },
  { slug: 'humanes-de-madrid', name: 'Humanes de Madrid', province: 'Madrid', region: 'madrid', lat: 40.2504, lng: -3.8306 },
  { slug: 'la-paz', name: 'La Paz', province: 'Madrid', region: 'madrid', lat: 40.4812, lng: -3.6966 },
  { slug: 'las-aguilas', name: 'Las Águilas', province: 'Madrid', region: 'madrid', lat: 40.3818, lng: -3.7711 },
  { slug: 'las-rozas-de-madrid', name: 'Las Rozas de Madrid', province: 'Madrid', region: 'madrid', lat: 40.4929, lng: -3.8737 },
  { slug: 'latina', name: 'Latina', province: 'Madrid', region: 'madrid', lat: 40.3890, lng: -3.7457 },
  { slug: 'leganes', name: 'Leganés', province: 'Madrid', region: 'madrid', lat: 40.3272, lng: -3.7635 },
  { slug: 'los-angeles', name: 'Los Angeles', province: 'Madrid', region: 'madrid', lat: 40.3558, lng: -3.6991 },
  { slug: 'los-rosales', name: 'Los Rosales', province: 'Madrid', region: 'madrid', lat: 40.3557, lng: -3.6886 },
  { slug: 'lucero', name: 'Lucero', province: 'Madrid', region: 'madrid', lat: 40.4023, lng: -3.7504 },
  { slug: 'madrid', name: 'Madrid', province: 'Madrid', region: 'madrid', lat: 40.4168, lng: -3.7038 },
  { slug: 'majadahonda', name: 'Majadahonda', province: 'Madrid', region: 'madrid', lat: 40.4735, lng: -3.8718 },
  { slug: 'marroquina', name: 'Marroquina', province: 'Madrid', region: 'madrid', lat: 40.4107, lng: -3.6406 },
  { slug: 'media-legua', name: 'Media Legua', province: 'Madrid', region: 'madrid', lat: 40.4119, lng: -3.6568 },
  { slug: 'mejorada-del-campo', name: 'Mejorada del Campo', province: 'Madrid', region: 'madrid', lat: 40.3928, lng: -3.4819 },
  { slug: 'mirasierra', name: 'Mirasierra', province: 'Madrid', region: 'madrid', lat: 40.4963, lng: -3.7196 },
  { slug: 'moratalaz', name: 'Moratalaz', province: 'Madrid', region: 'madrid', lat: 40.4074, lng: -3.6494 },
  { slug: 'mostoles', name: 'Móstoles', province: 'Madrid', region: 'madrid', lat: 40.3223, lng: -3.8650 },
  { slug: 'navalcarnero', name: 'Navalcarnero', province: 'Madrid', region: 'madrid', lat: 40.2891, lng: -4.0120 },
  { slug: 'nueva-espana', name: 'Nueva España', province: 'Madrid', region: 'madrid', lat: 40.4628, lng: -3.6781 },
  { slug: 'numancia', name: 'Numancia', province: 'Madrid', region: 'madrid', lat: 40.3995, lng: -3.6585 },
  { slug: 'orcasitas', name: 'Orcasitas', province: 'Madrid', region: 'madrid', lat: 40.3686, lng: -3.7124 },
  { slug: 'palomeras-bajas', name: 'Palomeras Bajas', province: 'Madrid', region: 'madrid', lat: 40.3848, lng: -3.6589 },
  { slug: 'palomeras-sureste', name: 'Palomeras Sureste', province: 'Madrid', region: 'madrid', lat: 40.3852, lng: -3.6373 },
  { slug: 'parla', name: 'Parla', province: 'Madrid', region: 'madrid', lat: 40.2360, lng: -3.7675 },
  { slug: 'pena-grande', name: 'Peña Grande', province: 'Madrid', region: 'madrid', lat: 40.4746, lng: -3.7224 },
  { slug: 'pilar', name: 'Pilar', province: 'Madrid', region: 'madrid', lat: 40.4771, lng: -3.7096 },
  { slug: 'pinar-de-chamartin', name: 'Pinar de Chamartín', province: 'Madrid', region: 'madrid', lat: 40.4790, lng: -3.6684 },
  { slug: 'pinar-del-rey', name: 'Pinar del Rey', province: 'Madrid', region: 'madrid', lat: 40.4724, lng: -3.6471 },
  { slug: 'pinto', name: 'Pinto', province: 'Madrid', region: 'madrid', lat: 40.2415, lng: -3.7000 },
  { slug: 'piovera', name: 'Piovera', province: 'Madrid', region: 'madrid', lat: 40.4557, lng: -3.6351 },
  { slug: 'portazgo', name: 'Portazgo', province: 'Madrid', region: 'madrid', lat: 40.3906, lng: -3.6482 },
  { slug: 'pozuelo-de-alarcon', name: 'Pozuelo de Alarcón', province: 'Madrid', region: 'madrid', lat: 40.4329, lng: -3.8134 },
  { slug: 'pradolongo', name: 'Pradolongo', province: 'Madrid', region: 'madrid', lat: 40.3781, lng: -3.7071 },
  { slug: 'prosperidad', name: 'Prosperidad', province: 'Madrid', region: 'madrid', lat: 40.4443, lng: -3.6693 },
  { slug: 'pueblo-nuevo', name: 'Pueblo Nuevo', province: 'Madrid', region: 'madrid', lat: 40.4263, lng: -3.6355 },
  { slug: 'puente-de-vallecas', name: 'Puente de Vallecas', province: 'Madrid', region: 'madrid', lat: 40.3935, lng: -3.6620 },
  { slug: 'puerta-bonita', name: 'Puerta Bonita', province: 'Madrid', region: 'madrid', lat: 40.3797, lng: -3.7391 },
  { slug: 'quintana', name: 'Quintana', province: 'Madrid', region: 'madrid', lat: 40.4370, lng: -3.6451 },
  { slug: 'rejas', name: 'Rejas', province: 'Madrid', region: 'madrid', lat: 40.4451, lng: -3.5702 },
  { slug: 'rivas-vaciamadrid', name: 'Rivas-Vaciamadrid', province: 'Madrid', region: 'madrid', lat: 40.3261, lng: -3.5109 },
  { slug: 'rosas', name: 'Rosas', province: 'Madrid', region: 'madrid', lat: 40.4275, lng: -3.5943 },
  { slug: 'san-blas-canillejas', name: 'San Blas-Canillejas', province: 'Madrid', region: 'madrid', lat: 40.4389, lng: -3.6154 },
  { slug: 'san-cristobal', name: 'San Cristobal', province: 'Madrid', region: 'madrid', lat: 40.3408, lng: -3.6884 },
  { slug: 'san-diego', name: 'San Diego', province: 'Madrid', region: 'madrid', lat: 40.3900, lng: -3.6679 },
  { slug: 'san-fermin', name: 'San Fermín', province: 'Madrid', region: 'madrid', lat: 40.3706, lng: -3.6891 },
  { slug: 'san-fernando-de-henares', name: 'San Fernando de Henares', province: 'Madrid', region: 'madrid', lat: 40.4239, lng: -3.5326 },
  { slug: 'san-lorenzo-de-el-escorial', name: 'San Lorenzo de El Escorial', province: 'Madrid', region: 'madrid', lat: 40.5914, lng: -4.1474 },
  { slug: 'san-martin-de-la-vega', name: 'San Martín de la Vega', province: 'Madrid', region: 'madrid', lat: 40.2073, lng: -3.5706 },
  { slug: 'san-sebastian-de-los-reyes', name: 'San Sebastián de los Reyes', province: 'Madrid', region: 'madrid', lat: 40.5555, lng: -3.6273 },
  { slug: 'santa-eugenia', name: 'Santa Eugenia', province: 'Madrid', region: 'madrid', lat: 40.3834, lng: -3.6113 },
  { slug: 'tetuan-de-las-victorias', name: 'Tetuán de las Victorias', province: 'Madrid', region: 'madrid', lat: 40.4597, lng: -3.6975 },
  { slug: 'torrejon-de-ardoz', name: 'Torrejón de Ardoz', province: 'Madrid', region: 'madrid', lat: 40.4554, lng: -3.4697 },
  { slug: 'torrelodones', name: 'Torrelodones', province: 'Madrid', region: 'madrid', lat: 40.5765, lng: -3.9266 },
  { slug: 'tres-cantos', name: 'Tres Cantos', province: 'Madrid', region: 'madrid', lat: 40.6009, lng: -3.7081 },
  { slug: 'valdeacederas', name: 'Valdeacederas', province: 'Madrid', region: 'madrid', lat: 40.4670, lng: -3.7042 },
  { slug: 'valdebernardo', name: 'Valdebernardo', province: 'Madrid', region: 'madrid', lat: 40.4007, lng: -3.6213 },
  { slug: 'valdemoro', name: 'Valdemoro', province: 'Madrid', region: 'madrid', lat: 40.1908, lng: -3.6789 },
  { slug: 'valdezarza', name: 'Valdezarza', province: 'Madrid', region: 'madrid', lat: 40.4652, lng: -3.7173 },
  { slug: 'vallecas', name: 'Vallecas', province: 'Madrid', region: 'madrid', lat: 40.3833, lng: -3.6167 },
  { slug: 'ventas', name: 'Ventas', province: 'Madrid', region: 'madrid', lat: 40.4225, lng: -3.6474 },
  { slug: 'vicalvaro', name: 'Vicálvaro', province: 'Madrid', region: 'madrid', lat: 40.4000, lng: -3.6000 },
  { slug: 'villa-de-vallecas', name: 'Villa de Vallecas', province: 'Madrid', region: 'madrid', lat: 40.3670, lng: -3.6015 },
  { slug: 'villanueva-de-la-canada', name: 'Villanueva de la Cañada', province: 'Madrid', region: 'madrid', lat: 40.4469, lng: -4.0043 },
  { slug: 'villanueva-del-pardillo', name: 'Villanueva del Pardillo', province: 'Madrid', region: 'madrid', lat: 40.4901, lng: -3.9638 },
  { slug: 'villaverde', name: 'Villaverde', province: 'Madrid', region: 'madrid', lat: 40.3500, lng: -3.7000 },
  { slug: 'villaviciosa-de-odon', name: 'Villaviciosa de Odón', province: 'Madrid', region: 'madrid', lat: 40.3581, lng: -3.9043 },
  { slug: 'vinateros', name: 'Vinateros', province: 'Madrid', region: 'madrid', lat: 40.4053, lng: -3.6425 },
  { slug: 'vista-alegre', name: 'Vista Alegre', province: 'Madrid', region: 'madrid', lat: 40.3843, lng: -3.7458 },

  // Málaga
  { slug: 'alhaurin-de-la-torre', name: 'Alhaurín de la Torre', province: 'Málaga', region: 'malaga', lat: 36.6640, lng: -4.5614 },
  { slug: 'alhaurin-el-grande', name: 'Alhaurín el Grande', province: 'Málaga', region: 'malaga', lat: 36.6431, lng: -4.6892 },
  { slug: 'antequera', name: 'Antequera', province: 'Málaga', region: 'malaga', lat: 37.0194, lng: -4.5612 },
  { slug: 'benalmadena', name: 'Benalmádena', province: 'Málaga', region: 'malaga', lat: 36.5988, lng: -4.5163 },
  { slug: 'cartama', name: 'Cártama', province: 'Málaga', region: 'malaga', lat: 36.7107, lng: -4.6330 },
  { slug: 'coin', name: 'Coín', province: 'Málaga', region: 'malaga', lat: 36.6597, lng: -4.7561 },
  { slug: 'estepona', name: 'Estepona', province: 'Málaga', region: 'malaga', lat: 36.4276, lng: -5.1459 },
  { slug: 'fuengirola', name: 'Fuengirola', province: 'Málaga', region: 'malaga', lat: 36.5397, lng: -4.6250 },
  { slug: 'malaga', name: 'Málaga', province: 'Málaga', region: 'malaga', lat: 36.7213, lng: -4.4214 },
  { slug: 'manilva', name: 'Manilva', province: 'Málaga', region: 'malaga', lat: 36.3761, lng: -5.2506 },
  { slug: 'marbella', name: 'Marbella', province: 'Málaga', region: 'malaga', lat: 36.5101, lng: -4.8825 },
  { slug: 'mijas', name: 'Mijas', province: 'Málaga', region: 'malaga', lat: 36.5958, lng: -4.6378 },
  { slug: 'nerja', name: 'Nerja', province: 'Málaga', region: 'malaga', lat: 36.7454, lng: -3.8730 },
  { slug: 'rincon-de-la-victoria', name: 'Rincón de la Victoria', province: 'Málaga', region: 'malaga', lat: 36.7167, lng: -4.2764 },
  { slug: 'ronda', name: 'Ronda', province: 'Málaga', region: 'malaga', lat: 36.7429, lng: -5.1665 },
  { slug: 'san-pedro-alcantara', name: 'San Pedro de Alcántara', province: 'Málaga', region: 'malaga', lat: 36.4847, lng: -4.9903 },
  { slug: 'torre-del-mar', name: 'Torre del Mar', province: 'Málaga', region: 'malaga', lat: 36.7420, lng: -4.0929 },
  { slug: 'torremolinos', name: 'Torremolinos', province: 'Málaga', region: 'malaga', lat: 36.6203, lng: -4.4998 },
  { slug: 'torrox', name: 'Torrox', province: 'Málaga', region: 'malaga', lat: 36.7578, lng: -3.9553 },
  { slug: 'velez-malaga', name: 'Vélez-Málaga', province: 'Málaga', region: 'malaga', lat: 36.7797, lng: -4.1006 },

  // Melilla
  { slug: 'melilla', name: 'Melilla', province: 'Melilla', region: 'melilla', lat: 35.2937, lng: -2.9383 },

  // Murcia
  { slug: 'aguilas', name: 'Águilas', province: 'Murcia', region: 'murcia', lat: 37.4066, lng: -1.5836 },
  { slug: 'alcantarilla', name: 'Alcantarilla', province: 'Murcia', region: 'murcia', lat: 37.9694, lng: -1.2171 },
  { slug: 'alhama-de-murcia', name: 'Alhama de Murcia', province: 'Murcia', region: 'murcia', lat: 37.8510, lng: -1.4251 },
  { slug: 'archena', name: 'Archena', province: 'Murcia', region: 'murcia', lat: 38.1163, lng: -1.3004 },
  { slug: 'atamaria', name: 'Atamaría', province: 'Murcia', region: 'murcia', lat: 37.5999, lng: -0.8068 },
  { slug: 'caravaca', name: 'Caravaca', province: 'Murcia', region: 'murcia', lat: 38.1056, lng: -1.8634 },
  { slug: 'cartagena', name: 'Cartagena', province: 'Murcia', region: 'murcia', lat: 37.6257, lng: -0.9966 },
  { slug: 'cehegin', name: 'Cehegín', province: 'Murcia', region: 'murcia', lat: 38.0924, lng: -1.7985 },
  { slug: 'cieza', name: 'Cieza', province: 'Murcia', region: 'murcia', lat: 38.2400, lng: -1.4199 },
  { slug: 'fuente-alamo', name: 'Fuente Álamo', province: 'Murcia', region: 'murcia', lat: 37.7275, lng: -1.1653 },
  { slug: 'jumilla', name: 'Jumilla', province: 'Murcia', region: 'murcia', lat: 38.4792, lng: -1.3250 },
  { slug: 'la-manga', name: 'La Manga del Mar Menor', province: 'Murcia', region: 'murcia', lat: 37.6392, lng: -0.7194 },
  { slug: 'la-union', name: 'La Unión', province: 'Murcia', region: 'murcia', lat: 37.6191, lng: -0.8780 },
  { slug: 'las-torres-de-cotillas', name: 'Las Torres de Cotillas', province: 'Murcia', region: 'murcia', lat: 38.0282, lng: -1.2419 },
  { slug: 'lorca', name: 'Lorca', province: 'Murcia', region: 'murcia', lat: 37.6712, lng: -1.7017 },
  { slug: 'los-alcazares', name: 'Los Alcázares', province: 'Murcia', region: 'murcia', lat: 37.7422, lng: -0.8517 },
  { slug: 'mazarron', name: 'Mazarrón', province: 'Murcia', region: 'murcia', lat: 37.5992, lng: -1.3139 },
  { slug: 'molina-de-segura', name: 'Molina de Segura', province: 'Murcia', region: 'murcia', lat: 38.0546, lng: -1.2076 },
  { slug: 'mula', name: 'Mula', province: 'Murcia', region: 'murcia', lat: 38.0410, lng: -1.4901 },
  { slug: 'murcia', name: 'Murcia', province: 'Murcia', region: 'murcia', lat: 37.9922, lng: -1.1307 },
  { slug: 'san-javier', name: 'San Javier', province: 'Murcia', region: 'murcia', lat: 37.8064, lng: -0.8372 },
  { slug: 'santomera', name: 'Santomera', province: 'Murcia', region: 'murcia', lat: 38.0615, lng: -1.0488 },
  { slug: 'torre-pacheco', name: 'Torre-Pacheco', province: 'Murcia', region: 'murcia', lat: 37.7411, lng: -0.9525 },
  { slug: 'totana', name: 'Totana', province: 'Murcia', region: 'murcia', lat: 37.7688, lng: -1.5023 },
  { slug: 'yecla', name: 'Yecla', province: 'Murcia', region: 'murcia', lat: 38.6136, lng: -1.1147 },

  // Navarra
  { slug: 'baranain', name: 'Barañáin', province: 'Navarra', region: 'navarra', lat: 42.8057, lng: -1.6773 },
  { slug: 'burlata', name: 'Burlata', province: 'Navarra', region: 'navarra', lat: 42.8256, lng: -1.6167 },
  { slug: 'ermitagana', name: 'Ermitagaña', province: 'Navarra', region: 'navarra', lat: 42.8108, lng: -1.6641 },
  { slug: 'iturrama', name: 'Iturrama', province: 'Navarra', region: 'navarra', lat: 42.8085, lng: -1.6583 },
  { slug: 'pamplona', name: 'Pamplona', province: 'Navarra', region: 'navarra', lat: 42.8169, lng: -1.6432 },
  { slug: 'primer-ensanche', name: 'Primer Ensanche', province: 'Navarra', region: 'navarra', lat: 42.8148, lng: -1.6490 },
  { slug: 'segundo-ensanche', name: 'Segundo Ensanche', province: 'Navarra', region: 'navarra', lat: 42.8139, lng: -1.6429 },
  { slug: 'tudela', name: 'Tudela', province: 'Navarra', region: 'navarra', lat: 42.0617, lng: -1.6045 },

  // Ourense
  { slug: 'ourense', name: 'Ourense', province: 'Ourense', region: 'ourense', lat: 42.3367, lng: -7.8641 },

  // Palencia
  { slug: 'palencia', name: 'Palencia', province: 'Palencia', region: 'palencia', lat: 42.0095, lng: -4.5241 },

  // Pontevedra
  { slug: 'a-estrada', name: 'A Estrada', province: 'Pontevedra', region: 'pontevedra', lat: 42.6891, lng: -8.4884 },
  { slug: 'cangas-do-morrazo', name: 'Cangas do Morrazo', province: 'Pontevedra', region: 'pontevedra', lat: 42.2641, lng: -8.7846 },
  { slug: 'lalin', name: 'Lalín', province: 'Pontevedra', region: 'pontevedra', lat: 42.6609, lng: -8.1128 },
  { slug: 'marin', name: 'Marín', province: 'Pontevedra', region: 'pontevedra', lat: 42.3914, lng: -8.7014 },
  { slug: 'moana', name: 'Moaña', province: 'Pontevedra', region: 'pontevedra', lat: 42.2781, lng: -8.7392 },
  { slug: 'nigran', name: 'Nigrán', province: 'Pontevedra', region: 'pontevedra', lat: 42.1415, lng: -8.8066 },
  { slug: 'poio', name: 'Poio', province: 'Pontevedra', region: 'pontevedra', lat: 42.4477, lng: -8.6859 },
  { slug: 'ponteareas', name: 'Ponteareas', province: 'Pontevedra', region: 'pontevedra', lat: 42.1748, lng: -8.5040 },
  { slug: 'pontevedra', name: 'Pontevedra', province: 'Pontevedra', region: 'pontevedra', lat: 42.4310, lng: -8.6443 },
  { slug: 'porrino', name: 'Porriño', province: 'Pontevedra', region: 'pontevedra', lat: 42.1616, lng: -8.6198 },
  { slug: 'redondela', name: 'Redondela', province: 'Pontevedra', region: 'pontevedra', lat: 42.2834, lng: -8.6096 },
  { slug: 'ribeira', name: 'Ribeira', province: 'Pontevedra', region: 'pontevedra', lat: 42.7381, lng: -8.4411 },
  { slug: 'sanxenxo', name: 'Sanxenxo', province: 'Pontevedra', region: 'pontevedra', lat: 42.4000, lng: -8.8070 },
  { slug: 'tui', name: 'Tui', province: 'Pontevedra', region: 'pontevedra', lat: 42.0471, lng: -8.6443 },
  { slug: 'vigo', name: 'Vigo', province: 'Pontevedra', region: 'pontevedra', lat: 42.2328, lng: -8.7226 },
  { slug: 'vilagarcia-de-arousa', name: 'Vilagarcía de Arousa', province: 'Pontevedra', region: 'pontevedra', lat: 42.5963, lng: -8.7643 },

  // Salamanca
  { slug: 'arapiles', name: 'Arapiles', province: 'Salamanca', region: 'salamanca', lat: 40.8937, lng: -5.6449 },
  { slug: 'bejar', name: 'Béjar', province: 'Salamanca', region: 'salamanca', lat: 40.3864, lng: -5.7634 },
  { slug: 'buenavista', name: 'Buenavista', province: 'Salamanca', region: 'salamanca', lat: 40.7676, lng: -5.6114 },
  { slug: 'salamanca', name: 'Salamanca', province: 'Salamanca', region: 'salamanca', lat: 40.9688, lng: -5.6639 },

  // Santa Cruz de Tenerife
  { slug: 'adeje', name: 'Adeje', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.1227, lng: -16.7261 },
  { slug: 'candelaria', name: 'Candelaria', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.3548, lng: -16.3727 },
  { slug: 'granadilla-de-abona', name: 'Granadilla de Abona', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.1188, lng: -16.5760 },
  { slug: 'guia-de-isora', name: 'Guía de Isora', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.2115, lng: -16.7795 },
  { slug: 'guimar', name: 'Güimar', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.3112, lng: -16.4128 },
  { slug: 'icod-de-los-vinos', name: 'Icod de los Vinos', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.3724, lng: -16.7119 },
  { slug: 'la-laguna', name: 'La Laguna', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.4853, lng: -16.3201 },
  { slug: 'los-cristianos', name: 'Los Cristianos (Arona)', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.0525, lng: -16.7183 },
  { slug: 'los-llanos-de-aridane', name: 'Los Llanos de Aridane', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.6585, lng: -17.9182 },
  { slug: 'los-realejos', name: 'Los Realejos', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.3849, lng: -16.5828 },
  { slug: 'puerto-de-la-cruz', name: 'Puerto de la Cruz', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.4139, lng: -16.5500 },
  { slug: 'realejo-alto', name: 'Realejo Alto', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.3764, lng: -16.5858 },
  { slug: 'san-isidro', name: 'San Isidro', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.0762, lng: -16.5580 },
  { slug: 'san-miguel-de-abona', name: 'San Miguel De Abona', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.0983, lng: -16.6171 },
  { slug: 'santa-cruz-de-la-palma', name: 'Santa Cruz de la Palma', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.6835, lng: -17.7642 },
  { slug: 'santa-cruz-tenerife', name: 'Santa Cruz de Tenerife', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.4636, lng: -16.2518 },
  { slug: 'tacoronte', name: 'Tacoronte', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 28.4769, lng: -16.4102 },
  { slug: 'valverde', name: 'Valverde', province: 'Santa Cruz de Tenerife', region: 'santa_cruz_de_tenerife', lat: 27.8063, lng: -17.9158 },

  // Segovia
  { slug: 'segovia', name: 'Segovia', province: 'Segovia', region: 'segovia', lat: 40.9481, lng: -4.1184 },

  // Sevilla
  { slug: 'alcala-de-guadaira', name: 'Alcalá de Guadaira', province: 'Sevilla', region: 'sevilla', lat: 37.3379, lng: -5.8395 },
  { slug: 'bormujos', name: 'Bormujos', province: 'Sevilla', region: 'sevilla', lat: 37.3736, lng: -6.0723 },
  { slug: 'camas', name: 'Camas', province: 'Sevilla', region: 'sevilla', lat: 37.4020, lng: -6.0331 },
  { slug: 'carmona', name: 'Carmona', province: 'Sevilla', region: 'sevilla', lat: 37.4712, lng: -5.6461 },
  { slug: 'castilleja-de-la-cuesta', name: 'Castilleja de la Cuesta', province: 'Sevilla', region: 'sevilla', lat: 37.3859, lng: -6.0526 },
  { slug: 'coria-del-rio', name: 'Coria del Río', province: 'Sevilla', region: 'sevilla', lat: 37.2877, lng: -6.0541 },
  { slug: 'dos-hermanas', name: 'Dos Hermanas', province: 'Sevilla', region: 'sevilla', lat: 37.2829, lng: -5.9209 },
  { slug: 'ecija', name: 'Écija', province: 'Sevilla', region: 'sevilla', lat: 37.5422, lng: -5.0826 },
  { slug: 'el-arahal', name: 'El Arahal', province: 'Sevilla', region: 'sevilla', lat: 37.2627, lng: -5.5453 },
  { slug: 'el-viso-del-alcor', name: 'El Viso del Alcor', province: 'Sevilla', region: 'sevilla', lat: 37.3911, lng: -5.7199 },
  { slug: 'la-algaba', name: 'La Algaba', province: 'Sevilla', region: 'sevilla', lat: 37.4633, lng: -6.0111 },
  { slug: 'la-rinconada', name: 'La Rinconada', province: 'Sevilla', region: 'sevilla', lat: 37.4861, lng: -5.9809 },
  { slug: 'las-cabezas-de-san-juan', name: 'Las Cabezas de San Juan', province: 'Sevilla', region: 'sevilla', lat: 36.9838, lng: -5.9393 },
  { slug: 'lebrija', name: 'Lebrija', province: 'Sevilla', region: 'sevilla', lat: 36.9208, lng: -6.0753 },
  { slug: 'lora-del-rio', name: 'Lora del Río', province: 'Sevilla', region: 'sevilla', lat: 37.6590, lng: -5.5275 },
  { slug: 'los-palacios-y-villafranca', name: 'Los Palacios y Villafranca', province: 'Sevilla', region: 'sevilla', lat: 37.1618, lng: -5.9243 },
  { slug: 'mairena-del-alcor', name: 'Mairena del Alcor', province: 'Sevilla', region: 'sevilla', lat: 37.3730, lng: -5.7495 },
  { slug: 'mairena-del-aljarafe', name: 'Mairena del Aljarafe', province: 'Sevilla', region: 'sevilla', lat: 37.3446, lng: -6.0639 },
  { slug: 'marchena', name: 'Marchena', province: 'Sevilla', region: 'sevilla', lat: 37.3290, lng: -5.4168 },
  { slug: 'moron-de-la-frontera', name: 'Morón de la Frontera', province: 'Sevilla', region: 'sevilla', lat: 37.1208, lng: -5.4540 },
  { slug: 'osuna', name: 'Osuna', province: 'Sevilla', region: 'sevilla', lat: 37.2376, lng: -5.1031 },
  { slug: 'san-juan-de-aznalfarache', name: 'San Juan de Aznalfarache', province: 'Sevilla', region: 'sevilla', lat: 37.3581, lng: -6.0373 },
  { slug: 'sevilla', name: 'Sevilla', province: 'Sevilla', region: 'sevilla', lat: 37.3891, lng: -5.9845 },
  { slug: 'tomares', name: 'Tomares', province: 'Sevilla', region: 'sevilla', lat: 37.3728, lng: -6.0459 },
  { slug: 'utrera', name: 'Utrera', province: 'Sevilla', region: 'sevilla', lat: 37.1852, lng: -5.7809 },

  // Soria
  { slug: 'soria', name: 'Soria', province: 'Soria', region: 'soria', lat: 41.7640, lng: -2.4688 },

  // Tarragona
  { slug: 'amposta', name: 'Amposta', province: 'Tarragona', region: 'tarragona', lat: 40.7099, lng: 0.5786 },
  { slug: 'calafell', name: 'Calafell', province: 'Tarragona', region: 'tarragona', lat: 41.2000, lng: 1.5683 },
  { slug: 'cambrils', name: 'Cambrils', province: 'Tarragona', region: 'tarragona', lat: 41.0672, lng: 1.0575 },
  { slug: 'el-vendrell', name: 'El Vendrell', province: 'Tarragona', region: 'tarragona', lat: 41.2167, lng: 1.5333 },
  { slug: 'reus', name: 'Reus', province: 'Tarragona', region: 'tarragona', lat: 41.1561, lng: 1.1069 },
  { slug: 'salou', name: 'Salou', province: 'Tarragona', region: 'tarragona', lat: 41.0763, lng: 1.1417 },
  { slug: 'sant-carles-de-la-rapita', name: 'Sant Carles de la Ràpita', province: 'Tarragona', region: 'tarragona', lat: 40.6167, lng: 0.6000 },
  { slug: 'tarragona', name: 'Tarragona', province: 'Tarragona', region: 'tarragona', lat: 41.1191, lng: 1.2454 },
  { slug: 'torredembarra', name: 'Torredembarra', province: 'Tarragona', region: 'tarragona', lat: 41.1450, lng: 1.3986 },
  { slug: 'tortosa', name: 'Tortosa', province: 'Tarragona', region: 'tarragona', lat: 40.8125, lng: 0.5216 },
  { slug: 'valls', name: 'Valls', province: 'Tarragona', region: 'tarragona', lat: 41.2861, lng: 1.2499 },

  // Teruel
  { slug: 'alcaniz', name: 'Alcañiz', province: 'Teruel', region: 'teruel', lat: 41.0500, lng: -0.1333 },
  { slug: 'teruel', name: 'Teruel', province: 'Teruel', region: 'teruel', lat: 40.3456, lng: -1.1065 },

  // Toledo
  { slug: 'illescas', name: 'Illescas', province: 'Toledo', region: 'toledo', lat: 40.1221, lng: -3.8470 },
  { slug: 'sesena', name: 'Seseña', province: 'Toledo', region: 'toledo', lat: 40.1047, lng: -3.6979 },
  { slug: 'talavera-de-la-reina', name: 'Talavera de la Reina', province: 'Toledo', region: 'toledo', lat: 39.9635, lng: -4.8308 },
  { slug: 'toledo', name: 'Toledo', province: 'Toledo', region: 'toledo', lat: 39.8581, lng: -4.0226 },

  // Valencia
  { slug: 'alaquas', name: 'Alaquàs', province: 'Valencia', region: 'valencia', lat: 39.4557, lng: -0.4610 },
  { slug: 'albal', name: 'Albal', province: 'Valencia', region: 'valencia', lat: 39.4000, lng: -0.4167 },
  { slug: 'alboraya', name: 'Alboraya', province: 'Valencia', region: 'valencia', lat: 39.5000, lng: -0.3500 },
  { slug: 'aldaia', name: 'Aldaia', province: 'Valencia', region: 'valencia', lat: 39.4657, lng: -0.4601 },
  { slug: 'alfafar', name: 'Alfafar', province: 'Valencia', region: 'valencia', lat: 39.4167, lng: -0.3833 },
  { slug: 'algemesi', name: 'Algemesí', province: 'Valencia', region: 'valencia', lat: 39.1904, lng: -0.4357 },
  { slug: 'alzira', name: 'Alzira', province: 'Valencia', region: 'valencia', lat: 39.1500, lng: -0.4333 },
  { slug: 'benetusser', name: 'Benetússer', province: 'Valencia', region: 'valencia', lat: 39.4226, lng: -0.3969 },
  { slug: 'betera', name: 'Bétera', province: 'Valencia', region: 'valencia', lat: 39.5911, lng: -0.4615 },
  { slug: 'burjassot', name: 'Burjassot', province: 'Valencia', region: 'valencia', lat: 39.5098, lng: -0.4133 },
  { slug: 'carcaixent', name: 'Carcaixent', province: 'Valencia', region: 'valencia', lat: 39.1218, lng: -0.4481 },
  { slug: 'carlet', name: 'Carlet', province: 'Valencia', region: 'valencia', lat: 39.2266, lng: -0.5214 },
  { slug: 'catarroja', name: 'Catarroja', province: 'Valencia', region: 'valencia', lat: 39.4000, lng: -0.4000 },
  { slug: 'cullera', name: 'Cullera', province: 'Valencia', region: 'valencia', lat: 39.1667, lng: -0.2500 },
  { slug: 'gandia', name: 'Gandía', province: 'Valencia', region: 'valencia', lat: 38.9678, lng: -0.1806 },
  { slug: 'grao-de-murviedro', name: 'Grao de Murviedro', province: 'Valencia', region: 'valencia', lat: 39.6417, lng: -0.2389 },
  { slug: 'l-eliana', name: "L'Eliana", province: 'Valencia', region: 'valencia', lat: 39.5667, lng: -0.5333 },
  { slug: 'la-pobla-de-vallbona', name: 'La Pobla de Vallbona', province: 'Valencia', region: 'valencia', lat: 39.5975, lng: -0.5547 },
  { slug: 'lliria', name: 'Llíria', province: 'Valencia', region: 'valencia', lat: 39.6289, lng: -0.5978 },
  { slug: 'manises', name: 'Manises', province: 'Valencia', region: 'valencia', lat: 39.4914, lng: -0.4635 },
  { slug: 'massamagrell', name: 'Massamagrell', province: 'Valencia', region: 'valencia', lat: 39.5667, lng: -0.3333 },
  { slug: 'moncada', name: 'Moncada', province: 'Valencia', region: 'valencia', lat: 39.5455, lng: -0.3955 },
  { slug: 'oliva', name: 'Oliva', province: 'Valencia', region: 'valencia', lat: 38.9186, lng: -0.1181 },
  { slug: 'ontinyent', name: 'Ontinyent', province: 'Valencia', region: 'valencia', lat: 38.8219, lng: -0.6060 },
  { slug: 'paiporta', name: 'Paiporta', province: 'Valencia', region: 'valencia', lat: 39.4281, lng: -0.4177 },
  { slug: 'paterna', name: 'Paterna', province: 'Valencia', region: 'valencia', lat: 39.5026, lng: -0.4408 },
  { slug: 'picassent', name: 'Picassent', province: 'Valencia', region: 'valencia', lat: 39.3635, lng: -0.4595 },
  { slug: 'pucol', name: 'Puçol', province: 'Valencia', region: 'valencia', lat: 39.6167, lng: -0.3000 },
  { slug: 'quart-de-poblet', name: 'Quart de Poblet', province: 'Valencia', region: 'valencia', lat: 39.4814, lng: -0.4394 },
  { slug: 'requena', name: 'Requena', province: 'Valencia', region: 'valencia', lat: 39.4883, lng: -1.1004 },
  { slug: 'ribarroja-del-turia', name: 'Ribarroja del Turia', province: 'Valencia', region: 'valencia', lat: 39.5459, lng: -0.5707 },
  { slug: 'sagunto', name: 'Sagunto', province: 'Valencia', region: 'valencia', lat: 39.6833, lng: -0.2667 },
  { slug: 'silla', name: 'Silla', province: 'Valencia', region: 'valencia', lat: 39.3626, lng: -0.4117 },
  { slug: 'sueca', name: 'Sueca', province: 'Valencia', region: 'valencia', lat: 39.2026, lng: -0.3111 },
  { slug: 'tavernes-de-la-valldigna', name: 'Tavernes de la Valldigna', province: 'Valencia', region: 'valencia', lat: 39.0720, lng: -0.2662 },
  { slug: 'torrent', name: 'Torrent', province: 'Valencia', region: 'valencia', lat: 39.4370, lng: -0.4655 },
  { slug: 'valencia', name: 'Valencia', province: 'Valencia', region: 'valencia', lat: 39.4699, lng: -0.3763 },
  { slug: 'xativa', name: 'Xàtiva', province: 'Valencia', region: 'valencia', lat: 38.9904, lng: -0.5185 },
  { slug: 'xirivella', name: 'Xirivella', province: 'Valencia', region: 'valencia', lat: 39.4659, lng: -0.4259 },

  // Valladolid
  { slug: 'laguna-de-duero', name: 'Laguna de Duero', province: 'Valladolid', region: 'valladolid', lat: 41.5815, lng: -4.7233 },
  { slug: 'medina-del-campo', name: 'Medina del Campo', province: 'Valladolid', region: 'valladolid', lat: 41.3124, lng: -4.9141 },
  { slug: 'simancas', name: 'Simancas', province: 'Valladolid', region: 'valladolid', lat: 41.5907, lng: -4.8280 },
  { slug: 'valladolid', name: 'Valladolid', province: 'Valladolid', region: 'valladolid', lat: 41.6554, lng: -4.7235 },

  // Vizcaya
  { slug: 'algorta', name: 'Algorta', province: 'Vizcaya', region: 'vizcaya', lat: 43.3493, lng: -3.0094 },
  { slug: 'amorebieta', name: 'Amorebieta', province: 'Vizcaya', region: 'vizcaya', lat: 43.2167, lng: -2.7333 },
  { slug: 'barakaldo', name: 'Barakaldo', province: 'Vizcaya', region: 'vizcaya', lat: 43.2964, lng: -2.9881 },
  { slug: 'basauri', name: 'Basauri', province: 'Vizcaya', region: 'vizcaya', lat: 43.2397, lng: -2.8858 },
  { slug: 'bermeo', name: 'Bermeo', province: 'Vizcaya', region: 'vizcaya', lat: 43.4209, lng: -2.7215 },
  { slug: 'bilbao', name: 'Bilbao', province: 'Vizcaya', region: 'vizcaya', lat: 43.2627, lng: -2.9253 },
  { slug: 'durango', name: 'Durango', province: 'Vizcaya', region: 'vizcaya', lat: 43.1712, lng: -2.6338 },
  { slug: 'erandio', name: 'Erandio', province: 'Vizcaya', region: 'vizcaya', lat: 43.3044, lng: -2.9735 },
  { slug: 'ermua', name: 'Ermua', province: 'Vizcaya', region: 'vizcaya', lat: 43.1872, lng: -2.5026 },
  { slug: 'galdakao', name: 'Galdakao', province: 'Vizcaya', region: 'vizcaya', lat: 43.2307, lng: -2.8429 },
  { slug: 'gernika-lumo', name: 'Gernika-Lumo', province: 'Vizcaya', region: 'vizcaya', lat: 43.3167, lng: -2.6833 },
  { slug: 'getxo', name: 'Getxo', province: 'Vizcaya', region: 'vizcaya', lat: 43.3569, lng: -3.0115 },
  { slug: 'leioa', name: 'Leioa', province: 'Vizcaya', region: 'vizcaya', lat: 43.3269, lng: -2.9888 },
  { slug: 'mungia', name: 'Mungia', province: 'Vizcaya', region: 'vizcaya', lat: 43.3546, lng: -2.8452 },
  { slug: 'portugalete', name: 'Portugalete', province: 'Vizcaya', region: 'vizcaya', lat: 43.3210, lng: -3.0206 },
  { slug: 'santurtzi', name: 'Santurtzi', province: 'Vizcaya', region: 'vizcaya', lat: 43.3284, lng: -3.0325 },
  { slug: 'santutxu', name: 'Santutxu', province: 'Vizcaya', region: 'vizcaya', lat: 43.2535, lng: -2.9161 },
  { slug: 'sestao', name: 'Sestao', province: 'Vizcaya', region: 'vizcaya', lat: 43.3098, lng: -3.0072 },

  // Zamora
  { slug: 'benavente', name: 'Benavente', province: 'Zamora', region: 'zamora', lat: 42.0025, lng: -5.6783 },
  { slug: 'zamora', name: 'Zamora', province: 'Zamora', region: 'zamora', lat: 41.5063, lng: -5.7446 },

  // Zaragoza
  { slug: 'almozara', name: 'Almozara', province: 'Zaragoza', region: 'zaragoza', lat: 41.6612, lng: -0.9017 },
  { slug: 'calatayud', name: 'Calatayud', province: 'Zaragoza', region: 'zaragoza', lat: 41.3535, lng: -1.6432 },
  { slug: 'delicias', name: 'Delicias', province: 'Zaragoza', region: 'zaragoza', lat: 41.6493, lng: -0.9076 },
  { slug: 'ejea-de-los-caballeros', name: 'Ejea de los Caballeros', province: 'Zaragoza', region: 'zaragoza', lat: 42.1263, lng: -1.1372 },
  { slug: 'montecanal', name: 'Montecanal', province: 'Zaragoza', region: 'zaragoza', lat: 41.6296, lng: -0.9387 },
  { slug: 'oliver-valdefierro', name: 'Oliver-Valdefierro', province: 'Zaragoza', region: 'zaragoza', lat: 41.6445, lng: -0.9335 },
  { slug: 'utebo', name: 'Utebo', province: 'Zaragoza', region: 'zaragoza', lat: 41.7083, lng: -0.9992 },
  { slug: 'zaragoza', name: 'Zaragoza', province: 'Zaragoza', region: 'zaragoza', lat: 41.6561, lng: -0.8773 },

];

export const LOCALITY_BY_SLUG = Object.fromEntries(LOCALITIES.map(l => [l.slug, l]));

// Strip accents so "Malaga" finds "Málaga" and "Javea" finds "Jávea". Foreign owners
// almost never type the accents, and a search that punishes them for it is useless.
export function fold(s) {
  return String(s || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

export function searchLocalities(query, limit = 8) {
  const q = fold(query);
  if (q.length < 2) return [];
  const scored = [];
  for (const l of LOCALITIES) {
    const name = fold(l.name);
    const prov = fold(l.province);
    let score = -1;
    if (name.startsWith(q)) score = 0;
    else if (name.includes(q)) score = 1;
    else if (fold(l.slug).includes(q)) score = 2;
    else if (prov.startsWith(q)) score = 3;
    if (score >= 0) scored.push({ l, score });
  }
  scored.sort((a, b) => a.score - b.score || a.l.name.localeCompare(b.l.name));
  return scored.slice(0, limit).map(s => s.l);
}
