// Every string the section renders, in all six site languages.
//
// WHY THE COPY LIVES HERE AND NOT IN THE RULES BASE
// The rules base is the sourced record: article, value, status, source, date read. It
// stays in one language on purpose, because it is evidence and it is audited. What the
// reader sees is a sentence written here, keyed by rule id, with the period badge and the
// article link injected from the rule itself.
//
// The effect is the one we want. A figure can only ever come from a verified rule, while
// the words around it are free to read naturally in Norwegian or German. If a rule id is
// ever missing from a locale, useCopy falls back to English rather than showing the key.
//
// The Spanish search phrases are not translated. They are what the owner types into their
// own policy document, and that document is in Spanish.

const en = {
  h1: 'Where you stand when something goes wrong',
  lede: 'Two things an owner living abroad almost never finds out in time. How long you have to act, because several of these clocks are shorter than people expect and one of them starts on the day you got the keys. And whether the legal costs are already covered by a policy you are paying for, because that chapter is written in Spanish and most owners have never opened it.',
  notAdvice: 'This is not legal advice and it cannot tell you whether you would win. It tells you what the clock is, what to look for in your own documents, and what to ask.',
  q: 'What has happened?',
  empty: 'Pick what has happened and the page fills in.',
  step1: 'The clock',
  step2: 'You may already be covered',
  step3: 'Gather this now',
  step4: 'Who to take it to',
  watchLabel: 'Watch this:',
  findPrefix: 'Open your home policy and search for',
  gatherNote: 'Before anything is repaired, cleared or thrown away.',
  whoNote: 'An abogado handles the case. An administrador de fincas handles the community. A gestoria does not litigate. The directory says which is which and shows who has been reviewed in your language.',
  cta: 'Find a professional',
  goneLabel: 'No longer available.',
  footer: 'Every period on this page is read from a sourced rule with its article and the date it was checked. Nothing here is legal advice.',
  units: { years: 'years', year: 'year', months: 'months', month: 'month', days: 'days', day: 'day' },
  sit: {
    neighbour_damage: {
      label: 'Water or damage from a neighbour, or to one',
      lead: 'A leak, a crack, damp coming through a shared wall.',
      watch: 'One year is short, and it runs from when you found out, not from when it was fixed. If the damage is still getting worse, get that recorded now.',
      evidence: [
        'Photographs with dates, before anything is repaired',
        'A plumber or builder report saying where the water came from',
        'The community minutes if a shared pipe or roof is involved',
        'Your own policy number and the other party insurer if you know it',
      ],
    },
    community_decision: {
      label: 'A decision the owners meeting took',
      lead: 'A levy, a works vote, a rule you were not there for.',
      watch: 'If you were not at the meeting your window runs from the day the minutes reached you, not the day of the meeting. Keep the envelope or the email.',
      evidence: [
        'The minutes, and proof of the date they reached you',
        'The notice calling the meeting',
        'Proof you are up to date with community payments',
        'The statutes if the objection is that the decision breaks them',
      ],
    },
    community_debt: {
      label: 'The community says you owe money',
      lead: 'Arrears, a special levy, charges from before you bought.',
      watch: 'If the debt predates your purchase, what you inherited is the elapsed part of that year plus the three calendar years before it. That is not the same as how long they have to sue.',
      evidence: [
        'The statement of account from the administrator',
        'Your purchase deed and the certificate of debt given at completion',
        'Bank records of what you have paid',
      ],
    },
    tenant_arrears: {
      label: 'A tenant who is not paying',
      lead: 'Rent behind, or you want the property back.',
      watch: 'A written demand restarts the clock against the tenant, but not against a guarantor. Only a court claim does that.',
      evidence: [
        'The tenancy agreement and any guarantee',
        'A statement of what was due and what arrived, month by month',
        'Every written demand you have sent, with proof of delivery',
      ],
    },
    deposit: {
      label: 'A deposit that has not come back',
      lead: 'Yours from a landlord, or a tenant asking for theirs.',
      watch: 'Interest starts one month after the keys go back. Deposits are usually lodged with the regional housing body, which has its own rules.',
      evidence: [
        'The tenancy agreement showing the deposit',
        'Proof of the date the keys were handed over',
        'The inventory or condition report from the start and the end',
      ],
    },
    builder: {
      label: 'Building work that has gone wrong',
      lead: 'A new build defect, or a renovation that failed.',
      watch: 'Two clocks, not one. The defect has to appear inside the guarantee, and then you have two years from when the damage appeared to bring the claim.',
      evidence: [
        'The sign off certificate for the works and its date',
        'The building permission date, which decides which regime applies',
        'A technical report saying what the defect is and when it appeared',
        'The contract and every invoice',
      ],
    },
    hidden_defect: {
      label: 'A defect the seller did not mention',
      lead: 'Something you found after you bought.',
      watch: 'The hidden defects route dies six months after the property was handed over, whether or not you had found the problem. If you are near that, this is urgent.',
      evidence: [
        'The deed and the date you took possession',
        'The listing, the survey and anything the seller put in writing',
        'A report dating the defect and saying it was there before the sale',
      ],
    },
    insurer_refused: {
      label: 'Your insurer has said no',
      lead: 'A claim turned down, or a cost they will not pay.',
      watch: 'Complain to the insurer own customer service department first. You cannot go to the supervisor until you have, and you cannot force anyone into arbitration.',
      evidence: [
        'The refusal in writing, with its reasons',
        'The full policy including the general conditions, not just the schedule',
        'The page where you signed to accept the limiting clauses',
      ],
    },
  },
  chapter: {
    defensa: { heading: 'Legal expenses', says: 'Pays your lawyer, the procurador and court costs when you are in a case. This is the chapter the free choice of lawyer belongs to.' },
    reclamacion: { heading: 'Claiming against someone else', says: 'The claimant side. Pursuing whoever damaged your property. Often listed as a separate line from legal expenses.' },
    rental: { heading: 'Letting cover', says: 'Landlord and tenant work is commonly handled by a separate rental product rather than by an ordinary home policy. Check which one you hold.' },
  },
  rule: {
    'limit_contract_general': { s: 'A personal action with no special period runs out after five years, counted from when performance of the obligation could be demanded. It was fifteen years before 7 October 2015.' },
    'limit_extracontractual': { s: 'A claim for damage caused by someone you have no contract with runs out after one year, counted from when the injured party found out about the damage.' },
    'limit_interruption': { s: 'Three things stop the clock and restart it: going to court, an out of court demand by the creditor, and any acknowledgement of the debt by the debtor. A written demand is enough, which is unusual and is why a burofax matters.', n: 'Applies to prescripcion only. It does not extend the community challenge windows, the four year annulment window or the six month hidden defects window, which are caducidad.' },
    'limit_interruption_guarantor': { s: 'A court claim against the main debtor also stops the clock against a guarantor, but an out of court demand or a private acknowledgement does not.' },
    'limit_rent_arrears': { s: 'Unpaid rent runs out after five years, and each month counts from the day that month fell due.' },
    'limit_deposit_return': { s: 'Recovering a rental deposit has no period of its own in the tenancy law, so the general five year period applies. Statutory interest starts one month after the keys are handed back.', n: 'The tenancy law fixes when interest starts, not when the clock starts. Handing back the keys is the practical starting point rather than a statutory one, so treat the five years as the outer limit and act sooner.' },
    'limit_community_challenge': { s: 'Challenging a decision of the owners meeting: three months if the ground is that it seriously harms the community or unfairly harms one owner, one year if the ground is that it breaks the law or the statutes.' },
    'limit_community_challenge_absent': { s: 'An owner who was not at the meeting counts the window from the day the decision was communicated to them, not from the day of the meeting. This is the single most useful rule for an owner who lives abroad.' },
    'limit_community_challenge_standing': { s: 'To challenge a decision you must be up to date with community payments, or have paid the disputed amount into court first. The exception is a challenge about the shares themselves.' },
    'limit_community_buyer_liability': { s: "A buyer takes on the seller's unpaid community charges for the elapsed part of the year of purchase plus the three previous calendar years, and the property itself answers for them." },
    'limit_building_guarantee': { s: 'Building guarantees run from the date the works were signed off: ten years for structural defects, three years for defects that make the home unfit to live in, one year for finishes and against the builder only.' },
    'limit_building_action': { s: 'Once a covered defect appears you have two years to bring the claim, counted from when the damage occurred, not from when the building was signed off.' },
    'limit_building_scope': { s: 'These guarantees apply to buildings whose planning permission was applied for on or after 6 May 2000. Older buildings fall under the previous regime.' },
    'limit_hidden_defects': { s: 'A claim against the seller for hidden defects dies six months after the property was handed over, not six months after you found the defect. This is the shortest and harshest clock on the list.' },
    'limit_contract_annulment': { s: 'Setting a contract aside for mistake or deceit has a four year window, counted from completion of the contract.' },
    'limit_insurance_own_claim': { s: 'A claim against your own insurer under a property policy runs out after two years.' },
    'limit_catalonia': { s: 'Catalonia has its own civil code with its own limitation regime and a longer general period, so the Codigo Civil figures on this page are not the ones that apply to a property in Catalonia.' },
    'cover_free_choice': { s: 'You have the right to choose your own lawyer and procurador in any kind of proceedings, and the lawyer you choose takes instructions from you, never from the insurer. The right does not depend on the insurer agreeing, and it does not depend on there being a conflict of interest.' },
    'cover_separate_chapter': { s: 'Inside a combined home policy the legal expenses cover must appear as a separate chapter, stating what it covers and carrying its own premium. If you cannot find a separate premium line for it, that is worth asking about.' },
    'cover_policy_must_state': { s: 'The policy has to set out your right to choose your own lawyer in so many words. If there is a conflict of interest, or you and the insurer disagree about how to run the case, the insurer must tell you about that right immediately.' },
    'cover_limiting_clause_form': { s: 'A clause that limits your rights, such as a cap on the fees of a lawyer you choose yourself, has to be highlighted in the policy and specifically accepted by you in writing. General conditions may never be harmful to the insured.' },
    'cover_complaint_route': { s: 'If the insurer refuses, you must complain to its own customer service department first. Only then can you take it to the insurance supervisor, whose report is free but not binding and cannot order anyone to pay. Courts remain the only binding route.' },
    'cover_arbitration_repealed': { s: 'The article that used to let either side send a legal expenses dispute to arbitration was struck down as unconstitutional and is void. You cannot force your insurer into arbitration, whatever an older policy or an out of date article may say.', n: 'Kept in the rules base precisely because it is still repeated as current in circulation. The page must show it as no longer available, never as an option.' },
    'cover_search_terms': { s: 'The Spanish phrases to search for in your own policy document. Finding them tells you what you have; not finding them tells you what to ask about.' },
  },
};
const no = {
  h1: 'Slik står du når noe går galt',
  lede: 'To ting en eier som bor i utlandet nesten aldri får vite i tide. Hvor lang tid du har på å handle, fordi flere av disse fristene er kortere enn folk tror, og én av dem starter den dagen du fikk nøklene. Og om advokatutgiftene allerede dekkes av en forsikring du betaler for, fordi det kapittelet er skrevet på spansk og de fleste eiere aldri har åpnet det.',
  notAdvice: 'Dette er ikke juridisk rådgivning, og det kan ikke si deg om du ville vunnet. Det forteller deg hva fristen er, hva du skal se etter i dine egne dokumenter, og hva du skal spørre om.',
  q: 'Hva har skjedd?',
  empty: 'Velg hva som har skjedd, så fylles siden ut.',
  step1: 'Fristen',
  step2: 'Du kan allerede være dekket',
  step3: 'Samle dette nå',
  step4: 'Hvem du skal gå til',
  watchLabel: 'Merk deg dette:',
  findPrefix: 'Åpne husforsikringen din og søk etter',
  gatherNote: 'Før noe blir reparert, ryddet bort eller kastet.',
  whoNote: 'En abogado fører saken. En administrador de fincas håndterer sameiet. En gestoria fører ikke rettssaker. Katalogen sier hvem som er hva, og viser hvem som er vurdert på ditt språk.',
  cta: 'Finn en fagperson',
  goneLabel: 'Ikke lenger tilgjengelig.',
  footer: 'Hver frist på denne siden leses fra en kildeført regel med artikkel og datoen den ble kontrollert. Ingenting her er juridisk rådgivning.',
  units: { years: 'år', year: 'år', months: 'måneder', month: 'måned', days: 'dager', day: 'dag' },
  sit: {
    neighbour_damage: {
      label: 'Vannskade eller skade fra en nabo, eller til en nabo',
      lead: 'En lekkasje, en sprekk, fukt som kommer gjennom en felles vegg.',
      watch: 'Ett år er kort, og fristen løper fra da du fikk vite om skaden, ikke fra da den ble utbedret. Hvis skaden fortsatt forverrer seg, få det dokumentert nå.',
      evidence: [
        'Bilder med dato, før noe blir reparert',
        'En rapport fra rørlegger eller håndverker som sier hvor vannet kom fra',
        'Protokollen fra sameiet hvis et felles rør eller tak er involvert',
        'Ditt eget polisenummer og motpartens forsikringsselskap hvis du kjenner det',
      ],
    },
    community_decision: {
      label: 'En beslutning fra sameiermøtet',
      lead: 'En ekstrautgift, en avstemning om arbeider, en regel du ikke var til stede for.',
      watch: 'Hvis du ikke var på møtet, løper fristen fra dagen protokollen nådde deg, ikke fra møtedagen. Ta vare på konvolutten eller e-posten.',
      evidence: [
        'Protokollen, og bevis for datoen den nådde deg',
        'Innkallingen til møtet',
        'Bevis for at du er à jour med felleskostnadene',
        'Vedtektene hvis innsigelsen er at beslutningen bryter dem',
      ],
    },
    community_debt: {
      label: 'Sameiet sier at du skylder penger',
      lead: 'Restanser, en ekstrautgift, kostnader fra før du kjøpte.',
      watch: 'Hvis gjelden er eldre enn kjøpet ditt, er det du overtok den forløpte delen av kjøpsåret pluss de tre kalenderårene før. Det er ikke det samme som hvor lang tid de har på å gå til sak.',
      evidence: [
        'Kontoutskriften fra forretningsføreren',
        'Skjøtet ditt og gjeldsattesten som ble gitt ved overtakelse',
        'Bankutskrifter som viser hva du har betalt',
      ],
    },
    tenant_arrears: {
      label: 'En leietaker som ikke betaler',
      lead: 'Etterslep på husleie, eller du vil ha boligen tilbake.',
      watch: 'Et skriftlig krav starter fristen på nytt mot leietakeren, men ikke mot en kausjonist. Bare et søksmål gjør det.',
      evidence: [
        'Leiekontrakten og eventuell garanti',
        'En oppstilling over hva som forfalt og hva som kom inn, måned for måned',
        'Hvert skriftlige krav du har sendt, med leveringsbevis',
      ],
    },
    deposit: {
      label: 'Et depositum som ikke har kommet tilbake',
      lead: 'Ditt eget fra en utleier, eller en leietaker som ber om sitt.',
      watch: 'Renter løper fra én måned etter at nøklene er levert tilbake. Depositum settes vanligvis inn hos det regionale boligorganet, som har sine egne regler.',
      evidence: [
        'Leiekontrakten som viser depositumet',
        'Bevis for datoen nøklene ble levert',
        'Inventarliste eller tilstandsrapport fra start og slutt',
      ],
    },
    builder: {
      label: 'Byggearbeid som har gått galt',
      lead: 'En feil i et nybygg, eller en oppussing som slo feil.',
      watch: 'To frister, ikke én. Feilen må vise seg innenfor garantien, og deretter har du to år fra da skaden oppsto til å fremme kravet.',
      evidence: [
        'Ferdigattesten for arbeidene og datoen på den',
        'Datoen for byggetillatelsen, som avgjør hvilket regelverk som gjelder',
        'En teknisk rapport som sier hva feilen er og når den oppsto',
        'Kontrakten og alle fakturaer',
      ],
    },
    hidden_defect: {
      label: 'En feil selgeren ikke nevnte',
      lead: 'Noe du oppdaget etter at du kjøpte.',
      watch: 'Veien om skjulte mangler dør seks måneder etter at boligen ble overtatt, uansett om du hadde funnet problemet eller ikke. Er du nær den grensen, haster dette.',
      evidence: [
        'Skjøtet og datoen du overtok',
        'Annonsen, takstrapporten og alt selgeren skrev ned',
        'En rapport som daterer feilen og sier at den var der før salget',
      ],
    },
    insurer_refused: {
      label: 'Forsikringsselskapet ditt har sagt nei',
      lead: 'Et krav avslått, eller en kostnad de ikke vil dekke.',
      watch: 'Klag til selskapets egen kundeserviceavdeling først. Du kan ikke gå til tilsynet før du har gjort det, og du kan ikke tvinge noen inn i voldgift.',
      evidence: [
        'Avslaget skriftlig, med begrunnelsen',
        'Hele polisen inkludert de generelle vilkårene, ikke bare forsikringsbeviset',
        'Siden der du signerte for å godta de begrensende klausulene',
      ],
    },
  },
  chapter: {
    defensa: { heading: 'Juridisk bistand', says: 'Dekker advokaten din, prosessfullmektigen og rettsomkostninger når du står i en sak. Det er dette kapittelet det frie advokatvalget hører hjemme i.' },
    reclamacion: { heading: 'Krav mot en annen part', says: 'Kravssiden. Å forfølge den som skadet eiendommen din. Ofte oppført som en egen linje fra juridisk bistand.' },
    rental: { heading: 'Utleiedekning', says: 'Saker mellom utleier og leietaker håndteres vanligvis av et eget utleieprodukt, ikke av en vanlig husforsikring. Sjekk hvilken du har.' },
  },
  rule: {
    'limit_contract_general': { s: 'Et personlig krav uten egen frist foreldes etter fem år, regnet fra da oppfyllelse av forpliktelsen kunne kreves. Fristen var femten år før 7. oktober 2015.' },
    'limit_extracontractual': { s: 'Et krav om skade voldt av noen du ikke har kontrakt med, foreldes etter ett år, regnet fra da den skadelidte fikk vite om skaden.' },
    'limit_interruption': { s: 'Tre ting stanser fristen og starter den på nytt: å gå til domstolen, et utenrettslig krav fra kreditor, og enhver erkjennelse av gjelden fra skyldneren. Et skriftlig krav er nok, noe som er uvanlig og er grunnen til at en burofax betyr noe.', n: 'Gjelder bare prescripcion. Det forlenger ikke fristene for å angripe sameievedtak, fireårsfristen for ugyldighet eller seksmånedersfristen for skjulte mangler, som er caducidad.' },
    'limit_interruption_guarantor': { s: 'Et søksmål mot hovedskyldneren stanser også fristen mot en kausjonist, men et utenrettslig krav eller en privat erkjennelse gjør det ikke.' },
    'limit_rent_arrears': { s: 'Ubetalt husleie foreldes etter fem år, og hver måned regnes fra den dagen den måneden forfalt.' },
    'limit_deposit_return': { s: 'Å få tilbake et leiedepositum har ingen egen frist i husleieloven, så den alminnelige femårsfristen gjelder. Lovbestemte renter løper fra én måned etter at nøklene er levert tilbake.', n: 'Husleieloven fastsetter når renter starter, ikke når fristen starter. Tilbakelevering av nøklene er et praktisk og ikke et lovfestet utgangspunkt, så behandle de fem årene som ytterste grense og handle før.' },
    'limit_community_challenge': { s: 'Å angripe et vedtak fra sameiermøtet: tre måneder hvis grunnlaget er at det skader sameiet alvorlig eller rammer én eier urimelig, ett år hvis grunnlaget er at det bryter loven eller vedtektene.' },
    'limit_community_challenge_absent': { s: 'En eier som ikke var på møtet, regner fristen fra dagen vedtaket ble meddelt vedkommende, ikke fra møtedagen. Dette er den enkeltregelen som er mest nyttig for en eier som bor i utlandet.' },
    'limit_community_challenge_standing': { s: 'For å angripe et vedtak må du være à jour med felleskostnadene, eller først ha deponert det omtvistede beløpet i retten. Unntaket er et angrep som gjelder selve eierbrøkene.' },
    'limit_community_buyer_liability': { s: 'En kjøper overtar selgerens ubetalte felleskostnader for den forløpte delen av kjøpsåret pluss de tre foregående kalenderårene, og eiendommen selv hefter for dem.' },
    'limit_building_guarantee': { s: 'Byggegarantier løper fra datoen arbeidene ble ferdigattestert: ti år for konstruksjonsfeil, tre år for feil som gjør boligen ubeboelig, ett år for overflater og bare mot entreprenøren.' },
    'limit_building_action': { s: 'Når en dekket feil viser seg, har du to år på å fremme kravet, regnet fra da skaden oppsto, ikke fra da bygget ble ferdigattestert.' },
    'limit_building_scope': { s: 'Disse garantiene gjelder bygg der byggetillatelse ble søkt om 6. mai 2000 eller senere. Eldre bygg faller inn under det tidligere regelverket.' },
    'limit_hidden_defects': { s: 'Et krav mot selgeren for skjulte mangler dør seks måneder etter at boligen ble overlevert, ikke seks måneder etter at du fant mangelen. Dette er den korteste og hardeste fristen på listen.' },
    'limit_contract_annulment': { s: 'Å sette en kontrakt til side på grunn av villfarelse eller svik har et vindu på fire år, regnet fra kontraktens inngåelse.' },
    'limit_insurance_own_claim': { s: 'Et krav mot ditt eget forsikringsselskap under en eiendomsforsikring foreldes etter to år.' },
    'limit_catalonia': { s: 'Catalonia har sin egen sivillovbok med sitt eget foreldelsesregelverk og en lengre alminnelig frist, så tallene fra Codigo Civil på denne siden gjelder ikke for en eiendom i Catalonia.' },
    'cover_free_choice': { s: 'Du har rett til å velge din egen advokat og prosessfullmektig i enhver type sak, og advokaten du velger tar instruks fra deg, aldri fra forsikringsselskapet. Retten er ikke avhengig av at selskapet samtykker, og den er ikke avhengig av at det foreligger en interessekonflikt.' },
    'cover_separate_chapter': { s: 'Inne i en kombinert husforsikring må dekningen for juridisk bistand stå som et eget kapittel, med hva den dekker og med sin egen premie. Finner du ingen egen premielinje for den, er det verdt å spørre om.' },
    'cover_policy_must_state': { s: 'Polisen må uttrykkelig angi retten din til å velge din egen advokat. Foreligger det en interessekonflikt, eller er du og selskapet uenige om hvordan saken skal føres, må selskapet informere deg om den retten umiddelbart.' },
    'cover_limiting_clause_form': { s: 'En klausul som begrenser rettighetene dine, for eksempel et tak på salæret til en advokat du selv velger, må fremheves i polisen og godtas særskilt av deg skriftlig. Generelle vilkår kan aldri være til skade for den forsikrede.' },
    'cover_complaint_route': { s: 'Hvis selskapet avslår, må du først klage til selskapets egen kundeserviceavdeling. Først da kan du ta saken til forsikringstilsynet, hvis uttalelse er gratis, men ikke bindende, og som ikke kan pålegge noen å betale. Domstolene er fortsatt den eneste bindende veien.' },
    'cover_arbitration_repealed': { s: 'Artikkelen som tidligere lot hver av partene sende en tvist om juridisk bistand til voldgift, ble kjent grunnlovsstridig og er ugyldig. Du kan ikke tvinge forsikringsselskapet ditt inn i voldgift, uansett hva en eldre polise eller en utdatert artikkel måtte si.', n: 'Beholdt i regelbasen nettopp fordi den fortsatt gjentas som gjeldende. Siden må vise den som ikke lenger tilgjengelig, aldri som et alternativ.' },
    'cover_search_terms': { s: 'De spanske uttrykkene du skal søke etter i ditt eget forsikringsdokument. Finner du dem, vet du hva du har; finner du dem ikke, vet du hva du skal spørre om.' },
  },
};
const sv = {
  h1: 'Så står du när något går fel',
  lede: 'Två saker som en ägare bosatt utomlands nästan aldrig får veta i tid. Hur lång tid du har på dig att agera, eftersom flera av de här fristerna är kortare än folk tror och en av dem börjar den dag du fick nycklarna. Och om advokatkostnaderna redan täcks av en försäkring du betalar för, eftersom det kapitlet är skrivet på spanska och de flesta ägare aldrig har öppnat det.',
  notAdvice: 'Detta är inte juridisk rådgivning och det kan inte säga dig om du skulle vinna. Det säger dig vad fristen är, vad du ska leta efter i dina egna handlingar och vad du ska fråga om.',
  q: 'Vad har hänt?',
  empty: 'Välj vad som har hänt, så fylls sidan i.',
  step1: 'Fristen',
  step2: 'Du kan redan vara täckt',
  step3: 'Samla in detta nu',
  step4: 'Vem du ska vända dig till',
  watchLabel: 'Tänk på detta:',
  findPrefix: 'Öppna din hemförsäkring och sök efter',
  gatherNote: 'Innan något repareras, röjs undan eller slängs.',
  whoNote: 'En abogado driver ärendet. En administrador de fincas sköter samfälligheten. En gestoria driver inte processer. Katalogen säger vem som är vad och visar vilka som har granskats på ditt språk.',
  cta: 'Hitta en yrkesperson',
  goneLabel: 'Inte längre tillgängligt.',
  footer: 'Varje frist på den här sidan läses från en källbelagd regel med sin artikel och det datum den kontrollerades. Inget här är juridisk rådgivning.',
  units: { years: 'år', year: 'år', months: 'månader', month: 'månad', days: 'dagar', day: 'dag' },
  sit: {
    neighbour_damage: {
      label: 'Vattenskada eller skada från en granne, eller till en granne',
      lead: 'En läcka, en spricka, fukt som kommer genom en gemensam vägg.',
      watch: 'Ett år är kort, och fristen löper från när du fick veta om skadan, inte från när den åtgärdades. Om skadan fortfarande förvärras, se till att det dokumenteras nu.',
      evidence: [
        'Fotografier med datum, innan något repareras',
        'Ett utlåtande från rörmokare eller byggare om varifrån vattnet kom',
        'Samfällighetens protokoll om ett gemensamt rör eller tak är inblandat',
        'Ditt eget försäkringsnummer och motpartens försäkringsbolag om du känner till det',
      ],
    },
    community_decision: {
      label: 'Ett beslut från ägarstämman',
      lead: 'En extra avgift, en omröstning om arbeten, en regel du inte var med om.',
      watch: 'Om du inte var på stämman löper din frist från den dag protokollet nådde dig, inte från stämmodagen. Spara kuvertet eller mejlet.',
      evidence: [
        'Protokollet, och bevis för vilket datum det nådde dig',
        'Kallelsen till stämman',
        'Bevis på att du är i fas med samfällighetsavgifterna',
        'Stadgarna om invändningen är att beslutet bryter mot dem',
      ],
    },
    community_debt: {
      label: 'Samfälligheten säger att du är skyldig pengar',
      lead: 'Obetalda avgifter, en extra uttaxering, kostnader från före ditt köp.',
      watch: 'Om skulden är äldre än ditt köp är det du övertog den förflutna delen av köpåret plus de tre kalenderåren dessförinnan. Det är inte samma sak som hur lång tid de har på sig att stämma.',
      evidence: [
        'Kontoutdraget från förvaltaren',
        'Ditt köpebrev och skuldintyget som lämnades vid tillträdet',
        'Bankunderlag på vad du har betalat',
      ],
    },
    tenant_arrears: {
      label: 'En hyresgäst som inte betalar',
      lead: 'Hyra på efterkälken, eller du vill ha tillbaka bostaden.',
      watch: 'Ett skriftligt krav startar om fristen mot hyresgästen, men inte mot en borgensman. Bara en stämning gör det.',
      evidence: [
        'Hyresavtalet och eventuell borgen',
        'En sammanställning över vad som förföll och vad som kom in, månad för månad',
        'Varje skriftligt krav du har skickat, med leveransbevis',
      ],
    },
    deposit: {
      label: 'En deposition som inte har kommit tillbaka',
      lead: 'Din egen från en hyresvärd, eller en hyresgäst som ber om sin.',
      watch: 'Ränta löper från en månad efter att nycklarna lämnats tillbaka. Depositioner deponeras normalt hos det regionala bostadsorganet, som har sina egna regler.',
      evidence: [
        'Hyresavtalet som visar depositionen',
        'Bevis för vilket datum nycklarna lämnades över',
        'Inventarielistan eller besiktningen från början och slutet',
      ],
    },
    builder: {
      label: 'Byggarbete som har gått fel',
      lead: 'Ett fel i en nybyggnation, eller en renovering som misslyckades.',
      watch: 'Två frister, inte en. Felet måste visa sig inom garantin, och sedan har du två år från när skadan uppstod att framställa kravet.',
      evidence: [
        'Slutbeskedet för arbetena och dess datum',
        'Datumet för bygglovet, som avgör vilket regelverk som gäller',
        'Ett tekniskt utlåtande som säger vad felet är och när det uppstod',
        'Avtalet och varje faktura',
      ],
    },
    hidden_defect: {
      label: 'Ett fel som säljaren inte nämnde',
      lead: 'Något du upptäckte efter att du köpt.',
      watch: 'Vägen om dolda fel dör sex månader efter att bostaden överlämnades, oavsett om du hade hittat problemet eller inte. Är du nära den gränsen är det brådskande.',
      evidence: [
        'Köpebrevet och datumet du tillträdde',
        'Annonsen, besiktningen och allt säljaren skrev ned',
        'Ett utlåtande som daterar felet och säger att det fanns före försäljningen',
      ],
    },
    insurer_refused: {
      label: 'Ditt försäkringsbolag har sagt nej',
      lead: 'Ett krav avslaget, eller en kostnad de inte vill betala.',
      watch: 'Klaga till bolagets egen kundserviceavdelning först. Du kan inte gå till tillsynsmyndigheten innan du gjort det, och du kan inte tvinga någon till skiljeförfarande.',
      evidence: [
        'Avslaget skriftligen, med sina skäl',
        'Hela försäkringsbrevet inklusive de allmänna villkoren, inte bara försäkringsbeskedet',
        'Sidan där du skrev under för att godta de begränsande klausulerna',
      ],
    },
  },
  chapter: {
    defensa: { heading: 'Rättsskydd', says: 'Betalar din advokat, ombudet och rättegångskostnader när du står i ett ärende. Det är i det här kapitlet det fria advokatvalet hör hemma.' },
    reclamacion: { heading: 'Krav mot någon annan', says: 'Kravsidan. Att gå efter den som skadade din egendom. Ofta angiven som en egen rad skild från rättsskyddet.' },
    rental: { heading: 'Uthyrningsskydd', says: 'Ärenden mellan hyresvärd och hyresgäst hanteras normalt av en separat uthyrningsprodukt snarare än av en vanlig hemförsäkring. Kontrollera vilken du har.' },
  },
  rule: {
    'limit_contract_general': { s: 'Ett personligt anspråk utan egen frist preskriberas efter fem år, räknat från när fullgörande av förpliktelsen kunde krävas. Fristen var femton år före den 7 oktober 2015.' },
    'limit_extracontractual': { s: 'Ett anspråk för skada orsakad av någon du inte har avtal med preskriberas efter ett år, räknat från när den skadelidande fick kännedom om skadan.' },
    'limit_interruption': { s: 'Tre saker stoppar fristen och startar om den: att gå till domstol, ett utomrättsligt krav från borgenären, och varje erkännande av skulden från gäldenären. Ett skriftligt krav räcker, vilket är ovanligt och är skälet till att en burofax spelar roll.', n: 'Gäller endast prescripcion. Det förlänger inte fristerna för att klandra stämmobeslut, fyraårsfristen för ogiltighet eller sexmånadersfristen för dolda fel, som är caducidad.' },
    'limit_interruption_guarantor': { s: 'En stämning mot huvudgäldenären stoppar också fristen mot en borgensman, men ett utomrättsligt krav eller ett privat erkännande gör det inte.' },
    'limit_rent_arrears': { s: 'Obetald hyra preskriberas efter fem år, och varje månad räknas från den dag den månaden förföll.' },
    'limit_deposit_return': { s: 'Att få tillbaka en hyresdeposition har ingen egen frist i hyreslagen, så den allmänna femårsfristen gäller. Lagstadgad ränta löper från en månad efter att nycklarna lämnats tillbaka.', n: 'Hyreslagen fastställer när räntan börjar löpa, inte när fristen börjar. Återlämnandet av nycklarna är en praktisk och inte en lagfäst utgångspunkt, så behandla de fem åren som en yttersta gräns och agera tidigare.' },
    'limit_community_challenge': { s: 'Att klandra ett beslut av ägarstämman: tre månader om grunden är att det allvarligt skadar samfälligheten eller drabbar en ägare oskäligt, ett år om grunden är att det strider mot lag eller stadgar.' },
    'limit_community_challenge_absent': { s: 'En ägare som inte var på stämman räknar fristen från den dag beslutet meddelades vederbörande, inte från stämmodagen. Det är den enskilda regel som är mest användbar för en ägare som bor utomlands.' },
    'limit_community_challenge_standing': { s: 'För att klandra ett beslut måste du vara i fas med samfällighetsavgifterna, eller först ha deponerat det omtvistade beloppet i domstol. Undantaget är ett klander som gäller själva andelstalen.' },
    'limit_community_buyer_liability': { s: 'En köpare övertar säljarens obetalda samfällighetsavgifter för den förflutna delen av köpåret plus de tre föregående kalenderåren, och fastigheten själv svarar för dem.' },
    'limit_building_guarantee': { s: 'Byggnadsgarantier löper från det datum arbetena slutbesiktigades: tio år för konstruktionsfel, tre år för fel som gör bostaden obeboelig, ett år för ytskikt och endast mot byggaren.' },
    'limit_building_action': { s: 'När ett täckt fel visar sig har du två år på dig att framställa kravet, räknat från när skadan uppstod, inte från när byggnaden slutbesiktigades.' },
    'limit_building_scope': { s: 'De här garantierna gäller byggnader vars bygglov söktes den 6 maj 2000 eller senare. Äldre byggnader faller under det tidigare regelverket.' },
    'limit_hidden_defects': { s: 'Ett anspråk mot säljaren för dolda fel dör sex månader efter att bostaden överlämnades, inte sex månader efter att du hittade felet. Det är den kortaste och hårdaste fristen på listan.' },
    'limit_contract_annulment': { s: 'Att sätta ett avtal åt sidan på grund av villfarelse eller svek har ett fönster på fyra år, räknat från avtalets ingående.' },
    'limit_insurance_own_claim': { s: 'Ett anspråk mot ditt eget försäkringsbolag under en egendomsförsäkring preskriberas efter två år.' },
    'limit_catalonia': { s: 'Katalonien har sin egen civillag med sitt eget preskriptionsregelverk och en längre allmän frist, så siffrorna från Codigo Civil på den här sidan gäller inte för en fastighet i Katalonien.' },
    'cover_free_choice': { s: 'Du har rätt att välja din egen advokat och ditt eget ombud i varje slags förfarande, och den advokat du väljer tar instruktioner från dig, aldrig från försäkringsbolaget. Rätten är inte beroende av att bolaget samtycker, och den är inte beroende av att det föreligger en intressekonflikt.' },
    'cover_separate_chapter': { s: 'Inuti en kombinerad hemförsäkring måste rättsskyddet stå som ett eget kapitel, med vad det täcker och med sin egen premie. Hittar du ingen egen premierad för det är det värt att fråga om.' },
    'cover_policy_must_state': { s: 'Försäkringsbrevet måste uttryckligen ange din rätt att välja din egen advokat. Föreligger en intressekonflikt, eller är du och bolaget oense om hur ärendet ska drivas, måste bolaget omedelbart upplysa dig om den rätten.' },
    'cover_limiting_clause_form': { s: 'En klausul som begränsar dina rättigheter, exempelvis ett tak för arvodet till en advokat du själv väljer, måste framhävas i försäkringsbrevet och godtas särskilt av dig skriftligen. Allmänna villkor får aldrig vara till skada för den försäkrade.' },
    'cover_complaint_route': { s: 'Om bolaget avslår måste du först klaga till dess egen kundserviceavdelning. Först därefter kan du ta det till försäkringstillsynen, vars utlåtande är kostnadsfritt men inte bindande och inte kan ålägga någon att betala. Domstolarna förblir den enda bindande vägen.' },
    'cover_arbitration_repealed': { s: 'Artikeln som tidigare lät endera sidan skicka en rättsskyddstvist till skiljeförfarande förklarades grundlagsstridig och är ogiltig. Du kan inte tvinga ditt försäkringsbolag till skiljeförfarande, oavsett vad ett äldre försäkringsbrev eller en föråldrad artikel säger.', n: 'Behållen i regelbasen just därför att den fortfarande upprepas som gällande. Sidan måste visa den som inte längre tillgänglig, aldrig som ett alternativ.' },
    'cover_search_terms': { s: 'De spanska uttryck du ska söka efter i ditt eget försäkringsdokument. Hittar du dem vet du vad du har; hittar du dem inte vet du vad du ska fråga om.' },
  },
};
const de = {
  h1: 'Wo Sie stehen, wenn etwas schiefgeht',
  lede: 'Zwei Dinge, die ein im Ausland lebender Eigentümer fast nie rechtzeitig erfährt. Wie lange Sie Zeit haben zu handeln, denn mehrere dieser Fristen sind kürzer als gedacht und eine davon beginnt an dem Tag, an dem Sie die Schlüssel bekommen haben. Und ob die Anwaltskosten bereits durch eine Police gedeckt sind, die Sie ohnehin bezahlen, denn dieses Kapitel ist auf Spanisch geschrieben und die meisten Eigentümer haben es nie geöffnet.',
  notAdvice: 'Dies ist keine Rechtsberatung und sagt Ihnen nicht, ob Sie gewinnen würden. Es sagt Ihnen, wie die Frist lautet, wonach Sie in Ihren eigenen Unterlagen suchen und was Sie fragen sollten.',
  q: 'Was ist passiert?',
  empty: 'Wählen Sie aus, was passiert ist, und die Seite füllt sich.',
  step1: 'Die Frist',
  step2: 'Sie sind womöglich schon gedeckt',
  step3: 'Sammeln Sie das jetzt',
  step4: 'An wen Sie sich wenden',
  watchLabel: 'Darauf achten:',
  findPrefix: 'Öffnen Sie Ihre Wohngebäude- oder Hausratpolice und suchen Sie nach',
  gatherNote: 'Bevor irgendetwas repariert, geräumt oder weggeworfen wird.',
  whoNote: 'Ein abogado führt den Fall. Ein administrador de fincas betreut die Eigentümergemeinschaft. Ein gestoria prozessiert nicht. Das Verzeichnis sagt, wer was ist, und zeigt, wer in Ihrer Sprache geprüft wurde.',
  cta: 'Fachperson finden',
  goneLabel: 'Nicht mehr verfügbar.',
  footer: 'Jede Frist auf dieser Seite stammt aus einer belegten Regel mit Artikel und Prüfdatum. Nichts hier ist Rechtsberatung.',
  units: { years: 'Jahre', year: 'Jahr', months: 'Monate', month: 'Monat', days: 'Tage', day: 'Tag' },
  sit: {
    neighbour_damage: {
      label: 'Wasser oder Schaden von einem Nachbarn, oder zu einem Nachbarn',
      lead: 'Ein Leck, ein Riss, Feuchtigkeit durch eine gemeinsame Wand.',
      watch: 'Ein Jahr ist kurz, und die Frist läuft ab dem Zeitpunkt, an dem Sie davon erfahren haben, nicht ab der Reparatur. Wenn der Schaden noch zunimmt, lassen Sie das jetzt festhalten.',
      evidence: [
        'Fotos mit Datum, bevor irgendetwas repariert wird',
        'Ein Bericht von Installateur oder Bauhandwerker, woher das Wasser kam',
        'Das Protokoll der Eigentümergemeinschaft, wenn eine gemeinsame Leitung oder ein Dach betroffen ist',
        'Ihre eigene Policennummer und der Versicherer der Gegenseite, falls bekannt',
      ],
    },
    community_decision: {
      label: 'Ein Beschluss der Eigentümerversammlung',
      lead: 'Eine Umlage, eine Abstimmung über Arbeiten, eine Regel, bei der Sie nicht dabei waren.',
      watch: 'Waren Sie nicht bei der Versammlung, läuft Ihre Frist ab dem Tag, an dem Sie das Protokoll erreicht hat, nicht ab dem Versammlungstag. Bewahren Sie den Umschlag oder die E-Mail auf.',
      evidence: [
        'Das Protokoll und ein Nachweis über das Datum, an dem es Sie erreicht hat',
        'Die Einladung zur Versammlung',
        'Ein Nachweis, dass Sie mit den Gemeinschaftszahlungen aktuell sind',
        'Die Satzung, wenn der Einwand lautet, dass der Beschluss gegen sie verstößt',
      ],
    },
    community_debt: {
      label: 'Die Eigentümergemeinschaft sagt, Sie schulden Geld',
      lead: 'Rückstände, eine Sonderumlage, Kosten aus der Zeit vor Ihrem Kauf.',
      watch: 'Liegt die Schuld vor Ihrem Kauf, haben Sie den abgelaufenen Teil des Kaufjahres plus die drei Kalenderjahre davor übernommen. Das ist nicht dasselbe wie die Frist, in der geklagt werden kann.',
      evidence: [
        'Die Kontoaufstellung des Verwalters',
        'Ihre Kaufurkunde und die bei Abschluss erteilte Schuldenbescheinigung',
        'Bankbelege über das, was Sie gezahlt haben',
      ],
    },
    tenant_arrears: {
      label: 'Ein Mieter, der nicht zahlt',
      lead: 'Miete im Rückstand, oder Sie wollen die Immobilie zurück.',
      watch: 'Eine schriftliche Mahnung setzt die Frist gegenüber dem Mieter neu in Gang, gegenüber einem Bürgen jedoch nicht. Das tut nur eine Klage.',
      evidence: [
        'Der Mietvertrag und eine etwaige Bürgschaft',
        'Eine Aufstellung, was fällig war und was einging, Monat für Monat',
        'Jede schriftliche Mahnung, die Sie gesendet haben, mit Zustellnachweis',
      ],
    },
    deposit: {
      label: 'Eine Kaution, die nicht zurückgekommen ist',
      lead: 'Ihre eigene von einem Vermieter, oder ein Mieter, der seine verlangt.',
      watch: 'Zinsen laufen ab einem Monat nach Rückgabe der Schlüssel. Kautionen werden meist bei der regionalen Wohnungsbehörde hinterlegt, die eigene Regeln hat.',
      evidence: [
        'Der Mietvertrag, der die Kaution ausweist',
        'Ein Nachweis über das Datum der Schlüsselübergabe',
        'Das Inventar oder Übergabeprotokoll von Anfang und Ende',
      ],
    },
    builder: {
      label: 'Bauarbeiten, die schiefgegangen sind',
      lead: 'Ein Mangel am Neubau, oder eine Renovierung, die misslungen ist.',
      watch: 'Zwei Fristen, nicht eine. Der Mangel muss innerhalb der Gewährleistung auftreten, und dann haben Sie zwei Jahre ab dem Auftreten des Schadens, um den Anspruch geltend zu machen.',
      evidence: [
        'Die Abnahmebescheinigung der Arbeiten und ihr Datum',
        'Das Datum der Baugenehmigung, das entscheidet, welches Regime gilt',
        'Ein technischer Bericht, der den Mangel benennt und sein Auftreten datiert',
        'Der Vertrag und jede Rechnung',
      ],
    },
    hidden_defect: {
      label: 'Ein Mangel, den der Verkäufer nicht erwähnt hat',
      lead: 'Etwas, das Sie nach dem Kauf gefunden haben.',
      watch: 'Der Weg über verdeckte Mängel endet sechs Monate nach Übergabe der Immobilie, unabhängig davon, ob Sie das Problem entdeckt hatten. Wenn Sie nahe daran sind, ist es dringend.',
      evidence: [
        'Die Urkunde und das Datum der Besitzübergabe',
        'Das Exposé, das Gutachten und alles, was der Verkäufer schriftlich festgehalten hat',
        'Ein Bericht, der den Mangel datiert und sagt, dass er vor dem Verkauf vorlag',
      ],
    },
    insurer_refused: {
      label: 'Ihr Versicherer hat nein gesagt',
      lead: 'Ein abgelehnter Anspruch, oder Kosten, die er nicht tragen will.',
      watch: 'Beschweren Sie sich zuerst bei der eigenen Kundendienstabteilung des Versicherers. Vor der Aufsicht geht es erst danach, und niemand kann zu einem Schiedsverfahren gezwungen werden.',
      evidence: [
        'Die Ablehnung schriftlich, mit ihren Gründen',
        'Die vollständige Police einschließlich der allgemeinen Bedingungen, nicht nur den Versicherungsschein',
        'Die Seite, auf der Sie die einschränkenden Klauseln unterschrieben haben',
      ],
    },
  },
  chapter: {
    defensa: { heading: 'Rechtsschutz', says: 'Zahlt Ihren Anwalt, den Prozessvertreter und Gerichtskosten, wenn Sie in einem Verfahren stehen. Zu diesem Kapitel gehört die freie Anwaltswahl.' },
    reclamacion: { heading: 'Anspruch gegen einen anderen', says: 'Die Anspruchsseite. Vorgehen gegen denjenigen, der Ihre Immobilie beschädigt hat. Oft als eigene Position getrennt vom Rechtsschutz aufgeführt.' },
    rental: { heading: 'Vermietungsschutz', says: 'Fälle zwischen Vermieter und Mieter werden üblicherweise über ein eigenes Vermietungsprodukt abgewickelt und nicht über eine gewöhnliche Wohngebäudepolice. Prüfen Sie, welche Sie halten.' },
  },
  rule: {
    'limit_contract_general': { s: 'Ein persönlicher Anspruch ohne eigene Frist verjährt nach fünf Jahren, gerechnet ab dem Zeitpunkt, zu dem die Erfüllung der Verpflichtung verlangt werden konnte. Vor dem 7. Oktober 2015 waren es fünfzehn Jahre.' },
    'limit_extracontractual': { s: 'Ein Anspruch wegen eines Schadens, den jemand verursacht hat, mit dem Sie keinen Vertrag haben, verjährt nach einem Jahr, gerechnet ab Kenntnis des Geschädigten vom Schaden.' },
    'limit_interruption': { s: 'Drei Dinge halten die Frist an und setzen sie neu in Gang: der Gang zum Gericht, eine außergerichtliche Mahnung des Gläubigers und jedes Anerkenntnis der Schuld durch den Schuldner. Eine schriftliche Mahnung genügt, was ungewöhnlich ist und der Grund dafür ist, dass ein burofax zählt.', n: 'Gilt nur für prescripcion. Es verlängert weder die Fristen zur Anfechtung von Beschlüssen der Eigentümergemeinschaft noch die Vierjahresfrist für die Anfechtung noch die Sechsmonatsfrist für verdeckte Mängel, denn das sind caducidad.' },
    'limit_interruption_guarantor': { s: 'Eine Klage gegen den Hauptschuldner hält die Frist auch gegenüber einem Bürgen an, eine außergerichtliche Mahnung oder ein privates Anerkenntnis jedoch nicht.' },
    'limit_rent_arrears': { s: 'Nicht gezahlte Miete verjährt nach fünf Jahren, und jeder Monat zählt ab dem Tag, an dem dieser Monat fällig wurde.' },
    'limit_deposit_return': { s: 'Die Rückforderung einer Mietkaution hat im Mietrecht keine eigene Frist, daher gilt die allgemeine Fünfjahresfrist. Gesetzliche Zinsen laufen ab einem Monat nach Rückgabe der Schlüssel.', n: 'Das Mietrecht regelt, wann die Zinsen beginnen, nicht wann die Frist beginnt. Die Rückgabe der Schlüssel ist ein praktischer und kein gesetzlicher Ausgangspunkt, behandeln Sie die fünf Jahre daher als äußerste Grenze und handeln Sie früher.' },
    'limit_community_challenge': { s: 'Anfechtung eines Beschlusses der Eigentümerversammlung: drei Monate, wenn der Grund ist, dass er die Gemeinschaft schwer schädigt oder einen Eigentümer unbillig benachteiligt, ein Jahr, wenn der Grund ist, dass er gegen Gesetz oder Satzung verstößt.' },
    'limit_community_challenge_absent': { s: 'Ein Eigentümer, der nicht bei der Versammlung war, rechnet die Frist ab dem Tag, an dem ihm der Beschluss mitgeteilt wurde, nicht ab dem Versammlungstag. Das ist die für einen im Ausland lebenden Eigentümer nützlichste Einzelregel.' },
    'limit_community_challenge_standing': { s: 'Um einen Beschluss anzufechten, müssen Sie mit den Gemeinschaftszahlungen aktuell sein oder den streitigen Betrag zuvor bei Gericht hinterlegt haben. Ausgenommen ist eine Anfechtung, die die Anteile selbst betrifft.' },
    'limit_community_buyer_liability': { s: 'Ein Käufer übernimmt die offenen Gemeinschaftskosten des Verkäufers für den abgelaufenen Teil des Kaufjahres plus die drei vorangegangenen Kalenderjahre, und die Immobilie selbst haftet dafür.' },
    'limit_building_guarantee': { s: 'Baugewährleistungen laufen ab dem Datum der Abnahme der Arbeiten: zehn Jahre für Mängel an der Konstruktion, drei Jahre für Mängel, die die Wohnung unbewohnbar machen, ein Jahr für Ausbau und nur gegenüber dem Bauunternehmer.' },
    'limit_building_action': { s: 'Sobald ein gedeckter Mangel auftritt, haben Sie zwei Jahre, um den Anspruch geltend zu machen, gerechnet ab dem Eintritt des Schadens, nicht ab der Abnahme des Gebäudes.' },
    'limit_building_scope': { s: 'Diese Gewährleistungen gelten für Gebäude, deren Baugenehmigung am 6. Mai 2000 oder später beantragt wurde. Ältere Gebäude fallen unter das frühere Regime.' },
    'limit_hidden_defects': { s: 'Ein Anspruch gegen den Verkäufer wegen verdeckter Mängel endet sechs Monate nach Übergabe der Immobilie, nicht sechs Monate nachdem Sie den Mangel gefunden haben. Das ist die kürzeste und härteste Frist auf der Liste.' },
    'limit_contract_annulment': { s: 'Die Aufhebung eines Vertrags wegen Irrtums oder Täuschung hat ein Fenster von vier Jahren, gerechnet ab Abschluss des Vertrags.' },
    'limit_insurance_own_claim': { s: 'Ein Anspruch gegen Ihren eigenen Versicherer aus einer Sachversicherung verjährt nach zwei Jahren.' },
    'limit_catalonia': { s: 'Katalonien hat ein eigenes Zivilgesetzbuch mit eigenem Verjährungsregime und einer längeren allgemeinen Frist, die Zahlen aus dem Codigo Civil auf dieser Seite gelten daher nicht für eine Immobilie in Katalonien.' },
    'cover_free_choice': { s: 'Sie haben das Recht, in jeder Art von Verfahren Ihren eigenen Anwalt und Prozessvertreter zu wählen, und der von Ihnen gewählte Anwalt nimmt Weisungen von Ihnen entgegen, nie vom Versicherer. Das Recht hängt weder von der Zustimmung des Versicherers noch vom Vorliegen eines Interessenkonflikts ab.' },
    'cover_separate_chapter': { s: 'In einer kombinierten Wohngebäudepolice muss der Rechtsschutz als eigenes Kapitel erscheinen, das angibt, was er deckt, und eine eigene Prämie tragen. Finden Sie keine eigene Prämienzeile dafür, lohnt sich die Nachfrage.' },
    'cover_policy_must_state': { s: 'Die Police muss Ihr Recht auf freie Anwaltswahl ausdrücklich benennen. Liegt ein Interessenkonflikt vor, oder sind Sie und der Versicherer über die Führung des Falls uneinig, muss der Versicherer Sie unverzüglich auf dieses Recht hinweisen.' },
    'cover_limiting_clause_form': { s: 'Eine Klausel, die Ihre Rechte einschränkt, etwa eine Obergrenze für das Honorar eines selbst gewählten Anwalts, muss in der Police hervorgehoben und von Ihnen ausdrücklich schriftlich angenommen werden. Allgemeine Bedingungen dürfen für den Versicherten nie nachteilig sein.' },
    'cover_complaint_route': { s: 'Lehnt der Versicherer ab, müssen Sie sich zuerst bei seiner eigenen Kundendienstabteilung beschweren. Erst danach können Sie die Versicherungsaufsicht anrufen, deren Stellungnahme kostenlos, aber nicht bindend ist und niemanden zur Zahlung verpflichten kann. Gerichte bleiben der einzige bindende Weg.' },
    'cover_arbitration_repealed': { s: 'Der Artikel, der es früher jeder Seite erlaubte, einen Rechtsschutzstreit in ein Schiedsverfahren zu geben, wurde als verfassungswidrig aufgehoben und ist nichtig. Sie können Ihren Versicherer nicht zu einem Schiedsverfahren zwingen, was auch immer eine ältere Police oder ein veralteter Artikel sagen mag.', n: 'Genau deshalb in der Regelbasis behalten, weil er weiterhin als geltend wiederholt wird. Die Seite muss ihn als nicht mehr verfügbar zeigen, nie als Option.' },
    'cover_search_terms': { s: 'Die spanischen Begriffe, nach denen Sie in Ihrem eigenen Policendokument suchen. Sie zu finden sagt Ihnen, was Sie haben; sie nicht zu finden sagt Ihnen, wonach Sie fragen sollten.' },
  },
};
const fr = {
  h1: 'Où vous en êtes quand un problème survient',
  lede: "Deux choses qu'un propriétaire vivant à l'étranger n'apprend presque jamais à temps. Le temps dont vous disposez pour agir, car plusieurs de ces délais sont plus courts qu'on ne le croit et l'un d'eux commence le jour où vous avez reçu les clés. Et si les frais d'avocat sont déjà couverts par un contrat que vous payez, car ce chapitre est rédigé en espagnol et la plupart des propriétaires ne l'ont jamais ouvert.",
  notAdvice: "Ceci n'est pas un conseil juridique et ne peut pas vous dire si vous gagneriez. Cela vous dit quel est le délai, ce qu'il faut chercher dans vos propres documents et ce qu'il faut demander.",
  q: "Que s'est-il passé ?",
  empty: "Choisissez ce qui s'est passé et la page se remplit.",
  step1: 'Le délai',
  step2: 'Vous êtes peut-être déjà couvert',
  step3: 'Rassemblez ceci maintenant',
  step4: 'À qui vous adresser',
  watchLabel: 'À surveiller :',
  findPrefix: 'Ouvrez votre contrat habitation et cherchez',
  gatherNote: "Avant que quoi que ce soit ne soit réparé, déblayé ou jeté.",
  whoNote: "Un abogado mène le dossier. Un administrador de fincas gère la copropriété. Un gestoria ne plaide pas. L'annuaire dit qui fait quoi et montre qui a été évalué dans votre langue.",
  cta: 'Trouver un professionnel',
  goneLabel: "Ce recours n'existe plus.",
  footer: "Chaque délai de cette page est lu depuis une règle sourcée, avec son article et la date de vérification. Rien ici n'est un conseil juridique.",
  units: { years: 'ans', year: 'an', months: 'mois', month: 'mois', days: 'jours', day: 'jour' },
  sit: {
    neighbour_damage: {
      label: "Dégât des eaux ou dommage venant d'un voisin, ou causé à un voisin",
      lead: 'Une fuite, une fissure, une humidité qui traverse un mur mitoyen.',
      watch: "Un an, c'est court, et le délai court à partir du moment où vous l'avez su, pas de la réparation. Si le dommage continue de s'aggraver, faites-le constater maintenant.",
      evidence: [
        "Des photographies datées, avant toute réparation",
        "Un rapport de plombier ou de maçon indiquant d'où venait l'eau",
        "Le procès-verbal de la copropriété si une canalisation ou une toiture commune est en cause",
        "Votre numéro de contrat et l'assureur de la partie adverse si vous le connaissez",
      ],
    },
    community_decision: {
      label: "Une décision prise par l'assemblée des copropriétaires",
      lead: "Un appel de fonds, un vote de travaux, une règle adoptée en votre absence.",
      watch: "Si vous n'étiez pas à l'assemblée, votre délai court du jour où le procès-verbal vous est parvenu, pas du jour de l'assemblée. Gardez l'enveloppe ou le courriel.",
      evidence: [
        "Le procès-verbal, et la preuve de la date à laquelle il vous est parvenu",
        "La convocation à l'assemblée",
        "La preuve que vous êtes à jour des charges de copropriété",
        "Les statuts si le grief est que la décision les enfreint",
      ],
    },
    community_debt: {
      label: "La copropriété dit que vous devez de l'argent",
      lead: "Des arriérés, un appel de fonds exceptionnel, des charges antérieures à votre achat.",
      watch: "Si la dette est antérieure à votre achat, ce que vous avez repris est la partie écoulée de l'année d'achat plus les trois années civiles précédentes. Ce n'est pas la même chose que le délai dont ils disposent pour agir en justice.",
      evidence: [
        "Le relevé de compte du syndic",
        "Votre acte d'achat et le certificat de dettes remis à la signature",
        "Les relevés bancaires de ce que vous avez payé",
      ],
    },
    tenant_arrears: {
      label: 'Un locataire qui ne paie pas',
      lead: 'Des loyers en retard, ou vous voulez récupérer le bien.',
      watch: "Une mise en demeure écrite fait repartir le délai contre le locataire, mais pas contre une caution. Seule une action en justice le fait.",
      evidence: [
        'Le bail et toute garantie',
        'Un relevé de ce qui était dû et de ce qui est arrivé, mois par mois',
        "Chaque mise en demeure écrite envoyée, avec preuve de remise",
      ],
    },
    deposit: {
      label: "Un dépôt de garantie qui n'est pas revenu",
      lead: "Le vôtre chez un bailleur, ou un locataire qui réclame le sien.",
      watch: "Les intérêts courent un mois après la remise des clés. Les dépôts sont en général consignés auprès de l'organisme régional du logement, qui a ses propres règles.",
      evidence: [
        'Le bail mentionnant le dépôt de garantie',
        'La preuve de la date de remise des clés',
        "L'état des lieux d'entrée et de sortie",
      ],
    },
    builder: {
      label: 'Des travaux qui ont mal tourné',
      lead: "Un défaut sur du neuf, ou une rénovation ratée.",
      watch: "Deux délais, pas un. Le défaut doit apparaître pendant la garantie, et vous avez ensuite deux ans à compter de l'apparition du dommage pour agir.",
      evidence: [
        "Le certificat de réception des travaux et sa date",
        "La date du permis de construire, qui décide du régime applicable",
        "Un rapport technique indiquant le défaut et la date de son apparition",
        'Le contrat et toutes les factures',
      ],
    },
    hidden_defect: {
      label: "Un défaut que le vendeur n'a pas signalé",
      lead: "Quelque chose découvert après l'achat.",
      watch: "La voie des vices cachés s'éteint six mois après la remise du bien, que vous ayez découvert le problème ou non. Si vous en êtes proche, c'est urgent.",
      evidence: [
        "L'acte et la date de prise de possession",
        "L'annonce, l'expertise et tout ce que le vendeur a écrit",
        "Un rapport datant le défaut et indiquant qu'il existait avant la vente",
      ],
    },
    insurer_refused: {
      label: 'Votre assureur a dit non',
      lead: "Un sinistre refusé, ou un coût qu'il ne veut pas prendre en charge.",
      watch: "Adressez d'abord une réclamation au service client de l'assureur. Vous ne pouvez pas saisir le superviseur avant, et personne ne peut être contraint à l'arbitrage.",
      evidence: [
        'Le refus par écrit, avec ses motifs',
        "Le contrat complet, conditions générales incluses, pas seulement les conditions particulières",
        'La page où vous avez signé pour accepter les clauses limitatives',
      ],
    },
  },
  chapter: {
    defensa: { heading: 'Protection juridique', says: "Paie votre avocat, le procurador et les frais de justice quand vous êtes dans une procédure. C'est le chapitre auquel appartient le libre choix de l'avocat." },
    reclamacion: { heading: "Réclamation contre un tiers", says: "Le côté demandeur. Poursuivre celui qui a endommagé votre bien. Souvent indiqué sur une ligne distincte de la protection juridique." },
    rental: { heading: 'Garantie location', says: "Les litiges entre bailleur et locataire relèvent le plus souvent d'un produit locatif distinct plutôt que d'un contrat habitation ordinaire. Vérifiez lequel vous détenez." },
  },
  rule: {
    'limit_contract_general': { s: "Une action personnelle sans délai propre se prescrit par cinq ans, comptés à partir du moment où l'exécution de l'obligation pouvait être exigée. Le délai était de quinze ans avant le 7 octobre 2015." },
    'limit_extracontractual': { s: "Une action pour un dommage causé par quelqu'un avec qui vous n'avez pas de contrat se prescrit par un an, compté à partir du moment où la victime a eu connaissance du dommage." },
    'limit_interruption': { s: "Trois choses arrêtent le délai et le font repartir : agir en justice, une mise en demeure extrajudiciaire du créancier, et toute reconnaissance de la dette par le débiteur. Une mise en demeure écrite suffit, ce qui est inhabituel et explique l'importance du burofax.", n: "Ne vaut que pour la prescripcion. Cela ne prolonge ni les délais de contestation des décisions de copropriété, ni le délai de quatre ans en annulation, ni celui de six mois pour vices cachés, qui relèvent de la caducidad." },
    'limit_interruption_guarantor': { s: "Une action en justice contre le débiteur principal arrête aussi le délai contre une caution, mais une mise en demeure extrajudiciaire ou une reconnaissance privée ne le fait pas." },
    'limit_rent_arrears': { s: "Les loyers impayés se prescrivent par cinq ans, et chaque mois compte à partir du jour où ce mois est devenu exigible." },
    'limit_deposit_return': { s: "La restitution d'un dépôt de garantie n'a pas de délai propre dans la loi sur les baux, le délai général de cinq ans s'applique donc. Les intérêts légaux courent un mois après la remise des clés.", n: "La loi sur les baux fixe le point de départ des intérêts, pas celui du délai. La remise des clés est un point de départ pratique et non légal : traitez les cinq ans comme une limite extrême et agissez plus tôt." },
    'limit_community_challenge': { s: "Contester une décision de l'assemblée des copropriétaires : trois mois si le motif est qu'elle nuit gravement à la copropriété ou lèse injustement un copropriétaire, un an si le motif est qu'elle enfreint la loi ou les statuts." },
    'limit_community_challenge_absent': { s: "Un copropriétaire absent de l'assemblée compte le délai à partir du jour où la décision lui a été communiquée, pas du jour de l'assemblée. C'est la règle la plus utile pour un propriétaire qui vit à l'étranger." },
    'limit_community_challenge_standing': { s: "Pour contester une décision, vous devez être à jour des charges de copropriété, ou avoir préalablement consigné en justice le montant contesté. L'exception est une contestation portant sur les quotes-parts elles-mêmes." },
    'limit_community_buyer_liability': { s: "L'acquéreur reprend les charges de copropriété impayées du vendeur pour la partie écoulée de l'année d'achat plus les trois années civiles précédentes, et le bien lui-même en répond." },
    'limit_building_guarantee': { s: "Les garanties de construction courent à partir de la date de réception des travaux : dix ans pour les défauts structurels, trois ans pour les défauts rendant le logement inhabitable, un an pour les finitions et contre le constructeur seulement." },
    'limit_building_action': { s: "Une fois qu'un défaut couvert apparaît, vous avez deux ans pour agir, comptés à partir de la survenance du dommage, pas de la réception du bâtiment." },
    'limit_building_scope': { s: "Ces garanties s'appliquent aux bâtiments dont le permis de construire a été demandé le 6 mai 2000 ou après. Les bâtiments plus anciens relèvent du régime antérieur." },
    'limit_hidden_defects': { s: "L'action contre le vendeur pour vices cachés s'éteint six mois après la remise du bien, et non six mois après la découverte du défaut. C'est le délai le plus court et le plus dur de la liste." },
    'limit_contract_annulment': { s: "L'annulation d'un contrat pour erreur ou dol dispose d'une fenêtre de quatre ans, comptée à partir de la conclusion du contrat." },
    'limit_insurance_own_claim': { s: "Une action contre votre propre assureur au titre d'un contrat de dommages aux biens se prescrit par deux ans." },
    'limit_catalonia': { s: "La Catalogne dispose de son propre code civil, avec son propre régime de prescription et un délai général plus long : les chiffres du Codigo Civil figurant sur cette page ne sont donc pas ceux qui s'appliquent à un bien situé en Catalogne." },
    'cover_free_choice': { s: "Vous avez le droit de choisir votre propre avocat et votre procurador dans toute procédure, et l'avocat que vous choisissez reçoit ses instructions de vous, jamais de l'assureur. Ce droit ne dépend ni de l'accord de l'assureur ni de l'existence d'un conflit d'intérêts." },
    'cover_separate_chapter': { s: "Au sein d'un contrat habitation multirisque, la protection juridique doit figurer dans un chapitre distinct, indiquant ce qu'elle couvre et portant sa propre prime. Si vous ne trouvez pas de ligne de prime distincte, cela mérite une question." },
    'cover_policy_must_state': { s: "Le contrat doit énoncer expressément votre droit de choisir votre propre avocat. En cas de conflit d'intérêts, ou de désaccord avec l'assureur sur la conduite du dossier, l'assureur doit vous informer immédiatement de ce droit." },
    'cover_limiting_clause_form': { s: "Une clause qui limite vos droits, par exemple un plafond sur les honoraires d'un avocat que vous choisissez vous-même, doit être mise en évidence dans le contrat et acceptée spécifiquement par vous par écrit. Les conditions générales ne peuvent jamais être défavorables à l'assuré." },
    'cover_complaint_route': { s: "Si l'assureur refuse, vous devez d'abord saisir son propre service client. Ensuite seulement vous pouvez saisir le superviseur des assurances, dont l'avis est gratuit mais non contraignant et ne peut condamner personne à payer. Les tribunaux restent la seule voie contraignante." },
    'cover_arbitration_repealed': { s: "L'article qui permettait autrefois à l'une ou l'autre partie de soumettre un litige de protection juridique à l'arbitrage a été déclaré inconstitutionnel et est nul. Vous ne pouvez pas contraindre votre assureur à l'arbitrage, quoi qu'en disent un ancien contrat ou un article périmé.", n: "Conservé dans la base de règles précisément parce qu'il continue d'être présenté comme en vigueur. La page doit le montrer comme n'existant plus, jamais comme une option." },
    'cover_search_terms': { s: "Les expressions espagnoles à chercher dans votre propre contrat. Les trouver vous dit ce que vous avez ; ne pas les trouver vous dit ce qu'il faut demander." },
  },
};
const nl = {
  h1: 'Hoe u ervoor staat als er iets misgaat',
  lede: 'Twee dingen die een eigenaar in het buitenland bijna nooit op tijd te weten komt. Hoeveel tijd u heeft om te handelen, want verschillende van deze termijnen zijn korter dan mensen denken en een ervan begint op de dag dat u de sleutels kreeg. En of de advocaatkosten al gedekt zijn door een polis waarvoor u betaalt, want dat hoofdstuk staat in het Spaans en de meeste eigenaren hebben het nooit opengeslagen.',
  notAdvice: 'Dit is geen juridisch advies en het kan u niet zeggen of u zou winnen. Het zegt u wat de termijn is, waar u in uw eigen stukken op moet letten en wat u moet vragen.',
  q: 'Wat is er gebeurd?',
  empty: 'Kies wat er gebeurd is, dan vult de pagina zich.',
  step1: 'De termijn',
  step2: 'U bent mogelijk al gedekt',
  step3: 'Verzamel dit nu',
  step4: 'Bij wie u moet zijn',
  watchLabel: 'Let hierop:',
  findPrefix: 'Open uw woonpolis en zoek op',
  gatherNote: 'Voordat er iets wordt gerepareerd, opgeruimd of weggegooid.',
  whoNote: 'Een abogado voert de zaak. Een administrador de fincas doet de vereniging van eigenaren. Een gestoria procedeert niet. De gids zegt wie wat doet en laat zien wie in uw taal beoordeeld is.',
  cta: 'Vind een professional',
  goneLabel: 'Niet langer beschikbaar.',
  footer: 'Elke termijn op deze pagina komt uit een bronvermelde regel met het artikel en de datum waarop die is gecontroleerd. Niets hier is juridisch advies.',
  units: { years: 'jaar', year: 'jaar', months: 'maanden', month: 'maand', days: 'dagen', day: 'dag' },
  sit: {
    neighbour_damage: {
      label: 'Water of schade van een buur, of aan een buur',
      lead: 'Een lekkage, een scheur, vocht dat door een gedeelde muur komt.',
      watch: 'Een jaar is kort, en de termijn loopt vanaf het moment dat u het wist, niet vanaf de reparatie. Als de schade nog erger wordt, laat dat nu vastleggen.',
      evidence: [
        'Fotos met datum, voordat er iets gerepareerd wordt',
        'Een rapport van loodgieter of aannemer over waar het water vandaan kwam',
        'De notulen van de vereniging als een gedeelde leiding of het dak erbij betrokken is',
        'Uw eigen polisnummer en de verzekeraar van de tegenpartij als u die kent',
      ],
    },
    community_decision: {
      label: 'Een besluit van de eigenarenvergadering',
      lead: 'Een heffing, een stemming over werkzaamheden, een regel waar u niet bij was.',
      watch: 'Was u niet op de vergadering, dan loopt uw termijn vanaf de dag waarop de notulen u bereikten, niet vanaf de vergaderdag. Bewaar de envelop of de e-mail.',
      evidence: [
        'De notulen, en bewijs van de datum waarop die u bereikten',
        'De oproeping voor de vergadering',
        'Bewijs dat u bij bent met de bijdragen aan de vereniging',
        'De statuten als het bezwaar is dat het besluit daarmee in strijd is',
      ],
    },
    community_debt: {
      label: 'De vereniging zegt dat u geld schuldig bent',
      lead: 'Achterstand, een bijzondere heffing, kosten van voor uw aankoop.',
      watch: 'Ligt de schuld voor uw aankoop, dan heeft u het verstreken deel van het aankoopjaar plus de drie kalenderjaren daarvoor overgenomen. Dat is niet hetzelfde als de termijn waarbinnen zij mogen dagvaarden.',
      evidence: [
        'Het rekeningoverzicht van de beheerder',
        'Uw akte van levering en de schuldverklaring die bij het passeren is afgegeven',
        'Bankafschriften van wat u betaald heeft',
      ],
    },
    tenant_arrears: {
      label: 'Een huurder die niet betaalt',
      lead: 'Huurachterstand, of u wilt de woning terug.',
      watch: 'Een schriftelijke aanmaning start de termijn tegen de huurder opnieuw, maar niet tegen een borg. Alleen een gerechtelijke vordering doet dat.',
      evidence: [
        'De huurovereenkomst en een eventuele borgstelling',
        'Een overzicht van wat verschuldigd was en wat binnenkwam, maand voor maand',
        'Elke schriftelijke aanmaning die u heeft gestuurd, met bewijs van bezorging',
      ],
    },
    deposit: {
      label: 'Een borg die niet is teruggekomen',
      lead: 'De uwe bij een verhuurder, of een huurder die om de zijne vraagt.',
      watch: 'Rente loopt vanaf een maand na teruggave van de sleutels. Borgsommen worden meestal gestort bij de regionale huisvestingsinstantie, die eigen regels heeft.',
      evidence: [
        'De huurovereenkomst waarin de borg staat',
        'Bewijs van de datum waarop de sleutels zijn overhandigd',
        'De inventaris of opnamestaat van begin en einde',
      ],
    },
    builder: {
      label: 'Bouwwerk dat is misgegaan',
      lead: 'Een gebrek in nieuwbouw, of een verbouwing die mislukte.',
      watch: 'Twee termijnen, niet een. Het gebrek moet binnen de garantie opkomen, en daarna heeft u twee jaar vanaf het moment dat de schade zich voordeed om de vordering in te stellen.',
      evidence: [
        'Het opleveringscertificaat van het werk en de datum daarvan',
        'De datum van de bouwvergunning, die bepaalt welk regime geldt',
        'Een technisch rapport dat zegt wat het gebrek is en wanneer het opkwam',
        'Het contract en elke factuur',
      ],
    },
    hidden_defect: {
      label: 'Een gebrek dat de verkoper niet noemde',
      lead: 'Iets dat u na de koop ontdekte.',
      watch: 'De route van verborgen gebreken vervalt zes maanden na oplevering van de woning, of u het probleem nu gevonden had of niet. Zit u daar dichtbij, dan is dit dringend.',
      evidence: [
        'De akte en de datum waarop u het bezit kreeg',
        'De advertentie, de bouwkundige keuring en alles wat de verkoper op papier zette',
        'Een rapport dat het gebrek dateert en zegt dat het er voor de verkoop al was',
      ],
    },
    insurer_refused: {
      label: 'Uw verzekeraar heeft nee gezegd',
      lead: 'Een afgewezen claim, of kosten die zij niet willen betalen.',
      watch: 'Klaag eerst bij de eigen klantenserviceafdeling van de verzekeraar. Naar de toezichthouder kunt u pas daarna, en niemand kan tot arbitrage worden gedwongen.',
      evidence: [
        'De afwijzing op schrift, met de redenen',
        'De volledige polis inclusief de algemene voorwaarden, niet alleen het polisblad',
        'De bladzijde waar u tekende voor aanvaarding van de beperkende clausules',
      ],
    },
  },
  chapter: {
    defensa: { heading: 'Rechtsbijstand', says: 'Betaalt uw advocaat, de procurador en de proceskosten als u in een zaak zit. Dit is het hoofdstuk waar de vrije advocaatkeuze bij hoort.' },
    reclamacion: { heading: 'Vordering tegen een ander', says: 'De eisende kant. Verhaal halen bij wie uw eigendom beschadigde. Vaak als aparte regel vermeld, los van rechtsbijstand.' },
    rental: { heading: 'Verhuurdekking', says: 'Zaken tussen verhuurder en huurder lopen doorgaans via een apart verhuurproduct en niet via een gewone woonpolis. Ga na welke u heeft.' },
  },
  rule: {
    'limit_contract_general': { s: 'Een persoonlijke vordering zonder eigen termijn verjaart na vijf jaar, gerekend vanaf het moment waarop nakoming van de verplichting kon worden gevorderd. Voor 7 oktober 2015 was het vijftien jaar.' },
    'limit_extracontractual': { s: 'Een vordering wegens schade veroorzaakt door iemand met wie u geen contract heeft, verjaart na een jaar, gerekend vanaf het moment waarop de benadeelde van de schade wist.' },
    'limit_interruption': { s: 'Drie dingen stoppen de termijn en starten die opnieuw: naar de rechter gaan, een buitengerechtelijke aanmaning door de schuldeiser, en elke erkenning van de schuld door de schuldenaar. Een schriftelijke aanmaning is genoeg, wat ongebruikelijk is en de reden dat een burofax ertoe doet.', n: 'Geldt alleen voor prescripcion. Het verlengt niet de termijnen om besluiten van de vereniging aan te vechten, niet de vierjaarstermijn voor vernietiging en niet de zesmaandstermijn voor verborgen gebreken, want dat is caducidad.' },
    'limit_interruption_guarantor': { s: 'Een gerechtelijke vordering tegen de hoofdschuldenaar stopt de termijn ook tegen een borg, maar een buitengerechtelijke aanmaning of een onderhandse erkenning doet dat niet.' },
    'limit_rent_arrears': { s: 'Onbetaalde huur verjaart na vijf jaar, en elke maand telt vanaf de dag waarop die maand verschuldigd werd.' },
    'limit_deposit_return': { s: 'Het terugkrijgen van een huurborg heeft in de huurwet geen eigen termijn, dus geldt de algemene termijn van vijf jaar. Wettelijke rente loopt vanaf een maand na teruggave van de sleutels.', n: 'De huurwet bepaalt wanneer de rente begint, niet wanneer de termijn begint. Teruggave van de sleutels is een praktisch en geen wettelijk startpunt, behandel de vijf jaar dus als uiterste grens en handel eerder.' },
    'limit_community_challenge': { s: 'Een besluit van de eigenarenvergadering aanvechten: drie maanden als de grond is dat het de vereniging ernstig schaadt of een eigenaar onredelijk benadeelt, een jaar als de grond is dat het in strijd is met de wet of de statuten.' },
    'limit_community_challenge_absent': { s: 'Een eigenaar die niet op de vergadering was, rekent de termijn vanaf de dag waarop het besluit aan hem is meegedeeld, niet vanaf de vergaderdag. Dit is de nuttigste enkele regel voor een eigenaar die in het buitenland woont.' },
    'limit_community_challenge_standing': { s: 'Om een besluit aan te vechten moet u bij zijn met de bijdragen aan de vereniging, of het betwiste bedrag eerst bij de rechtbank hebben gestort. De uitzondering is een betwisting van de aandelen zelf.' },
    'limit_community_buyer_liability': { s: 'Een koper neemt de onbetaalde verenigingsbijdragen van de verkoper over voor het verstreken deel van het aankoopjaar plus de drie voorgaande kalenderjaren, en het pand zelf staat daarvoor in.' },
    'limit_building_guarantee': { s: 'Bouwgaranties lopen vanaf de datum waarop het werk is opgeleverd: tien jaar voor constructieve gebreken, drie jaar voor gebreken die de woning onbewoonbaar maken, een jaar voor afwerking en alleen tegen de aannemer.' },
    'limit_building_action': { s: 'Zodra een gedekt gebrek opkomt heeft u twee jaar om de vordering in te stellen, gerekend vanaf het moment dat de schade zich voordeed, niet vanaf de oplevering van het gebouw.' },
    'limit_building_scope': { s: 'Deze garanties gelden voor gebouwen waarvoor de bouwvergunning op of na 6 mei 2000 is aangevraagd. Oudere gebouwen vallen onder het vorige regime.' },
    'limit_hidden_defects': { s: 'Een vordering tegen de verkoper wegens verborgen gebreken vervalt zes maanden na oplevering van de woning, niet zes maanden nadat u het gebrek vond. Dit is de kortste en hardste termijn op de lijst.' },
    'limit_contract_annulment': { s: 'Een contract laten vernietigen wegens dwaling of bedrog kent een venster van vier jaar, gerekend vanaf het sluiten van het contract.' },
    'limit_insurance_own_claim': { s: 'Een vordering op uw eigen verzekeraar onder een opstal- of inboedelpolis verjaart na twee jaar.' },
    'limit_catalonia': { s: 'Catalonië heeft een eigen burgerlijk wetboek met een eigen verjaringsregime en een langere algemene termijn, dus de cijfers uit de Codigo Civil op deze pagina gelden niet voor een pand in Catalonië.' },
    'cover_free_choice': { s: 'U heeft het recht om in elke procedure uw eigen advocaat en procurador te kiezen, en de advocaat die u kiest neemt instructies van u aan, nooit van de verzekeraar. Het recht hangt niet af van instemming van de verzekeraar en niet van het bestaan van een belangenconflict.' },
    'cover_separate_chapter': { s: 'Binnen een gecombineerde woonpolis moet de rechtsbijstanddekking als apart hoofdstuk staan, met wat zij dekt en met een eigen premie. Vindt u geen aparte premieregel, dan is dat een vraag waard.' },
    'cover_policy_must_state': { s: 'De polis moet uw recht op vrije advocaatkeuze met zoveel woorden vastleggen. Is er een belangenconflict, of verschillen u en de verzekeraar van mening over de aanpak van de zaak, dan moet de verzekeraar u onmiddellijk op dat recht wijzen.' },
    'cover_limiting_clause_form': { s: 'Een clausule die uw rechten beperkt, zoals een maximum op het honorarium van een zelfgekozen advocaat, moet in de polis worden benadrukt en door u afzonderlijk schriftelijk zijn aanvaard. Algemene voorwaarden mogen nooit nadelig zijn voor de verzekerde.' },
    'cover_complaint_route': { s: 'Weigert de verzekeraar, dan moet u eerst klagen bij de eigen klantenserviceafdeling. Pas daarna kunt u naar de verzekeringstoezichthouder, wiens oordeel gratis is maar niet bindend en niemand tot betaling kan verplichten. De rechter blijft de enige bindende weg.' },
    'cover_arbitration_repealed': { s: 'Het artikel dat elk van beide partijen vroeger toestond een rechtsbijstandgeschil naar arbitrage te sturen, is ongrondwettig verklaard en is nietig. U kunt uw verzekeraar niet tot arbitrage dwingen, wat een oudere polis of een verouderd artikel ook zegt.', n: 'Juist daarom in de regelbasis gehouden, omdat het nog steeds als geldend wordt herhaald. De pagina moet het tonen als niet langer beschikbaar, nooit als optie.' },
    'cover_search_terms': { s: 'De Spaanse termen om in uw eigen polisdocument op te zoeken. Ze vinden zegt u wat u heeft; ze niet vinden zegt u waar u naar moet vragen.' },
  },
};

export default { en, no, sv, de, fr, nl };
