// The answers layer: the part of this site an answer engine can actually quote.
//
// WHY THIS EXISTS
// The site is eleven thousand pages of calculators. A calculator is useless to ChatGPT,
// Perplexity, Google's AI Overviews or anything else that answers a question by quoting a
// source: there is no sentence on the page to lift. So the site had no way of being cited,
// which is the only way those systems send traffic.
//
// What it does have, and almost nobody else does, is rules/: 122 verified rules, each with
// the article it comes from, the official URL, and the date a human last read it. That is
// exactly the shape of thing an answer engine prefers to cite. It was sitting in JSON,
// rendered nowhere.
//
// This turns it into questions. One page per question, the answer in the first sentence,
// the article underneath it, the date it was checked, and a link to the tool that does the
// arithmetic. Short on purpose: the job is to be quotable, not to be long.
//
// EVERY ANSWER IS TIED TO VERIFIED RULES
// `rules` names the ids. A build gate refuses any answer whose rules are missing or are not
// status "verified", so the answers layer cannot drift from the sourced base underneath it.

export const ANSWER_LANGS = ['en', 'no', 'sv', 'de', 'fr', 'nl'];

export const ANSWERS = [
{
  slug: 'tax-on-a-spanish-property-you-do-not-rent-out',
  tool: 'tax-calculator',
  rules: ['irnr.imputed.base', 'irnr.imputed.no_deductions', 'irnr.rates'],
  q: {
    en: 'Do I pay Spanish tax on a property I never rent out?',
    no: 'Betaler jeg spansk skatt på en bolig jeg aldri leier ut?',
    sv: 'Betalar jag spansk skatt på en bostad jag aldrig hyr ut?',
    de: 'Zahle ich spanische Steuer auf eine Immobilie, die ich nie vermiete?',
    fr: 'Dois-je payer un impôt espagnol sur un bien que je ne loue jamais ?',
    nl: 'Betaal ik Spaanse belasting over een woning die ik nooit verhuur?',
  },
  a: {
    en: 'Yes. A non-resident who owns a second home in Spain pays tax on an imputed income, even with no rent at all. The base is the cadastral value on the IBI bill, not the purchase price or the market value, and nothing is deductible against it. The rate is 19 percent for residents of the EU, Norway, Iceland and Liechtenstein, and 24 percent for everyone else.',
    no: 'Ja. En ikke-bosatt som eier en sekundærbolig i Spania betaler skatt av en imputert inntekt, selv uten leieinntekt. Grunnlaget er matrikkelverdien på IBI-regningen, ikke kjøpesummen eller markedsverdien, og ingenting kan trekkes fra. Satsen er 19 prosent for bosatte i EU, Norge, Island og Liechtenstein, og 24 prosent for alle andre.',
    sv: 'Ja. En icke-bosatt som äger en andrabostad i Spanien betalar skatt på en schablonintäkt, även utan hyresinkomst. Underlaget är taxeringsvärdet på IBI-avin, inte köpeskillingen eller marknadsvärdet, och ingenting får dras av. Skattesatsen är 19 procent för boende i EU, Norge, Island och Liechtenstein, och 24 procent för alla andra.',
    de: 'Ja. Ein Nichtansässiger mit einer Zweitwohnung in Spanien zahlt Steuer auf fiktive Einkünfte, auch ganz ohne Miete. Bemessungsgrundlage ist der Katasterwert auf dem IBI-Bescheid, nicht der Kaufpreis und nicht der Marktwert, und es ist nichts abziehbar. Der Satz beträgt 19 Prozent für Ansässige in der EU, Norwegen, Island und Liechtenstein und 24 Prozent für alle übrigen.',
    fr: "Oui. Un non-résident propriétaire d'une résidence secondaire en Espagne paie un impôt sur un revenu imputé, même sans aucun loyer. La base est la valeur cadastrale figurant sur l'avis d'IBI, ni le prix d'achat ni la valeur de marché, et rien n'est déductible. Le taux est de 19 pour cent pour les résidents de l'UE, de Norvège, d'Islande et du Liechtenstein, et de 24 pour cent pour les autres.",
    nl: 'Ja. Een niet-inwoner met een tweede woning in Spanje betaalt belasting over een fictief inkomen, ook zonder enige huur. De grondslag is de kadastrale waarde op de IBI-aanslag, niet de koopprijs en niet de marktwaarde, en er is niets aftrekbaar. Het tarief is 19 procent voor inwoners van de EU, Noorwegen, IJsland en Liechtenstein, en 24 procent voor alle anderen.',
  },
},
{
  slug: 'deduct-costs-from-spanish-rental-income',
  tool: 'rental-tax',
  rules: ['irnr.rental.deductibility', 'irnr.rates'],
  q: {
    en: 'Can I deduct expenses from Spanish rental income as a non-resident?',
    no: 'Kan jeg trekke fra utgifter mot spansk leieinntekt som ikke-bosatt?',
    sv: 'Kan jag dra av kostnader mot spansk hyresinkomst som icke-bosatt?',
    de: 'Kann ich als Nichtansässiger Kosten von spanischen Mieteinkünften absetzen?',
    fr: 'Puis-je déduire mes charges des revenus locatifs espagnols en tant que non-résident ?',
    nl: 'Mag ik als niet-inwoner kosten aftrekken van Spaanse huurinkomsten?',
  },
  a: {
    en: 'Only if you live in an EU country, or in Norway, Iceland or Liechtenstein. Those owners deduct management fees, insurance, repairs, the community charge, mortgage interest and depreciation, and are taxed on what is left at 19 percent. Everyone else is taxed on the gross rent with no deductions at all, at 24 percent.',
    no: 'Bare hvis du bor i et EU-land, eller i Norge, Island eller Liechtenstein. De eierne trekker fra forvaltningshonorar, forsikring, reparasjoner, fellesutgifter, renter på lån og avskrivning, og skattlegges av det som står igjen med 19 prosent. Alle andre skattlegges av brutto leie uten fradrag i det hele tatt, med 24 prosent.',
    sv: 'Bara om du bor i ett EU-land, eller i Norge, Island eller Liechtenstein. De ägarna drar av förvaltningsarvode, försäkring, reparationer, samfällighetsavgift, ränta på lån och avskrivning, och beskattas på det som blir kvar med 19 procent. Alla andra beskattas på bruttohyran utan några avdrag alls, med 24 procent.',
    de: 'Nur wenn Sie in einem EU-Land leben, oder in Norwegen, Island oder Liechtenstein. Diese Eigentümer setzen Verwaltungshonorar, Versicherung, Reparaturen, Hausgeld, Kreditzinsen und Abschreibung ab und werden mit 19 Prozent auf den Rest besteuert. Alle anderen werden ohne jeden Abzug auf die Bruttomiete besteuert, mit 24 Prozent.',
    fr: "Seulement si vous vivez dans un pays de l'UE, ou en Norvège, en Islande ou au Liechtenstein. Ces propriétaires déduisent honoraires de gestion, assurance, réparations, charges de copropriété, intérêts d'emprunt et amortissement, et sont imposés sur le solde à 19 pour cent. Tous les autres sont imposés sur le loyer brut sans aucune déduction, à 24 pour cent.",
    nl: 'Alleen als u in een EU-land woont, of in Noorwegen, IJsland of Liechtenstein. Die eigenaren trekken beheerkosten, verzekering, reparaties, VvE-bijdrage, hypotheekrente en afschrijving af, en worden over het restant belast tegen 19 procent. Alle anderen worden zonder enige aftrek over de brutohuur belast, tegen 24 procent.',
  },
},
{
  slug: 'three-percent-withheld-when-selling-spanish-property',
  tool: 'sale-tax',
  rules: ['irnr.sale.retention', 'deadline.210.sale', 'irnr.rates'],
  q: {
    en: 'Why does the buyer keep 3 percent when a non-resident sells in Spain?',
    no: 'Hvorfor holder kjøperen tilbake 3 prosent når en ikke-bosatt selger i Spania?',
    sv: 'Varför håller köparen inne 3 procent när en icke-bosatt säljer i Spanien?',
    de: 'Warum behält der Käufer 3 Prozent ein, wenn ein Nichtansässiger in Spanien verkauft?',
    fr: 'Pourquoi l’acheteur retient-il 3 pour cent quand un non-résident vend en Espagne ?',
    nl: 'Waarom houdt de koper 3 procent in als een niet-inwoner in Spanje verkoopt?',
  },
  a: {
    en: 'It is not a tax. The buyer must withhold 3 percent of the agreed price and pay it to the tax office on modelo 211 within one month, as a payment on account of the seller’s capital gains tax. The actual tax is 19 percent of the gain, for everyone. If the 3 percent exceeds what is owed, the difference is refunded on a return filed from one month after completion and within the following three.',
    no: 'Det er ikke en skatt. Kjøperen må holde tilbake 3 prosent av avtalt pris og betale det til skattekontoret på modelo 211 innen en måned, som akontobetaling på selgerens gevinstskatt. Selve skatten er 19 prosent av gevinsten, for alle. Overstiger de 3 prosentene det som skyldes, refunderes differansen på en oppgave levert fra en måned etter overdragelsen og innen de tre påfølgende.',
    sv: 'Det är inte en skatt. Köparen måste hålla inne 3 procent av det avtalade priset och betala in det till skattemyndigheten på modelo 211 inom en månad, som preliminär betalning på säljarens kapitalvinstskatt. Själva skatten är 19 procent av vinsten, för alla. Överstiger de 3 procenten det som ska betalas återbetalas mellanskillnaden på en deklaration som lämnas från en månad efter tillträdet och inom de följande tre.',
    de: 'Es ist keine Steuer. Der Käufer muss 3 Prozent des vereinbarten Preises einbehalten und binnen eines Monats mit modelo 211 an das Finanzamt abführen, als Vorauszahlung auf die Gewinnsteuer des Verkäufers. Die eigentliche Steuer beträgt 19 Prozent des Gewinns, für alle. Übersteigen die 3 Prozent das Geschuldete, wird die Differenz auf eine Erklärung erstattet, die ab einem Monat nach dem Notartermin und innerhalb der folgenden drei Monate abzugeben ist.',
    fr: "Ce n'est pas un impôt. L'acheteur doit retenir 3 pour cent du prix convenu et les verser au fisc sur le modelo 211 dans le mois, à titre d'acompte sur l'impôt de plus-value du vendeur. L'impôt réel est de 19 pour cent du gain, pour tous. Si les 3 pour cent dépassent le dû, la différence est remboursée via une déclaration déposée à partir d'un mois après la signature et dans les trois mois suivants.",
    nl: 'Het is geen belasting. De koper moet 3 procent van de overeengekomen prijs inhouden en binnen een maand met modelo 211 aan de belastingdienst afdragen, als voorschot op de vermogenswinstbelasting van de verkoper. De werkelijke belasting is 19 procent over de winst, voor iedereen. Overtreffen de 3 procent het verschuldigde, dan wordt het verschil terugbetaald via een aangifte die vanaf een maand na de overdracht en binnen de drie maanden daarna wordt ingediend.',
  },
},
{
  slug: 'filing-a-spanish-tax-return-late',
  tool: 'late-surcharge',
  rules: ['late.recargo.voluntary', 'late.recargo.excludes_penalty', 'late.recargo.reduction'],
  q: {
    en: 'What happens if I file modelo 210 late?',
    no: 'Hva skjer hvis jeg leverer modelo 210 for sent?',
    sv: 'Vad händer om jag lämnar modelo 210 för sent?',
    de: 'Was passiert, wenn ich die modelo 210 verspätet abgebe?',
    fr: 'Que se passe-t-il si je dépose la modelo 210 en retard ?',
    nl: 'Wat gebeurt er als ik modelo 210 te laat indien?',
  },
  a: {
    en: 'It depends entirely on whether the tax office has written to you first. File late on your own initiative and it is a surcharge: 1 percent, plus 1 percent for each complete month of delay, up to 12 months, then a flat 15 percent plus interest from month 13. That surcharge replaces the penalty that could otherwise have been imposed, and is reduced by 25 percent if you pay within the voluntary period. Once a demand has been issued, none of that applies.',
    no: 'Det avhenger helt av om skattekontoret har skrevet til deg først. Leverer du for sent på eget initiativ, er det et tillegg: 1 prosent, pluss 1 prosent for hver hele måned forsinkelse, opp til 12 måneder, deretter flate 15 prosent pluss renter fra måned 13. Tillegget erstatter boten som ellers kunne blitt ilagt, og reduseres med 25 prosent hvis du betaler innen den frivillige fristen. Har kravet først kommet, gjelder ingenting av dette.',
    sv: 'Det beror helt på om skattemyndigheten har skrivit till dig först. Deklarerar du sent på eget initiativ är det ett tillägg: 1 procent, plus 1 procent för varje hel månads dröjsmål, upp till 12 månader, därefter platta 15 procent plus ränta från månad 13. Tillägget ersätter den sanktionsavgift som annars kunnat påföras, och sätts ned med 25 procent om du betalar inom den frivilliga fristen. Har kravet väl kommit gäller inget av detta.',
    de: 'Das hängt ganz davon ab, ob das Finanzamt Ihnen zuerst geschrieben hat. Geben Sie aus eigenem Antrieb verspätet ab, ist es ein Zuschlag: 1 Prozent, plus 1 Prozent je vollem Monat Verzug, bis zu 12 Monaten, danach pauschal 15 Prozent plus Zinsen ab Monat 13. Der Zuschlag tritt an die Stelle der sonst möglichen Sanktion und wird um 25 Prozent gemindert, wenn Sie innerhalb der freiwilligen Frist zahlen. Ist die Aufforderung ergangen, gilt nichts davon.',
    fr: "Tout dépend de savoir si le fisc vous a écrit en premier. Déposez de votre propre initiative et c'est une majoration : 1 pour cent, plus 1 pour cent par mois complet de retard, jusqu'à 12 mois, puis 15 pour cent forfaitaires plus intérêts à partir du 13e mois. Cette majoration remplace la sanction qui aurait pu être infligée, et est réduite de 25 pour cent si vous payez dans le délai volontaire. Une fois la mise en demeure émise, rien de cela ne s'applique.",
    nl: 'Het hangt er volledig van af of de belastingdienst u eerst heeft aangeschreven. Dient u uit eigen beweging te laat in, dan is het een toeslag: 1 procent, plus 1 procent voor elke volle maand vertraging, tot 12 maanden, daarna een vlakke 15 procent plus rente vanaf maand 13. Die toeslag komt in plaats van de boete die anders opgelegd had kunnen worden, en wordt met 25 procent verminderd als u binnen de vrijwillige termijn betaalt. Zodra er een aanmaning is uitgegaan, geldt hier niets van.',
  },
},
{
  slug: 'iva-on-a-spanish-holiday-let',
  tool: 'rental-vat',
  rules: ['vat.letting'],
  q: {
    en: 'Do I charge IVA on a Spanish holiday let?',
    no: 'Skal jeg beregne IVA på korttidsutleie i Spania?',
    sv: 'Ska jag ta ut IVA på korttidsuthyrning i Spanien?',
    de: 'Muss ich auf eine spanische Ferienvermietung IVA berechnen?',
    fr: 'Dois-je facturer l’IVA sur une location saisonnière en Espagne ?',
    nl: 'Moet ik IVA rekenen over Spaanse vakantieverhuur?',
  },
  a: {
    en: 'It depends on what you provide during the stay, not on how long the guest stays. A residential let with no services is exempt from IVA. Add hotel type services during the stay, such as daily cleaning, reception or breakfast, and the let is taxed at 10 percent. 21 percent applies where the operation is neither an exempt residential let nor a hotel type accommodation service. Cleaning between guests is not a hotel type service.',
    no: 'Det avhenger av hva du leverer under oppholdet, ikke av hvor lenge gjesten blir. Boligutleie uten tjenester er fritatt for IVA. Legger du til hotelliknende tjenester under oppholdet, som daglig renhold, resepsjon eller frokost, beskattes utleien med 10 prosent. 21 prosent gjelder når virksomheten verken er en fritatt boligutleie eller en hotelliknende overnattingstjeneste. Vask mellom gjester er ikke en hotelliknende tjeneste.',
    sv: 'Det beror på vad du tillhandahåller under vistelsen, inte på hur länge gästen stannar. Bostadsuthyrning utan tjänster är undantagen från IVA. Lägger du till hotelliknande tjänster under vistelsen, som daglig städning, reception eller frukost, beskattas uthyrningen med 10 procent. 21 procent gäller när verksamheten varken är en undantagen bostadsuthyrning eller en hotelliknande logitjänst. Städning mellan gäster är inte en hotelliknande tjänst.',
    de: 'Es hängt davon ab, was Sie während des Aufenthalts erbringen, nicht davon, wie lange der Gast bleibt. Wohnraumvermietung ohne Leistungen ist von der IVA befreit. Kommen hotelartige Leistungen während des Aufenthalts hinzu, etwa tägliche Reinigung, Rezeption oder Frühstück, wird mit 10 Prozent besteuert. 21 Prozent gelten, wenn der Vorgang weder eine befreite Wohnraumvermietung noch eine hotelartige Beherbergungsleistung ist. Reinigung zwischen den Gästen ist keine hotelartige Leistung.',
    fr: "Cela dépend de ce que vous fournissez pendant le séjour, pas de sa durée. Une location résidentielle sans services est exonérée d'IVA. Ajoutez des services de type hôtelier pendant le séjour, comme le ménage quotidien, une réception ou le petit déjeuner, et la location est taxée à 10 pour cent. 21 pour cent s'appliquent lorsque l'opération n'est ni une location résidentielle exonérée ni un service d'hébergement de type hôtelier. Le ménage entre deux séjours n'est pas un service de type hôtelier.",
    nl: 'Het hangt af van wat u tijdens het verblijf levert, niet van hoe lang de gast blijft. Woonruimteverhuur zonder diensten is vrijgesteld van IVA. Voegt u hoteldiensten toe tijdens het verblijf, zoals dagelijks schoonmaken, receptie of ontbijt, dan wordt de verhuur belast tegen 10 procent. 21 procent geldt wanneer de activiteit noch een vrijgestelde woonverhuur, noch een hotelmatige logiesdienst is. Schoonmaken tussen gasten is geen hoteldienst.',
  },
},
{
  slug: 'how-long-can-i-stay-in-spain-without-residency',
  tool: 'day-counter',
  rules: ['schengen.short_stay', 'schengen.entry_exit_days'],
  q: {
    en: 'How many days can I spend in Spain without becoming resident?',
    no: 'Hvor mange dager kan jeg være i Spania uten å bli bosatt?',
    sv: 'Hur många dagar kan jag vara i Spanien utan att bli bosatt?',
    de: 'Wie viele Tage darf ich in Spanien verbringen, ohne ansässig zu werden?',
    fr: 'Combien de jours puis-je passer en Espagne sans devenir résident ?',
    nl: 'Hoeveel dagen mag ik in Spanje zijn zonder inwoner te worden?',
  },
  a: {
    en: 'A third country national may stay in the Schengen area for no more than 90 days in any 180 day period. It is a rolling window, not a calendar year, so days from the previous autumn still count against a trip in spring. Both the date of entry and the date of exit count as full days of stay, which makes a long weekend four days rather than two.',
    no: 'En tredjelandsborger kan oppholde seg i Schengen-området i høyst 90 dager innenfor enhver periode på 180 dager. Det er et rullerende vindu, ikke et kalenderår, så dager fra forrige høst teller fortsatt mot en tur om våren. Både innreisedagen og utreisedagen teller som hele oppholdsdager, noe som gjør en lang helg til fire dager i stedet for to.',
    sv: 'En tredjelandsmedborgare får vistas i Schengenområdet i högst 90 dagar inom varje 180-dagarsperiod. Det är ett rullande fönster, inte ett kalenderår, så dagar från förra hösten räknas fortfarande mot en resa på våren. Både inresedagen och utresedagen räknas som hela vistelsedagar, vilket gör en långhelg till fyra dagar i stället för två.',
    de: 'Ein Drittstaatsangehöriger darf sich höchstens 90 Tage in jedem Zeitraum von 180 Tagen im Schengen-Raum aufhalten. Es ist ein rollierendes Fenster, kein Kalenderjahr, Tage aus dem vergangenen Herbst zählen also weiterhin gegen eine Reise im Frühjahr. Sowohl der Einreise- als auch der Ausreisetag zählen als volle Aufenthaltstage, womit ein langes Wochenende vier statt zwei Tage ergibt.',
    fr: "Un ressortissant de pays tiers peut séjourner dans l'espace Schengen au maximum 90 jours sur toute période de 180 jours. C'est une fenêtre glissante, pas une année civile : les jours de l'automne précédent comptent encore contre un voyage au printemps. La date d'entrée et la date de sortie comptent toutes deux comme journées entières, ce qui fait d'un long week-end quatre jours et non deux.",
    nl: 'Een onderdaan van een derde land mag maximaal 90 dagen binnen elke periode van 180 dagen in het Schengengebied verblijven. Het is een voortschrijdend venster, geen kalenderjaar, dus dagen van afgelopen najaar tellen nog mee bij een reis in het voorjaar. Zowel de dag van binnenkomst als de dag van vertrek telt als volledige verblijfsdag, waardoor een lang weekend vier dagen is in plaats van twee.',
  },
},
{
  slug: 'who-pays-for-storm-damage-in-spain',
  tool: 'storm-claim',
  rules: ['consorcio.perils', 'consorcio.wind_threshold', 'consorcio.precondition'],
  q: {
    en: 'Who pays for storm or flood damage to a Spanish property?',
    no: 'Hvem betaler for storm- eller flomskade på en spansk eiendom?',
    sv: 'Vem betalar för storm- eller översvämningsskada på en spansk fastighet?',
    de: 'Wer zahlt bei Sturm- oder Hochwasserschaden an einer spanischen Immobilie?',
    fr: 'Qui paie les dégâts de tempête ou d’inondation sur un bien espagnol ?',
    nl: 'Wie betaalt storm- of overstromingsschade aan een Spaanse woning?',
  },
  a: {
    en: 'Not always your insurer. A public body, the Consorcio de Compensacion de Seguros, covers extraordinary risks: earthquake, extraordinary flood, volcanic eruption, atypical cyclonic storm and others. Extraordinary wind means gusts above 120 km/h measured over three seconds; below that, storm damage is your own insurer’s ordinary storm cover. The Consorcio is not bought separately: if you hold a qualifying policy, the surcharge is already collected with your premium.',
    no: 'Ikke alltid forsikringsselskapet ditt. Et offentlig organ, Consorcio de Compensacion de Seguros, dekker ekstraordinære risikoer: jordskjelv, ekstraordinær flom, vulkanutbrudd, atypisk syklonstorm og flere. Ekstraordinær vind betyr kast over 120 km/t målt over tre sekunder; under det er stormskade ditt eget selskaps ordinære stormdekning. Consorcio kjøpes ikke separat: har du en kvalifiserende polise, kreves tillegget allerede inn med premien.',
    sv: 'Inte alltid ditt försäkringsbolag. Ett offentligt organ, Consorcio de Compensacion de Seguros, täcker extraordinära risker: jordbävning, extraordinär översvämning, vulkanutbrott, atypisk cyklonstorm med flera. Extraordinär vind betyder byar över 120 km/h mätt över tre sekunder; under det är stormskada ditt eget bolags vanliga stormskydd. Consorcio köps inte separat: har du en kvalificerande försäkring tas tillägget redan ut med premien.',
    de: 'Nicht immer Ihr Versicherer. Eine öffentliche Stelle, der Consorcio de Compensacion de Seguros, deckt außergewöhnliche Risiken: Erdbeben, außergewöhnliche Überschwemmung, Vulkanausbruch, atypischen Zyklonsturm und weitere. Außergewöhnlicher Wind bedeutet Böen über 120 km/h, gemessen über drei Sekunden; darunter greift die gewöhnliche Sturmdeckung Ihres eigenen Versicherers. Der Consorcio wird nicht separat gekauft: bei einer qualifizierenden Police wird der Zuschlag bereits mit der Prämie eingezogen.',
    fr: "Pas toujours votre assureur. Un organisme public, le Consorcio de Compensacion de Seguros, couvre les risques extraordinaires : séisme, inondation extraordinaire, éruption volcanique, tempête cyclonique atypique et d'autres. Le vent extraordinaire signifie des rafales supérieures à 120 km/h mesurées sur trois secondes ; en dessous, le dégât de tempête relève de la garantie tempête ordinaire de votre assureur. Le Consorcio ne s'achète pas à part : si vous détenez un contrat éligible, la surprime est déjà prélevée avec votre cotisation.",
    nl: 'Niet altijd uw verzekeraar. Een publiek orgaan, het Consorcio de Compensacion de Seguros, dekt buitengewone risico’s: aardbeving, buitengewone overstroming, vulkaanuitbarsting, atypische cycloonstorm en meer. Buitengewone wind betekent windstoten boven 120 km/u gemeten over drie seconden; daaronder valt stormschade onder de gewone stormdekking van uw eigen verzekeraar. Het Consorcio koopt u niet apart: heeft u een kwalificerende polis, dan wordt de opslag al met uw premie geïnd.',
  },
},
{
  slug: 'free-choice-of-lawyer-spanish-home-insurance',
  tool: 'your-rights',
  rules: ['cover.free_choice', 'cover.separate_chapter', 'cover.policy_must_state'],
  q: {
    en: 'Can I choose my own lawyer under Spanish legal expenses cover?',
    no: 'Kan jeg velge min egen advokat under spansk dekning for juridisk bistand?',
    sv: 'Kan jag välja min egen advokat under spanskt rättsskydd?',
    de: 'Kann ich beim spanischen Rechtsschutz meinen eigenen Anwalt wählen?',
    fr: 'Puis-je choisir mon propre avocat avec une protection juridique espagnole ?',
    nl: 'Mag ik bij Spaanse rechtsbijstand mijn eigen advocaat kiezen?',
  },
  a: {
    en: 'Yes. Under Spanish insurance contract law you have the right to choose your own lawyer and procurador in any kind of proceedings, and the lawyer you choose takes instructions from you, not from the insurer. The right does not depend on the insurer agreeing, and does not require a conflict of interest. Inside a combined home policy the legal expenses cover must appear as a separate chapter with its own premium, and the policy must state the right expressly.',
    no: 'Ja. Etter spansk forsikringsavtalerett har du rett til å velge din egen advokat og prosessfullmektig i enhver type sak, og advokaten du velger tar instruks fra deg, ikke fra selskapet. Retten er ikke avhengig av at selskapet samtykker, og krever ikke en interessekonflikt. I en kombinert husforsikring må dekningen for juridisk bistand stå som et eget kapittel med egen premie, og polisen må uttrykkelig angi retten.',
    sv: 'Ja. Enligt spansk försäkringsavtalsrätt har du rätt att välja din egen advokat och ditt eget ombud i varje slags förfarande, och den advokat du väljer tar instruktioner av dig, inte av bolaget. Rätten beror inte på att bolaget samtycker och kräver ingen intressekonflikt. I en kombinerad hemförsäkring måste rättsskyddet stå som ett eget kapitel med egen premie, och försäkringsbrevet måste uttryckligen ange rätten.',
    de: 'Ja. Nach spanischem Versicherungsvertragsrecht haben Sie das Recht, in jeder Art von Verfahren Ihren eigenen Anwalt und Prozessvertreter zu wählen, und der gewählte Anwalt nimmt Weisungen von Ihnen entgegen, nicht vom Versicherer. Das Recht hängt nicht von dessen Zustimmung ab und setzt keinen Interessenkonflikt voraus. In einer kombinierten Wohngebäudepolice muss der Rechtsschutz als eigenes Kapitel mit eigener Prämie erscheinen, und die Police muss das Recht ausdrücklich benennen.',
    fr: "Oui. En droit espagnol du contrat d'assurance, vous avez le droit de choisir votre propre avocat et votre procurador dans toute procédure, et l'avocat choisi reçoit ses instructions de vous, pas de l'assureur. Ce droit ne dépend pas de l'accord de l'assureur et n'exige aucun conflit d'intérêts. Dans un contrat habitation multirisque, la protection juridique doit figurer dans un chapitre distinct avec sa propre prime, et le contrat doit énoncer ce droit expressément.",
    nl: 'Ja. Naar Spaans verzekeringsrecht heeft u het recht in elke procedure uw eigen advocaat en procurador te kiezen, en de gekozen advocaat neemt instructies van u aan, niet van de verzekeraar. Het recht hangt niet af van instemming van de verzekeraar en vereist geen belangenconflict. Binnen een gecombineerde woonpolis moet de rechtsbijstanddekking als apart hoofdstuk met een eigen premie staan, en de polis moet het recht uitdrukkelijk vermelden.',
  },
},
{
  slug: 'challenge-a-spanish-community-of-owners-decision',
  tool: 'your-rights',
  rules: ['limit.community.challenge', 'limit.community.challenge.absent', 'limit.community.challenge.standing'],
  q: {
    en: 'How long do I have to challenge a decision of the owners meeting in Spain?',
    no: 'Hvor lang tid har jeg på å angripe et vedtak fra sameiermøtet i Spania?',
    sv: 'Hur lång tid har jag på mig att klandra ett stämmobeslut i Spanien?',
    de: 'Wie lange kann ich einen Beschluss der Eigentümerversammlung in Spanien anfechten?',
    fr: 'Combien de temps ai-je pour contester une décision d’assemblée en Espagne ?',
    nl: 'Hoe lang heb ik om een besluit van de eigenarenvergadering in Spanje aan te vechten?',
  },
  a: {
    en: 'Three months if the ground is that the decision seriously harms the community or unfairly harms one owner, and one year if the ground is that it breaks the law or the statutes. An owner who was not at the meeting counts the window from the day the decision was communicated to them, not from the day of the meeting. To challenge, you generally have to be up to date with community payments or have paid the disputed amount into court first.',
    no: 'Tre måneder hvis grunnlaget er at vedtaket skader sameiet alvorlig eller rammer én eier urimelig, og ett år hvis grunnlaget er at det bryter loven eller vedtektene. En eier som ikke var på møtet regner fristen fra dagen vedtaket ble meddelt vedkommende, ikke fra møtedagen. For å angripe må du som regel være à jour med fellesutgiftene eller først ha deponert det omtvistede beløpet i retten.',
    sv: 'Tre månader om grunden är att beslutet allvarligt skadar samfälligheten eller drabbar en ägare oskäligt, och ett år om grunden är att det strider mot lag eller stadgar. En ägare som inte var på stämman räknar fristen från den dag beslutet meddelades vederbörande, inte från stämmodagen. För att klandra måste du normalt vara i fas med samfällighetsavgifterna eller först ha deponerat det omtvistade beloppet i domstol.',
    de: 'Drei Monate, wenn der Grund ist, dass der Beschluss die Gemeinschaft schwer schädigt oder einen Eigentümer unbillig benachteiligt, und ein Jahr, wenn der Grund ist, dass er gegen Gesetz oder Satzung verstößt. Ein Eigentümer, der nicht bei der Versammlung war, rechnet die Frist ab dem Tag, an dem ihm der Beschluss mitgeteilt wurde, nicht ab dem Versammlungstag. Zum Anfechten müssen Sie in der Regel mit den Gemeinschaftszahlungen aktuell sein oder den streitigen Betrag zuvor bei Gericht hinterlegt haben.',
    fr: "Trois mois si le motif est que la décision nuit gravement à la copropriété ou lèse injustement un copropriétaire, et un an si le motif est qu'elle enfreint la loi ou les statuts. Un copropriétaire absent de l'assemblée compte le délai à partir du jour où la décision lui a été communiquée, et non du jour de l'assemblée. Pour contester, il faut en général être à jour des charges ou avoir consigné en justice le montant contesté.",
    nl: 'Drie maanden als de grond is dat het besluit de vereniging ernstig schaadt of een eigenaar onredelijk benadeelt, en een jaar als de grond is dat het in strijd is met de wet of de statuten. Een eigenaar die niet op de vergadering was, rekent de termijn vanaf de dag waarop het besluit aan hem is meegedeeld, niet vanaf de vergaderdag. Om aan te vechten moet u doorgaans bij zijn met de bijdragen of het betwiste bedrag eerst bij de rechtbank hebben gestort.',
  },
},
{
  slug: 'buying-a-spanish-property-with-unpaid-community-fees',
  tool: 'your-rights',
  rules: ['limit.community.buyer_liability'],
  q: {
    en: 'Do I inherit the seller’s unpaid community fees when I buy in Spain?',
    no: 'Arver jeg selgerens ubetalte fellesutgifter når jeg kjøper i Spania?',
    sv: 'Ärver jag säljarens obetalda samfällighetsavgifter när jag köper i Spanien?',
    de: 'Übernehme ich beim Kauf in Spanien das offene Hausgeld des Verkäufers?',
    fr: 'Est-ce que je reprends les charges impayées du vendeur en achetant en Espagne ?',
    nl: 'Neem ik bij aankoop in Spanje de onbetaalde VvE-bijdragen van de verkoper over?',
  },
  a: {
    en: 'Partly, and the property itself answers for them. A buyer takes on the seller’s unpaid community charges for the elapsed part of the year of purchase plus the three previous calendar years. This is why a certificate of debt from the administrator is asked for at completion: it is the only way to see what you are taking on before you sign.',
    no: 'Delvis, og eiendommen selv hefter for dem. En kjøper overtar selgerens ubetalte fellesutgifter for den forløpte delen av kjøpsåret pluss de tre foregående kalenderårene. Derfor bes det om en gjeldsattest fra forretningsføreren ved overtakelse: det er den eneste måten å se hva du overtar før du signerer.',
    sv: 'Delvis, och fastigheten själv svarar för dem. En köpare övertar säljarens obetalda samfällighetsavgifter för den förflutna delen av köpåret plus de tre föregående kalenderåren. Därför begärs ett skuldintyg från förvaltaren vid tillträdet: det är enda sättet att se vad du tar över innan du skriver under.',
    de: 'Teilweise, und die Immobilie selbst haftet dafür. Ein Käufer übernimmt das offene Hausgeld des Verkäufers für den abgelaufenen Teil des Kaufjahres plus die drei vorangegangenen Kalenderjahre. Deshalb wird beim Notartermin eine Schuldenbescheinigung des Verwalters verlangt: nur so sehen Sie vor der Unterschrift, was Sie übernehmen.',
    fr: "En partie, et le bien lui-même en répond. L'acquéreur reprend les charges de copropriété impayées du vendeur pour la partie écoulée de l'année d'achat plus les trois années civiles précédentes. C'est pourquoi un certificat de dettes du syndic est demandé à la signature : c'est le seul moyen de voir ce que vous reprenez avant de signer.",
    nl: 'Gedeeltelijk, en het pand zelf staat ervoor in. Een koper neemt de onbetaalde verenigingsbijdragen van de verkoper over voor het verstreken deel van het aankoopjaar plus de drie voorgaande kalenderjaren. Daarom wordt bij de overdracht een schuldverklaring van de beheerder gevraagd: dat is de enige manier om vóór ondertekening te zien wat u overneemt.',
  },
},
{
  slug: 'hidden-defects-after-buying-a-spanish-property',
  tool: 'your-rights',
  rules: ['limit.hidden_defects', 'limit.contract.annulment'],
  q: {
    en: 'How long do I have to claim for a hidden defect after buying in Spain?',
    no: 'Hvor lang tid har jeg på å kreve for en skjult mangel etter kjøp i Spania?',
    sv: 'Hur lång tid har jag på mig att kräva för ett dolt fel efter köp i Spanien?',
    de: 'Wie lange kann ich nach einem Kauf in Spanien versteckte Mängel geltend machen?',
    fr: 'Combien de temps ai-je pour agir en vice caché après un achat en Espagne ?',
    nl: 'Hoe lang heb ik om een verborgen gebrek te claimen na aankoop in Spanje?',
  },
  a: {
    en: 'Six months from the day the property was handed over. Not six months from the day you found the defect, which is what catches people. It is the shortest and harshest period in Spanish property law. A separate route, setting the contract aside for mistake or deceit, has four years counted from completion of the contract, and is a different claim with different requirements.',
    no: 'Seks måneder fra dagen boligen ble overlevert. Ikke seks måneder fra dagen du fant mangelen, og det er der folk går på. Det er den korteste og hardeste fristen i spansk eiendomsrett. En egen vei, å sette kontrakten til side for villfarelse eller svik, har fire år regnet fra kontraktens inngåelse, og er et annet krav med andre vilkår.',
    sv: 'Sex månader från den dag bostaden överlämnades. Inte sex månader från den dag du hittade felet, och det är där folk går bet. Det är den kortaste och hårdaste fristen i spansk fastighetsrätt. En separat väg, att sätta avtalet åt sidan för villfarelse eller svek, har fyra år räknat från avtalets ingående, och är ett annat krav med andra villkor.',
    de: 'Sechs Monate ab dem Tag der Übergabe der Immobilie. Nicht sechs Monate ab dem Tag, an dem Sie den Mangel entdeckt haben, und genau daran scheitern viele. Es ist die kürzeste und härteste Frist im spanischen Immobilienrecht. Ein eigener Weg, die Aufhebung des Vertrags wegen Irrtums oder Täuschung, hat vier Jahre ab Vertragsschluss und ist ein anderer Anspruch mit anderen Voraussetzungen.',
    fr: "Six mois à compter de la remise du bien. Pas six mois à compter du jour où vous avez découvert le vice, et c'est là que les gens se font piéger. C'est le délai le plus court et le plus dur du droit immobilier espagnol. Une voie distincte, l'annulation du contrat pour erreur ou dol, dispose de quatre ans à compter de la conclusion du contrat, et constitue une action différente avec d'autres conditions.",
    nl: 'Zes maanden vanaf de dag dat de woning is opgeleverd. Niet zes maanden vanaf de dag dat u het gebrek vond, en daar gaat het mis. Het is de kortste en hardste termijn in het Spaanse vastgoedrecht. Een aparte route, vernietiging van het contract wegens dwaling of bedrog, kent vier jaar vanaf het sluiten van het contract, en is een andere vordering met andere voorwaarden.',
  },
},
{
  slug: 'new-build-guarantees-in-spain',
  tool: 'contractor-check',
  rules: ['limit.building.guarantee', 'limit.building.action', 'limit.building.scope'],
  q: {
    en: 'What are the building guarantees on a new build in Spain?',
    no: 'Hvilke byggegarantier gjelder for nybygg i Spania?',
    sv: 'Vilka byggnadsgarantier gäller för nybyggnation i Spanien?',
    de: 'Welche Baugewährleistungen gelten für einen Neubau in Spanien?',
    fr: 'Quelles garanties de construction s’appliquent à un neuf en Espagne ?',
    nl: 'Welke bouwgaranties gelden voor nieuwbouw in Spanje?',
  },
  a: {
    en: 'Ten years for structural defects, three years for defects that make the home unfit to live in, and one year for finishes, against the builder only. All three run from the date the works were signed off. Separately, once a covered defect appears you have two years to bring the claim, counted from when the damage occurred. The regime applies to buildings whose planning permission was applied for on or after 6 May 2000.',
    no: 'Ti år for konstruksjonsfeil, tre år for feil som gjør boligen ubeboelig, og ett år for overflater, kun mot entreprenøren. Alle tre løper fra datoen arbeidene ble ferdigattestert. Separat gjelder at når en dekket feil viser seg, har du to år på å fremme kravet, regnet fra da skaden oppsto. Regelverket gjelder bygg der byggetillatelse ble søkt 6. mai 2000 eller senere.',
    sv: 'Tio år för konstruktionsfel, tre år för fel som gör bostaden obeboelig, och ett år för ytskikt, endast mot byggaren. Alla tre löper från det datum arbetena slutbesiktigades. Separat gäller att när ett täckt fel visar sig har du två år att framställa kravet, räknat från när skadan uppstod. Regelverket gäller byggnader vars bygglov söktes den 6 maj 2000 eller senare.',
    de: 'Zehn Jahre für Mängel an der Konstruktion, drei Jahre für Mängel, die die Wohnung unbewohnbar machen, und ein Jahr für den Ausbau, nur gegenüber dem Bauunternehmer. Alle drei laufen ab dem Datum der Abnahme der Arbeiten. Gesondert gilt: sobald ein gedeckter Mangel auftritt, haben Sie zwei Jahre für den Anspruch, gerechnet ab Eintritt des Schadens. Das Regime gilt für Gebäude, deren Baugenehmigung am 6. Mai 2000 oder später beantragt wurde.',
    fr: "Dix ans pour les défauts structurels, trois ans pour ceux qui rendent le logement inhabitable, et un an pour les finitions, contre le constructeur seulement. Les trois courent à partir de la date de réception des travaux. Séparément, dès qu'un défaut couvert apparaît, vous avez deux ans pour agir, à compter de la survenance du dommage. Le régime s'applique aux bâtiments dont le permis a été demandé le 6 mai 2000 ou après.",
    nl: 'Tien jaar voor constructieve gebreken, drie jaar voor gebreken die de woning onbewoonbaar maken, en een jaar voor afwerking, alleen tegen de aannemer. Alle drie lopen vanaf de datum waarop het werk is opgeleverd. Los daarvan geldt: zodra een gedekt gebrek opkomt, heeft u twee jaar om de vordering in te stellen, gerekend vanaf het moment dat de schade zich voordeed. Het regime geldt voor gebouwen waarvoor de bouwvergunning op of na 6 mei 2000 is aangevraagd.',
  },
},
{
  slug: 'plusvalia-when-selling-in-spain',
  tool: 'sale-tax',
  rules: ['plusvalia.methods', 'plusvalia.no_gain', 'plusvalia.deadlines'],
  q: {
    en: 'How is the plusvalia calculated when I sell in Spain?',
    no: 'Hvordan beregnes plusvalia når jeg selger i Spania?',
    sv: 'Hur beräknas plusvalia när jag säljer i Spanien?',
    de: 'Wie wird die plusvalia beim Verkauf in Spanien berechnet?',
    fr: 'Comment la plusvalia est-elle calculée lors d’une vente en Espagne ?',
    nl: 'Hoe wordt de plusvalia berekend als ik in Spanje verkoop?',
  },
  a: {
    en: 'Two methods, and the taxpayer may elect the lower. The objective method multiplies the cadastral value of the land by a coefficient for the holding period. The real gain method uses the actual increase between the two deeds. Where no increase arose there is no liability, though the transfer must still be declared with both deeds. The deadline on a sale is 30 working days from the date of the public deed. Coefficients and rates vary by municipality.',
    no: 'To metoder, og skattyter kan velge den laveste. Den objektive metoden ganger matrikkelverdien på grunnen med en koeffisient for eiertiden. Metoden med reell gevinst bruker den faktiske økningen mellom de to skjøtene. Oppsto ingen økning, er det ingen skatt, men overdragelsen må fortsatt meldes med begge skjøtene. Fristen ved salg er 30 virkedager fra datoen på det offentlige skjøtet. Koeffisienter og satser varierer fra kommune til kommune.',
    sv: 'Två metoder, och den skattskyldige får välja den lägsta. Den objektiva metoden multiplicerar markens taxeringsvärde med en koefficient för innehavstiden. Metoden med verklig vinst använder den faktiska ökningen mellan de två handlingarna. Uppstod ingen ökning finns ingen skatt, men överlåtelsen måste ändå anmälas med båda handlingarna. Fristen vid försäljning är 30 arbetsdagar från datumet på den offentliga handlingen. Koefficienter och satser varierar mellan kommuner.',
    de: 'Zwei Methoden, und der Steuerpflichtige darf die niedrigere wählen. Die objektive Methode multipliziert den Katasterwert des Grundstücks mit einem Koeffizienten für die Haltedauer. Die Methode des tatsächlichen Gewinns nimmt die reale Steigerung zwischen den beiden Urkunden. Entstand keine Steigerung, fällt keine Steuer an, die Übertragung ist aber weiterhin mit beiden Urkunden zu erklären. Die Frist beim Verkauf beträgt 30 Werktage ab dem Datum der öffentlichen Urkunde. Koeffizienten und Sätze sind von Gemeinde zu Gemeinde verschieden.',
    fr: "Deux méthodes, et le contribuable peut choisir la plus faible. La méthode objective multiplie la valeur cadastrale du terrain par un coefficient lié à la durée de détention. La méthode du gain réel utilise l'augmentation effective entre les deux actes. En l'absence d'augmentation, il n'y a pas d'imposition, mais la transmission doit tout de même être déclarée avec les deux actes. Le délai en cas de vente est de 30 jours ouvrables à compter de la date de l'acte public. Coefficients et taux varient selon la commune.",
    nl: 'Twee methoden, en de belastingplichtige mag de laagste kiezen. De objectieve methode vermenigvuldigt de kadastrale grondwaarde met een coëfficiënt voor de bezitsduur. De methode van de werkelijke winst gebruikt de feitelijke stijging tussen de twee akten. Was er geen stijging, dan is er geen belasting, al moet de overdracht nog steeds met beide akten worden aangegeven. De termijn bij verkoop is 30 werkdagen vanaf de datum van de notariële akte. Coëfficiënten en tarieven verschillen per gemeente.',
  },
},
{
  slug: 'nie-number-form-and-fee',
  tool: 'utility-setup',
  rules: ['nie.form', 'nie.fee'],
  q: {
    en: 'Which form and fee do I need for a Spanish NIE?',
    no: 'Hvilket skjema og gebyr trenger jeg for et spansk NIE?',
    sv: 'Vilken blankett och avgift behöver jag för ett spanskt NIE?',
    de: 'Welches Formular und welche Gebühr brauche ich für eine spanische NIE?',
    fr: 'Quel formulaire et quelle taxe pour un NIE espagnol ?',
    nl: 'Welk formulier en welke leges heb ik nodig voor een Spaans NIE?',
  },
  a: {
    en: 'The NIE application form is the EX-15, and the fee for assignment of a NIE is 9.84 euros. The EX-18 is a different form: it is the EU citizen registration certificate application, under a separate procedure, and turning up with it instead is a common reason for being sent away. The NIE is usually the first step, because the utility and council registrations depend on it.',
    no: 'Søknadsskjemaet for NIE er EX-15, og gebyret for tildeling av NIE er 9,84 euro. EX-18 er et annet skjema: det er søknaden om registreringsbevis for EU-borgere, under en egen prosedyre, og å møte opp med det i stedet er en vanlig grunn til å bli sendt bort. NIE er som regel første steg, fordi registreringene for strøm, vann og kommune avhenger av det.',
    sv: 'Ansökningsblanketten för NIE är EX-15, och avgiften för tilldelning av NIE är 9,84 euro. EX-18 är en annan blankett: det är ansökan om registreringsbevis för EU-medborgare, under en separat procedur, och att dyka upp med den i stället är ett vanligt skäl att bli hemskickad. NIE är oftast första steget, eftersom registreringarna för el, vatten och kommun bygger på det.',
    de: 'Das Antragsformular für die NIE ist das EX-15, und die Gebühr für die Zuteilung einer NIE beträgt 9,84 Euro. Das EX-18 ist ein anderes Formular: es ist der Antrag auf die Anmeldebescheinigung für EU-Bürger, in einem eigenen Verfahren, und damit anzukommen ist ein häufiger Grund, weggeschickt zu werden. Die NIE ist meist der erste Schritt, weil die Anmeldungen bei Versorgern und Gemeinde darauf aufbauen.',
    fr: "Le formulaire de demande de NIE est l'EX-15, et la taxe pour l'attribution d'un NIE est de 9,84 euros. L'EX-18 est un autre formulaire : c'est la demande de certificat d'enregistrement des citoyens de l'UE, sous une procédure distincte, et se présenter avec celui-là est une cause fréquente de renvoi. Le NIE est en général la première étape, car les abonnements et l'inscription communale en dépendent.",
    nl: 'Het aanvraagformulier voor de NIE is de EX-15, en de leges voor toekenning van een NIE bedragen 9,84 euro. De EX-18 is een ander formulier: dat is de aanvraag voor het registratiebewijs voor EU-burgers, onder een aparte procedure, en daarmee komen opdagen is een veelvoorkomende reden om te worden weggestuurd. De NIE is meestal de eerste stap, omdat de aansluitingen en de gemeentelijke inschrijving ervan afhangen.',
  },
},
{
  slug: 'is-a-spanish-second-home-a-morada',
  tool: 'closing-up',
  rules: ['squat.second_home_is_morada', 'squat.civil_express'],
  q: {
    en: 'Does a Spanish second home count as a morada if I leave it empty?',
    no: 'Regnes en spansk sekundærbolig som en morada hvis den står tom?',
    sv: 'Räknas en spansk andrabostad som en morada om den står tom?',
    de: 'Gilt eine spanische Zweitwohnung als morada, wenn sie leer steht?',
    fr: 'Une résidence secondaire espagnole est-elle une morada si elle reste vide ?',
    nl: 'Telt een Spaanse tweede woning als morada als die leegstaat?',
  },
  a: {
    en: 'Yes. Second residences and seasonal residences are a morada, provided the legitimate occupiers carry on their private life there, even occasionally. That matters because the protection attaching to a morada is stronger than most owners abroad assume. A separate civil express recovery route is also open to natural persons and non-profits.',
    no: 'Ja. Sekundærboliger og sesongboliger er en morada, forutsatt at de rettmessige beboerne lever sitt privatliv der, om enn leilighetsvis. Det betyr noe fordi vernet som følger en morada er sterkere enn de fleste eiere i utlandet antar. En egen sivil hurtigprosess for tilbakeføring står også åpen for fysiske personer og ideelle organisasjoner.',
    sv: 'Ja. Andrabostäder och säsongsbostäder är en morada, förutsatt att de rättmätiga boende lever sitt privatliv där, om än tillfälligt. Det spelar roll eftersom skyddet som följer en morada är starkare än de flesta ägare utomlands antar. En separat civil snabbprocess för återvinnande står också öppen för fysiska personer och ideella organisationer.',
    de: 'Ja. Zweitwohnungen und Saisonwohnungen sind eine morada, sofern die rechtmäßigen Bewohner dort ihr Privatleben führen, und sei es gelegentlich. Das zählt, weil der Schutz einer morada stärker ist, als die meisten Eigentümer im Ausland annehmen. Daneben steht natürlichen Personen und gemeinnützigen Einrichtungen ein eigener zivilrechtlicher Eilweg zur Rückerlangung offen.',
    fr: "Oui. Les résidences secondaires et saisonnières sont une morada, dès lors que les occupants légitimes y mènent leur vie privée, même occasionnellement. Cela compte, car la protection attachée à une morada est plus forte que ne le supposent la plupart des propriétaires à l'étranger. Une voie civile accélérée de récupération est par ailleurs ouverte aux personnes physiques et aux organismes sans but lucratif.",
    nl: 'Ja. Tweede woningen en seizoenswoningen zijn een morada, mits de rechtmatige bewoners er hun privéleven leiden, al is het af en toe. Dat doet ertoe, omdat de bescherming die bij een morada hoort sterker is dan de meeste eigenaren in het buitenland aannemen. Daarnaast staat een aparte civiele spoedprocedure tot terugkrijgen open voor natuurlijke personen en non-profitorganisaties.',
  },
},
{
  slug: 'when-to-file-spanish-rental-income-from-2026',
  tool: 'rental-tax',
  rules: ['deadline.rental.last_quarterly', 'deadline.rental.from_2026', 'deadline.imputed.from_2026'],
  q: {
    en: 'When do I file Spanish rental income from 2026?',
    no: 'Når leverer jeg spansk leieinntekt fra 2026?',
    sv: 'När deklarerar jag spansk hyresinkomst från 2026?',
    de: 'Wann erkläre ich spanische Mieteinkünfte ab 2026?',
    fr: 'Quand déclarer les revenus locatifs espagnols à partir de 2026 ?',
    nl: 'Wanneer geef ik Spaanse huurinkomsten vanaf 2026 aan?',
  },
  a: {
    en: 'The quarterly rhythm ends. Q3 2026 is the last quarterly rental return, due 1 to 20 October 2026. Rental income accrued from 1 October 2026 goes into a single annual return filed in the first 20 calendar days of April the following year. Imputed income for accruals from 2026 is filed from 1 April to 31 December of the following year, with direct debit closing on 23 December.',
    no: 'Den kvartalsvise rytmen tar slutt. Q3 2026 er den siste kvartalsvise leieoppgaven, med frist 1. til 20. oktober 2026. Leieinntekt som påløper fra 1. oktober 2026 går inn i én årlig oppgave levert i de første 20 kalenderdagene i april året etter. Imputert inntekt som påløper fra 2026 leveres fra 1. april til 31. desember året etter, med avtalegiro som stenger 23. desember.',
    sv: 'Den kvartalsvisa rytmen tar slut. Q3 2026 är den sista kvartalsvisa hyresdeklarationen, med frist 1 till 20 oktober 2026. Hyresinkomst som uppkommer från 1 oktober 2026 går in i en enda årlig deklaration som lämnas under de första 20 kalenderdagarna i april året därpå. Schablonintäkt som uppkommer från 2026 deklareras från 1 april till 31 december året därpå, med autogiro som stänger 23 december.',
    de: 'Der vierteljährliche Rhythmus endet. Q3 2026 ist die letzte vierteljährliche Mieterklärung, fällig vom 1. bis 20. Oktober 2026. Mieteinkünfte ab dem 1. Oktober 2026 gehen in eine einzige Jahreserklärung ein, abzugeben in den ersten 20 Kalendertagen des April im Folgejahr. Fiktive Einkünfte für Zeiträume ab 2026 werden vom 1. April bis 31. Dezember des Folgejahres erklärt, das Lastschriftverfahren schließt am 23. Dezember.',
    fr: "Le rythme trimestriel prend fin. Le troisième trimestre 2026 est la dernière déclaration locative trimestrielle, à déposer du 1er au 20 octobre 2026. Les revenus locatifs perçus à partir du 1er octobre 2026 entrent dans une déclaration annuelle unique, déposée dans les 20 premiers jours d'avril de l'année suivante. Le revenu imputé à partir de 2026 se déclare du 1er avril au 31 décembre de l'année suivante, le prélèvement se fermant le 23 décembre.",
    nl: 'Het kwartaalritme eindigt. Q3 2026 is de laatste kwartaalaangifte voor huurinkomsten, in te dienen van 1 tot 20 oktober 2026. Huurinkomsten vanaf 1 oktober 2026 gaan op in één jaarlijkse aangifte, in te dienen in de eerste 20 kalenderdagen van april van het jaar daarna. Fictief inkomen vanaf 2026 wordt aangegeven van 1 april tot 31 december van het jaar daarna, waarbij automatische incasso op 23 december sluit.',
  },
},
{
  slug: 'spanish-wealth-tax-for-non-residents',
  tool: 'cost-audit',
  rules: ['ip.minimo_exento', 'ip.filing_trigger', 'ip.eu_option'],
  q: {
    en: 'Do non-residents pay Spanish wealth tax?',
    no: 'Betaler ikke-bosatte spansk formuesskatt?',
    sv: 'Betalar icke-bosatta spansk förmögenhetsskatt?',
    de: 'Zahlen Nichtansässige spanische Vermögensteuer?',
    fr: 'Les non-résidents paient-ils l’impôt sur la fortune espagnol ?',
    nl: 'Betalen niet-inwoners Spaanse vermogensbelasting?',
  },
  a: {
    en: 'Non-residents are taxed by obligacion real on Spanish assets, with a 700,000 euro minimo exento. A return is due where the tax payable after deductions is positive, or where the value of assets and rights exceeds the filing threshold even if no tax is payable. EU and EEA non-residents may opt to apply the autonomic rules of the Comunidad where the greatest value of their assets is situated, which can change the outcome considerably.',
    no: 'Ikke-bosatte skattlegges etter obligacion real på spanske eiendeler, med et bunnfradrag på 700 000 euro. Oppgave skal leveres når skatten etter fradrag er positiv, eller når verdien av eiendeler og rettigheter overstiger terskelen selv om ingen skatt skal betales. Ikke-bosatte i EU og EØS kan velge å anvende de autonome reglene i den Comunidad der størstedelen av verdien ligger, noe som kan endre utfallet betydelig.',
    sv: 'Icke-bosatta beskattas enligt obligacion real på spanska tillgångar, med ett grundavdrag på 700 000 euro. Deklaration ska lämnas när skatten efter avdrag är positiv, eller när värdet av tillgångar och rättigheter överstiger tröskeln även om ingen skatt ska betalas. Icke-bosatta i EU och EES får välja att tillämpa de autonoma reglerna i den Comunidad där störst värde finns, vilket kan ändra utfallet avsevärt.',
    de: 'Nichtansässige werden nach obligacion real auf spanisches Vermögen besteuert, mit einem Freibetrag von 700.000 Euro. Eine Erklärung ist abzugeben, wenn die Steuer nach Abzügen positiv ist, oder wenn der Wert von Vermögen und Rechten die Schwelle übersteigt, auch wenn keine Steuer anfällt. Nichtansässige aus EU und EWR können die autonomen Regeln der Comunidad wählen, in der der größte Vermögenswert liegt, was das Ergebnis erheblich verändern kann.',
    fr: "Les non-résidents sont imposés par obligacion real sur les actifs espagnols, avec un minimo exento de 700 000 euros. Une déclaration est due lorsque l'impôt après déductions est positif, ou lorsque la valeur des biens et droits dépasse le seuil de dépôt même sans impôt à payer. Les non-résidents de l'UE et de l'EEE peuvent opter pour les règles autonomes de la Comunidad où se situe la plus grande valeur de leurs actifs, ce qui peut changer sensiblement le résultat.",
    nl: 'Niet-inwoners worden via obligacion real belast over Spaanse vermogensbestanddelen, met een vrijstelling van 700.000 euro. Er moet aangifte worden gedaan wanneer de belasting na aftrek positief is, of wanneer de waarde van bezittingen en rechten de drempel overschrijdt, ook zonder verschuldigde belasting. Niet-inwoners uit de EU en EER mogen kiezen voor de autonome regels van de Comunidad waar de grootste waarde ligt, wat de uitkomst aanzienlijk kan veranderen.',
  },
},
{
  slug: 'energy-certificate-for-a-spanish-property',
  tool: 'closing-up',
  rules: ['epc.requirement', 'epc.validity'],
  q: {
    en: 'Do I need an energy certificate to sell or let in Spain?',
    no: 'Trenger jeg energiattest for å selge eller leie ut i Spania?',
    sv: 'Behöver jag energideklaration för att sälja eller hyra ut i Spanien?',
    de: 'Brauche ich einen Energieausweis zum Verkaufen oder Vermieten in Spanien?',
    fr: 'Faut-il un certificat énergétique pour vendre ou louer en Espagne ?',
    nl: 'Heb ik een energiecertificaat nodig om in Spanje te verkopen of verhuren?',
  },
  a: {
    en: 'Yes. A registered certificate is required for new buildings and for existing buildings that are sold or let. Maximum validity is ten years, with one exception: where the rating is G the validity is shorter, so an old certificate on a poorly rated property may already have expired even though ten years have not passed.',
    no: 'Ja. En registrert attest kreves for nybygg og for eksisterende bygg som selges eller leies ut. Maksimal gyldighet er ti år, med ett unntak: er karakteren G, er gyldigheten kortere, så en gammel attest på en dårlig vurdert bolig kan allerede være utløpt selv om det ikke har gått ti år.',
    sv: 'Ja. En registrerad deklaration krävs för nybyggnation och för befintliga byggnader som säljs eller hyrs ut. Maximal giltighet är tio år, med ett undantag: är betyget G är giltigheten kortare, så en gammal deklaration på en lågt betygsatt bostad kan redan ha gått ut även om tio år inte passerat.',
    de: 'Ja. Ein registrierter Ausweis ist für Neubauten und für bestehende Gebäude erforderlich, die verkauft oder vermietet werden. Die Höchstgültigkeit beträgt zehn Jahre, mit einer Ausnahme: bei der Klasse G ist die Gültigkeit kürzer, ein alter Ausweis für eine schlecht bewertete Immobilie kann also bereits abgelaufen sein, obwohl keine zehn Jahre vergangen sind.',
    fr: "Oui. Un certificat enregistré est exigé pour les bâtiments neufs et pour les bâtiments existants vendus ou loués. La validité maximale est de dix ans, avec une exception : lorsque la classe est G, la validité est plus courte, si bien qu'un ancien certificat sur un bien mal classé peut déjà être périmé alors que dix ans ne sont pas écoulés.",
    nl: 'Ja. Een geregistreerd certificaat is vereist voor nieuwbouw en voor bestaande gebouwen die worden verkocht of verhuurd. De maximale geldigheid is tien jaar, met één uitzondering: bij label G is de geldigheid korter, dus een oud certificaat op een slecht scorende woning kan al zijn verlopen terwijl er nog geen tien jaar voorbij zijn.',
  },
},
{
  slug: 'tourist-letting-and-the-community-of-owners',
  tool: 'rental-vat',
  rules: ['lph.17_12.majority', 'lph.17_12.effective_date', 'lph.17_12.retroactivity'],
  q: {
    en: 'Can a Spanish community of owners stop me letting to tourists?',
    no: 'Kan et spansk sameie hindre meg i å leie ut til turister?',
    sv: 'Kan en spansk samfällighet hindra mig från att hyra ut till turister?',
    de: 'Kann eine spanische Eigentümergemeinschaft die Ferienvermietung untersagen?',
    fr: 'Une copropriété espagnole peut-elle m’empêcher de louer aux touristes ?',
    nl: 'Kan een Spaanse VvE mij verbieden aan toeristen te verhuren?',
  },
  a: {
    en: 'A three-fifths majority of owners, who must also represent three-fifths of participation quotas, can restrict or condition tourist letting. The current wording takes effect from 3 April 2025. The agreements have no retroactive effect, so an owner already carrying on the activity is not caught by a later vote. The same majority may set a special expense quota or increased share of up to 20 percent.',
    no: 'Et flertall på tre femtedeler av eierne, som også må representere tre femtedeler av eierbrøkene, kan begrense eller sette vilkår for turistutleie. Den gjeldende ordlyden trer i kraft fra 3. april 2025. Vedtakene har ikke tilbakevirkende kraft, så en eier som allerede driver aktiviteten rammes ikke av et senere vedtak. Samme flertall kan fastsette en særskilt utgiftsandel eller økt andel på inntil 20 prosent.',
    sv: 'En majoritet om tre femtedelar av ägarna, som också måste representera tre femtedelar av andelstalen, kan begränsa eller villkora turistuthyrning. Den nuvarande lydelsen gäller från 3 april 2025. Besluten har ingen retroaktiv verkan, så en ägare som redan bedriver verksamheten träffas inte av ett senare beslut. Samma majoritet får fastställa en särskild kostnadsandel eller ökad andel på upp till 20 procent.',
    de: 'Eine Mehrheit von drei Fünfteln der Eigentümer, die zugleich drei Fünftel der Miteigentumsanteile vertreten muss, kann die Ferienvermietung beschränken oder an Bedingungen knüpfen. Die geltende Fassung wirkt ab dem 3. April 2025. Die Beschlüsse haben keine Rückwirkung, ein Eigentümer, der die Tätigkeit bereits ausübt, wird von einem späteren Beschluss also nicht erfasst. Dieselbe Mehrheit kann eine besondere Kostenquote oder einen erhöhten Anteil von bis zu 20 Prozent festsetzen.',
    fr: "Une majorité des trois cinquièmes des copropriétaires, représentant aussi les trois cinquièmes des tantièmes, peut restreindre ou conditionner la location touristique. La rédaction actuelle prend effet au 3 avril 2025. Les accords n'ont pas d'effet rétroactif : un propriétaire exerçant déjà l'activité n'est pas visé par un vote ultérieur. La même majorité peut fixer une quote-part de charges spéciale ou majorée jusqu'à 20 pour cent.",
    nl: 'Een meerderheid van drie vijfde van de eigenaren, die ook drie vijfde van de aandelen moet vertegenwoordigen, kan toeristische verhuur beperken of aan voorwaarden binden. De huidige tekst geldt vanaf 3 april 2025. De besluiten hebben geen terugwerkende kracht, dus een eigenaar die de activiteit al uitoefent wordt door een later besluit niet geraakt. Dezelfde meerderheid mag een bijzondere kostenquote of verhoogd aandeel van maximaal 20 procent vaststellen.',
  },
},
{
  slug: 'guest-registration-for-spanish-holiday-lets',
  tool: 'rental-vat',
  rules: ['parte.obligation', 'registry.survives', 'registry.regional_unaffected'],
  q: {
    en: 'Do I have to register guests when I let a property in Spain?',
    no: 'Må jeg registrere gjester når jeg leier ut en bolig i Spania?',
    sv: 'Måste jag registrera gäster när jag hyr ut en bostad i Spanien?',
    de: 'Muss ich Gäste melden, wenn ich in Spanien vermiete?',
    fr: 'Dois-je déclarer les voyageurs quand je loue un bien en Espagne ?',
    nl: 'Moet ik gasten registreren als ik een woning in Spanje verhuur?',
  },
  a: {
    en: 'Yes. Anyone carrying on or intermediating in lodging activity, expressly including private hosts, must submit traveller data, with a deadline of 24 hours. Separately, the single digital window and the platform data-sharing duties survive as implementation of EU rules, and regional tourist registration and licensing is unaffected and remains fully in force. Those are three different obligations, not one.',
    no: 'Ja. Enhver som driver eller formidler overnattingsvirksomhet, uttrykkelig inkludert private verter, må sende inn reisendedata, med en frist på 24 timer. Separat består den digitale enkeltportalen og plattformenes plikter til datadeling som gjennomføring av EU-regler, og regional turistregistrering og lisensiering er uberørt og fullt i kraft. Det er tre ulike plikter, ikke én.',
    sv: 'Ja. Var och en som bedriver eller förmedlar logiverksamhet, uttryckligen inklusive privata värdar, måste lämna resenärsuppgifter, med en frist på 24 timmar. Separat består den digitala enda kontaktpunkten och plattformarnas skyldigheter att dela data som genomförande av EU-regler, och regional turistregistrering och licensiering är oberörd och fullt gällande. Det är tre olika skyldigheter, inte en.',
    de: 'Ja. Wer Beherbergung betreibt oder vermittelt, ausdrücklich einschließlich privater Gastgeber, muss Reisendendaten übermitteln, mit einer Frist von 24 Stunden. Gesondert bestehen das digitale Einheitsportal und die Datenweitergabepflichten der Plattformen als Umsetzung von EU-Recht fort, und die regionale Tourismusregistrierung und Lizenzierung bleibt unberührt und voll in Kraft. Das sind drei verschiedene Pflichten, nicht eine.',
    fr: "Oui. Toute personne exerçant ou intermédiant une activité d'hébergement, y compris expressément les hôtes particuliers, doit transmettre les données des voyageurs, dans un délai de 24 heures. Séparément, le guichet numérique unique et les obligations de partage de données des plateformes subsistent en application des règles européennes, et l'enregistrement et la licence touristiques régionaux restent pleinement en vigueur. Ce sont trois obligations distinctes, pas une.",
    nl: 'Ja. Iedereen die logiesactiviteit uitoefent of bemiddelt, uitdrukkelijk inclusief particuliere verhuurders, moet reizigersgegevens indienen, met een termijn van 24 uur. Daarnaast blijven het digitale ene loket en de verplichtingen van platforms om gegevens te delen bestaan als uitvoering van EU-regels, en de regionale toeristische registratie en vergunning blijft onaangetast en volledig van kracht. Dat zijn drie verschillende verplichtingen, niet één.',
  },
},
];
