// Screen text for the purchase costs tool, in the site's six languages. The handout itself
// is in handout.js, in seven.
export default {
  en: {
    title: 'Buying costs by region', note: 'Guidance only, not tax advice.',
    eyebrow: 'For buyers, agents and lawyers', headline: 'What a buyer pays on top of the price, region by region',
    body: 'Pick the region, say whether it is a resale or a new home, and enter the price. You get the taxes line by line, with the source for each rate, and a handout in the buyer’s language.',
    points: ['Banded regions taxed slice by slice, the way the law does it', 'No rate shown where none is confirmed', 'A handout in seven languages, with your letterhead'],
    cta: 'Work it out', minutes: 'Under a minute',
    f_region: 'Region', f_region_ph: 'Choose a region', f_kind: 'What is being bought?', kind_resale: 'A resale home', kind_newbuild: 'A new home from the developer',
    f_price: 'Price in euros', f_client: 'Buyer’s name (optional)', f_lang: 'Handout language',
    empty: 'Choose a region and enter a price to see the taxes.',
    print: 'Print or save as PDF', copy: 'Copy the handout', copied: 'Copied', sources_t: 'Where the rates come from',
    pro_hint: 'Agents and lawyers: add your details on your section page and they print at the top.',
  },
  no: {
    title: 'Kjøpskostnader per region', note: 'Kun til veiledning, ikke skatterådgivning.',
    eyebrow: 'For kjøpere, meglere og advokater', headline: 'Dette betaler kjøperen i tillegg til prisen, region for region',
    body: 'Velg region, si om det er en brukt eller ny bolig, og legg inn prisen. Du får skattene post for post, med kilde for hver sats, og et ark på kjøperens språk.',
    points: ['Trinnvise regioner beregnes trinn for trinn, slik loven gjør', 'Ingen sats vises der ingen er bekreftet', 'Et ark på sju språk, med ditt brevhode'],
    cta: 'Regn det ut', minutes: 'Under ett minutt',
    f_region: 'Region', f_region_ph: 'Velg region', f_kind: 'Hva kjøpes?', kind_resale: 'En brukt bolig', kind_newbuild: 'En ny bolig fra utbygger',
    f_price: 'Pris i euro', f_client: 'Kjøperens navn (valgfritt)', f_lang: 'Språk for arket',
    empty: 'Velg region og legg inn pris for å se skattene.',
    print: 'Skriv ut eller lagre som PDF', copy: 'Kopier arket', copied: 'Kopiert', sources_t: 'Hvor satsene kommer fra',
    pro_hint: 'Meglere og advokater: legg inn detaljene dine på seksjonssiden, så skrives de ut øverst.',
  },
  sv: {
    title: 'Köpkostnader per region', note: 'Endast som vägledning, inte skatterådgivning.',
    eyebrow: 'För köpare, mäklare och advokater', headline: 'Det här betalar köparen utöver priset, region för region',
    body: 'Välj region, ange om det är en begagnad eller nyproducerad bostad och fyll i priset. Du får skatterna post för post, med källa för varje sats, och ett blad på köparens språk.',
    points: ['Regioner med trappsteg beräknas steg för steg, som lagen gör', 'Ingen sats visas där ingen är bekräftad', 'Ett blad på sju språk, med ditt brevhuvud'],
    cta: 'Räkna ut det', minutes: 'Under en minut',
    f_region: 'Region', f_region_ph: 'Välj region', f_kind: 'Vad köps?', kind_resale: 'En begagnad bostad', kind_newbuild: 'En nyproducerad bostad från byggherren',
    f_price: 'Pris i euro', f_client: 'Köparens namn (valfritt)', f_lang: 'Bladets språk',
    empty: 'Välj region och fyll i ett pris för att se skatterna.',
    print: 'Skriv ut eller spara som PDF', copy: 'Kopiera bladet', copied: 'Kopierat', sources_t: 'Var satserna kommer ifrån',
    pro_hint: 'Mäklare och advokater: fyll i era uppgifter på er sektionssida så skrivs de ut överst.',
  },
  de: {
    title: 'Kaufnebenkosten nach Region', note: 'Nur zur Orientierung, keine Steuerberatung.',
    eyebrow: 'Für Käufer, Makler und Anwälte', headline: 'Was ein Käufer zusätzlich zum Preis zahlt, Region für Region',
    body: 'Wählen Sie die Region, ob Bestand oder Neubau, und geben Sie den Preis ein. Sie erhalten die Steuern Posten für Posten, mit Quelle für jeden Satz, und ein Merkblatt in der Sprache des Käufers.',
    points: ['Stufentarife werden Stufe für Stufe berechnet, wie es das Gesetz vorsieht', 'Kein Satz, wo keiner bestätigt ist', 'Ein Merkblatt in sieben Sprachen, mit Ihrem Briefkopf'],
    cta: 'Berechnen', minutes: 'Unter einer Minute',
    f_region: 'Region', f_region_ph: 'Region wählen', f_kind: 'Was wird gekauft?', kind_resale: 'Eine Bestandsimmobilie', kind_newbuild: 'Ein Neubau vom Bauträger',
    f_price: 'Preis in Euro', f_client: 'Name des Käufers (optional)', f_lang: 'Sprache des Merkblatts',
    empty: 'Wählen Sie eine Region und geben Sie einen Preis ein, um die Steuern zu sehen.',
    print: 'Drucken oder als PDF speichern', copy: 'Merkblatt kopieren', copied: 'Kopiert', sources_t: 'Woher die Sätze stammen',
    pro_hint: 'Makler und Anwälte: Hinterlegen Sie Ihre Angaben auf Ihrer Bereichsseite, dann erscheinen sie oben.',
  },
  fr: {
    title: 'Frais d’achat par région', note: 'À titre indicatif, pas un conseil fiscal.',
    eyebrow: 'Pour acheteurs, agents et avocats', headline: 'Ce qu’un acheteur paie en plus du prix, région par région',
    body: 'Choisissez la région, indiquez s’il s’agit d’un bien ancien ou neuf et saisissez le prix. Vous obtenez les impôts ligne par ligne, avec la source de chaque taux, et une fiche dans la langue de l’acheteur.',
    points: ['Barèmes par tranches calculés tranche par tranche, comme le prévoit la loi', 'Aucun taux affiché s’il n’est pas confirmé', 'Une fiche en sept langues, à votre en-tête'],
    cta: 'Calculer', minutes: 'Moins d’une minute',
    f_region: 'Région', f_region_ph: 'Choisir une région', f_kind: 'Qu’est-ce qui est acheté ?', kind_resale: 'Un logement ancien', kind_newbuild: 'Un logement neuf du promoteur',
    f_price: 'Prix en euros', f_client: 'Nom de l’acheteur (facultatif)', f_lang: 'Langue de la fiche',
    empty: 'Choisissez une région et saisissez un prix pour voir les impôts.',
    print: 'Imprimer ou enregistrer en PDF', copy: 'Copier la fiche', copied: 'Copié', sources_t: 'D’où viennent les taux',
    pro_hint: 'Agents et avocats : ajoutez vos coordonnées sur la page de votre section, elles s’imprimeront en haut.',
  },
  nl: {
    title: 'Aankoopkosten per regio', note: 'Alleen ter informatie, geen fiscaal advies.',
    eyebrow: 'Voor kopers, makelaars en advocaten', headline: 'Wat een koper bovenop de prijs betaalt, per regio',
    body: 'Kies de regio, geef aan of het een bestaande of nieuwe woning is en vul de prijs in. U krijgt de belastingen per post, met de bron van elk tarief, en een overzicht in de taal van de koper.',
    points: ['Schijventarieven per schijf berekend, zoals de wet het doet', 'Geen tarief waar er geen bevestigd is', 'Een overzicht in zeven talen, met uw briefhoofd'],
    cta: 'Bereken het', minutes: 'Minder dan een minuut',
    f_region: 'Regio', f_region_ph: 'Kies een regio', f_kind: 'Wat wordt er gekocht?', kind_resale: 'Een bestaande woning', kind_newbuild: 'Een nieuwbouwwoning van de ontwikkelaar',
    f_price: 'Prijs in euro', f_client: 'Naam van de koper (optioneel)', f_lang: 'Taal van het overzicht',
    empty: 'Kies een regio en vul een prijs in om de belastingen te zien.',
    print: 'Afdrukken of als pdf opslaan', copy: 'Overzicht kopiëren', copied: 'Gekopieerd', sources_t: 'Waar de tarieven vandaan komen',
    pro_hint: 'Makelaars en advocaten: vul uw gegevens in op uw sectiepagina, dan staan ze bovenaan.',
  },
};
