// The buyer handout, in the client's language. The same words appear on screen.

export const HANDOUT_LANGS = ['en', 'es', 'no', 'sv', 'de', 'fr', 'nl'];

export const REGION_LABEL = {
  'Comunitat Valenciana': 'Comunitat Valenciana', Andalucia: 'Andalucía', 'Illes Balears': 'Illes Balears',
  Canarias: 'Canarias', 'Region de Murcia': 'Región de Murcia', Catalunya: 'Catalunya', Madrid: 'Madrid',
  Aragon: 'Aragón', 'Castilla y Leon': 'Castilla y León', Extremadura: 'Extremadura', Galicia: 'Galicia',
  'Castilla-La Mancha': 'Castilla-La Mancha', Cantabria: 'Cantabria', 'La Rioja': 'La Rioja',
  'Principado de Asturias': 'Asturias', 'Comunidad Foral de Navarra': 'Navarra', 'Pais Vasco': 'País Vasco',
  Ceuta: 'Ceuta', Melilla: 'Melilla',
};

export const H = {
  en: {
    title: 'What you pay on top of the price', for: 'Prepared for {name}',
    intro: 'Taxes on a {kind} bought for {price} in {region}.',
    k_resale: 'resale home', k_newbuild: 'new home from the developer',
    l_itp: 'Transfer tax (ITP)', l_iva: 'IVA', l_igic: 'IGIC', l_ajd: 'Stamp duty on the deed (AJD)',
    r_flat: '{r} percent', r_banded: 'Banded scale, {e} percent overall',
    total: 'Taxes on the price',
    minimum: 'This is a minimum. The tax is charged on the higher of the price and the reference value published by the Catastro, which can be checked with the cadastral reference. If that value is higher, so is the tax.',
    reduced: 'Some buyers pay lower rates, but almost all of those rates require the home to be the buyer’s main residence. They are not included here.',
    canarias: 'The Canary Islands use IGIC instead of IVA. The lower rates apply only to a main residence, so the general rate is shown.',
    g_itp: 'There is no confirmed transfer tax rate for {region} in our sources, so no figure is shown. Your lawyer or gestor can confirm it.',
    g_itp_valencia_high: 'Above €1,000,000 the rate in the Comunitat Valenciana is not confirmed since the June 2026 change, so no figure is shown.',
    g_vat_ceuta_melilla: 'Ceuta and Melilla do not charge IVA. Their local tax is not covered here.',
    g_ajd: 'There is no confirmed stamp duty rate for new homes in {region} in our sources, so it is not included.',
    other_t: 'Other costs to budget for',
    other: ['Notary fees, which follow an official scale', 'Land registry fees', 'A lawyer or gestoría', 'A valuation and bank costs, if there is a mortgage', 'Sworn translations and the NIE, if needed'],
    other_note: 'These are not estimated here. Ask for written quotes.',
    note: 'This is an estimate based on the published rules on the dates shown, not tax advice.',
  },
  es: {
    title: 'Lo que se paga además del precio', for: 'Preparado para {name}',
    intro: 'Impuestos de una {kind} comprada por {price} en {region}.',
    k_resale: 'vivienda de segunda mano', k_newbuild: 'vivienda nueva de promotor',
    l_itp: 'Impuesto de transmisiones (ITP)', l_iva: 'IVA', l_igic: 'IGIC', l_ajd: 'Actos jurídicos documentados (AJD)',
    r_flat: '{r} por ciento', r_banded: 'Escala por tramos, {e} por ciento en total',
    total: 'Impuestos sobre el precio',
    minimum: 'Es un mínimo. El impuesto se calcula sobre el mayor entre el precio y el valor de referencia del Catastro, que puede consultarse con la referencia catastral. Si ese valor es mayor, el impuesto también lo es.',
    reduced: 'Algunos compradores pagan tipos reducidos, pero casi todos exigen que sea la vivienda habitual. No se incluyen aquí.',
    canarias: 'En Canarias se aplica IGIC en lugar de IVA. Los tipos reducidos solo se aplican a la vivienda habitual, por lo que se muestra el tipo general.',
    g_itp: 'Nuestras fuentes no confirman el tipo de ITP de {region}, así que no se muestra ninguna cifra. Su abogado o gestor puede confirmarlo.',
    g_itp_valencia_high: 'Por encima de €1.000.000 el tipo en la Comunitat Valenciana no está confirmado desde el cambio de junio de 2026, así que no se muestra ninguna cifra.',
    g_vat_ceuta_melilla: 'Ceuta y Melilla no aplican IVA. Su impuesto local no se incluye aquí.',
    g_ajd: 'Nuestras fuentes no confirman el tipo de AJD para vivienda nueva en {region}, así que no se incluye.',
    other_t: 'Otros gastos a prever',
    other: ['Notaría, según el arancel oficial', 'Registro de la Propiedad', 'Abogado o gestoría', 'Tasación y gastos bancarios, si hay hipoteca', 'Traducciones juradas y NIE, si hacen falta'],
    other_note: 'Aquí no se estiman. Pida presupuestos por escrito.',
    note: 'Es una estimación basada en las normas publicadas en las fechas indicadas, no asesoramiento fiscal.',
  },
  no: {
    title: 'Dette betaler du i tillegg til prisen', for: 'Utarbeidet for {name}',
    intro: 'Skatter på en {kind} kjøpt for {price} i {region}.',
    k_resale: 'brukt bolig', k_newbuild: 'ny bolig fra utbygger',
    l_itp: 'Dokumentavgift (ITP)', l_iva: 'IVA', l_igic: 'IGIC', l_ajd: 'Stempelavgift på skjøtet (AJD)',
    r_flat: '{r} prosent', r_banded: 'Trinnvis skala, {e} prosent samlet',
    total: 'Skatter på prisen',
    minimum: 'Dette er et minimum. Skatten beregnes av det høyeste av prisen og referanseverdien fra Catastro, som kan sjekkes med matrikkelnummeret. Er den verdien høyere, blir også skatten høyere.',
    reduced: 'Noen kjøpere får lavere satser, men nesten alle krever at boligen er kjøperens faste bolig. De er ikke tatt med her.',
    canarias: 'Kanariøyene har IGIC i stedet for IVA. De lavere satsene gjelder bare fast bolig, så den generelle satsen vises.',
    g_itp: 'Kildene våre bekrefter ikke satsen for dokumentavgift i {region}, så ingen sum vises. Advokaten eller gestoren din kan bekrefte den.',
    g_itp_valencia_high: 'Over €1 000 000 er satsen i Comunitat Valenciana ikke bekreftet etter endringen i juni 2026, så ingen sum vises.',
    g_vat_ceuta_melilla: 'Ceuta og Melilla har ikke IVA. Den lokale avgiften er ikke dekket her.',
    g_ajd: 'Kildene våre bekrefter ikke stempelavgiften for nye boliger i {region}, så den er ikke tatt med.',
    other_t: 'Andre kostnader å sette av til',
    other: ['Notarhonorar etter offisiell tariff', 'Tinglysingsgebyr', 'Advokat eller gestoría', 'Takst og bankkostnader, hvis du har lån', 'Autoriserte oversettelser og NIE, ved behov'],
    other_note: 'Disse er ikke beregnet her. Be om skriftlige tilbud.',
    note: 'Dette er et anslag basert på publiserte regler på datoene som vises, ikke skatterådgivning.',
  },
  sv: {
    title: 'Det här betalar du utöver priset', for: 'Framtaget för {name}',
    intro: 'Skatter på en {kind} köpt för {price} i {region}.',
    k_resale: 'begagnad bostad', k_newbuild: 'nyproducerad bostad från byggherren',
    l_itp: 'Överlåtelseskatt (ITP)', l_iva: 'IVA', l_igic: 'IGIC', l_ajd: 'Stämpelskatt på köpebrevet (AJD)',
    r_flat: '{r} procent', r_banded: 'Trappstegsskala, {e} procent totalt',
    total: 'Skatter på priset',
    minimum: 'Det här är ett minimum. Skatten beräknas på det högsta av priset och Catastros referensvärde, som kan kontrolleras med fastighetsbeteckningen. Är det värdet högre blir också skatten högre.',
    reduced: 'Vissa köpare får lägre satser, men nästan alla kräver att bostaden är köparens permanentbostad. De ingår inte här.',
    canarias: 'Kanarieöarna har IGIC i stället för IVA. De lägre satserna gäller bara permanentbostad, så den allmänna satsen visas.',
    g_itp: 'Våra källor bekräftar inte överlåtelseskatten i {region}, så ingen siffra visas. Din advokat eller gestor kan bekräfta den.',
    g_itp_valencia_high: 'Över €1 000 000 är satsen i Comunitat Valenciana inte bekräftad sedan ändringen i juni 2026, så ingen siffra visas.',
    g_vat_ceuta_melilla: 'Ceuta och Melilla har inte IVA. Den lokala skatten ingår inte här.',
    g_ajd: 'Våra källor bekräftar inte stämpelskatten för nyproduktion i {region}, så den ingår inte.',
    other_t: 'Andra kostnader att räkna med',
    other: ['Notarieavgift enligt officiell taxa', 'Inskrivningsavgift', 'Advokat eller gestoría', 'Värdering och bankkostnader, om du har lån', 'Auktoriserade översättningar och NIE, vid behov'],
    other_note: 'De uppskattas inte här. Be om skriftliga offerter.',
    note: 'Det här är en uppskattning utifrån publicerade regler de datum som visas, inte skatterådgivning.',
  },
  de: {
    title: 'Was Sie zusätzlich zum Kaufpreis zahlen', for: 'Erstellt für {name}',
    intro: 'Steuern auf eine {kind}, gekauft für {price} in {region}.',
    k_resale: 'Bestandsimmobilie', k_newbuild: 'Neubauimmobilie vom Bauträger',
    l_itp: 'Grunderwerbsteuer (ITP)', l_iva: 'IVA', l_igic: 'IGIC', l_ajd: 'Urkundensteuer (AJD)',
    r_flat: '{r} Prozent', r_banded: 'Stufentarif, insgesamt {e} Prozent',
    total: 'Steuern auf den Kaufpreis',
    minimum: 'Das ist ein Mindestwert. Besteuert wird der höhere Wert aus Kaufpreis und dem Referenzwert des Katasters, der mit der Katasternummer abgefragt werden kann. Ist dieser höher, steigt auch die Steuer.',
    reduced: 'Manche Käufer zahlen ermäßigte Sätze, doch fast alle setzen voraus, dass es der Hauptwohnsitz ist. Sie sind hier nicht enthalten.',
    canarias: 'Auf den Kanarischen Inseln gilt IGIC statt IVA. Die ermäßigten Sätze gelten nur für den Hauptwohnsitz, daher wird der allgemeine Satz gezeigt.',
    g_itp: 'Unsere Quellen bestätigen den Grunderwerbsteuersatz für {region} nicht, daher wird kein Betrag gezeigt. Ihr Anwalt oder Gestor kann ihn bestätigen.',
    g_itp_valencia_high: 'Über €1.000.000 ist der Satz in der Comunitat Valenciana seit der Änderung im Juni 2026 nicht bestätigt, daher wird kein Betrag gezeigt.',
    g_vat_ceuta_melilla: 'Ceuta und Melilla erheben keine IVA. Die dortige Steuer ist hier nicht abgedeckt.',
    g_ajd: 'Unsere Quellen bestätigen den Urkundensteuersatz für Neubauten in {region} nicht, daher ist sie nicht enthalten.',
    other_t: 'Weitere Kosten, die Sie einplanen sollten',
    other: ['Notargebühren nach amtlicher Gebührenordnung', 'Grundbuchgebühren', 'Anwalt oder Gestoría', 'Bewertung und Bankkosten bei einer Hypothek', 'Beglaubigte Übersetzungen und NIE, falls nötig'],
    other_note: 'Diese werden hier nicht geschätzt. Holen Sie schriftliche Angebote ein.',
    note: 'Dies ist eine Schätzung auf Grundlage der veröffentlichten Regeln zu den angegebenen Daten, keine Steuerberatung.',
  },
  fr: {
    title: 'Ce que vous payez en plus du prix', for: 'Préparé pour {name}',
    intro: 'Impôts sur un {kind} acheté {price} en {region}.',
    k_resale: 'logement ancien', k_newbuild: 'logement neuf acheté au promoteur',
    l_itp: 'Droits de mutation (ITP)', l_iva: 'IVA', l_igic: 'IGIC', l_ajd: 'Droit de timbre sur l’acte (AJD)',
    r_flat: '{r} pour cent', r_banded: 'Barème par tranches, {e} pour cent au total',
    total: 'Impôts sur le prix',
    minimum: 'C’est un minimum. L’impôt est calculé sur le plus élevé du prix et de la valeur de référence publiée par le Catastro, consultable avec la référence cadastrale. Si cette valeur est plus élevée, l’impôt l’est aussi.',
    reduced: 'Certains acheteurs bénéficient de taux réduits, mais presque tous exigent qu’il s’agisse de la résidence principale. Ils ne sont pas inclus ici.',
    canarias: 'Les Canaries appliquent l’IGIC au lieu de l’IVA. Les taux réduits ne concernent que la résidence principale, le taux général est donc affiché.',
    g_itp: 'Nos sources ne confirment pas le taux des droits de mutation pour {region}, aucun montant n’est donc affiché. Votre avocat ou gestor peut le confirmer.',
    g_itp_valencia_high: 'Au-delà de €1 000 000, le taux de la Comunitat Valenciana n’est pas confirmé depuis le changement de juin 2026, aucun montant n’est donc affiché.',
    g_vat_ceuta_melilla: 'Ceuta et Melilla n’appliquent pas l’IVA. Leur taxe locale n’est pas couverte ici.',
    g_ajd: 'Nos sources ne confirment pas le droit de timbre sur le neuf pour {region}, il n’est donc pas inclus.',
    other_t: 'Autres frais à prévoir',
    other: ['Frais de notaire, selon le barème officiel', 'Frais d’inscription au registre foncier', 'Un avocat ou une gestoría', 'Une expertise et des frais bancaires en cas de prêt', 'Traductions assermentées et NIE, si nécessaire'],
    other_note: 'Ils ne sont pas estimés ici. Demandez des devis écrits.',
    note: 'Il s’agit d’une estimation fondée sur les règles publiées aux dates indiquées, pas d’un conseil fiscal.',
  },
  nl: {
    title: 'Wat u betaalt bovenop de prijs', for: 'Opgesteld voor {name}',
    intro: 'Belastingen op een {kind} gekocht voor {price} in {region}.',
    k_resale: 'bestaande woning', k_newbuild: 'nieuwbouwwoning van de ontwikkelaar',
    l_itp: 'Overdrachtsbelasting (ITP)', l_iva: 'IVA', l_igic: 'IGIC', l_ajd: 'Zegelrecht op de akte (AJD)',
    r_flat: '{r} procent', r_banded: 'Schijventarief, in totaal {e} procent',
    total: 'Belastingen over de prijs',
    minimum: 'Dit is een minimum. De belasting wordt berekend over het hoogste van de prijs en de referentiewaarde van het Catastro, die met de kadastrale referentie op te vragen is. Is die waarde hoger, dan is de belasting dat ook.',
    reduced: 'Sommige kopers betalen een verlaagd tarief, maar bijna altijd moet het dan om de hoofdverblijfplaats gaan. Die tarieven zijn hier niet meegenomen.',
    canarias: 'Op de Canarische Eilanden geldt IGIC in plaats van IVA. De lagere tarieven gelden alleen voor een hoofdverblijf, dus het algemene tarief staat hier.',
    g_itp: 'Onze bronnen bevestigen het tarief overdrachtsbelasting voor {region} niet, dus er staat geen bedrag. Uw advocaat of gestor kan het bevestigen.',
    g_itp_valencia_high: 'Boven €1.000.000 is het tarief in de Comunitat Valenciana sinds de wijziging van juni 2026 niet bevestigd, dus er staat geen bedrag.',
    g_vat_ceuta_melilla: 'Ceuta en Melilla heffen geen IVA. Hun lokale belasting valt hier buiten.',
    g_ajd: 'Onze bronnen bevestigen het zegelrecht op nieuwbouw in {region} niet, dus het is niet meegenomen.',
    other_t: 'Andere kosten om rekening mee te houden',
    other: ['Notariskosten volgens het officiële tarief', 'Kosten van het kadaster', 'Een advocaat of gestoría', 'Een taxatie en bankkosten bij een hypotheek', 'Beëdigde vertalingen en NIE, indien nodig'],
    other_note: 'Die worden hier niet geschat. Vraag schriftelijke offertes.',
    note: 'Dit is een schatting op basis van de gepubliceerde regels op de getoonde data, geen fiscaal advies.',
  },
};

export function fill(s, v) {
  return String(s).replace(/\{(\w+)\}/g, (_, k) => (v[k] != null ? String(v[k]) : ''));
}
