// Words for the estate agents' hub. Six languages, like every public page on the site.
// Tool card keys: <key>_t title, <key>_d description, <key>_cta link label.
export default {
  en: {
    purchase_costs_t: 'Buying costs by region',
    purchase_costs_d: 'Transfer tax, IVA or IGIC and stamp duty for any region, taxed slice by slice where the region uses bands, with a buyer handout in seven languages.',
    purchase_costs_cta: 'Work out the taxes',
    poa_planner_t: 'Power of attorney planner',
    poa_planner_d: 'For a client who cannot come to sign: consulate or local notary with apostille, the steps in order, the powers to name, and a client letter.',
    poa_planner_cta: 'Plan the power',
    aml_file_t: 'Anti-money-laundering client file',
    aml_file_d: 'Agents are obliged subjects under Spanish anti-money-laundering law. Check scope, see what stops the deal, and print a dated record for the file.',
    aml_file_cta: 'Open a client file',
    eyebrow: 'For estate agents in Spain',
    h1: 'Win the listing. Close the sale. Keep the client.',
    body: 'Free tools for agents who work with international buyers and sellers. The documents carry your name, your clients read them in their own language, and every figure shows the source it comes from.',
    bueno_body: 'These tools are built with Bueno, the platform that looks after Spanish accounts, payments and paperwork for foreign property owners.',
    bueno_referral: 'Using the tools never passes your client to anyone. If you ever want to introduce a client to Bueno, you decide when, and any arrangement is agreed with you in writing first.',
    note: 'Practical guidance for property professionals. Not legal or tax advice.',

    s_win: 'Win the listing',
    s_win_d: 'Walk into the valuation with evidence, and show the seller honestly what they will take home.',
    s_close: 'Close the sale',
    s_close_d: 'Know what is missing before the notary does, and keep an international buyer calm.',
    s_after: 'Look after the client',
    s_after_d: 'Send new owners the tools that keep them right with the Spanish tax office. They will remember who sent them.',

    seller_pack_t: 'Seller meeting pack',
    seller_pack_d: 'Your comparables, the price conversation and your marketing plan in one document with your letterhead, written in the seller’s language.',
    seller_pack_cta: 'Build a pack',
    deal_checklist_t: 'Sale readiness checklist',
    deal_checklist_d: 'Answer a few questions about a live sale. Get the tasks, who owns each one, the dates that follow from completion, and a letter for your client.',
    deal_checklist_cta: 'Build a checklist',
  },
  no: {
    purchase_costs_t: 'Kjøpskostnader per region',
    purchase_costs_d: 'Dokumentavgift, IVA eller IGIC og stempelavgift for alle regioner, trinn for trinn der regionen har trinnskala, med et ark til kjøperen på sju språk.',
    purchase_costs_cta: 'Regn ut skattene',
    poa_planner_t: 'Planlegger for fullmakt',
    poa_planner_d: 'For kunder som ikke kan komme og signere: konsulat eller lokal notar med apostille, stegene i rekkefølge, fullmaktene som bør nevnes og et brev til kunden.',
    poa_planner_cta: 'Planlegg fullmakten',
    aml_file_t: 'Hvitvaskingsmappe for kunden',
    aml_file_d: 'Meglere har plikter etter spansk hvitvaskingslov. Sjekk om saken omfattes, se hva som stopper den, og skriv ut en datert oversikt til mappen.',
    aml_file_cta: 'Åpne en mappe',
    eyebrow: 'For eiendomsmeglere i Spania',
    h1: 'Få oppdraget. Fullfør salget. Behold kunden.',
    body: 'Gratis verktøy for meglere som jobber med internasjonale kjøpere og selgere. Dokumentene bærer ditt navn, kundene leser dem på sitt eget språk, og hvert tall viser kilden det kommer fra.',
    bueno_body: 'Verktøyene er laget sammen med Bueno, plattformen som tar seg av spanske konti, betalinger og papirarbeid for utenlandske boligeiere.',
    bueno_referral: 'Når du bruker verktøyene, gis kunden din aldri videre til noen. Vil du en dag introdusere en kunde for Bueno, bestemmer du når, og en eventuell avtale inngås skriftlig med deg først.',
    note: 'Praktisk veiledning for eiendomsprofesjonelle. Ikke juridisk rådgivning eller skatterådgivning.',

    s_win: 'Få oppdraget',
    s_win_d: 'Møt til verdivurderingen med dokumentasjon, og vis selgeren ærlig hva de sitter igjen med.',
    s_close: 'Fullfør salget',
    s_close_d: 'Vit hva som mangler før notaren gjør det, og hold en internasjonal kjøper rolig.',
    s_after: 'Ta vare på kunden',
    s_after_d: 'Send nye eiere verktøyene som holder dem på rett side av det spanske skattekontoret. De husker hvem som sendte dem.',

    seller_pack_t: 'Selgermøtepakke',
    seller_pack_d: 'Sammenlignbare boliger, prissamtalen og markedsføringsplanen din i ett dokument med ditt brevhode, skrevet på selgerens språk.',
    seller_pack_cta: 'Lag en pakke',
    deal_checklist_t: 'Sjekkliste for salget',
    deal_checklist_d: 'Svar på noen spørsmål om et pågående salg. Få oppgavene, hvem som eier hver av dem, datoene som følger av overtakelsen og et brev til kunden.',
    deal_checklist_cta: 'Lag en sjekkliste',
  },
  sv: {
    purchase_costs_t: 'Köpkostnader per region',
    purchase_costs_d: 'Överlåtelseskatt, IVA eller IGIC och stämpelskatt för alla regioner, steg för steg där regionen har trappsteg, med ett blad till köparen på sju språk.',
    purchase_costs_cta: 'Räkna ut skatterna',
    poa_planner_t: 'Planerare för fullmakt',
    poa_planner_d: 'För kunder som inte kan komma och skriva under: konsulat eller lokal notarie med apostille, stegen i ordning, befogenheterna att nämna och ett brev till kunden.',
    poa_planner_cta: 'Planera fullmakten',
    aml_file_t: 'Penningtvättsakt för kunden',
    aml_file_d: 'Mäklare har skyldigheter enligt spansk penningtvättslag. Kontrollera om affären omfattas, se vad som stoppar den och skriv ut en daterad dokumentation.',
    aml_file_cta: 'Öppna en akt',
    eyebrow: 'För fastighetsmäklare i Spanien',
    h1: 'Vinn uppdraget. Slutför affären. Behåll kunden.',
    body: 'Gratis verktyg för mäklare som arbetar med internationella köpare och säljare. Dokumenten bär ditt namn, kunderna läser dem på sitt eget språk och varje siffra visar källan den kommer från.',
    bueno_body: 'Verktygen är byggda tillsammans med Bueno, plattformen som sköter spanska konton, betalningar och pappersarbete för utländska fastighetsägare.',
    bueno_referral: 'När du använder verktygen lämnas din kund aldrig vidare till någon. Vill du någon gång presentera en kund för Bueno bestämmer du när, och en eventuell överenskommelse görs skriftligt med dig först.',
    note: 'Praktisk vägledning för fastighetsproffs. Inte juridisk rådgivning eller skatterådgivning.',

    s_win: 'Vinn uppdraget',
    s_win_d: 'Kom till värderingen med underlag och visa säljaren ärligt vad de får behålla.',
    s_close: 'Slutför affären',
    s_close_d: 'Vet vad som saknas innan notarien gör det och håll en internationell köpare lugn.',
    s_after: 'Ta hand om kunden',
    s_after_d: 'Skicka nya ägare verktygen som håller dem på rätt sida om den spanska skattemyndigheten. De minns vem som skickade dem.',

    seller_pack_t: 'Säljarmötespaket',
    seller_pack_d: 'Jämförbara objekt, prissamtalet och din marknadsplan i ett dokument med ditt brevhuvud, skrivet på säljarens språk.',
    seller_pack_cta: 'Skapa ett paket',
    deal_checklist_t: 'Checklista inför tillträdet',
    deal_checklist_d: 'Svara på några frågor om en pågående affär. Få uppgifterna, vem som äger varje uppgift, datumen som följer av tillträdet och ett brev till kunden.',
    deal_checklist_cta: 'Skapa en checklista',
  },
  de: {
    purchase_costs_t: 'Kaufnebenkosten nach Region',
    purchase_costs_d: 'Grunderwerbsteuer, IVA oder IGIC und Urkundensteuer für jede Region, bei Stufentarifen Stufe für Stufe berechnet, mit einem Käufer-Merkblatt in sieben Sprachen.',
    purchase_costs_cta: 'Steuern berechnen',
    poa_planner_t: 'Vollmacht-Planer',
    poa_planner_d: 'Für Kunden, die nicht zur Unterschrift kommen können: Konsulat oder örtlicher Notar mit Apostille, die Schritte in Reihenfolge, die Befugnisse und ein Kundenbrief.',
    poa_planner_cta: 'Vollmacht planen',
    aml_file_t: 'Geldwäsche-Akte zum Kunden',
    aml_file_d: 'Makler sind nach spanischem Geldwäscherecht Verpflichtete. Anwendbarkeit prüfen, Hindernisse erkennen und eine datierte Dokumentation für die Akte drucken.',
    aml_file_cta: 'Akte anlegen',
    eyebrow: 'Für Immobilienmakler in Spanien',
    h1: 'Den Auftrag gewinnen. Den Verkauf abschließen. Den Kunden halten.',
    body: 'Kostenlose Tools für Makler, die mit internationalen Käufern und Verkäufern arbeiten. Die Dokumente tragen Ihren Namen, Ihre Kunden lesen sie in ihrer eigenen Sprache, und jede Zahl zeigt ihre Quelle.',
    bueno_body: 'Die Tools entstehen zusammen mit Bueno, der Plattform, die spanische Konten, Zahlungen und Formalitäten für ausländische Eigentümer übernimmt.',
    bueno_referral: 'Die Nutzung der Tools gibt Ihren Kunden an niemanden weiter. Wenn Sie einen Kunden an Bueno vermitteln möchten, entscheiden Sie wann, und jede Vereinbarung wird vorher schriftlich mit Ihnen getroffen.',
    note: 'Praktische Orientierung für Immobilienprofis. Keine Rechts- oder Steuerberatung.',

    s_win: 'Den Auftrag gewinnen',
    s_win_d: 'Gehen Sie mit Belegen in die Bewertung und zeigen Sie dem Verkäufer ehrlich, was ihm bleibt.',
    s_close: 'Den Verkauf abschließen',
    s_close_d: 'Wissen, was fehlt, bevor der Notar es merkt, und einen internationalen Käufer beruhigen.',
    s_after: 'Den Kunden betreuen',
    s_after_d: 'Senden Sie neuen Eigentümern die Tools, mit denen sie beim spanischen Finanzamt auf der sicheren Seite bleiben. Sie werden sich erinnern, von wem sie kamen.',

    seller_pack_t: 'Unterlagen für das Verkäufergespräch',
    seller_pack_d: 'Vergleichsobjekte, das Preisgespräch und Ihr Vermarktungsplan in einem Dokument mit Ihrem Briefkopf, in der Sprache des Verkäufers.',
    seller_pack_cta: 'Unterlagen erstellen',
    deal_checklist_t: 'Checkliste bis zur Beurkundung',
    deal_checklist_d: 'Beantworten Sie einige Fragen zu einem laufenden Verkauf. Sie erhalten die Aufgaben, die Zuständigkeiten, die Fristen ab der Beurkundung und einen Brief an Ihren Kunden.',
    deal_checklist_cta: 'Checkliste erstellen',
  },
  fr: {
    purchase_costs_t: 'Frais d’achat par région',
    purchase_costs_d: 'Droits de mutation, IVA ou IGIC et droit de timbre pour chaque région, calculés tranche par tranche si la région applique un barème, avec une fiche acheteur en sept langues.',
    purchase_costs_cta: 'Calculer les impôts',
    poa_planner_t: 'Planificateur de procuration',
    poa_planner_d: 'Pour le client qui ne peut pas venir signer : consulat ou notaire local avec apostille, les étapes dans l’ordre, les pouvoirs à citer et une lettre au client.',
    poa_planner_cta: 'Préparer la procuration',
    aml_file_t: 'Dossier anti-blanchiment du client',
    aml_file_d: 'Les agents sont assujettis à la loi espagnole contre le blanchiment. Vérifiez le champ, voyez ce qui bloque l’opération et imprimez un registre daté.',
    aml_file_cta: 'Ouvrir un dossier',
    eyebrow: 'Pour les agents immobiliers en Espagne',
    h1: 'Décrocher le mandat. Conclure la vente. Garder le client.',
    body: 'Des outils gratuits pour les agents qui travaillent avec des acheteurs et vendeurs internationaux. Les documents portent votre nom, vos clients les lisent dans leur langue et chaque chiffre indique sa source.',
    bueno_body: 'Ces outils sont conçus avec Bueno, la plateforme qui prend en charge les comptes, les paiements et les démarches espagnoles des propriétaires étrangers.',
    bueno_referral: "Utiliser ces outils ne transmet jamais votre client à qui que ce soit. Si vous souhaitez un jour présenter un client à Bueno, c'est vous qui décidez du moment, et tout accord est d'abord conclu par écrit avec vous.",
    note: 'Repères pratiques pour les professionnels de l’immobilier. Pas un conseil juridique ou fiscal.',

    s_win: 'Décrocher le mandat',
    s_win_d: "Arrivez à l'estimation avec des preuves, et montrez honnêtement au vendeur ce qu'il touchera.",
    s_close: 'Conclure la vente',
    s_close_d: 'Savoir ce qui manque avant le notaire, et rassurer un acheteur étranger.',
    s_after: 'Accompagner le client',
    s_after_d: "Envoyez aux nouveaux propriétaires les outils qui les gardent en règle avec l'administration fiscale espagnole. Ils se souviendront de vous.",

    seller_pack_t: 'Dossier pour le rendez-vous vendeur',
    seller_pack_d: 'Vos comparables, la discussion sur le prix et votre plan de commercialisation dans un seul document à votre en-tête, rédigé dans la langue du vendeur.',
    seller_pack_cta: 'Créer un dossier',
    deal_checklist_t: 'Check-list avant la signature',
    deal_checklist_d: "Répondez à quelques questions sur une vente en cours. Obtenez les tâches, le responsable de chacune, les dates qui découlent de la signature et une lettre pour votre client.",
    deal_checklist_cta: 'Créer une check-list',
  },
  nl: {
    purchase_costs_t: 'Aankoopkosten per regio',
    purchase_costs_d: 'Overdrachtsbelasting, IVA of IGIC en zegelrecht voor elke regio, per schijf berekend waar de regio schijven heeft, met een overzicht voor de koper in zeven talen.',
    purchase_costs_cta: 'Bereken de belastingen',
    poa_planner_t: 'Planner voor een volmacht',
    poa_planner_d: 'Voor een klant die niet kan komen tekenen: consulaat of lokale notaris met apostille, de stappen op volgorde, de bevoegdheden en een brief aan de klant.',
    poa_planner_cta: 'Volmacht plannen',
    aml_file_t: 'Witwasdossier van de klant',
    aml_file_d: 'Makelaars hebben verplichtingen onder de Spaanse witwaswet. Controleer of de transactie eronder valt, zie wat haar tegenhoudt en druk een gedateerde vastlegging af.',
    aml_file_cta: 'Dossier openen',
    eyebrow: 'Voor makelaars in Spanje',
    h1: 'De opdracht winnen. De verkoop afronden. De klant houden.',
    body: 'Gratis tools voor makelaars die met internationale kopers en verkopers werken. De documenten dragen uw naam, uw klanten lezen ze in hun eigen taal en elk bedrag toont de bron waar het vandaan komt.',
    bueno_body: 'Deze tools zijn gebouwd met Bueno, het platform dat Spaanse rekeningen, betalingen en papierwerk regelt voor buitenlandse eigenaren.',
    bueno_referral: 'Het gebruik van de tools draagt uw klant nooit aan iemand over. Wilt u ooit een klant aan Bueno voorstellen, dan bepaalt u wanneer, en elke afspraak wordt eerst schriftelijk met u gemaakt.',
    note: 'Praktische informatie voor vastgoedprofessionals. Geen juridisch of fiscaal advies.',

    s_win: 'De opdracht winnen',
    s_win_d: 'Kom met onderbouwing naar de waardebepaling en laat de verkoper eerlijk zien wat er overblijft.',
    s_close: 'De verkoop afronden',
    s_close_d: 'Weet wat er ontbreekt voordat de notaris het ziet, en houd een internationale koper gerust.',
    s_after: 'Zorg voor de klant',
    s_after_d: 'Stuur nieuwe eigenaren de tools die hen goed houden met de Spaanse Belastingdienst. Ze onthouden wie ze stuurde.',

    seller_pack_t: 'Map voor het verkoopgesprek',
    seller_pack_d: 'Uw vergelijkbare woningen, het prijsgesprek en uw marketingplan in één document met uw briefhoofd, in de taal van de verkoper.',
    seller_pack_cta: 'Map maken',
    deal_checklist_t: 'Checklist tot de overdracht',
    deal_checklist_d: 'Beantwoord een paar vragen over een lopende verkoop. U krijgt de taken, wie waarvoor verantwoordelijk is, de data die uit de overdracht volgen en een brief voor uw klant.',
    deal_checklist_cta: 'Checklist maken',
  },
};
