// Screen text for the seller meeting pack, in the site's six languages. Labels that also
// appear in the printed pack (property types, marketing items, statuses) are read from
// PACK in pack.js so the form and the document always use the same words.
export default {
  en: {
    title: 'Seller meeting pack', note: 'Practical guidance for property professionals. Not legal or tax advice.',
    eyebrow: 'For estate agents', headline: 'Walk into the valuation with a pack the seller keeps',
    body: 'Enter the property, your comparables and your plan. You get a clean document with your letterhead, written in the seller’s language, that shows the evidence honestly and says what it cannot prove.',
    points: ['Asking and sold prices are kept apart, never averaged together', 'Seven languages, including Spanish', 'Nothing you type leaves this browser'],
    cta: 'Start a pack', minutes: 'About five minutes',
    sec_seller: 'The seller and the meeting', f_seller: 'Seller’s name', f_meeting: 'Meeting date',
    f_packlang: 'Pack language', f_packlang_hint: 'The language the seller reads most comfortably.',
    f_residency: 'Is the seller tax resident in Spain?', res_yes: 'Yes', res_no: 'No', res_unsure: 'Not sure',
    sec_property: 'The property', f_address: 'Address or area', f_type: 'Type', f_area: 'Built area in m²', f_beds: 'Bedrooms', f_baths: 'Bathrooms', f_plot: 'Plot in m², if any',
    sec_price: 'Price', f_hoped: 'Price the seller has in mind', f_low: 'Your recommended range, from', f_high: 'Up to',
    f_reason: 'Your reasoning', f_reason_hint: 'A few sentences, printed as your note in the pack. Write it in the pack language.',
    sec_comps: 'Comparables', comps_hint: 'Homes you know nearby. Mark each as for sale or sold. Only use sold prices from your own records or a source you are allowed to share.',
    c_label: 'Home', c_status: 'Status', c_price: 'Price', c_area: 'm²', c_note: 'Note', add_comp: 'Add a comparable', remove: 'Remove',
    sec_plan: 'Marketing and review', f_marketing: 'What you will do', f_review: 'Review the price after', weeks: '{n} weeks',
    build: 'Build the pack', edit: 'Edit the details', print: 'Print or save as PDF',
    need: 'Add the property’s built area and at least one price to build the pack.',
    no_profile: 'Add your details on the agents page and your letterhead will appear at the top of the pack.',
  },
  no: {
    title: 'Selgermøtepakke', note: 'Praktisk veiledning for eiendomsprofesjonelle. Ikke juridisk rådgivning eller skatterådgivning.',
    eyebrow: 'For eiendomsmeglere', headline: 'Kom til verdivurderingen med en pakke selgeren beholder',
    body: 'Legg inn boligen, de sammenlignbare boligene og planen din. Du får et ryddig dokument med ditt brevhode, på selgerens språk, som viser tallene ærlig og sier hva de ikke kan bevise.',
    points: ['Prisantydning og salgspris holdes adskilt og blandes aldri i ett snitt', 'Sju språk, også spansk', 'Ingenting du skriver forlater denne nettleseren'],
    cta: 'Lag en pakke', minutes: 'Omtrent fem minutter',
    sec_seller: 'Selgeren og møtet', f_seller: 'Selgerens navn', f_meeting: 'Møtedato',
    f_packlang: 'Språk for pakken', f_packlang_hint: 'Språket selgeren leser best.',
    f_residency: 'Er selgeren skattemessig bosatt i Spania?', res_yes: 'Ja', res_no: 'Nei', res_unsure: 'Usikker',
    sec_property: 'Boligen', f_address: 'Adresse eller område', f_type: 'Type', f_area: 'Bebygd areal i m²', f_beds: 'Soverom', f_baths: 'Bad', f_plot: 'Tomt i m², hvis aktuelt',
    sec_price: 'Pris', f_hoped: 'Prisen selgeren ser for seg', f_low: 'Anbefalt prisspenn, fra', f_high: 'Opptil',
    f_reason: 'Din begrunnelse', f_reason_hint: 'Noen setninger som skrives ut som din merknad i pakken. Skriv på pakkens språk.',
    sec_comps: 'Sammenlignbare boliger', comps_hint: 'Boliger du kjenner i nærheten. Merk hver som til salgs eller solgt. Bruk bare salgspriser fra egne registre eller en kilde du har lov til å dele.',
    c_label: 'Bolig', c_status: 'Status', c_price: 'Pris', c_area: 'm²', c_note: 'Merknad', add_comp: 'Legg til en bolig', remove: 'Fjern',
    sec_plan: 'Markedsføring og evaluering', f_marketing: 'Dette gjør du', f_review: 'Vurder prisen etter', weeks: '{n} uker',
    build: 'Lag pakken', edit: 'Endre detaljene', print: 'Skriv ut eller lagre som PDF',
    need: 'Legg inn boligens bebygde areal og minst én pris for å lage pakken.',
    no_profile: 'Legg inn detaljene dine på meglersiden, så vises brevhodet ditt øverst i pakken.',
  },
  sv: {
    title: 'Säljarmötespaket', note: 'Praktisk vägledning för fastighetsproffs. Inte juridisk rådgivning eller skatterådgivning.',
    eyebrow: 'För fastighetsmäklare', headline: 'Kom till värderingen med ett paket som säljaren behåller',
    body: 'Fyll i bostaden, dina jämförbara objekt och din plan. Du får ett stilrent dokument med ditt brevhuvud, på säljarens språk, som visar underlaget ärligt och säger vad det inte kan bevisa.',
    points: ['Utgångspriser och försäljningspriser hålls isär och blandas aldrig i ett snitt', 'Sju språk, även spanska', 'Inget du skriver lämnar den här webbläsaren'],
    cta: 'Skapa ett paket', minutes: 'Ungefär fem minuter',
    sec_seller: 'Säljaren och mötet', f_seller: 'Säljarens namn', f_meeting: 'Mötesdatum',
    f_packlang: 'Paketets språk', f_packlang_hint: 'Det språk säljaren läser bäst.',
    f_residency: 'Har säljaren skatterättslig hemvist i Spanien?', res_yes: 'Ja', res_no: 'Nej', res_unsure: 'Osäker',
    sec_property: 'Bostaden', f_address: 'Adress eller område', f_type: 'Typ', f_area: 'Boarea i m²', f_beds: 'Sovrum', f_baths: 'Badrum', f_plot: 'Tomt i m², om det finns',
    sec_price: 'Pris', f_hoped: 'Priset säljaren har i tankarna', f_low: 'Ditt rekommenderade prisspann, från', f_high: 'Upp till',
    f_reason: 'Din motivering', f_reason_hint: 'Några meningar som skrivs ut som din anteckning i paketet. Skriv på paketets språk.',
    sec_comps: 'Jämförbara objekt', comps_hint: 'Bostäder du känner till i närheten. Markera var och en som till salu eller såld. Använd bara försäljningspriser från egna register eller en källa du får dela.',
    c_label: 'Bostad', c_status: 'Status', c_price: 'Pris', c_area: 'm²', c_note: 'Anteckning', add_comp: 'Lägg till ett objekt', remove: 'Ta bort',
    sec_plan: 'Marknadsföring och uppföljning', f_marketing: 'Det här gör du', f_review: 'Se över priset efter', weeks: '{n} veckor',
    build: 'Skapa paketet', edit: 'Ändra uppgifterna', print: 'Skriv ut eller spara som PDF',
    need: 'Fyll i bostadens boarea och minst ett pris för att skapa paketet.',
    no_profile: 'Lägg till dina uppgifter på mäklarsidan så visas ditt brevhuvud överst i paketet.',
  },
  de: {
    title: 'Unterlagen für das Verkäufergespräch', note: 'Praktische Orientierung für Immobilienprofis. Keine Rechts- oder Steuerberatung.',
    eyebrow: 'Für Immobilienmakler', headline: 'Zur Bewertung mit Unterlagen, die der Verkäufer behält',
    body: 'Erfassen Sie die Immobilie, Ihre Vergleichsobjekte und Ihren Plan. Sie erhalten ein klares Dokument mit Ihrem Briefkopf in der Sprache des Verkäufers, das die Zahlen ehrlich zeigt und sagt, was sie nicht belegen können.',
    points: ['Angebots- und Verkaufspreise werden getrennt und nie gemittelt', 'Sieben Sprachen, auch Spanisch', 'Nichts, was Sie eingeben, verlässt diesen Browser'],
    cta: 'Unterlagen erstellen', minutes: 'Etwa fünf Minuten',
    sec_seller: 'Verkäufer und Termin', f_seller: 'Name des Verkäufers', f_meeting: 'Termin',
    f_packlang: 'Sprache der Unterlagen', f_packlang_hint: 'Die Sprache, die der Verkäufer am besten liest.',
    f_residency: 'Ist der Verkäufer in Spanien steuerlich ansässig?', res_yes: 'Ja', res_no: 'Nein', res_unsure: 'Unklar',
    sec_property: 'Die Immobilie', f_address: 'Adresse oder Lage', f_type: 'Art', f_area: 'Wohnfläche in m²', f_beds: 'Schlafzimmer', f_baths: 'Bäder', f_plot: 'Grundstück in m², falls vorhanden',
    sec_price: 'Preis', f_hoped: 'Wunschpreis des Verkäufers', f_low: 'Ihre empfohlene Spanne, ab', f_high: 'Bis',
    f_reason: 'Ihre Begründung', f_reason_hint: 'Einige Sätze, die als Ihre Anmerkung gedruckt werden. Bitte in der Sprache der Unterlagen schreiben.',
    sec_comps: 'Vergleichsobjekte', comps_hint: 'Objekte in der Nähe, die Sie kennen. Markieren Sie jedes als im Angebot oder verkauft. Verwenden Sie Verkaufspreise nur aus eigenen Unterlagen oder aus einer Quelle, die Sie weitergeben dürfen.',
    c_label: 'Objekt', c_status: 'Status', c_price: 'Preis', c_area: 'm²', c_note: 'Anmerkung', add_comp: 'Vergleichsobjekt hinzufügen', remove: 'Entfernen',
    sec_plan: 'Vermarktung und Überprüfung', f_marketing: 'Das werden Sie tun', f_review: 'Preis überprüfen nach', weeks: '{n} Wochen',
    build: 'Unterlagen erstellen', edit: 'Angaben ändern', print: 'Drucken oder als PDF speichern',
    need: 'Erfassen Sie die Wohnfläche und mindestens einen Preis, um die Unterlagen zu erstellen.',
    no_profile: 'Hinterlegen Sie Ihre Angaben auf der Maklerseite, dann erscheint Ihr Briefkopf oben auf den Unterlagen.',
  },
  fr: {
    title: 'Dossier pour le rendez-vous vendeur', note: 'Repères pratiques pour les professionnels de l’immobilier. Pas un conseil juridique ou fiscal.',
    eyebrow: 'Pour les agents immobiliers', headline: 'Arrivez à l’estimation avec un dossier que le vendeur garde',
    body: 'Saisissez le bien, vos comparables et votre plan. Vous obtenez un document soigné à votre en-tête, dans la langue du vendeur, qui présente les chiffres honnêtement et dit ce qu’ils ne prouvent pas.',
    points: ['Prix affichés et prix de vente restent séparés, jamais mélangés dans une moyenne', 'Sept langues, dont l’espagnol', 'Rien de ce que vous saisissez ne quitte ce navigateur'],
    cta: 'Créer un dossier', minutes: 'Environ cinq minutes',
    sec_seller: 'Le vendeur et le rendez-vous', f_seller: 'Nom du vendeur', f_meeting: 'Date du rendez-vous',
    f_packlang: 'Langue du dossier', f_packlang_hint: 'La langue que le vendeur lit le plus facilement.',
    f_residency: 'Le vendeur est-il résident fiscal en Espagne ?', res_yes: 'Oui', res_no: 'Non', res_unsure: 'Pas sûr',
    sec_property: 'Le bien', f_address: 'Adresse ou secteur', f_type: 'Type', f_area: 'Surface construite en m²', f_beds: 'Chambres', f_baths: 'Salles de bains', f_plot: 'Terrain en m², le cas échéant',
    sec_price: 'Prix', f_hoped: 'Prix envisagé par le vendeur', f_low: 'Votre fourchette recommandée, de', f_high: 'À',
    f_reason: 'Votre argumentaire', f_reason_hint: 'Quelques phrases imprimées comme votre remarque dans le dossier. Rédigez-les dans la langue du dossier.',
    sec_comps: 'Biens comparables', comps_hint: 'Des biens proches que vous connaissez. Indiquez pour chacun s’il est en vente ou vendu. N’utilisez des prix de vente que s’ils viennent de vos propres dossiers ou d’une source que vous pouvez partager.',
    c_label: 'Bien', c_status: 'Statut', c_price: 'Prix', c_area: 'm²', c_note: 'Remarque', add_comp: 'Ajouter un comparable', remove: 'Retirer',
    sec_plan: 'Commercialisation et suivi', f_marketing: 'Ce que vous ferez', f_review: 'Revoir le prix après', weeks: '{n} semaines',
    build: 'Créer le dossier', edit: 'Modifier les informations', print: 'Imprimer ou enregistrer en PDF',
    need: 'Indiquez la surface construite et au moins un prix pour créer le dossier.',
    no_profile: 'Ajoutez vos coordonnées sur la page des agents et votre en-tête apparaîtra en haut du dossier.',
  },
  nl: {
    title: 'Map voor het verkoopgesprek', note: 'Praktische informatie voor vastgoedprofessionals. Geen juridisch of fiscaal advies.',
    eyebrow: 'Voor makelaars', headline: 'Kom naar de waardebepaling met een map die de verkoper houdt',
    body: 'Vul de woning, uw vergelijkbare woningen en uw plan in. U krijgt een verzorgd document met uw briefhoofd, in de taal van de verkoper, dat de cijfers eerlijk toont en zegt wat ze niet kunnen bewijzen.',
    points: ['Vraagprijzen en verkoopprijzen blijven gescheiden en worden nooit samen gemiddeld', 'Zeven talen, ook Spaans', 'Niets van wat u invult verlaat deze browser'],
    cta: 'Map maken', minutes: 'Ongeveer vijf minuten',
    sec_seller: 'De verkoper en het gesprek', f_seller: 'Naam van de verkoper', f_meeting: 'Datum van het gesprek',
    f_packlang: 'Taal van de map', f_packlang_hint: 'De taal die de verkoper het prettigst leest.',
    f_residency: 'Woont de verkoper fiscaal in Spanje?', res_yes: 'Ja', res_no: 'Nee', res_unsure: 'Weet niet',
    sec_property: 'De woning', f_address: 'Adres of gebied', f_type: 'Type', f_area: 'Woonoppervlak in m²', f_beds: 'Slaapkamers', f_baths: 'Badkamers', f_plot: 'Perceel in m², indien van toepassing',
    sec_price: 'Prijs', f_hoped: 'Prijs die de verkoper voor ogen heeft', f_low: 'Uw geadviseerde bandbreedte, vanaf', f_high: 'Tot',
    f_reason: 'Uw onderbouwing', f_reason_hint: 'Een paar zinnen die als uw opmerking in de map worden afgedrukt. Schrijf ze in de taal van de map.',
    sec_comps: 'Vergelijkbare woningen', comps_hint: 'Woningen in de buurt die u kent. Markeer elke woning als te koop of verkocht. Gebruik verkoopprijzen alleen uit uw eigen administratie of een bron die u mag delen.',
    c_label: 'Woning', c_status: 'Status', c_price: 'Prijs', c_area: 'm²', c_note: 'Opmerking', add_comp: 'Woning toevoegen', remove: 'Verwijderen',
    sec_plan: 'Marketing en evaluatie', f_marketing: 'Wat u gaat doen', f_review: 'Prijs evalueren na', weeks: '{n} weken',
    build: 'Map maken', edit: 'Gegevens wijzigen', print: 'Afdrukken of als pdf opslaan',
    need: 'Vul het woonoppervlak en minstens één prijs in om de map te maken.',
    no_profile: 'Vul uw gegevens in op de makelaarspagina, dan staat uw briefhoofd bovenaan de map.',
  },
};
