// The agents stream: 30 English masters, as approved.
// Regenerated 18 September 2026 from the live table, which is where the September content
// pass and the reviewers' edits landed. The table and this file now say the same thing, so
// /api/linkedin-refresh is a no-op on text and the nine re-pointed partner slugs are
// re-pointed no more: the post under each slug here is the post the deck reviewed.
//
// post_text carries the call to action already, because the deck has to show exactly what
// the team is sent. image_url is null on purpose: the photograph is resolved per post by
// api/_lk_images.js, which returns the text-free Bueno frame in public/posts.
export default [
 {
  "slug": "ag_epc_advertising",
  "batch": 1,
  "day": 1,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "EPC fines start at the advert",
  "source_slug": "epc_certificates_en",
  "source_slug2": "lost_documents_en",
  "source_article": "epc.txt, lost-documents.txt",
  "post_text": "The energy certificate is not end of process paperwork. It has to exist before the property is listed.\n\nMarket a property without one and the fine follows. Enforcement is devolved, so the band depends on your region, and it is worth asking your regional energy office what theirs is. I no longer quote a national range, because the bands circulating online have no primary source behind them.\n\nThe certificate lasts ten years, or five if the rating comes back G, and must be registered with the regional authority. A large share of older coastal stock rates E, F or G, so check the letter and the date before you promise a buyer anything.\n\nA copy goes into the notarial deed when it sells. Holiday and non-residential properties need one too.\n\nOrder it at the instruction, not at the offer.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_nota_simple_twice",
  "batch": 1,
  "day": 2,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The Nota Simple does not size the loan",
  "source_slug": "nota_simple_en",
  "source_slug2": "land_registry_en",
  "source_article": "nota-simple.txt, land-registry.txt",
  "post_text": "The Nota Simple is the first document on the file. It is not the document that sizes the mortgage.\n\nBanks size the loan on the tasacion, the bank's own appraisal, not on the price and not on the cadastral value. Order the appraisal early, because that number is what the offer has to survive. The cadastral value does not appear on the Nota Simple in any case. That extract comes from the Land Registry, not from the Catastro.\n\nWhat the page does give you is the registered owner, the IDUFIR, the legal description and the charges. Mortgages, unpaid taxes, debts. In Spain those debts sit on the property, so your buyer inherits whatever that page reveals.\n\nIt costs around 10 euros online and can arrive the same day, or under 4 euros in person. Any party to a live transaction has the legitimate interest needed to order one.\n\nTen euros of reading before 10 percent changes hands.\n\nOrder it for every serious buyer before the arras is drafted.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_arras_window",
  "batch": 1,
  "day": 3,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The arras amendment window",
  "source_slug": "arras_contract_en",
  "source_article": "property-contracts.txt",
  "post_text": "The arras contract is where a Spanish purchase becomes real. It is also the last easy moment to change anything.\n\nOnce signed, a buyer who withdraws loses the 10 percent deposit, and a seller who withdraws pays double. So the amendment window is before signature, not after.\n\nFour things to settle in that window. Check the property description against the Nota Simple, word for word. Fix the completion date, usually two to three months out, and say what happens if it slips. Get the inclusions in writing, furniture, appliances, the mooring, the parking space. And make sure the deposit sits in a safeguarded account at a financial institution rather than in anybody's current account.\n\nOn a new build, add a look at the bank guarantee standing behind the staged payments.\n\nRead the clause with your buyer before they sign it, not after.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_offer_accepted",
  "batch": 1,
  "day": 4,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "An accepted offer binds nobody",
  "source_slug": "offer_accepted_en",
  "source_article": "offer-accepted.txt",
  "post_text": "An accepted offer in Spain binds nobody. That is the single most useful thing to tell a foreign buyer in week one.\n\nWhat follows the handshake is a sequence. A reservation takes the property off the market and transfers 1,000 to 2,000 euros. The arras contract is the binding step. Ten percent of the price changes hands, and from there withdrawal has a price on both sides. Pull out as seller and you repay double.\n\nThen the escritura at the notary, where the balance moves and the keys change hands. Registration and the utility transfers come after, and somebody has to own them. A power of attorney solves the attendance problem for a buyer who cannot fly in.\n\nFrom deposit to keys usually takes six to ten weeks.\n\nWalk your buyer through the sequence at the first viewing, not at the offer.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_partner_week_after_keys",
  "batch": 1,
  "day": 5,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The week after the keys",
  "post_text": "The week after the keys is where your referral either forms or quietly disappears.\n\nYour buyer has a Spanish home and no Spanish admin. Utilities in the wrong name. A first IBI bill they cannot read. A direct debit that will not set up. None of it is your job, and all of it lands in your inbox anyway.\n\nThat is the gap Bueno sits in. An account, property tools, energy switching, Modelo 210 filing, insurance, and human support in the client's own language. Bueno is licensed by the Bank of Spain via SEFIDE EDE S.L.U.\n\nIt means you can answer the week after the keys with a handover rather than an apology.\n\nIf you want to see how the partner side works, my inbox is open.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null,
  "source_article": "month-by-month-checklist.txt"
 },
 {
  "slug": "ag_tourist_licence_first",
  "batch": 1,
  "day": 6,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Licence first, yield second",
  "source_slug": "tourist_license_en",
  "source_article": "legally-renting.txt",
  "post_text": "Yield is the second question. The licence is the first, and since 3 April 2025 it is not even the hardest gate.\n\nWhat makes your buyer a tourist landlord is not the length of the let. It is marketing the whole furnished home through tourist channels, which pulls it into the regional tourism regime. A genuine seasonal let is a different contract with different rules.\n\nBefore the region, the community. A three fifths majority of owners who also represent three fifths of the participation quotas is now needed to approve a new tourist let, not only to limit or prohibit one. The same majority can load the letting flat with up to 20 percent more of the common expenses, which comes straight off the return.\n\nFines are regional. In the Balearics a serious infraction runs 4,001 to 40,000 euros and a very serious one 40,001 to 400,000. Elsewhere, check the region's own tourism law before quoting a number.\n\nIn Barcelona, short term lets of private rooms are not allowed and licences for entire homes are hard to come by. Valencia is generally only granting them to ground floor properties in popular areas. Approval takes one to six months.\n\nRead the community minutes before you quote a yield.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_seller_debt_certificate",
  "batch": 1,
  "day": 7,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Community debt comes off the price",
  "source_slug": "community_fees_en",
  "source_slug2": "hoa_disagree_vote_en",
  "source_article": "community-fees.txt",
  "post_text": "Community fees are not a service charge footnote. On a resale they are a price negotiation.\n\nSome owners pay around 100 euros a quarter, while high end developments with pools, security and a gym can run past 1,000. A bigger share of the quotas also means more voting weight at the annual general meeting, which matters to any buyer thinking about letting.\n\nThe part that moves the price is the arrears. Unpaid fees do not always leave with the seller, they can follow the keys, and unchecked community debts may become the new owner's liability. The escalation ladder runs from interest to a court demand to a forced auction, so nobody treats it as soft debt.\n\nThe lawyer's job during the purchase is to confirm nothing is outstanding. And if the plan is to let, the fees stay the owner's responsibility, never the tenant's.\n\nAsk for the administrator's debt position on every resale file, before the arras.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_3pct_withholding",
  "batch": 1,
  "day": 8,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The 3 percent withholding",
  "source_slug": "plusvalia_en",
  "source_article": "plusvalia.txt",
  "post_text": "A non-resident seller does not receive the full price at the notary, and it helps if they hear that from you rather than on the day.\n\nThe buyer holds back 3 percent of the purchase price and pays it to the tax authorities within one month of the sale, on modelo 211. It is a holding against the seller's capital gains bill, which is 19 percent of the profit for every non-resident, whatever their country. The 19 and 24 split belongs to rental and imputed income, not to the gain.\n\nIf the 3 percent exceeds the real tax, the seller reclaims the difference on a refund return, which can be filed from 1 February and stays open for four years.\n\nThen plusvalia, the municipal tax on the increase in land value. The window is 30 working days from the date of the public deed. Saturdays, Sundays and holidays do not count, and August does. The council can pursue the buyer where the seller is non-resident, so buyers routinely retain the estimated plusvalia from the price at completion, on top of the 3 percent. A non-resident seller should expect both deductions at the notary.\n\nTwo methods exist, the objective one on the cadastral land value and the real gain, and the taxpayer may elect the lower. Coefficients stop rising at 20 years. If the land value genuinely fell, no tax is due, but the transfer is still declared with both deeds attached.\n\nSay all of this at the valuation, not at completion.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_law5768_guarantee",
  "batch": 1,
  "day": 9,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Law 57/68 off plan guarantees",
  "source_slug": "bank_guarantee_en",
  "source_slug2": "arras_contract_en",
  "source_article": "bank-guarantees.txt, property-contracts.txt",
  "post_text": "Off plan buyers hand over money for something that does not exist yet. The protection for that is worth knowing in detail, because it is the question a careful foreign buyer asks first.\n\nOff-plan buyers in Spain are protected by a statutory guarantee regime that refunds staged payments with interest if the build is not delivered. Ask the developer to produce the guarantee and the dedicated account before the first instalment moves.\n\nTwo documents, then. A dedicated account for buyer payments, separate from the developer's own money. And a guarantee that covers the refund of every payment plus interest if the home is never delivered.\n\nI am deliberately not citing a statute number here. The regime has moved through several instruments and the safe version of this post is the obligation, not the citation. Your buyer's lawyer will name the instrument in the file.\n\nAsk for both documents in writing before the first instalment moves.\n\n#SpanishProperty #NewBuild #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_partner_utility_bill_text",
  "batch": 1,
  "day": 10,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The utility bill text message",
  "post_text": "The message that arrives six weeks after completion is never about the property. It is about a bill.\n\nA Spanish utility text, in Spanish, about a direct debit that did not go through. Your former buyer cannot read it and has nobody else to ask. So they ask you, and you answer it for free, because the relationship is worth more than the hour.\n\nBueno exists for that message. A Spanish account, property management tools, energy switching, non-resident tax filing, home insurance, and human support in the client's own language. Bueno is licensed by the Bank of Spain via SEFIDE EDE S.L.U.\n\nThe point is not that you stop helping. It is that the help has somewhere to go.\n\nIf you want to see the partner side, my messages are open.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null,
  "source_article": "utilities-setup.txt, direct-debit.txt"
 },
 {
  "slug": "ag_three_fifths_ruling",
  "batch": 1,
  "day": 11,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The three fifths tourist let ruling",
  "source_slug": "community_rental_ban_en",
  "source_slug2": "rental_rule_changes_en",
  "source_article": "supreme-court-tourist-ban.txt, rental-rule-changes.txt",
  "post_text": "If you are still explaining community tourist let rules the way they worked in 2019, the answer you are giving is the wrong way round.\n\nThe current wording of article 17.12 of the Horizontal Property Law takes effect from 3 April 2025, through article 4.2 of Ley Organica 1/2025. Before that, three fifths was already the threshold to limit, condition or prohibit. The disputed question was whether limiting reached an outright ban.\n\nWhat changed is the word approve. Three fifths of owners, who between them also hold three fifths of the quotas, is now what a community needs to allow a tourist let in the first place, not just to stop one. It is a majority of owners and of quotas, not one or the other. Most guidance still describes the old position.\n\nThe same majority can also impose up to a 20 percent increased share of common expenses on the letting flat. Price that into any yield you quote.\n\nAgreements are not retroactive. An owner already letting can carry on, but only if the tourist licence or declaracion responsable was in hand before 3 April 2025. A municipal compatibility report on its own does not save them.\n\nAnd what binds the owner is the regional licence, which is unaffected and varies by region and increasingly by town. The national registration number no longer exists.\n\nCheck the minutes and the licence date on every letting enquiry.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_fx_completion_funds",
  "batch": 1,
  "day": 12,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Completion money, on time",
  "source_slug": "currency_transfer_en",
  "source_slug2": "sepa_swift_en",
  "source_article": "currency-transfer.txt, sepa-swift.txt",
  "post_text": "Completion funds that arrive late can cost your buyer the 10 percent deposit. So the transfer plan belongs in the file from the first week, not the last.\n\nSEPA covers euro payments across the EU, EEA and the UK, and a euro transfer inside it is straightforward. Outside it, money moves through correspondent banks, which is where the days and the deductions appear. Ask where the funds are coming from before you fix a completion date.\n\nIn practice some Spanish utilities and councils still make life difficult for a foreign IBAN, which is why a Spanish account belongs in the same conversation as the transfer plan. Not for the completion money, for everything after it.\n\nCheck how the receiving party holds client funds, and whether they are segregated. And leave more time than the bank quotes, because the quoted time assumes nothing is queried.\n\nPut the transfer plan on the file in week one, alongside the account setup.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_rural_land_checks",
  "batch": 1,
  "day": 13,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Four checks for rural land",
  "source_slug": "rural_property_en",
  "source_article": "rural-property.txt",
  "post_text": "Rural land in Spain rewards four checks and punishes none of them being done.\n\nOne, the registry against the reality. Boundaries, access and the built footprint often differ from the extract. An owner lookup runs around 10 euros online, plus around 30 for an English translation.\n\nTwo, easements. A neighbour's right of way, a water channel, an electricity line. They do not show on a photograph and they do not go away with the sale.\n\nThree, the buildings. A casa de aperos is a tool store, not a home, and turning one into a home is a planning question rather than a building one. Pre 1956 constructions are usually legal without a licence but often cannot be extended.\n\nFour, services. Water rights, septic tanks and a mains connection that may be hundreds of metres away, costing thousands.\n\nBring an independent surveyor into every rural file before the arras.\n\n#SpanishProperty #RuralProperty #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_notary_role",
  "batch": 1,
  "day": 14,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The notary is not their lawyer",
  "source_slug": "escritura_notary_en",
  "source_slug2": "land_registry_en",
  "source_article": "property-contracts.txt, land-registry.txt",
  "post_text": "Foreign buyers arrive assuming the notary is on their side. The notary is on nobody's side, and that is the job.\n\nA Spanish notary checks identity, capacity and the legality of the deed. They do not negotiate, they do not chase the community certificate, and they do not tell your buyer whether the price is sensible. If the buyer does not speak Spanish, a translator is required at the signing.\n\nOn a mortgage there is a pre-contractual period. The FEIN, with the loan conditions, is delivered to the borrower at the start of it, and what is authorised before the notary is the acta of pre-contractual advice. The buyer's meeting with the notary sits inside that window, not alongside it. Treat the period as at least ten days and build the timeline backwards from signing.\n\nRegistration at the Land Registry is a separate step afterwards, and somebody has to own it. Valencia has 18 registry offices and Alicante 8, so the office matters as much as the paperwork.\n\nTell your buyer in the first week that they need their own lawyer.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_partner_aftersales_list",
  "batch": 1,
  "day": 15,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "What after-sales actually contains",
  "post_text": "After-sales is a word agencies use and rarely define. Here is what it contains when a foreign owner is on the other end.\n\nUtilities in the right name, with a direct debit that actually works. A first IBI bill that somebody reads. The non-resident tax return nobody mentioned at the notary. Insurance that covers a home empty for eight months of the year. And a phone number that answers in the owner's language.\n\nBueno bundles that into a subscription. The core plan is 99 euros a year, with other tiers above and below it, and it covers the account, property management tools, energy switching, non-resident tax filing and insurance, with multilingual human support behind all of it. Bueno is licensed by the Bank of Spain via SEFIDE EDE S.L.U.\n\nDefine your after-sales before a client defines it for you.\n\nIf you want to compare notes on handover, I am easy to find.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null,
  "source_article": "non-resident-property-tax.txt"
 },
 {
  "slug": "ag_ibi_attaches",
  "batch": 1,
  "day": 16,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "IBI stays with the house",
  "source_slug": "ibi_deep_en",
  "source_article": "ibi-tax.txt",
  "post_text": "IBI does not follow the owner. It stays with the house, which is why it turns up on a resale file as somebody else's problem.\n\nThe bill is the cadastral value, usually below market value, multiplied by the municipal rate. Across Spain that rate averages 0.3 to 1.1 percent. A Coruna, Zaragoza and Madrid sit low, while parts of Catalunya and the Costa Blanca run higher.\n\nBills land between May and October in many municipalities, and some councils no longer post abroad. So an owner who moved, changed email or never set up a direct debit can miss several years without ever seeing a letter.\n\nWhen it goes unpaid the council escalates, from reminder to surcharge to enforcement, and money can be seized from the owner's Spanish account. I am not quoting a surcharge ladder here, because the figures in circulation belong to a regime that was retired. Ask the council for the current position on the specific bill.\n\nCheck the IBI receipts for the last four years on every resale you take on.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_true_buying_costs",
  "batch": 1,
  "day": 17,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The real price is 12 to 14 more",
  "source_slug": "buying_fees_en",
  "source_slug2": "buying_cost_stages_en",
  "source_article": "buying-fees.txt, cost-of-buying-expats.txt",
  "post_text": "The asking price is not the price. Tell a foreign buyer that in the first conversation and you will never have the awkward one later.\n\nOn resales, transfer tax is regional and banded in several regions. Madrid is 6 percent, Andalucia 7, Valencia 9 since June 2026, and Catalonia runs from 10 percent up to 13 on the top band. Three regions are foral or unpublished, so check rather than quote.\n\nNew builds skip it and pay 10 percent VAT, or IGIC in the Canaries, plus stamp duty that runs from 0.75 percent in Madrid to 2 percent in Murcia depending on region.\n\nOn top of the tax. A reservation fee of 1,000 to 2,000 euros. Notary fees sitting around 1,000 euros on a 250,000 euro purchase. Land registry fees of 400 to 700. A lawyer costing a few thousand euros, or a gestor a few hundred. With a mortgage, valuation reports of 250 to 600 euros and bank setup fees of up to 2 percent, plus bank life insurance at roughly twice what the open market charges. Around 60 to 70 percent of foreigners buying in Spain never take a Spanish loan at all.\n\nBuild the buyer a total cost line before the first viewing, region by region.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_100pct_tax_calm",
  "batch": 1,
  "day": 18,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The 100 percent tax, calmly",
  "source_slug": "noneu_tax_proposal_en",
  "source_article": "noneu-100-tax.txt",
  "post_text": "The 100 percent tax question comes up at nearly every viewing with a non-EU buyer. Here is the calm version.\n\nThe 100 percent tax itself remains a proposal being studied, with no set mechanism or date. Nothing has changed at the notary. No surcharge on foreign or non-resident buyers is enacted anywhere in Spain.\n\nWho would it target? Buyers who are neither EU nationals nor Spanish residents. For most UK and US second-home owners, that is both. Those are two separate tests, one about nationality and one about tax residence, and mixing them is where the confusion starts.\n\nIn Valencia today, residents, non-residents and Spanish citizens alike pay the same transfer tax, 9 percent since June 2026. The rate follows the region and the property, not the passport.\n\nWhat did change is the Golden Visa. It closed to new applicants on 3 April 2025, and it closed the whole investor route, not just the property one. Existing holders can still renew.\n\nGive buyers the position, not the headline, and the viewing stays about the house.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_scam_red_flags",
  "batch": 1,
  "day": 19,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Scam red flags for foreign buyers",
  "source_slug": "scams_en",
  "source_slug2": "land_registry_en",
  "source_article": "scams.txt",
  "post_text": "Foreign buyers get targeted because they cannot check the things a local checks by reflex. These are the flags worth naming out loud.\n\nA seller who will not produce the Nota Simple. A deposit requested to an account in a private name. A price that only holds if the buyer signs this week. A property described as licensed for tourist letting with no paperwork to show it.\n\nThat last one now has a second gate. Ask whether an existing licence actually transfers between owners, and then ask whether the community has approved the activity at all, because a transferring licence does not survive a community that has not.\n\nOther flags. Documents only in Spanish, with no translation offered. A lawyer recommended by the seller and paid by nobody in particular. A build described as legal because it has been there for years. A registry description that does not match what you walked through.\n\nName the flags before the buyer falls for one. It is the cheapest trust you will ever build.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_partner_saying_no",
  "batch": 1,
  "day": 20,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Why saying no costs referrals",
  "post_text": "Saying no to the small questions is what quietly ends the referral chain.\n\nA client asks you to read a utility bill. To explain a tax letter. To sit on a call with a council. None of it is your mandate, and every one of those moments is where the recommendation to their friend either forms or does not.\n\nYou cannot answer all of it yourself. The answer is having somewhere to send it. A platform that handles the account, taxes, energy, insurance and paperwork, with human support in their own language.\n\nThat way no is never the answer. The answer is here is who does this.\n\nIf you want to see how the partner side works, my inbox is open.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null,
  "source_article": "local-tax-office.txt, ibi-tax.txt"
 },
 {
  "slug": "ag_market_calendar",
  "batch": 1,
  "day": 21,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The market calendar as a tool",
  "source_slug": "market_seasons_en",
  "source_article": "market-seasons.txt",
  "post_text": "The Spanish property year has a shape, and working with it is easier than working against it.\n\nJanuary and February bring the planners, the people who decided over Christmas and want to view in spring. March to June is the strongest viewing run on the coast, and the best month to get a survey booked quickly.\n\nAugust is not a dead month for viewings, but it is a slow month for everything else. Offices close, files sit, and a completion date set in August needs more slack than one set in May. Local calendars matter too. Fallas in Valencia and the Seville feria move an entire week.\n\nSeptember to November is when second home buyers who spent the summer in a rental come back with a budget. December is for paperwork, not for signatures.\n\nSet your completion dates against the calendar, not against the buyer's optimism.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_resale_questions",
  "batch": 1,
  "day": 22,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "New build or resale, wrong question",
  "source_slug": "new_build_vs_resale_en",
  "source_slug2": "renovation_permits_en",
  "source_article": "key-questions.txt, new-build-vs-resale.txt, renovation.txt",
  "post_text": "New build or resale is the wrong question. What the buyer is actually choosing between is two different sets of risks.\n\nOn tax, resales carry transfer tax while new builds carry VAT. In the Canaries it is IGIC rather than VAT, and a non-resident buying a Canary holiday home pays the 7 percent general rate. IBI is based on the cadastral value, varying by region and by whether the home is a new build.\n\nOn risk, a new build's exposure is delivery, the developer and the guarantee. A resale's exposure is condition and history. Hidden defects and illegal renovations transfer with the keys. Once the home is in the buyer's name they are the buyer's issues.\n\nOn time, a resale can complete in six to ten weeks, a new build when it is finished. On works, renovation plans need permits from the town hall for each aspect of the work, and any renovation will cost more than the budget says.\n\nAsk what risk your buyer would rather carry. That is the real question.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_nie_timing",
  "batch": 1,
  "day": 23,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "NIE timing breaks timelines",
  "source_slug": "nie_application_en",
  "source_slug2": "nie_realities_en",
  "source_article": "nie-application.txt, buying-documents.txt",
  "post_text": "The NIE is the step that quietly breaks timelines, because it sits before everything and nobody schedules it.\n\nThe application is the EX-15, submitted in Spanish in two copies. EX-18 is a different form for a different procedure, and sending it wastes the appointment. The fee is 9.84 euros, paid first at a bank branch on form 790 codigo 012. Bring a passport with at least six months left.\n\nThen the timing trap. Your NIE number stays with you. The certificate that proves it is only accepted for three months, so banks, notaries and tax offices may ask for a fresh one. Apply too early in a long new build timeline and your buyer will be back at the window.\n\nPractical notes. Many stations stop letting people in around 13:30. Brits can wait longer than EU applicants. A translated letter explaining the reason for the application helps.\n\nBook the NIE appointment the week the buyer decides, not the week the arras is drafted.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_paperwork_sequence",
  "batch": 1,
  "day": 24,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Paperwork before the search",
  "source_slug": "buying_documents_en",
  "source_article": "buying-documents.txt",
  "post_text": "The paperwork a foreign buyer needs is small, dull and best finished before the search starts.\n\nA passport or ID card with at least six months left. The NIE, which everything else depends on. A Spanish account for the local bills, and a note that free account offers in Spain often are not free once card charges and minimum spending conditions kick in. A non-resident certificate is sometimes requested, available from the police station or the requesting bank.\n\nIf a mortgage is in play, proof of income and existing debts, because Spanish banks are required to lend only to people who can demonstrably repay. Get the appraisal question answered early.\n\nFor the property itself, the Nota Simple, around 10 euros online and under 4 euros in person. It shows the debts associated with the property, and because in Spain those transfer to the new owner, that page is what your buyer is really buying. A reserve fee of roughly 1,000 to 2,000 euros holds it while the lawyer reads.\n\nSend the list at the first enquiry. It saves a fortnight later.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_partner_handover_service",
  "batch": 1,
  "day": 25,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Handover as a service",
  "post_text": "Handover is a service, not an email. The agencies that treat it that way get the second sale.\n\nA foreign owner leaves the notary with a deed and a list of things nobody has done. Utilities to move, a direct debit to set up, a first tax return to find out about, insurance to arrange for a home that stands empty most of the year.\n\nBueno covers that list. An account, property tools, energy switching, the Modelo 210 filing, insurance, and support in their own language. Bueno is licensed by the Bank of Spain via SEFIDE EDE S.L.U.\n\nThe agency benefit is not the commission. It is that your client's first three months in Spain go well, and they tell people.\n\nIf you want to compare handover notes, my messages are open.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null,
  "source_article": "frozen-account.txt"
 },
 {
  "slug": "ag_unregistered_extensions",
  "batch": 1,
  "day": 26,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Extensions not on the deeds",
  "source_slug": "extension_deeds_en",
  "source_article": "extension-deeds.txt",
  "post_text": "An extension that is not on the deeds is not a detail. It is the thing that stops a sale three weeks before completion.\n\nStart with the paperwork trail. The town hall file should hold the licence, the project and the Certificado Final de Obra. If the work was Obra Mayor it needed a licence and a technical project. Obra Menor is lighter, and the boundary between them is where most disputes sit.\n\nWhere the work was never declared, the antiquity certificate is the usual route, with an architect confirming the age on site, after which the extension is declared before a notary and written into the land registry. In a community property the neighbours' consent is still needed before the deeds can be updated, even for work finished years ago, and that certificate is signed before a notary.\n\nBudget for the ICIO tax on construction cost plus a smaller urban development fee. The rate is municipal, so ask the town hall rather than take a national figure from an article.\n\nOn timing rules for legalising by antiquity, the period is regional. Ask the town hall for theirs rather than quoting a number.\n\nCheck the deeds against the walls on every instruction, because your foreign buyer's lawyer will ask.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_rental_registration_2025",
  "batch": 1,
  "day": 27,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The 2025 rental registration number",
  "source_slug": "rental_rule_changes_en",
  "source_article": "rental-rule-changes.txt",
  "post_text": "The national rental register was struck down. Your regional licence is what binds.\n\nThe registration number procedure created by Real Decreto 1312/2024 has been annulled by the Tribunal Supremo, in judgments of 19 May, 21 May and 1 June 2026. The ground was competence: the State could not create the registry. There is no state registration number requirement.\n\nSo if a platform, a portal or an article tells a foreign owner they need a national registration number, that is now wrong at state level. What binds them is the regional licence, which varies by region and increasingly by municipality. Platforms may still be asking for a number in practice, and that is a platform requirement rather than a legal one.\n\nWhat survives is real. The Ventanilla Unica Digital and the platform data sharing duties implementing EU Regulation 2024/1028 stand, and platforms have 48 hours to act on a removal order.\n\nOne caution. This area has moved three times in two years, so check the BOE position before you put anything in writing for a client.\n\nUpdate your letting notes to the regional licence, and stop quoting a national number.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_brexit_briefing",
  "batch": 1,
  "day": 28,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Brexit answers for UK buyers",
  "source_slug": "brexit_buying_en",
  "source_slug2": "buyer_visas_en",
  "source_article": "brexit-impact.txt, buyer-visas.txt",
  "post_text": "UK buyers arrive expecting Brexit to have changed the purchase. It changed the stay and the tax, not the purchase.\n\nThe purchase costs, tax, notary and registration fees are identical for UK and EU buyers. No surcharge exists anywhere in Spain on foreign or non-resident buyers.\n\nWhat did change. Non resident income tax on rental income rose from 19 to 24 percent for Brits, and rental expenses can no longer be deducted first. Time is capped at 90 days in any 180 without a residence permit.\n\nOn visas. The Golden Visa is closed to new applicants, though existing holders can renew, and renewals are decided under the law in force when the original permit was granted. The digital nomad visa asks for 200 percent of the Spanish minimum wage, mostly earned from clients or employers outside Spain, with health insurance and proof of qualifications or experience. The non lucrative visa asks for 400 percent of IPREM for the main applicant and 100 percent per family member, currently 28,800 euros a year plus 7,200 each, alongside private health insurance, a clean criminal record and a medical certificate. It is renewed after one year and then every two.\n\nTax paid in Spain can be offset against UK tax. Mortgages for UK nationals involve more paperwork, and NIE appointments can be slower.\n\nSeparate the purchase from the stay in every first conversation with a UK buyer.\n\n#SpanishProperty #UKBuyers #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_modelo210_answer",
  "batch": 1,
  "day": 29,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The Modelo 210 answer on the spot",
  "source_slug": "modelo210_scenarios_en",
  "source_slug2": "modelo210_en",
  "source_article": "non-resident-property-tax.txt, irnr.txt",
  "post_text": "Agents get asked about the Modelo 210 on viewings, so here is the version that is current as of this year.\n\nRental income is no longer quarterly. There is one last quarterly return, Q3 2026, due 1 to 20 October 2026. Everything accrued from 1 October 2026 goes into an annual return filed 1 to 20 April 2027.\n\nIf the home is not let, the owner still files on imputed income. For 2023, 2024 and 2025 the rate is 1.1 percent of the cadastral value wherever those values were revised from 2012 onwards, and 2 percent otherwise. Whether that carries into 2026 is not yet settled, and the 2026 window does not open until April 2027.\n\nA worked example from the tax office. A UK owner with a cadastral value of 45,986 euros pays around 220 euros for a full year, at the 2 percent rate.\n\nDeadlines to know. For the 2026 accrual the imputed window is 1 April to 31 December, with a direct debit cut-off of 23 December. That cut-off is the most common way an owner believes they have paid and has not. On a sale the return is filed within three months once one month has elapsed from the transfer, so the window opens one month after completion and closes four months after it.\n\nLate and honest beats late and found. File voluntarily before the tax office makes contact and you get a surcharge instead of a penalty, which is a much better outcome. Pay between 1 and 12 months late and the surcharge runs 1 to 12 percent of the tax owed. Beyond 12 months it is 15 percent plus interest. The surcharge drops by 25 percent where the conditions in article 27.5 of the General Tax Law are met.\n\nOn VAT, straightforward holiday lets are exempt, hotel style services like meals or regular cleaning bring 10 percent, and a let that is neither an exempt residential let nor a hotel-type service is 21 percent. Booking platforms now report revenue to the Spanish tax office.\n\nKeep those dates on your phone. They come up more often than you expect.\n\n#SpanishProperty #Modelo210 #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null
 },
 {
  "slug": "ag_partner_99_euros",
  "batch": 1,
  "day": 30,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "What 99 euros a year buys",
  "post_text": "The fair question about Bueno is what a client actually gets. The core plan is 99 euros a year, with other tiers above and below it.\n\nWhat it covers. A Spanish IBAN account, the Bueno Account, with a Bueno Visa Card. Property management tools for a home the owner is not standing in. Energy switching through Bueno Energy. The Modelo 210, filed. Home insurance. And human support in the owner's own language.\n\nBueno is licensed by the Bank of Spain via SEFIDE EDE S.L.U. We serve customers in more than 25 countries, with Norway, Sweden, Germany, the UK and France as the main markets.\n\nFor an agent the value is narrow and real. The week after the keys stops being your unpaid job, and your client's first year goes well enough to talk about.\n\nIf you want the partner detail, my inbox is open.\n\n#SpanishProperty #EstateAgents #Spain247\n\nOwning or planning to buy property in Spain? Bueno is trusted by homeowners from 25+ countries. getbueno.com",
  "image_url": null,
  "source_article": "holiday-home-cost.txt"
 }
];
