// Owners stream: 30 posts, rewritten from the full blog articles (studio/articles). Generated; do not hand-edit.
export default [
 {
  "slug": "arras_contract",
  "batch": 1,
  "day": 1,
  "language": "en",
  "member": "",
  "title": "The arras contract decides what you bought",
  "source_article": "property-contracts.txt, buying-10-steps.txt, bank-guarantees.txt",
  "post_text": "The arras draft lands in your inbox two days before signing day. That window is not a courtesy. It is your only real chance to change the contract.\n\nMost buyers in Spain check the price and skim the rest. But the arras decides what you actually bought.\n\nThe agency usually adapts a standard contract, filling in the property details as they appear on the Nota Simple. Beyond price and description, it should fix:\n\nThe completion date, usually two to three months after signing, enough time for your documents and mortgage.\nThe penalties: pull out and you lose your 10 percent deposit; if the seller pulls out, they pay you double.\nThe specifics: which furniture stays, which repairs the seller pays for, whether appliances are included, whether water and electricity will be switched on.\n\nIf it is not written in the arras, it was never agreed.\n\nNow the money. That 10 percent often goes directly to the owners. Common in Spain, but a safeguarded account at a financial institution is the safer route. Ask for it.\n\nBuying a new build? Add completion date clauses and insist on the bank guarantee that protects staged payments.\n\nSo here is the habit: read the draft the day it arrives, line by line, and send your amendments before signing day. At the table it is too late.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #MoveToSpain",
  "image_url": "/photos/coast_bay.jpg"
 },
 {
  "slug": "irnr_who_pays",
  "batch": 1,
  "day": 2,
  "language": "en",
  "member": "",
  "title": "Spain taxes your empty holiday home",
  "source_article": "irnr.txt, non-resident-property-tax.txt",
  "post_text": "Your Spanish holiday home earned nothing this year. Spain will still tax you on it. The trap is that no bill ever arrives to remind you.\n\nFirst, work out which side of the line you are on. Spain treats you as a tax resident if any of these is true:\n\nYou spent more than 183 days in Spain this calendar year, continuous or not.\nYour spouse and underage children live there.\nThe majority of your income and economic activity is in Spain.\n\nNone of those? Then you are a non-resident, and IRNR applies simply for owning property. Spain imputes income at 1.1 percent of the cadastral value, or 2 percent in municipalities without a recent cadastral revision, then taxes it at 19 percent if you live in the EU or EEA, 24 percent for everyone else.\n\nReal numbers: on a 300,000 euro property at 1.1 percent, an owner in Norway pays 19 percent of 3,300 euros. About 627 euros a year.\n\nThe filing is Modelo 210, due by 31 December, and it always covers the previous year. Rent the place out and the rhythm changes to quarterly.\n\nIgnore it long enough and the escalation is real: fines, closure of bank accounts, even confiscation of property in extreme cases.\n\nThis week: count your days in Spain, and check whether last year's Modelo 210 was actually filed. Many owners assume someone else did it.\n\nGeneral information, not tax advice.\n\n#SpanishTax #Modelo210 #HolidayHome",
  "image_url": null
 },
 {
  "slug": "squatter_eviction",
  "batch": 1,
  "day": 3,
  "language": "en",
  "member": "",
  "title": "The 48-hour squatter rule",
  "source_article": "squatter-laws.txt",
  "post_text": "Spanish law gives you 48 hours to remove squatters without a court. Most owners lose that window before they even know it opened.\n\nInside 48 hours of entry, police can evict occupiers immediately if you can prove the property is yours. Past that, Spain's complicated squatting law takes over.\n\nWhy complicated? The law splits squatting into two figures: allanamiento de morada, breaking into an inhabited home, and okupacion, occupying an uninhabited one. What counts as uninhabited is blurry for a second home, and Article 47 of the Constitution declares a right to decent housing. That mix is why evictions take time.\n\nOutside the window, it becomes a court case. You prove ownership and regular use: deeds, photos of you in the home, flight tickets, neighbour statements. The squatters can argue their own rights or show they are paying to stay. Only when a judge sets the date can police remove them by force. Depending on the region, 18 months to 2 years, though many resolve faster.\n\nAnd the counterintuitive part: do not change the locks, block re-entry or confront anyone. All of it can backfire on you legally.\n\nWhat protects you is detection speed. An alarm connected to the police deters entry and timestamps it, keeping you inside the 48 hours. A neighbour who checks the property does the same. Some insurers even offer illegal occupation cover.\n\nSet up the alarm and the neighbour before the season you are away. Not after.\n\nGeneral information, not legal advice.\n\n#SpainProperty #SpanishHomeOwners #HolidayHome",
  "image_url": "/photos/golden_coast.jpg"
 },
 {
  "slug": "cash_rules",
  "batch": 1,
  "day": 4,
  "language": "en",
  "member": "",
  "title": "Cash in Spain now needs paperwork",
  "source_article": "cash-rules.txt",
  "post_text": "Want to withdraw 3,000 euros in cash from your Spanish bank tomorrow? You needed to tell the tax office today.\n\nSince 2025, withdrawals above 3,000 euros, or any amount involving 500 euro notes, must be reported to the Agencia Tributaria 24 hours in advance. You notify via their website with proof of ID, sometimes proof of where the funds came from, and receive a certificate to present at the bank. From 100,000 euros, the notice period becomes 72 hours.\n\nPaying in cash has its own ceilings: 1,000 euros for any transaction involving a business, 1,000 between private individuals, and 10,000 if you are a non-resident who does not pay tax in Spain.\n\nTransfers get paperwork too. Any cash transfer within Spain over 100,000 euros, property purchases included, must be declared on the S1 form. Sending more than 10,000 euros to someone requires documentation proving the origin of the funds.\n\nBreak the rules and fines run from up to 50 percent for minor infractions to 150 percent where fraud is involved. One softener: if payer or payee self-reports within three months, they may be exempt.\n\nCrossing the border with more than 10,000 euros in cash? Declare it, or risk a fine of up to half the undeclared amount.\n\nSo if you are buying, furnishing or renovating: plan on transfers, not envelopes, and keep receipts for large transactions for at least five years. Questions can come long after the money moved.\n\nGeneral information, not tax advice.\n\n#BankingInSpain #SpanishTax #ExpatSpain",
  "image_url": null
 },
 {
  "slug": "tourist_license",
  "batch": 1,
  "day": 5,
  "language": "en",
  "member": "",
  "title": "Tourist rentals need a licence",
  "source_article": "legally-renting.txt",
  "post_text": "\"We'll rent it out when we're not there.\" Fine. But in Spain, any rental contract under three months makes you a tourist landlord, and that status needs a licence.\n\nThe licence comes in two forms: individual for private owners, collective for companies managing several properties. Its job is to certify hygiene, safety and quality standards, and that you are paying the right taxes.\n\nThe process: bring the property up to standard, obtain habitability and energy efficiency certificates, register with the local tourism agency where required, then submit the application at your tourist office. Expect one to six months depending on region and demand.\n\nSkipping it is where the numbers get serious. Fines typically run 4,000 to 60,000 euros, rising sharply for repeat infractions, and up to 111,000 euros in Ibiza. Catalunya has dedicated teams hunting illegal lets. Barcelona has made short-term private room rentals illegal, and new licences for entire homes are now very hard to come by. Valencia mostly issues them to ground-floor properties in popular areas.\n\nTwo consequences follow. A property that already has a licence attached is a genuine selling point. And renting legally is what makes proper rental insurance valid, and what lets you list on the big booking platforms at all.\n\nSo if rental income is part of your purchase maths, check licence availability in that exact area before you buy, not after. Two streets apart can be two different answers.\n\nGeneral information, not legal advice.\n\n#HolidayRental #SpainProperty #HolidayHome",
  "image_url": "/photos/terrace_sunset.jpg"
 },
 {
  "slug": "nota_simple",
  "batch": 1,
  "day": 6,
  "language": "en",
  "member": "",
  "title": "The Nota Simple line buyers never read",
  "source_article": "nota-simple.txt, land-registry.txt, buying-10-steps.txt",
  "post_text": "There is a line on the 10 euro Nota Simple that can quietly shrink your Spanish mortgage. Most buyers never read it.\n\nThe Nota Simple is the Land Registry's summary of a property: current owner, mortgages and debts, boundaries, square metres, land classification.\n\nEveryone tells you to check the debts, and they are right. In Spain, debts travel with the home, not the seller. Buy a property with unpaid charges and they become yours. The document also confirms the seller actually owns what they are selling. There have been cases of squatters selling homes that were never theirs.\n\nBut here is the line people miss: the valor catastral, the official estimate of the property's value. If it is registered lower than your agreed price, the bank can base your mortgage on that lower figure. Registered 10k under your buying price? Expect a mortgage for 10k less. You want to know this before you talk to the bank, not when the offer letter arrives.\n\nGetting one is trivial: around 10 euros online, arriving as fast as the same day, or under 4 euros in person at the registry. Anyone with a legitimate interest can request it. You will need the property's registry identifier, which the seller or agent can supply.\n\nThe rule: order the Nota Simple before you sign the arras, and read the cadastral value line as carefully as the debts section.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #NotaSimple",
  "image_url": null
 },
 {
  "slug": "wealth_tax",
  "batch": 1,
  "day": 7,
  "language": "en",
  "member": "",
  "title": "The €700,000 wealth tax line",
  "source_article": "late-tax-penalties.txt",
  "source_slug": "wealth_tax_en",
  "post_text": "Spain runs a second property-owner tax most people never meet. If your Spanish assets are drifting toward 700,000 euros, you should know exactly where the line sits.\n\nWealth tax applies to residents and non-residents alike, measured on total assets. Below 700,000 euros, nothing is owed. Above it, the tax bites incrementally, only on the value over the line, at progressive rates from 0.2 to 2.5 percent. No sale, no income, no trigger. Owning is enough.\n\nNow the twist: where you own matters as much as what you own. The tax is shaped by local government, and Madrid applies a 100 percent discount. Identical assets, zero bill. Residents who live in their Spanish home also get an extra 300,000 euro allowance on that main home.\n\nWho actually gets caught? Two profiles. Non-residents holding one high-value property. And owners whose several Spanish assets, the apartment, the garage, the plot, quietly add up past the threshold without anyone doing the sum.\n\nThat last part is the real danger. Nobody sends a warning when you cross the line. The threshold does not announce itself.\n\nThe discipline costs one hour a year: total your Spanish assets. Anywhere near the line, get advice for your specific region, because in this tax, geography changes everything.\n\nGeneral information, not tax advice.\n\n#SpanishTax #WealthTax #SpainProperty",
  "image_url": "/photos/sunset_village.jpg"
 },
 {
  "slug": "community_rental_ban",
  "batch": 1,
  "day": 8,
  "language": "en",
  "member": "",
  "title": "Neighbours can ban your tourist let",
  "source_article": "supreme-court-tourist-ban.txt, hoa-rules.txt",
  "post_text": "48 votes to 3. That is how a Marbella community ended six tourist flats in their building, and the Supreme Court backed them.\n\nHere is the legal chain behind it.\n\nSince 2019, Article 17.12 of the Horizontal Property Law has let owner communities condition and limit tourist rentals in their building. But judges across Spain disagreed on whether limiting included banning outright, and the law never set a voting threshold.\n\nThe Supreme Court has now settled both: prohibition counts as a form of limitation, and a three-fifths majority, 60 percent of owners, is enough. No unanimity needed.\n\nThe Marbella case that forced the ruling involved complaints of noise, drug use, damage and misuse of common spaces. Two companies owning six tourist apartments fought the ban and lost.\n\nIf you let short term in a community building, two safeguards still stand: bans are not retroactive, and they must be properly justified by problems still affecting residents. And a community vote can be revoked on grounds including that it is contrary to the law or detrimental to the community. Disliking the result counts for nothing.\n\nOne detail owners forget: votes are weighted by ownership, so someone holding several flats holds a bigger share of the decision. Voting by proxy is allowed.\n\nSo read your community statutes this month, and be at the next assembly, in person or by proxy. Your rental's future is decided in that room, with or without you.\n\nGeneral information, not legal advice.\n\n#HolidayRental #SpainProperty #SpanishHomeOwners",
  "image_url": null
 },
 {
  "slug": "currency_transfer",
  "batch": 1,
  "day": 9,
  "language": "en",
  "member": "",
  "title": "Moving money to Spain is timing",
  "source_article": "currency-transfer.txt, sepa-swift.txt",
  "post_text": "In a Spanish purchase, the completion date is fixed and the exchange rate is not. Miss the date because your money is in transit and your 10 percent deposit is at risk.\n\nSo the transfer plan is part of the purchase, not an afterthought.\n\nTiming first. Exchange rates move all day. Instead of guessing, set rate alerts and move when the level works for you. On a purchase-sized sum, a small difference in rate is real money.\n\nThen the rails, because not all transfers are equal.\n\nSEPA covers euro payments across the EU, EEA and the UK. It needs nothing more than an IBAN, and it is faster and cheaper than other international payments. Most UK banks send European transfers as SEPA by default. The rule: send euros, via SEPA.\n\nSWIFT is the global network. Your money hops through correspondent banks, and each one takes its cut. Slower, more expensive, and what you use for non-European currencies.\n\nAnd one Spanish quirk that surprises everyone: Spain also runs its own domestic network, Iberpay, and many utility companies only support direct debits through it. That is why you need a Spanish account to pay Spanish bills, however good your other accounts are.\n\nBefore using any provider, check two things: client funds held in segregated accounts, separate from company money, and fees stated upfront.\n\nPlan the transfer timeline the day you sign the arras. Everything after that is a countdown.\n\nGeneral information, not financial advice.\n\n#BuyingInSpain #SpainProperty #BankingInSpain",
  "image_url": "/photos/pool_dusk.jpg"
 },
 {
  "slug": "inheritance_foreign_law",
  "batch": 1,
  "day": 10,
  "language": "en",
  "member": "",
  "title": "One will clause opts out of Spanish law",
  "source_article": "estate-planning.txt",
  "post_text": "One clause in your will decides whether Spain chooses your heirs for you. Most foreign owners have never checked if it is there.\n\nUnder the European Inheritance Regulation of 2012, anyone who dies after 17 August 2015 can choose the inheritance law of their home country instead of the country where they live.\n\nThe condition is strict: the choice must be stated clearly, in a Spanish or international will.\n\nStay silent while living in Spain and Spanish law governs your entire estate, including forced heirship. Here is what that means in numbers. Half of the joint property goes to your spouse. The rest of the estate is split into thirds: one third divided equally between your children, a second third divided between the children as you wish, and only the final third free for you to leave to anyone at all.\n\nRemarried? Want to include stepchildren or other family members? That final third is all the room Spanish law gives you.\n\nNon-residents, this reaches you too. If you keep a holiday home in Spain, your will should state which country's law governs those Spanish assets. Otherwise the default can still catch them.\n\nThe fix costs an hour: reread your will this month. If it predates your Spanish property and names no governing law, amend it while the choice is still yours. Later, it becomes your family's problem instead.\n\nGeneral information, not legal advice.\n\n#SpainProperty #ExpatSpain #InheritancePlanning",
  "image_url": null
 },
 {
  "slug": "bank_guarantee",
  "batch": 1,
  "day": 11,
  "language": "en",
  "member": "",
  "title": "Off plan? Demand the bank guarantee",
  "source_article": "bank-guarantees.txt",
  "post_text": "Buying off plan in Spain can mean paying up to 80 percent of the price for a home that does not exist yet. One document stands between you and losing all of it.\n\nWith off-plan purchases, you pay a deposit and then agreed instalments all the way to the day you sign the deed. That money finances the construction itself. Before 1968, nothing protected it, and the stories from that era are exactly what you would imagine.\n\nLaw 57/68 changed the rules. Any developer taking staged payments must now do two things:\n\nOpen a specific bank account for buyer deposits. Not a personal account, not one previously held. An account that can only be used for the construction of your property.\n\nProvide a bank guarantee that refunds every payment plus interest if the build is not started, or not finished, by the agreed completion date. And the guarantee must have no expiry date. It stays valid until the property is fully finished and deemed safe to live in.\n\nThink of it as an insurance policy with a peculiar feature: it costs you nothing and costs the developer a lot. Which is exactly why some try to work around it, sometimes by dangling better conditions instead.\n\nThat is the tell. If a developer resists the guarantee, walk away, whatever the discount. Either you get your finished Spanish home, or you get every euro back with interest. Accept nothing between those two outcomes.\n\nGeneral information, not legal advice.\n\n#SpainProperty #OffPlan #BuyingInSpain",
  "image_url": "/photos/marina.jpg"
 },
 {
  "slug": "noneu_tax_proposal",
  "batch": 1,
  "day": 12,
  "language": "en",
  "member": "",
  "title": "The 100% tax: the real numbers",
  "source_article": "noneu-100-tax.txt",
  "post_text": "\"Spain will charge non-EU buyers 100 percent tax.\" Before you shelve your plans over that headline, look at the numbers underneath it.\n\nYes, Spain's Prime Minister has proposed a 100 percent tax on property purchases by non-EU residents: anyone spending under 183 days a year in Spain, which includes UK and US buyers of second homes.\n\nThe context: it is one of twelve measures against a housing crisis in which prices have nearly doubled in a decade, and rents in Madrid and Barcelona rose by as much as 33 percent in five years. It landed alongside the closing of the Golden Visa on 3 April 2025, which ended residency through 500,000 euro property purchases.\n\nNow the scale nobody quotes. In 2023, foreigners bought 15 percent of Spanish properties: 87,000 of 583,000 sales. Non-EU non-residents? 27,000, about 5 percent, mostly from the US, UK, Morocco, Venezuela and Mexico, and mostly coastal holiday homes rather than the city flats at the centre of the crisis.\n\nFor perspective on today's reality: in Valencia, residents and non-residents alike currently pay the same 10 percent transfer tax.\n\nAnd the detail that matters most: this remains a proposal under study. There is no final text, no date, no mechanism.\n\nSo watch the legislation, by all means. But a 5 percent slice of the market is the thing being debated. Do not restructure your life around a headline.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #MoveToSpain",
  "image_url": null
 },
 {
  "slug": "rental_rule_changes",
  "batch": 1,
  "day": 13,
  "language": "en",
  "member": "",
  "title": "Your NRA number needs renewing yearly",
  "source_article": "nra-deadline.txt, rental-rule-changes.txt",
  "post_text": "Renting out in Spain? Your NRA registration number is not a one-time formality. For 2025 rentals, the renewal window is 1 February to 2 March 2026.\n\nThe NRA, Numero de Registro de Alquiler, came into force on 1 July 2025. Every short, mid-term and tourist rental needs one, displayed on the listing, or you cannot legally advertise on the big platforms.\n\nWhat surprises owners is the annual filing. Even if you rented the place out once all year, you must renew, and the renewal is a report:\n\nConfirmation the property is still used for rentals.\nAny ownership changes.\nThe year's rental activity: the different lets and their lengths.\nThe reasons for each stay: holiday, work, studying.\nConfirmation that safety and habitability standards are maintained.\n\nYou file through the Land Registry your property is registered under. If you already hold an NRA, expect a reminder email in January.\n\nTwo practical warnings. The registry websites can be temperamental: in Valencia, the forms famously only download on a Microsoft computer, so some owners end up going in person. And your community can close the door entirely: if the building has voted to ban tourist rentals, no registration code will be issued.\n\nThe habit that makes all of this painless: keep a running log of every rental, dates, length and reason for stay, as the year goes. February you will thank August you.\n\nGeneral information, not legal advice.\n\n#HolidayRental #SpainProperty #SpanishHomeOwners",
  "image_url": "/photos/cove_house.jpg"
 },
 {
  "slug": "epc_certificates",
  "batch": 1,
  "day": 14,
  "language": "en",
  "member": "",
  "title": "Fined for the advert itself: the EPC",
  "source_article": "epc.txt, lost-documents.txt",
  "post_text": "In Spain you can be fined for the property advert itself: 300 to 600 euros for listing a home without an energy certificate.\n\nThe EPC is required at the advertising stage, not just at completion. The certificate must be available before the property is listed, a copy goes into the notarial deed when you sell, and notaries may refuse to complete a sale without one. Having no certificate at all, or falsifying one, moves the fine into the 1,000 to 6,000 euro range.\n\nThe good news: getting one is genuinely easy. A certified technician inspects insulation, windows, heating, cooling and lighting, then issues a rating from A to G. Expect 100 to 300 euros and less than a week. It stays valid for ten years, and a decent rating can support your asking price and open access to green funding and subsidies.\n\nBut there is a step that catches even professionals: the certificate must also be registered with your regional authority. The technician usually handles this. Usually. Confirm it was done and keep the reference with your property papers, because each region runs its own inspections and penalties.\n\nLost the certificate later? The technician who issued it can supply a copy, or a licensed assessor can reissue one for 60 to 150 euros.\n\nSelling or letting soon? Make the EPC the first document you sort, because everything else waits behind the listing.\n\nGeneral information, not legal advice.\n\n#SpainProperty #SellingInSpain #EPC",
  "image_url": null
 },
 {
  "slug": "plusvalia",
  "batch": 1,
  "day": 15,
  "language": "en",
  "member": "",
  "title": "Buying from a non-resident seller",
  "source_article": "plusvalia.txt",
  "post_text": "Buying from a non-resident seller in Spain? Congratulations, you just inherited two of their tax jobs.\n\nJob one: capital gains withholding. You keep back 3 percent of the purchase price and pay it to the tax authorities within one month of the sale. Understand what this is: not an extra tax, but a holding that guarantees the seller's capital gains bill, 19 percent of profit for EU and EEA residents, 24 percent for others. It gets withheld even if the seller made no profit at all. They then claim a partial or full rebate within the year.\n\nJob two: plusvalia, the municipal tax on the increase in urban land value. Normally the seller pays it. But when the seller is a non-resident, the buyer pays. Whoever pays has 30 days from the transfer to get the money to the council, or fines follow.\n\nHow much? It depends on the land value on the council tax receipt, local rates, and above all how long the seller owned the property, up to a 20-year cap. And if the land value genuinely fell, or the sale made a loss, there may be nothing to pay at all.\n\nNone of this needs to be stressful if you do one thing: agree in writing, before completion, who handles each payment and which sums are withheld from the price. Ten minutes of clarity, zero arguments later.\n\nGeneral information, not tax advice.\n\n#SpainProperty #SpanishTax #BuyingInSpain",
  "image_url": "/photos/arch_terrace.jpg"
 },
 {
  "slug": "buying_fees",
  "batch": 2,
  "day": 16,
  "language": "en",
  "member": "",
  "title": "Same home, 6% tax or 10%, by region",
  "source_article": "buying-fees.txt, cost-of-buying-expats.txt",
  "post_text": "The same resale home costs 6 percent in tax in Madrid and 10 percent in Valencia. Most buyers compare asking prices and never compare regions.\n\nBudget 12 to 14 percent on top of the price in Spain, but where you buy decides the biggest slice.\n\nOn resales, transfer tax runs from 4 percent in the Basque Country and 6 percent in Madrid to 8 percent in Andalucia and 10 percent in Valencia and Catalonia. New builds skip it and pay 10 percent VAT plus a regional document fee of up to 1.5 percent.\n\nThen the fixed layer: notary fees around 1,000 euros on a 250,000 euro purchase, land registry fees of 400 to 700 euros at government-set rates, a lawyer at a few thousand euros or a gestor at a few hundred.\n\nAgent fees have their own geography. In Madrid, around 3 percent, typically paid by the seller. In foreigner hotspots, 5 to 6 percent, often shared between the two sides, plus 21 percent VAT. On a 200,000 euro home at 6 percent shared, that is 7,260 euros from each side.\n\nBorrowing adds more: bank setup fees up to 2 percent of the loan, valuation reports of 250 to 600 euros that sometimes land on the buyer, and bank-sold insurance that can easily cost twice the market price.\n\nBefore you sign anything, ask for a full written cost breakdown for your region.\n\nGeneral information, not tax advice.\n\n#SpainProperty #BuyingInSpain #MoveToSpain",
  "image_url": null
 },
 {
  "slug": "ibi_deep",
  "batch": 2,
  "day": 17,
  "language": "en",
  "member": "",
  "title": "IBI: the tax that stays with the house",
  "source_article": "ibi-tax.txt, local-tax-office.txt",
  "post_text": "Your Spanish property tax bill might not come from Spain's tax agency, or even your town hall. In Alicante province it comes from an agency called Suma.\n\nIBI is the local property tax, and knowing who collects it is half the battle. Each municipality runs its own Oficina de Recaudacion, but in some provinces collection is delegated: Suma Gestion Tributaria in Alicante, the Patronato de Recaudacion in Malaga. Letters from these agencies are real bills, not junk mail.\n\nThe bill itself: your cadastral value, an official valuation usually below market value, multiplied by your municipality's rate. Across Spain that averages 0.3 to 1.1 percent. Santander, Zaragoza and Madrid sit low; parts of Catalunya and the Costa Blanca run higher.\n\nBills land between May and October, and many councils will not post abroad. That is exactly how absent owners miss them.\n\nMiss one and the sequence is predictable: a reminder, surcharges from around 5 percent rising past 20 percent, then debt collection, meaning money seized from your Spanish account and charges placed against the property.\n\nThe same office usually bills the waste tax too: 50 to 200 euros a year, sometimes calculated on your water consumption or bins, owed even if you never visit.\n\nTwo moves fix nearly all of it. Owners: direct debit plus electronic notifications. Buyers: check the IBI is paid up before completion, because unpaid IBI stays attached to the property, not the previous owner.\n\nGeneral information, not tax advice.\n\n#IBI #SpanishTax #SpainProperty",
  "image_url": "/photos/couple_beach.jpg"
 },
 {
  "slug": "frozen_account",
  "batch": 2,
  "day": 18,
  "language": "en",
  "member": "",
  "title": "Why Spanish banks freeze accounts",
  "source_article": "frozen-account.txt",
  "post_text": "Spanish banks are allowed to freeze your account first and explain later. For absent owners, the first sign is usually a declined card.\n\nUnder anti-money-laundering law, a bank that spots suspicious activity can freeze the account to stop funds moving, report it to Spain's Financial Intelligence Unit, and only notify you afterwards. When letters do come, they arrive by post, in Spanish, at your Spanish address. If nobody reads that mailbox, you find out at the checkout.\n\nThe easiest one to fix: an expired passport or ID. Banks must keep your identification current, and an out-of-date document is enough. Send updated papers and the account usually reopens within days.\n\nThe heavier causes: unpaid taxes, IBI and non-resident income tax included, where the tax agency freezes accounts through court-ordered debt collection. Missed mortgage or loan payments. Court orders in disputes like divorce, which hit joint accounts especially.\n\nAnd the one people trip without knowing: unusual transactions. A large or out-of-pattern transfer, a property purchase being the classic case, can set off the fraud checks. The fix is almost embarrassingly simple: tell your bank before you move the money or use the card abroad, not after.\n\nThree habits prevent nearly all of it: keep every ID document valid, ask for correspondence online where possible, and have someone check the Spanish mailbox.\n\nGeneral information, not financial advice.\n\n#BankingInSpain #SpanishHomeOwners #ExpatSpain",
  "image_url": null
 },
 {
  "slug": "community_fees",
  "batch": 2,
  "day": 19,
  "language": "en",
  "member": "",
  "title": "Community fees: the underestimated cost",
  "source_article": "community-fees.txt, hoa-rules.txt",
  "post_text": "In a Spanish community of owners, the size of your apartment sets two things: your share of the bills, and the weight of your vote.\n\nCommunity fees fund the lifts, pools, gardens, security and the fabric of the building itself. Some owners pay around 100 euros a quarter; high-end developments run past 1,000. The budget is usually set from the previous year's expenses, collected monthly or quarterly, with a surplus on top. That surplus later repaints the facade or retiles the pool without a sudden demand for cash.\n\nYour share depends on the services and the size of your property. And that same share is your voting power at the annual general meeting, where budgets, works and increases are decided. Notice can legally be as short as three days, though most presidents give two weeks. Cannot attend? Vote by proxy.\n\nBefore you buy, two protections matter. In Spain, community fee debts attach to the property, so arrears can arrive with the keys. Have your lawyer check, and if debt exists, it is normally deducted from the purchase price before signing.\n\nAnd know the endgame for non-payers: late fees, interest, court demands, and in extreme multi-year cases a forced sale of the property at auction.\n\nOne quirk worth knowing: a ground-floor owner who votes against the new lift may avoid paying for it, but gets no key.\n\nThe rule once you own: be at the annual meeting, or be represented.\n\nGeneral information, not legal advice.\n\n#SpainProperty #SpanishHomeOwners #CommunityFees",
  "image_url": "/photos/poolside.jpg"
 },
 {
  "slug": "modelo210_scenarios",
  "batch": 2,
  "day": 20,
  "language": "en",
  "member": "",
  "title": "Modelo 210 prorates by days",
  "source_article": "non-resident-property-tax.txt",
  "post_text": "Bought in June? Sold in March? Spain does not charge Modelo 210 for the full year. There is a formula, and almost nobody runs it.\n\nHere it is: cadastral value x 2 percent (or 1.1 percent where the municipality has had a general cadastral revision in the last 10 years) x 19 percent for EU and EEA residents or 24 percent for everyone else, x days owned over 365.\n\nReal example from a UK owner: 45,986 euros cadastral value x 2 percent x 24 percent for a full year comes to about 220 euros.\n\nNow the scenarios, because this is where owners get lost:\n\nBought this year and not renting? Your first return is due next year, covering only your ownership days.\nSold? You file for the days up to completion, early the following year.\nRenting? Rental income is declared quarterly, in the year it is earned, with deadlines on 20 April, 20 July, 20 October and 20 January. January to March income is filed in April.\nPartially rented? Both at once: quarterly returns for the rented days, an annual return for the empty ones.\nCo-owners? Each files and pays their own share. Two names on the deed, two returns.\n\nAnd a quiet warning: booking platforms now report your revenue to the Spanish tax office, so the figures need to match.\n\nYour cadastral value is sitting on your IBI bill. Pull it out tonight and run your own number.\n\nGeneral information, not tax advice.\n\n#Modelo210 #SpanishTax #HolidayHome",
  "image_url": null
 },
 {
  "slug": "escritura_notary",
  "batch": 2,
  "day": 21,
  "language": "en",
  "member": "",
  "title": "The notary is not your lawyer",
  "source_article": "property-contracts.txt, land-registry.txt",
  "post_text": "The notary at your Spanish signing is not your lawyer. They are impartial by design, and buyers who miss this leave a hole in their team.\n\nAt the escritura publica, the deed of sale, the notary prepares and oversees the document, reads it out to buyer and seller together, and confirms both fully understand it before anyone signs. Not strong in Spanish? You may be required to bring a translator or a Spanish-speaking legal adviser.\n\nBuying with a mortgage adds two protective delays that surprise people. The FEIN, the document laying out your mortgage terms, must be signed at least 10 days before the mortgage deed. That gap is a legal requirement. Then you meet the notary at least 24 hours before signing, so they can walk you through the loan conditions.\n\nWhat the notary never does is represent your interests. They act as an impartial adviser to both parties and confirm the sale is legal. Checking whether the deal is good for you is someone else's job. Yours, or your lawyer's.\n\nAnd signing is not the finish line. The property and its new owners must still be registered at the Land Registry, and only once registered are you officially recognised as the owner. Cities have multiple offices, Valencia has 18, and the right one appears in the first line of your Nota Simple.\n\nBring your own adviser to the table, and register promptly after completion.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #ExpatSpain",
  "image_url": "/photos/coast_bay.jpg"
 },
 {
  "slug": "owners_year",
  "batch": 2,
  "day": 22,
  "language": "en",
  "member": "",
  "title": "The absent owner's bill calendar",
  "source_article": "local-tax-office.txt, ibi-tax.txt, plusvalia.txt, community-fees.txt, non-resident-property-tax.txt",
  "post_text": "Spanish property bills do not arrive all at once. They arrive all year, from offices you have never heard of, to an address you are not at.\n\nHere is the absent owner's calendar.\n\n1 January: the year often opens with vehicle tax if you keep a car there, from around 20 euros for small vehicles to over 200 for powerful ones. IBI is also pinned to this date: it is charged to whoever owns the home on 1 January, whatever happens later.\n\nMay to October: the IBI bill itself lands, whenever your municipality sends it. In some areas, collection is handled by a provincial agency rather than the town hall, and many councils will not post abroad. This is the bill absent owners miss most.\n\nJune to October: the waste tax, typically 50 to 200 euros a year, owed even if you never visit.\n\nAll year: community fees, monthly or quarterly, with increases decided at the annual general meeting.\n\n31 December: the non-resident tax return, Modelo 210, closes the year.\n\nThree moves cover all of it. Put every date in one annual calendar. Set up direct debits with the collection office for the recurring bills. And have someone check the Spanish mailbox, because most surprises in Spanish ownership are really just missed post.\n\nGeneral information, not tax advice.\n\n#SpainProperty #SpanishHomeOwners #Modelo210",
  "image_url": null
 },
 {
  "slug": "free_banking_myth",
  "batch": 2,
  "day": 23,
  "language": "en",
  "member": "",
  "title": "The free banking myth",
  "source_article": "free-banking-myth.txt, buying-fees.txt, bank-fees.txt",
  "post_text": "The quiet rule of Spanish banking: the mortgage customers get the free accounts. Everyone else pays, one condition at a time.\n\nHere is how the game works. Take a loan from a Spanish bank and you will often get free banking bundled in. No loan? Then free usually means conditional: you must buy the bank's products and push a minimum transaction volume through the account every month. Miss the conditions and the fees start.\n\nAnd here is why that matters for foreign owners specifically: 60 to 70 percent of foreigners who buy property in Spain never take a Spanish loan. The free-banking route was never built for you.\n\nThe base costs when conditions fail: Spain's most expensive banks charge 240 euros a year for basic banking, plus roughly 20 euros for a credit card and up to 30 for a debit card. Products sold alongside are usually significantly overpriced; bank-sold insurance can easily cost twice the market price.\n\nThen the drain nobody itemises: international transfers at up to 35 euros each. A pension arriving monthly can lose hundreds a year.\n\nOn average Spanish bank fees run higher than in other European countries. The account type matters too: living there points to a resident account, owning from abroad to a non-resident one.\n\nSo map your real usage and read the account conditions against it line by line. An account that is free for a Spanish salary earner is rarely free for you.\n\nGeneral information, not financial advice.\n\n#BankingInSpain #ExpatSpain #RetireInSpain",
  "image_url": "/photos/golden_coast.jpg"
 },
 {
  "slug": "inheritance_tax",
  "batch": 2,
  "day": 24,
  "language": "en",
  "member": "",
  "title": "Heirs pay before they inherit",
  "source_article": "estate-planning.txt",
  "post_text": "In Spain, heirs pay the inheritance tax before they can touch the inheritance. The estate stays locked until the bill is settled.\n\nThat sequencing is the part that catches families. Succession tax falls on the beneficiary, not the estate, and the estate cannot be released until the tax is paid. If the inheritance is a property and the cash is inside the estate, you can see the problem.\n\nThe clock: 6 months from the death, extension possible. Miss it and 5 percent is added every 3 months, up to a maximum of 20 percent on top.\n\nThe amount: progressive rates from 7.65 to 36.5 percent, shaped by three things. The region, and they differ sharply, with Andalucia among the lowest in the country. The relationship between the deceased and the beneficiary. And the value inherited.\n\nThe reach: residents and non-residents alike pay on assets located in Spain. Assets outside Spain escape Spanish inheritance tax, with one exception: a beneficiary who is a Spanish resident.\n\nAnd if there is no will at all, Spain applies a strict order: children first, then parents, then the surviving spouse, then wider relatives, and finally the state itself. Notice where the spouse sits in that queue.\n\nIf you stand to inherit Spanish property, start the paperwork the same month. Six months evaporates when you are working across two legal systems and a locked estate.\n\nGeneral information, not tax advice.\n\n#InheritanceTax #SpanishTax #SpainProperty",
  "image_url": null
 },
 {
  "slug": "rural_property",
  "batch": 2,
  "day": 25,
  "language": "en",
  "member": "",
  "title": "Rural land: run these four checks",
  "source_article": "rural-property.txt",
  "post_text": "Rural land in Spain fails checks that urban flats pass without trying. Before you fall for the finca, run these four.\n\nOne: compare paper to ground. The Land Registry and the Cadastral Registry frequently disagree with real life on plot size, property description and boundaries, and any discrepancy brings legal and financial consequences. If the Title Deed is missing or outdated, do not proceed. Wait until the vendor updates everything at the Land Registry, at their expense, and have your lawyer check it. For about 9 euros you can even look up the registered owner yourself, because sellers are not always who they claim.\n\nTwo: check the building is legal. Some owners register a casa de aperos, literally a tool shed, to dodge planning restrictions, then build a villa on the paperwork of a shed. A surveyor can confirm whether Town Hall permission exists. If it does not, walk away and skip the legal battle. Pre-1956 constructions are usually legal without a licence, but often cannot be extended.\n\nThree: easements. Rural plots carry rights urban homes rarely do: rights of way, rights of view, rights to extract water. Know who can cross your land before it is yours.\n\nFour: wastewater. Septic tanks are the norm, they cost money to empty, and a renovation can force a modern replacement costing thousands.\n\nThe one-line summary: hire an independent rural surveyor or lawyer before signing anything. On rural land, they are not optional.\n\nGeneral information, not legal advice.\n\n#SpainProperty #RuralSpain #BuyingInSpain",
  "image_url": "/photos/terrace_sunset.jpg"
 },
 {
  "slug": "late_tax_penalties",
  "batch": 2,
  "day": 26,
  "language": "en",
  "member": "",
  "title": "Missed a deadline? Move first",
  "source_article": "late-tax-penalties.txt, non-resident-property-tax.txt",
  "post_text": "Missed a Spanish tax deadline? The order of events now decides the cost. Filing before their letter arrives is worth real money.\n\nThe mechanism has a name: Declaracion Extemporanea sin Requerimiento Previo, a voluntary filing made before the tax office contacts you. File this way and the surcharge starts at 1 percent, plus 1 percent for each month of delay. Pass twelve months and it becomes 15 percent plus late interest. Annoying, survivable.\n\nWait for the tax office to write first and the arithmetic changes completely: the fine can be at least 50 percent of the tax owed, on top of the original bill.\n\nThe same logic covers mistakes. Filed something wrong? A Declaracion Complementaria, submitted before any notification, keeps corrections cheap, especially if the fix increases what you owe.\n\nWhy do so many foreign owners end up here? Because the non-resident tax runs on its own quiet schedule, due by 31 December of the following year, and no reminder ever comes.\n\nIf the catch-up sum is uncomfortable, you can request an instalment plan from the Agencia Tributaria. You justify the hardship, larger sums may need a guarantee, and interest still runs, but it beats letting the debt compound.\n\nThe rule to remember: file first, then fix. Every week you move before they do is money kept.\n\nGeneral information, not tax advice.\n\n#SpanishTax #Modelo210 #SpanishHomeOwners",
  "image_url": null
 },
 {
  "slug": "property_insurance",
  "batch": 2,
  "day": 27,
  "language": "en",
  "member": "",
  "title": "The vacant-home insurance trap",
  "source_article": "property-insurance.txt, earthquake-flood-insurance.txt",
  "post_text": "Two facts about insuring a Spanish holiday home: the empty months are your weak spot, and floods are covered by a state fund most owners have never heard of.\n\nHome insurance is not legally required in Spain, except when a mortgage bank insists. But two mechanisms decide whether it actually protects you.\n\nFirst, vacancy. If your home sits unoccupied for long stretches, the classic risk is the burst pipe that goes unnoticed for weeks. This is exactly why vacant property insurance exists as its own product. If your Spanish home spends most of the year without you, ask the direct question before you sign: what happens to my claim if the house has been empty for months?\n\nSecond, the Consorcio de Compensacion de Seguros. A mandatory surcharge on ordinary policies funds this state-backed scheme, and it covers extraordinary risks: flooding, earthquakes, tsunamis, windstorms above 120 km/h. The CCS acts as a direct insurer: you can claim from it directly, cover is automatic with no official disaster declaration needed, and there is no upper or lower limit. Document damage with photos as soon as it is safe. Flooding accounts for around 70 percent of what it has paid out.\n\nThe gaps in between, hail, frost, lightning, winds below 120 km/h, sit with the private market, some as optional extras.\n\nSo this week, two questions to your insurer: the vacancy question, and which extraordinary risks your policy's surcharge already funds.\n\nGeneral information, not financial advice.\n\n#SpainProperty #HolidayHome #HomeInsurance",
  "image_url": "/photos/sunset_village.jpg"
 },
 {
  "slug": "gift_tax",
  "batch": 2,
  "day": 28,
  "language": "en",
  "member": "",
  "title": "Gifts are taxed within 30 days",
  "source_article": "estate-planning.txt",
  "post_text": "Gift money or property in Spain and the recipient has 30 days to pay the tax. Not six months. Thirty days.\n\nGift tax here falls on the person receiving, not the person giving. If you are planning to help family, a deposit for a child buying near you, a transfer of the apartment itself, they are the ones who will face the bill, and the clock is short.\n\nCompare it with inheritance. Beneficiaries of an estate get 6 months, can request an extension, and even late payment escalates gradually: 5 percent added every 3 months, capped at 20 percent on top. Gifts get none of that grace. Thirty days from the gift being made, full stop.\n\nThe rates are not national either. Gift tax varies from region to region across Spain, so an identical gift can produce a very different bill depending on where the assets and the people involved sit.\n\nThis is why the order of operations matters so much for families. The moment to involve an adviser who knows your specific region is before anything moves, when timing and structure are still choices. After the transfer, the only question left is how big the bill is.\n\nParents helping children buy in Spain: treat this as homework for the month before the transfer, not the month after.\n\nGeneral information, not tax advice.\n\n#SpanishTax #GiftTax #SpainProperty",
  "image_url": null
 },
 {
  "slug": "extension_deeds",
  "batch": 2,
  "day": 29,
  "language": "en",
  "member": "",
  "title": "Pools and extensions belong on deeds",
  "source_article": "extension-deeds.txt, renovation.txt",
  "post_text": "In Spain, your pool, enclosed porch or extra floor is legally an extension. If it is not on the deeds, it resurfaces at the worst moment: the sale.\n\nThe proper route runs like this. Structural work needs an Obra Mayor licence. Even non-structural jobs, painting, retiling, same-size window swaps, need the Obra Menor. A licensed technical architect drafts the plans, you file them at the town hall, and if the property shares communal spaces, the community must approve, with its certificate signed before a notary.\n\nThe cost: ICIO tax at 2 to 5 percent of the construction cost, plus a smaller urban development licence fee. Processing runs from a few weeks to several months.\n\nWhen work finishes, the architect issues the Certificado Final de Obra, and the extension is declared before a notary and entered in the land registry. That is what lets the added space count in your asking price.\n\nAlready built without a licence? The antiquity certificate can legalise retrospectively, with a threshold worth knowing: works finished after August 2014 must be 15 years old, versus 4 years for earlier ones. An architect visits to confirm the age.\n\nPlanning bigger works? Confirm the legal viability before you even buy the property, and settle from day one who handles permits. Renovation companies will often do it, though usually as a paid extra.\n\nUnregistered extensions stall sales and carry demolition risk. Legalise before you list, not while a buyer waits.\n\nGeneral information, not legal advice.\n\n#SpainProperty #SpanishHomeOwners #HolidayHome",
  "image_url": "/photos/pool_dusk.jpg"
 },
 {
  "slug": "brexit_buying",
  "batch": 2,
  "day": 30,
  "language": "en",
  "member": "",
  "title": "What Brexit really changed",
  "source_article": "brexit-impact.txt, buyer-visas.txt",
  "post_text": "Brexit did not change the price of a Spanish home by one euro. It changed almost everything around it.\n\nWhat stayed the same: the right to buy never depended on nationality, and the purchase costs, tax, notary and registration fees, are identical for UK and EU buyers.\n\nWhat changed sits downstream.\n\nTax on rental income rose from 19 to 24 percent for Brits. Worse, rental expenses can no longer be deducted before the tax applies, which changes the maths more than the headline rate does. Tax paid in Spain can at least be offset against tax in the UK.\n\nMortgages involve more paperwork and can take longer. NIE appointments can be slower for UK applicants.\n\nTime itself is capped: 90 days in any 180 without a visa. Want the whole summer and autumn? The non-lucrative visa is the classic route for non-workers: proof of roughly 28,000 euros a year for the main applicant plus 600 euros a month per family member, private health insurance, and no working in Spain. It renews after the first year, then every two. The Golden Visa route through 500,000 euro property purchases has closed to new applicants; existing holders can still renew.\n\nNone of this says do not buy. It says model it first. If you plan to rent out or stay long, run the numbers on the 24 percent and the calendar before you commit, not after.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #BrexitSpain",
  "image_url": null
 }
];
