// Agents stream: 30 posts, article-sourced, human voice, audience-woven, no disclaimers. Generated; do not hand-edit.
export default [
  {
    "slug": "ag_epc_advertising",
    "batch": 1,
    "day": 1,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "EPC fines start at the advert",
    "source_slug": "epc_certificates_en",
    "source_slug2": "lost_documents_en",
    "source_article": "epc.txt, lost-documents.txt",
    "post_text": "In Spain the EPC fine starts at the advert, not the sale. Market a property without one and it's 300 to 600 euros before a single viewing happens.\n\nMost agents file the certificate under completion paperwork. It isn't. It has to exist before the property is listed, and a copy goes into the notarial deed when it sells, because notaries may refuse to complete without it. So a missing EPC surfaces twice, on day one of marketing and again at the finish line.\n\nThe fines scale with the offence, too. Advertising without a valid certificate runs 300 to 600 euros, while failing to provide one at all, or falsifying it, runs 1,000 to 6,000. Each autonomous region manages its own inspections and penalties, so enforcement varies by postcode. And the rule isn't just for main homes, holiday properties and even non-residential buildings need one as well.\n\nThe fix, though, is genuinely small. A certified technician inspects insulation, windows, heating, cooling and lighting, then issues the A to G rating. You're looking at 100 to 300 euros and less than a week, start to finish. The certificate lasts ten years and must be registered with the regional authority, which the technician will usually handle.\n\nTwo selling angles hide inside it as well. The certificate lists concrete recommendations for improving the rating, and a strong score can support the price, reassure the foreign buyers you sell to about long-term running costs, and open access to green funding and subsidies. And if the seller has renovated since the last one, new windows, better insulation, it can be worth reissuing early even though the old certificate is still valid, because the improved score becomes part of the listing.\n\nAnd if the seller's lost theirs? The issuing technician or any licensed assessor replaces it for roughly 60 to 150 euros. No drama, just lead time.\n\nSo don't let a listing go live without one on file. Build it into your intake checklist.\n\n#SpainProperty #RealEstateSpain #EPC",
    "image_url": "/photos/sunset_village.jpg"
  },
  {
    "slug": "ag_nota_simple_twice",
    "batch": 1,
    "day": 2,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The Nota Simple sizes the mortgage",
    "source_slug": "nota_simple_en",
    "source_slug2": "land_registry_en",
    "source_article": "nota-simple.txt, land-registry.txt",
    "post_text": "The cheapest document in a Spanish purchase can quietly shrink your buyer's mortgage. Banks read the Nota Simple more carefully than buyers do.\n\nIf the cadastral value on it sits 10k under the price, the bank may lend 10k less. That's the detail from the Land Registry that catches foreign buyers off guard, and it's exactly the kind of thing an agent can flag early.\n\nThe document itself costs around 10 euros online and can arrive the same day, or under 4 euros in person at the registry, where it's usually ready within a few days. You supply the property details or its identifier, the IDUFIR, which the seller or the agent usually has to hand. Anyone with a legitimate interest in buying can request one, and even a friend or family member can order it on the buyer's behalf, since the registrar decides whether the interest is legitimate. If your client needs it translated, that's a further fee worth mentioning upfront.\n\nIt shows the whole picture. The registered owner, when they bought and with which notary they signed, the property description and square metres, boundaries, the land classification, and any charges. Mortgages, unpaid taxes, debts. In Spain those debts sit on the property, so your buyer inherits whatever that page reveals. It also settles quieter questions: that the seller really is the owner, because there have been cases of properties sold by people with no right to sell them, and that no inheritance dispute is hanging over the title.\n\nWhich is why two moments matter. Before the arras, because any debt or discrepancy is far easier to resolve before 10 percent changes hands. And at mortgage time, because when the registered cadastral value comes in below the offer, the bank looks at that lower figure, not the price your buyer agreed.\n\nIf the page shows something unexpected, the next call is a property lawyer, not the seller.\n\nOrder it for every serious buyer before the arras is drafted. Ten euros of paper beats six weeks of surprises.\n\n#NotaSimple #BuyingInSpain #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_arras_window",
    "batch": 1,
    "day": 3,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The arras amendment window",
    "source_slug": "arras_contract_en",
    "source_article": "property-contracts.txt",
    "post_text": "There's a window built into every arras that most foreign buyers never use. The draft arrives a couple of days before signing precisely so someone can request amendments.\n\nIf you sell to foreign buyers, that window is where the deal is really made, because this contract decides everything that follows.\n\nWorth knowing how the document is usually born, too. Most agencies work from a standard template, amended with the exact details of the property as they appear on the Nota Simple, plus the clauses that safeguard both parties. Templates are fine, but they're also why line by line checking matters, because a template doesn't know about this seller's furniture or that buyer's mortgage.\n\nSo what should be inside? An accurate description of the property, address, size and layout. The price. A completion date, usually two to three months out, which has to leave enough time for the buyer's documentation and any mortgage. The penalties if either side pulls out. And then the specifics, meaning furniture the sellers leave, repairs they agreed to fund, whether appliances are included, whether water and electricity will be switched on. If it isn't written here, it was never agreed.\n\nThe stakes are real on both sides. Once signed, a buyer who withdraws loses the 10 percent deposit, and a seller who withdraws pays double. That's why the draft goes out a couple of days early, so the buyer or their representative can read it and push back.\n\nTwo more habits worth building. The 10 percent sometimes goes straight to the owners, which is common, but a safeguarded account at a financial institution is the safer route, so raise it. And on a new build, add completion date clauses of their own, plus a look at the bank guarantee standing behind the staged payments.\n\nSend the draft to your buyer the day it lands, with one line: read this now, not at the table.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
    "image_url": "/photos/pool_dusk.jpg"
  },
  {
    "slug": "ag_offer_accepted",
    "batch": 1,
    "day": 4,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "An accepted offer binds nobody",
    "source_slug": "offer_accepted_en",
    "source_article": "offer-accepted.txt",
    "post_text": "An accepted offer in Spain binds nobody. Either side can still walk away without penalty, because what actually binds is the arras, and that can arrive within days.\n\nIt's the speed that foreign buyers never see coming.\n\nThe sequence goes like this. The property comes off the market, the buyer signs an offer contract, usually at the agency, and transfers 1,000 to 2,000 euros. That sum comes off the fees if the sale proceeds and comes back if it falls through. But nothing yet stops the seller changing their mind. Call this stage what it is, a gentleman's agreement, and your buyer will understand it instantly.\n\nThen the arras lands. Ten percent of the price, terms formally agreed, completion date fixed. Pull out as buyer and the deposit is gone. Pull out as seller and you repay double. Between acceptance and that signature there's sometimes only a matter of days, which makes it a huge commitment on a very short runway.\n\nAnd squeezed into that same gap sits the due diligence: the Nota Simple, confirming the registered owner, checking for debts tied to the property, verifying planning permissions and correct registration. The money has to be ready to move through a Spanish account too, because the transaction and everything after it runs through one.\n\nCompletion itself happens in front of a notary with both parties present, though a buyer who can't travel can sign through power of attorney, and with a mortgage a representative from the bank attends as well. Then comes the quiet tail: registering the property in the buyer's name, moving utilities over, setting up the local tax payments.\n\nFrom deposit to keys usually takes six to ten weeks, stretched or shortened by the mortgage, the seller's circumstances and how fast the documents move. The buyers who sail through are the ones whose NIE, account and funds existed before the offer did.\n\nSo ask the qualifying questions at the first viewing, not at the accepted offer.\n\n#SpainProperty #RealEstateSpain #BuyingInSpain",
    "image_url": null
  },
  {
    "slug": "ag_partner_week_after_keys",
    "batch": 1,
    "day": 5,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The owner's first twelve months",
    "post_text": "Your client's first year of Spanish ownership has a calendar. Nobody hands it to them at the notary, so it tends to arrive one panicked message at a time.\n\nHere's the rough shape of it. Deadlines shift between municipalities and autonomous communities, so treat this as a planning framework and check the local ayuntamiento before quoting a date.\n\nJanuary is tax and review. Rental income declared annually gets filed for the previous year, and it's the sensible moment to check that last year's utilities, community fees, insurance and tax all actually went out.\n\nFebruary is the rental registration question. The NRA, the Número de Registro de Alquiler, is currently on hold after the Supreme Court declared it illegal, so the honest answer to clients is paused, not gone.\n\nMarch is post winter. Plumbing, damp, appliances, heating and water systems, especially on the coast or in a home that sat empty for months. Small fixes now instead of expensive ones in July. It's also when photos and listings get refreshed for the season ahead.\n\nApril is utility contracts. Tariffs move, and plenty of non resident owners sit on an outdated one for years simply because nobody rang round.\n\nMay is summer prep. Air conditioning serviced, pool started, garden cleared, cleaning schedules and key handover confirmed. June is the insurance review, worth doing because Spanish policies renew annually, so there's one window a year to get a competing quote.\n\nJuly brings community fees, often quarterly, often by direct debit, though communities differ wildly and plenty bill in January or monthly. August is quiet, since Spanish offices slow right down or close.\n\nSeptember is post season repairs and checking rental platforms took the right commission. October is the heavy one. IBI usually lands around then on the Costa Blanca, rubbish tax often runs from late July to mid October, and on the Costa del Sol IBI is often billed twice, spring and autumn.\n\nNovember is the banking review, hidden costs and exchange rates. December is imputed income tax, the Modelo 210, usually due by 31 December when it's paid annually.\n\nNone of that is your job, and all of it still reaches you, months after the commission cleared. It's the year Bueno covers for the owner, Modelo 210 filing and property admin included, with human support in their own language. Happy to walk you through how the handover works.\n\n#RealEstateSpain #Proptech #SpainProperty",
    "image_url": "/photos/marina.jpg",
    "source_article": "month-by-month-checklist.txt"
  },
  {
    "slug": "ag_tourist_licence_first",
    "batch": 1,
    "day": 6,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Licence first, yield second",
    "source_slug": "tourist_license_en",
    "source_article": "legally-renting.txt",
    "post_text": "A tourist licence already issued is a selling point you can price. An area where none are granted is a yield pitch you shouldn't make.\n\nThe line between those two matters because any rental contract under three months makes your buyer a tourist landlord, and that requires a licence. There are two types, individual for private owners and collective for companies owning or managing several properties.\n\nThe demand side explains why foreign investors keep asking you about it. More than 85 million tourists visited Spain in 2023, all needing somewhere to sleep, and per night a short let earns far more than a long term tenant pays. The sums should still include the extras, insurance and cleaning among them, but the pull is real.\n\nDon't picture a form, picture a project. The property has to meet hygiene, safety and quality standards, it needs habitability and energy efficiency certificates, and some areas require registration with the local tourism agency. Then the application, with ID and proof of payment, goes to the tourist office, and approval takes one to six months depending on region and demand.\n\nAvailability is the real filter, though. In Barcelona, renting out short term private rooms is illegal, and licences for entire homes are now very hard to come by. Valencia is generally only granting them to ground floor properties in popular areas. Catalunya runs dedicated teams hunting illegal lets. Outside the big cities it's usually easier, but that's something to verify, never to assume.\n\nGetting it wrong costs real money too. Fines typically run 4,000 to 60,000 euros, rising sharply for repeat infractions, and reach 111,000 in Ibiza. A licence also unlocks proper rental insurance and legitimate advertising, and it signals the owner is registered and paying the right tax, which is why listings that already hold one command attention.\n\nSo before the words rental income leave your mouth, confirm licences are actually being issued in that exact area. One call protects the sale and the relationship after it.\n\n#HolidayRental #SpainProperty #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_seller_debt_certificate",
    "batch": 1,
    "day": 7,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Community debt comes off the price",
    "source_slug": "community_fees_en",
    "source_slug2": "hoa_disagree_vote_en",
    "source_article": "community-fees.txt",
    "post_text": "Before any shared building sale closes, find the community debt and deduct it from the purchase price.\n\nThat one habit matters because unpaid fees don't always leave with the seller, they can follow the keys, and if you sell apartments or anything with shared spaces to buyers from abroad, it's your buyer who inherits the surprise.\n\nThe numbers first, since buyers always ask. Fees fund cleaning, gardening, lifts, maintenance, a reserve pot for surprises and the safety work Spanish law requires. Some owners pay around 100 euros a quarter, while high end developments with pools, security and a gym can run past 1,000, and older communities with fewer facilities tend to sit cheaper. The share depends on two things, the services provided and the size of the property, and a bigger share also means more voting weight at the annual general meeting where budgets are set. Payment is usually quarterly, sometimes monthly, occasionally a year upfront, and the budget itself is normally based on the previous year's expenses, so the history is worth a look. When something big lands, an emergency or major works, the community can call an extra meeting and agree additional payments on top of the regular ones.\n\nNow the trap. If the previous owner fell behind, the debt can land on your buyer, because unchecked community debts may become the new owner's liability. The lawyer's job during the purchase is to confirm nothing is outstanding, and where something is, the usual mechanism is simple. The outstanding amount comes off the purchase price so it's settled before the deeds are signed.\n\nWorth telling landlord clients too that when the property is rented out, the fees stay the owner's responsibility, never the tenant's. And communities do escalate, from late fees and interest to court demands where the non payer can end up covering the legal costs of the case as well, and, after years, a forced auction.\n\nSo make the community debt check, and the price deduction, a fixed step in every shared building sale.\n\n#SpainProperty #CommunityFees #RealEstateSpain",
    "image_url": "/photos/cove_house.jpg"
  },
  {
    "slug": "ag_3pct_withholding",
    "batch": 1,
    "day": 8,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The 3 percent withholding",
    "source_slug": "plusvalia_en",
    "source_article": "plusvalia.txt",
    "post_text": "Most buyers find out at the notary's table that they've just inherited two of the seller's tax jobs. It happens whenever the seller is a non-resident, and each job has its own deadline.\n\nIf you list homes owned by foreigners, it's worth explaining at the mandate instead.\n\nJob one is the 3 percent withholding. The buyer holds back 3 percent of the purchase price and pays it to the tax authorities within one month of the sale. It isn't an extra tax, it's a holding against the seller's capital gains bill, which runs 19 percent of the profit for EU and EEA residents and 24 percent for everyone else. The two don't stack, the 3 percent simply secures the rest, and if the final tax comes to less than the amount withheld, the seller is entitled to a rebate of the difference within the year. Even a seller making no profit at all sees the 3 percent withheld first and reclaimed later.\n\nJob two is plusvalia, the municipal tax on the increase in urban land value, the council's way of charging for the infrastructure that grew around the property over the years, transport, hospitals, supermarkets, parks. It's triggered by any transfer, sale, inheritance or donation, and on inheritances and donations it's the receiver who pays. Normally the seller pays it on a sale, but when the seller is a non-resident, the buyer pays it instead, with 30 days from the transfer to get it to the local council before fines start. The amount depends on local rates and the years of ownership, up to a 20 year cap, and if the land value genuinely fell, or the sale closed at a loss, there's an exemption.\n\nNone of this needs drama. It needs a written agreement before completion on who handles which payment.\n\nSo raise it the moment you learn the seller lives abroad.\n\n#SpanishTax #SpainProperty #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_law5768_guarantee",
    "batch": 1,
    "day": 9,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Law 57/68 off plan guarantees",
    "source_slug": "bank_guarantee_en",
    "source_slug2": "arras_contract_en",
    "source_article": "bank-guarantees.txt, property-contracts.txt",
    "post_text": "A law from 1968 is still what stands between your buyer's off plan money and disaster.\n\nOff plan in Spain can mean staged payments of up to 80 percent before the escritura is signed, money the developer uses to finance the build itself, so if you sell new developments to foreign buyers, Law 57/68 answers their biggest fear. Make it part of the pitch.\n\nSince 1968, a developer taking a deposit and staged payments must do two things. First, open a specific bank account for those payments. Not a personal account, not one previously held, and the money in it can only be used for the construction of that property. Second, provide a guarantee that refunds every payment plus interest if the build isn't started, or isn't finished, by the agreed completion date. Developer goes under, disappears, or the project stalls, and the money comes back.\n\nOne detail carries most of the weight. The guarantee must have no expiry date, staying valid until the property is fully finished and deemed safe to live in, because a guarantee that lapses mid build protects nobody.\n\nThe economics explain the behaviour you'll meet. The guarantee costs the buyer nothing but is expensive for developers, which is why some try to work around it, sometimes by dangling better conditions instead. Whatever the sweetener, the advice for any client stays the same. Don't proceed without the guarantee. Framed properly, it's an insurance policy the buyer never pays a premium for: either they get the finished home, or every instalment back with interest.\n\nAnd a practical pairing, since the guarantee bites on the agreed completion date. On a new build the arras deserves its own completion date clauses.\n\nA developer who resists the guarantee has answered your due diligence for you. Walk.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
    "image_url": "/photos/arch_terrace.jpg"
  },
  {
    "slug": "ag_partner_utility_bill_text",
    "batch": 1,
    "day": 10,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Utilities into the client's name",
    "post_text": "Switching the utilities looks like a phone call and behaves like a small project. That gap is where your name ends up on the client's Sunday messages.\n\nStart earlier than most people do. Once the Contrato de Arras is signed, you already know whether the property needs electricity alone or electricity and gas, so that's the moment to look at providers rather than the week after completion.\n\nElectricity and gas can be chosen, though options are limited in some areas and vary by region. Water can't. It comes with the building, run either by a private company or the municipality, and the change of ownership goes through the ayuntamiento, which also issues the new contract. If the property isn't connected to water at all, that's a much longer job, so it needs starting early rather than late.\n\nFor gas, only certain areas and towns are on the mains supply. Where it exists it can be cheaper than electricity, but appliances have to be checked every year for compliance and safety, at around 70 euros. Elsewhere it's canisters delivered to the door.\n\nThe provider will want the same four things every time: name and proof of ID, the NIE, Spanish bank account details, and proof of address such as the purchase paperwork. Then a technician comes out to connect the supply.\n\nOne trap worth flagging. If the client keeps the existing providers rather than switching, check every previous bill has been paid before the new contract is signed.\n\nThen there's the direct debit, which is how most Spanish utilities are paid, monthly or quarterly, and in many cases the only payment method offered. The mandate carries the name, IBAN, reference, amount, frequency and start date. Changing the bank details later is the painful part. There's no automatic switch as in the UK. The customer has to supply precise documentation, receipts and screenshots of every mandate, and even then some companies insist on dealing with the customer directly, sometimes by a recorded phone call.\n\nAll of that lands on the agent, long after completion, unpaid. Bueno gives the owner a Spanish IBAN account, energy switching and property admin tools, with human support in their own language. Worth a look if these calls sound familiar.\n\n#RealEstateSpain #Proptech #ExpatSpain",
    "image_url": null,
    "source_article": "utilities-setup.txt, direct-debit.txt"
  },
  {
    "slug": "ag_three_fifths_ruling",
    "batch": 1,
    "day": 11,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The three fifths tourist let ruling",
    "source_slug": "community_rental_ban_en",
    "source_slug2": "rental_rule_changes_en",
    "source_article": "supreme-court-tourist-ban.txt, rental-rule-changes.txt",
    "post_text": "The Supreme Court has settled a question that split judges across Spain: limiting tourist flats includes banning them outright, and three fifths of owners is enough. No unanimity required.\n\nIf you sell apartments as rental investments to buyers from abroad, that ruling rewrote your due diligence.\n\nIn 2019, article 17.12 of the Horizontal Property Law was amended to let owner communities condition and limit tourist rentals, and two ambiguities followed. Judges across Spain disagreed on whether limiting stretched to an outright ban, and the law never set a voting threshold, so nobody knew if a majority sufficed or unanimity was needed.\n\nThe court answered both. Prohibition is a form of limitation, and three fifths of the vote, 60 percent, is enough. The reasoning matters as much as the result, because the judges weighed the individual's right to rent out property against the collective interest of the people living in the building, and looked at the broader social context rather than the legality of the rental alone. That framing tells you which way future disputes will lean.\n\nThe case that carried it came from Marbella, where residents complained about noise, illegal substances and damage to common spaces from tourist flats. The community voted 48 to 3 to ban them, and the two companies owning the six apartments involved lost in court.\n\nTwo safeguards survive for owners, though. A ban can't be retroactive; the problems must still be ongoing and affecting residents. And it must be properly justified and implemented under the law's requirements, not just voted through.\n\nCommercially, the connection that matters is the new national rental register, which can certify whether the building allows tourist lets. A community ban means no registration code, before any other paperwork starts. And for an owner caught by a vote, the fallback is usually the long term market, a different yield and a different pitch.\n\nSo before pitching short term yield on any apartment, you'll want to read the statutes and ask when the community last voted.\n\n#HolidayRental #RealEstateSpain #SpainProperty",
    "image_url": "/photos/couple_beach.jpg"
  },
  {
    "slug": "ag_fx_completion_funds",
    "batch": 1,
    "day": 12,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Completion money, on time",
    "source_slug": "currency_transfer_en",
    "source_slug2": "sepa_swift_en",
    "source_article": "currency-transfer.txt, sepa-swift.txt",
    "post_text": "Completion funds that arrive late can cost your buyer the 10 percent deposit, because the deadline is fixed in the arras. The exchange rate isn't.\n\nThat mismatch is why the transfer plan belongs in your post arras conversation, not in the panicked week before the notary.\n\nRoute comes first. SEPA covers euro payments across the EU, EEA and the UK using nothing more than an IBAN, and it's faster and cheaper than the alternative. SWIFT routes money through correspondent banks, each of which needs paying, which makes it slower and more expensive, and it's the network anything from outside Europe will travel on. Most UK banks send European transfers as SEPA by default, and a UK IBAN already contains the familiar account number and bank details, but the instruction that matters is simple: send euros, on the SEPA network.\n\nTiming comes second. Exchange rates change throughout the day, and on a purchase sized sum a small difference is real money. Rather than guessing, the buyer can set rate alerts and transfer when the level works in their favour, with completion as the hard stop.\n\nProvider comes third. Whoever moves the money should hold client funds in segregated accounts, separate from the business's own money, be upfront about fees, and handle regular automated payments if the buyer will later move a pension or pay a mortgage from abroad.\n\nOne local quirk deserves a mention too. Spain runs its own domestic payment network alongside SEPA, and many direct debits only work through Spanish accounts. It's actually the utility company that creates the debit and collects from the account, which is why the banking setup belongs in the same conversation as the transfer plan.\n\nAdd one line to your post arras email, and make it plan your transfer timeline today.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_rural_land_checks",
    "batch": 1,
    "day": 13,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Four checks for rural land",
    "source_slug": "rural_property_en",
    "source_article": "rural-property.txt",
    "post_text": "Rural property in Spain fails checks that urban flats pass without breaking stride. Four of them decide whether your finca sale survives due diligence, so let's walk through them.\n\nThe title deed comes first. If it doesn't exist, or it's outdated or inaccurate, the sale should wait while the vendor updates the missing details at the Land Registry, at their expense, and the buyer's lawyer checks the registry before anything proceeds.\n\nThen paper versus ground. The Land Registry and the Cadastral Registry frequently disagree with real life on plot size, description and boundaries, and any discrepancy brings legal and financial consequences. The cadastral records can be checked online, so there's no excuse for skipping it. Rural land also carries easements urban homes rarely see: rights of way, rights of view, rights to extract water. Your buyer should know who can cross the land before it's theirs. And confirm the vendor really is the registered owner, which a Nota Simple settles; an owner lookup runs about 9 euros, plus around 30 for an English translation your foreign buyer can actually read.\n\nThird, is the build legal? Some owners register a casa de aperos, a shed, to get around planning restrictions, then build a villa on it. A surveyor can confirm whether the property has Town Hall permission, and if it doesn't, the advice is blunt: walk away and avoid the legal battle. Pre 1956 constructions are usually legal without a licence but often can't be extended.\n\nFourth, water out, not just in. Electricity and running water are easy to spot on a viewing; wastewater is where the surprise hides. Rural homes often run on septic tanks that cost money to empty, and a renovation can force a modern replacement costing thousands.\n\nSo recommend an independent rural surveyor before any offer, and treat a local lawyer as essential rather than optional on rural deals. Every time.\n\n#RuralSpain #SpainProperty #RealEstateSpain",
    "image_url": "/photos/poolside.jpg"
  },
  {
    "slug": "ag_notary_role",
    "batch": 1,
    "day": 14,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The notary is not their lawyer",
    "source_slug": "escritura_notary_en",
    "source_slug2": "land_registry_en",
    "source_article": "property-contracts.txt, land-registry.txt",
    "post_text": "Foreign buyers assume the notary is on their side. In Spain the notary is impartial by design, which means nobody at that table represents your buyer unless someone fixes it early.\n\nIt's worth explaining at the first meeting, because it changes who your client hires.\n\nAt the escritura publica, the notary prepares and oversees the deed, reads it out to buyer and seller together, and checks both fully understand before anyone signs. If the buyer's Spanish is weak, the notary may require a translator or a Spanish speaking legal adviser in the room. With a mortgage there's more structure still, since the FEIN with the loan conditions must be signed at least 10 days before the mortgage deed, those 10 days being a legal requirement so the terms can sink in, and the buyer meets the notary at least 24 hours ahead so the conditions are explained first. A cash buyer skips the FEIN and instead signs a purchase contract, the compraventa, drawn up by a legal representative or sometimes the agency.\n\nWhat the notary doesn't do is represent anyone. They act as an impartial adviser to both parties and confirm the sale is legal, and that's the whole job. The checks beyond legality belong to the legal adviser your buyer may not have hired yet.\n\nAnd signing isn't the finish either. The property and its new owners still need registering at the Land Registry, and only once registered is ownership officially recognised. Rural areas may have a single registry office while cities can have many, Valencia has 18 and Alicante 8, and the right one appears in the first line of the Nota Simple; the notary will point to it too.\n\nSo tell every foreign buyer at viewing one to bring their own adviser to the table.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_partner_aftersales_list",
    "batch": 1,
    "day": 15,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The Modelo 210 questions clients ask",
    "post_text": "Most Modelo 210 questions your buyers ask aren't about the formula. They're about their own situation, and the answers change completely depending on it.\n\nStart with the four scenarios.\n\nNot renting it out. One annual return, reporting the previous year's ownership. So a purchase this year produces its first return next year. It can be filed at any point, but it has to be paid by the end of the year.\n\nRenting it out all year. No annual return. Rental income is declared quarterly instead, in the year it was earned, with deadlines on the 20th of April, July, October and January.\n\nRenting it out part of the year. Both. Quarterly declarations for the rented days, plus the annual return for the days it wasn't.\n\nSelling. The annual return runs up to the sale date, filed early the following year, while any rental income still gets declared during the current year.\n\nThe calculation itself is short. Take the cadastral value from the IBI bill, multiply by 2 percent, or 1.1 percent where the municipality has had a general cadastral revision in the previous 10 tax years, then by 19 percent for EU and EEA residents or 24 percent for everyone else, including the UK. A cadastral value of 45,986 euros at 2 percent and 24 percent comes out at around 220 euros for the full year.\n\nTwo details clients rarely see coming. The tax is split between owners, so two names on the deed means two separate returns, each for their share. And the booking platforms now report rental revenue to the Spanish tax office directly.\n\nThe penalty side rewards moving early. File voluntarily before the tax office makes contact and penalties can be avoided. Pay 1 to 12 months late and the surcharge is 1 to 12 percent of the tax owed. Past 12 months it's 15 percent plus interest. Let the tax office reach the owner first and the fine can be at least 50 percent of the tax, plus interest.\n\nNone of this is your job, yet the question lands on you every December. Bueno files the Modelo 210 for the owner and answers those questions in their own language. Say the word if you'd like to see it.\n\n#RealEstateSpain #Proptech #SpainProperty",
    "image_url": "/photos/coast_bay.jpg",
    "source_article": "non-resident-property-tax.txt"
  },
  {
    "slug": "ag_ibi_attaches",
    "batch": 1,
    "day": 16,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "IBI stays with the house",
    "source_slug": "ibi_deep_en",
    "source_article": "ibi-tax.txt",
    "post_text": "IBI has a long memory. Unpaid bills can stay attached to the property through a sale, which makes the seller's arrears your buyer's problem unless someone checks.\n\nTwo sides of this tax matter to an agent. The buyer side first. When ownership changes, the land registry updates and the council knows who to bill, but arrears don't reset. Unpaid IBI can remain attached to the home, with charges placed against it, and it surfaces exactly when someone tries to sell. Checking the position before purchase is basic protection, and your foreign buyer won't know to request it.\n\nThen there's the owner side, which becomes the same client's problem within a year. The bill is the cadastral value, an official valuation based on location, size, age and characteristics, usually below market value, multiplied by the municipal rate. Across Spain that rate averages 0.3 to 1.1 percent. Santander, Zaragoza and Madrid sit low, while parts of Catalunya and the Costa Blanca run higher. What it buys is entirely local: rubbish collection, street lighting, parks, the infrastructure around the home.\n\nBills land between May and October in many municipalities as the Recibo de IBI, stating the amount, the deadline and how to pay, and some councils no longer post abroad. Miss one and the sequence runs from reminder letter to surcharges starting around 5 percent and climbing to 20 or more, then debt collection, which can mean money seized from the owner's Spanish account. If a client inherits arrears or falls behind, the honest advice is to call the town hall rather than hide, because they'll usually negotiate a payment plan with anyone who shows willingness to settle.\n\nThe fix costs nothing, though. A direct debit with the town hall and electronic notifications, set up while the keys are still warm, receipts kept for the file. Paying online through the town hall website or in person works too, but only for owners who actually see the bill arrive.\n\nSo check the IBI position before every sale, and hand over the direct debit tip with the keys.\n\n#IBI #SpanishTax #SpainProperty",
    "image_url": null
  },
  {
    "slug": "ag_true_buying_costs",
    "batch": 1,
    "day": 17,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The real price is 12 to 14 more",
    "source_slug": "buying_fees_en",
    "source_slug2": "buying_cost_stages_en",
    "source_article": "buying-fees.txt, cost-of-buying-expats.txt",
    "post_text": "Move the same home a few regions over and the tax bill shifts by thousands. The 12 to 14 percent on top of the asking price isn't a flat number, so your buyer should see the breakdown early.\n\nFollow the money in the order it leaves. A reservation fee of 1,000 to 6,000 euros secures the bid while the arras is drawn up, refunded if the sale falls through in that window. Then comes the 10 percent arras deposit.\n\nThe tax layer is the regional one, and it's where the spread lives. On resales, transfer tax runs from 4 percent in the Basque Country to 6 in Madrid and 10 in Valencia and Catalonia. New builds skip it and pay 10 percent VAT plus a document fee of roughly 0.5 to 1.5 percent. That's why the same budget stretches differently a few kilometres apart.\n\nThe fixed layer is steadier. Notary fees sit around 1,000 euros on a 250,000 euro purchase, land registry fees run 400 to 700 and are set by the government, and a lawyer costs a few thousand euros or a gestor a few hundred.\n\nBorrowing adds bank setup fees of up to 2 percent of the loan, plus valuation reports of 250 to 600 euros that should be the bank's cost but sometimes land on the buyer. Worth knowing the base rate of that conversation, though: 60 to 70 percent of foreigners buying in Spain never take a Spanish loan at all. And when a bank does lend, it usually pushes its own life insurance alongside, which can cost roughly twice what the open market charges, so the buyer is free to shop around, even if the bank then adjusts the interest rate.\n\nOn used homes there's often room to haggle, though, which is where the costs get clawed back.\n\nGive every buyer a written, region specific cost sheet at the first serious conversation.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
    "image_url": "/photos/golden_coast.jpg"
  },
  {
    "slug": "ag_100pct_tax_calm",
    "batch": 1,
    "day": 18,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The 100 percent tax, calmly",
    "source_slug": "noneu_tax_proposal_en",
    "source_article": "noneu-100-tax.txt",
    "post_text": "Your UK buyer read about a 100 percent tax on non EU purchases and froze. Fair enough, it's a scary headline. What the proposal actually says is a lot calmer.\n\nStatus first. It's one of twelve measures announced by the Prime Minister to tackle the housing crisis, alongside things like refurbishing empty homes into affordable stock, tightening the rules on seasonal rental fraud and reducing tourist licences. The 100 percent tax itself remains a proposal being studied, with no set mechanism or date. Nothing has changed at the notary. In Valencia today, residents, non-residents and Spanish citizens alike pay the same 10 percent transfer tax.\n\nWho would it target? Non-EU residents, meaning anyone spending under 183 days a year in Spain, which includes UK and US buyers of second homes.\n\nThe context your buyer half read is real. Property prices have almost doubled in a decade, rents in Madrid and Barcelona rose by as much as 33 percent in five years, and the Golden Visa closed on April 3rd 2025, ending residency through 500,000 euro property purchases.\n\nNow the scale, which is the genuinely useful part. In 2023, foreigners bought 15 percent of Spanish properties, 87,000 out of 583,000 sales. Non-EU residents accounted for 27,000, around 5 percent, mostly from the US, UK, Morocco, Venezuela and Mexico, and mostly coastal holiday homes rather than the city centres where the crisis bites hardest. Critics add that squeezing a UK buyer off the coast mostly frees the home for other European buyers, German, French, Belgian, rather than for Spaniards, and that the structural answer is building more homes. Which is part of why the measure is being studied rather than rushed.\n\nSo the honest line for a worried buyer goes like this. Watch the legislation, plan on today's rules, and don't restructure around a draft that doesn't exist yet.\n\nSave these numbers. You'll need them at a viewing soon.\n\n#SpainProperty #RealEstateSpain #BuyingInSpain",
    "image_url": null
  },
  {
    "slug": "ag_scam_red_flags",
    "batch": 1,
    "day": 19,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Scam red flags for foreign buyers",
    "source_slug": "scams_en",
    "source_slug2": "land_registry_en",
    "source_article": "scams.txt",
    "post_text": "Scammers pick foreign buyers on purpose. Distance, language and urgency do half the work for them, which makes your clients the exact demographic and you the first line of defence.\n\nMost of the communication happens remotely, several third parties sit between buyer and seller, and every extra link in that chain is a place a scammer can stand.\n\nStart with the listing that doesn't exist. A real property, reposted at an irresistible price, then a reservation fee requested before any viewing, sometimes with the line that this is normal in Spain. It isn't. Someone should always view in person, and no money moves without legal confirmation.\n\nThen the bait and switch. The perfect listing was just sold, but here's a similar one, more expensive and not quite right. Check how long a property has been on the market, be wary of listings reposted unusually often, and hold the budget.\n\nThe hijacked email is the nastiest. Criminals impersonate agents, lawyers, even notaries, intercept a thread and alter the payment instructions, usually with a same day deadline. So verify bank details verbally or in person before sending, and treat any change of payment instructions as an alarm, not an update. Legitimate details normally arrive in a formal document with everything clearly laid out, and a client who can't attend in person can appoint someone they trust, or a power of attorney, to do the face to face checks for them.\n\nThere's also the licence that doesn't exist, where buyers get told a property holds a tourist licence or sits where one is obtainable. Check whether short term rentals are permitted in that area, and whether an existing licence actually transfers between owners.\n\nAnd the fake demand, urgent letters about unpaid taxes or community fees. Verify with the community administrator or tax authority before paying anything.\n\nSend your buyers this list before their first deposit. Honest sellers never mind the extra day.\n\n#PropertyScams #SpainProperty #RealEstateSpain",
    "image_url": "/photos/terrace_sunset.jpg"
  },
  {
    "slug": "ag_partner_saying_no",
    "batch": 1,
    "day": 20,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The town hall bills nobody forwards",
    "post_text": "Your buyer will get letters from an office they've never heard of, in a language they don't read, about bills that don't stop if they're ignored.\n\nThat office is the Oficina de Recaudación Municipal, and it isn't the national tax agency. The Agencia Tributaria handles income tax and VAT. The municipal office collects local taxes for the ayuntamiento, and in some areas a provincial body does it instead, such as Suma Gestión Tributaria in Alicante or the Patronato de Recaudación in Málaga.\n\nThree bills come from there. IBI, calculated on the cadastral value times the municipal rate, which averages 0.3 to 1.1 percent across Spain and is billed by many municipalities between May and October as the Recibo de IBI.\n\nThen rubbish tax, the tasa de basura, which surprises foreign owners most often because it applies whether or not anyone lives there. It runs roughly 50 to 200 euros a year depending on the size and type of property and local waste policy, and some councils calculate it on water consumption or the number of bins. It's usually billed once a year, often between June and October, and it's usually the owner who pays, though some municipalities charge the occupier.\n\nAnd vehicle tax, IVTM, if the client keeps a car in Spain. Around 20 to 60 euros a year for small vehicles, up to 150 for mid sized ones, over 200 for powerful or high emission ones, often due on 1 January.\n\nThe real failure point is correspondence. Some councils no longer post abroad, so the client has to ask for electronic notifications and keep contact details current. Miss a bill and the sequence is predictable: reminder letter, then surcharges starting around 5 percent and climbing to 20 or more, then debt collection, which can mean money seized from the Spanish account and charges placed against the property. Unpaid IBI stays attached to the home, and it surfaces the day someone tries to sell it. If a client does fall behind, tell them to call the town hall rather than hide, because councils usually negotiate a payment plan.\n\nAll of this reaches you months after completion, and nobody pays you for it. Bueno gives the owner property admin tools and a Spanish account to pay from, with human support in their language. Ask me if you want to see the handover.\n\n#RealEstateSpain #Proptech #SpainProperty",
    "image_url": null,
    "source_article": "local-tax-office.txt, ibi-tax.txt"
  },
  {
    "slug": "ag_market_calendar",
    "batch": 1,
    "day": 21,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The market calendar as a tool",
    "source_slug": "market_seasons_en",
    "source_article": "market-seasons.txt",
    "post_text": "Spring sells, autumn competes, winter negotiates, and August simply stops. In Spain the calendar is a pricing tool.\n\nForeign clients don't know this rhythm, which makes it easy value for you to hand over.\n\nSpring is prime selling season because buyers want to have exchanged well before the warm weather, and homes show at their best, gardens and balconies in bloom. Curbside appeal isn't a small thing in listing photos.\n\nSummer brings tourists who combine the holiday with a property hunt, so visibility runs high. One counterintuitive note for sellers of holiday homes, though: peak season rental income can be worth more than a summer sale, so sometimes the right advice is rent it out now, list it after. But August is its own rule. Many estate agents, lawyers and banks are on holiday, several Spanish companies close for almost the entire month, and a completion scheduled across it will stall.\n\nAutumn runs hot for a different reason. Tourists head home wanting their own slice of Spain, and families push to finalise before the new school year. That competition can drive up prices, especially in popular coastal towns, which favours your sellers and squeezes your buyers.\n\nWinter is the buyer's window. Few people make a big financial decision with Christmas around the corner, so sellers are more willing to negotiate and prices can sit lower than at other points in the year.\n\nThe rhythm also changes with geography. Madrid, Barcelona, Valencia and Seville stay fairly consistent year round, coastal second home markets swing hardest with the seasons, and rural areas move slower whatever the month. Interest rates sit underneath all of it, since cheaper borrowing pulls more buyers into the market and dearer borrowing thins them out.\n\nTwo local quirks worth knowing: the Fallas in Valencia in March and Seville's feria in May both create noticeable spikes in interest around them.\n\nPut plainly, sellers aim for late summer or early autumn, buyers hunt in winter, and every timeline you draft routes around August.\n\n#SpainProperty #RealEstateSpain #BuyingInSpain",
    "image_url": "/photos/sunset_village.jpg"
  },
  {
    "slug": "ag_resale_questions",
    "batch": 1,
    "day": 22,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "New build or resale, wrong question",
    "source_slug": "new_build_vs_resale_en",
    "source_slug2": "renovation_permits_en",
    "source_article": "key-questions.txt, new-build-vs-resale.txt, renovation.txt",
    "post_text": "Buyers agonise over new build versus resale, but honestly that's the wrong question. The right one is what becomes your buyer's problem the day the property is in their name.\n\nWith a resale in Spain, hidden defects and illegal renovations transfer with the keys. Once the home is in the buyer's name they're the buyer's issues, and they can be very expensive to resolve.\n\nWhich is why the questions matter more than the finish. How long has it been on the market? Why is the owner selling? Has it been renovated before? What do community fees, utilities and insurance actually cost? Does it need maintenance or repairs? Are there outstanding debts, which the Nota Simple will confirm anyway? What are the neighbours like?\n\nAn agent who asks these out loud, in front of the client, is doing visible due diligence, and that's what foreign buyers remember and repeat.\n\nThree details still surprise people. The tax differs by type, since resales carry transfer tax while new builds carry VAT instead, and IBI is based on the cadastral value, varying by region and by whether the home is a new build. Community fees can run higher on new developments with modern pools and common areas, so check the expected figure before commitment. And renovation plans need permits from the town hall for each aspect of the work, so their legal viability should be confirmed before the purchase, not after.\n\nTwo more things worth saying out loud to a buyer weighing the options. Heavy negotiation on resale prices is normal in Spain, so the listed gap between old and new is rarely the real gap. And any renovation will cost more than the budget says, every time, so a contingency pot belongs in the plan from day one, ideally aimed at the upgrades that resell, insulation, solar, energy efficiency, because green credentials are becoming one of the bigger selling points in the market.\n\nRecommend an expert inspection before any resale offer. Standard for you, a revelation for them.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_nie_timing",
    "batch": 1,
    "day": 23,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "NIE timing breaks timelines",
    "source_slug": "nie_application_en",
    "source_slug2": "nie_realities_en",
    "source_article": "nie-application.txt, buying-documents.txt",
    "post_text": "Apply for the NIE too late and the purchase can't complete. Apply too early and the document ages out before the deal reaches the notary.\n\nBoth failures come from the same rule. For a property purchase, the NIE your buyer shows must be recently issued, because the initial document is only valid three months for that purpose. So if you sell to foreign buyers, this is where timelines quietly break, and the application should be timed to the buying window, not to convenience.\n\nThe process itself has friction worth warning about. The fee, around 11 euros, is paid first at a bank branch using form 790, because the police station rarely takes the payment and online isn't usually an option, and the stamped proof goes to the appointment. The application itself is the EX-18, submitted in Spanish in two copies; the English version is a guide, not a valid submission. Add a passport with at least a year left, two photocopies, two photos, and a translated letter explaining the reason, a purchase agreement works. Non EU citizens bring their visa or landing card. Smart applicants pack extras too, a proof of address and a second piece of photo ID, because requirements shift between regions and municipalities.\n\nAppointments are booked on the official site by province, with different application types for EU and non EU citizens. Without one, the queue starts early and many stations stop letting people in around 13:30. Don't count on English at the counter either, so a client going alone should carry the key phrases written down. Brits can wait longer than EU applicants, and if that's all too slow, the alternatives are the Spanish consulate at home or a lawyer applying on the buyer's behalf.\n\nSo ask about the NIE before your client books the viewing trip, and diarise the three month window against the likely completion date.\n\n#NIE #BuyingInSpain #RealEstateSpain",
    "image_url": "/photos/pool_dusk.jpg"
  },
  {
    "slug": "ag_paperwork_sequence",
    "batch": 1,
    "day": 24,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Paperwork before the search",
    "source_slug": "buying_documents_en",
    "source_article": "buying-documents.txt",
    "post_text": "The buyers who complete on time in Spain all did their paperwork before the search started. That's the pattern, so the sequence is worth handing every foreign lead.\n\nIdentity and money come first. A passport or ID card with at least six months left. The NIE, applied for early, because Brits can wait longer for appointments and the consulate route takes several weeks. And proof of financial solvency ready to show, meaning tax returns, payslips or income certificates plus recent bank statements, since Spanish banks are required to lend only to people who can demonstrably repay.\n\nThen the account. Taxes and fees in the purchase are paid through a Spanish bank account, and many utility providers only work with Spanish accounts, so it isn't admin, it's infrastructure. One warning to pass on: free banking offers in Spain often aren't free once card charges and minimum spending conditions kick in, so the client should read the terms, not the headline. A non-resident certificate is sometimes requested for banking, available from the police station or the requesting bank.\n\nThen, per property, the Nota Simple, a few euros in person and a little more online. It shows the debts associated with the property, and because in Spain those transfer to the new owner, that page is what your buyer is really buying.\n\nWhen the offer lands, it runs in order. An offer contract with a reserve fee of roughly 1,000 to 2,000 euros, refundable if the sale falls through, stating the offer price, the target completion date and whether a mortgage is involved. Then the arras draft a few days before signing, with 10 percent due at signature. And on deed day the whole file travels to the notary, because the public deed of sale is signed with every one of these documents in the room.\n\nSo turn this into a one page checklist and send it with your first reply to every foreign enquiry.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_partner_handover_service",
    "batch": 1,
    "day": 25,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Why the Spanish account freezes",
    "post_text": "Plenty of owners discover their Spanish account is frozen the same week they arrive for the summer, when the electricity is already off and the card doesn't work.\n\nFreezing is legal. Under the money laundering and terrorist financing rules, a bank has to identify the account holder and monitor transfers, and can freeze the account if activity looks suspicious or it's told the activity is illegal.\n\nBanks generally do notify, usually by formal letter setting out the reason and the steps to fix it. Two exceptions matter for your clients. Where the freeze comes from a legal demand, the notice can arrive from the authority instead, such as the Agencia Tributaria. And where the bank suspects money laundering, it may freeze first and tell the holder later, having reported the case to Spain's Financial Intelligence Unit. All of it arrives by post, in Spanish, at a house nobody's checking.\n\nThe common causes are dull and preventable. Expired documents come first, an out of date passport, foreigner's identity card or residence permit, and that one usually clears within a few days of sending updated papers. Then tax debt, unpaid IBI, income tax or non resident tax, where the tax agency can freeze the account as part of debt collection. Then missed mortgage or loan repayments.\n\nAfter that, anti money laundering checks, where the bank asks about the holder's profession or an explanation for a particular transaction and gets no reply. Legal orders come next, a civil suit or a divorce, and joint accounts are especially exposed. Then suspected fraud, where unusual transactions or large withdrawals trigger a precautionary freeze. And finally a breach of the terms the client signed without reading.\n\nTwo habits prevent most of it. Keep identity documents and contact details current with the bank, and warn the bank before anything out of the ordinary, like completing a property purchase or using the Spanish card abroad.\n\nYou'll hear about it first, because you're the person in Spain they know, and it isn't your job. Bueno gives the owner a Spanish account with multilingual support behind it, so questions like this go somewhere else. Happy to show you how it works.\n\n#RealEstateSpain #Proptech #SpainProperty",
    "image_url": "/photos/marina.jpg",
    "source_article": "frozen-account.txt"
  },
  {
    "slug": "ag_unregistered_extensions",
    "batch": 1,
    "day": 26,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Extensions not on the deeds",
    "source_slug": "extension_deeds_en",
    "source_article": "extension-deeds.txt",
    "post_text": "That pool the seller added without paperwork? Notaries and buyers will demand it on the deeds, and the risk scale ends at demolition. So check at listing, not at completion.\n\nThe definition is broader than sellers think, too. Pools, extra floors, bigger rooms and an enclosed porch all count as extensions. Structural work needs the Obra Mayor licence, and even non structural jobs, painting, retiling, replacing windows in the same size and position, need the Obra Menor.\n\nThe proper route isn't quick. A licensed technical architect drafts the plans and project documentation, and an architect is needed even for minor work the moment it touches structure or layout. The file goes to the town hall with the project reports, proof of the architect's registration, proof of fee payment, proof of ownership, ID and NIE, and processing takes anywhere from a few weeks to several months. If the property shares communal spaces, the neighbours must approve, with the community's certificate signed before a notary. Budget the ICIO tax at 2 to 5 percent of construction cost plus a smaller urban development fee. When the work finishes, the architect issues the Certificado Final de Obra and the extension is declared before a notary into the land registry.\n\nFor work done without a licence, there's the antiquity certificate, which can legalise retrospectively. The catch is worth memorising, because extensions completed after August 2014 must be 15 years old, versus 4 years for earlier ones, and an architect confirms the age on site. The dates can shift by region, and community consent is still needed even when the work was finished years ago.\n\nThere's an upside to selling with it done, too. Once the extension sits in the deeds, the extra space and value count towards the asking price instead of against the sale.\n\nSo walk every new listing against its deeds, and start sellers legalising the day you take the mandate, because your foreign buyer's lawyer will find it either way.\n\n#SpainProperty #SellingInSpain #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_rental_registration_2025",
    "batch": 1,
    "day": 27,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The 2025 rental registration number",
    "source_slug": "rental_rule_changes_en",
    "source_article": "rental-rule-changes.txt",
    "post_text": "Every rental advert in Spain now points to a registration number, and the platforms themselves must check it.\n\nSo the responsibility stopped being only the landlord's. If you or your clients market rentals for foreign owners, this system is the new baseline.\n\nThe scheme rolls out from January 2025, with a voluntary phase first and the mandatory switch expected towards the end of 2025. Every property advertised for tourist or short term rental needs its own identification number from a single national register, displayed on the advert, and platforms are required to ensure listings carry it. Short term has its own definition too, more than a month and less than a year, so the register captures far more than holiday flats.\n\nRegistration runs through the central electronic office of the Colegio de Registradores. It asks for proof of ownership and proof of compliance with local and regional rules, and it can certify whether the residents' association allows tourist rental. That last part bites, because a building that voted to ban tourist lets means no code, before any other paperwork starts. Through the register, the authorities can also see what portion of the property is rented, entire home or a single room, the type of agreement, how many people can stay and whether a tourist licence exists. Advertise without a code and the fine can come from the local council, the regional authority or consumer law enforcement.\n\nThe number lasts 12 months, and renewal means listing the leases from the past year plus, for short lets, a declaracion responsable justifying why they were short term. Work, an academic year, medical treatment.\n\nWhy does it exist at all? Various sources suggest up to 90 percent of properties that should hold a tourist licence don't, and that's exactly what it's built to surface. And in cities where few licences are granted, owners who can't qualify are left choosing between the short term register and the long term market.\n\nTwo habits to build now: check the community statutes before promising rental income, and put the renewal date in the calendar.\n\n#HolidayRental #SpainProperty #RealEstateSpain",
    "image_url": "/photos/cove_house.jpg"
  },
  {
    "slug": "ag_brexit_briefing",
    "batch": 1,
    "day": 28,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "Brexit answers for UK buyers",
    "source_slug": "brexit_buying_en",
    "source_slug2": "buyer_visas_en",
    "source_article": "brexit-impact.txt, buyer-visas.txt",
    "post_text": "Brexit didn't change the price of a Spanish home by one euro. Your UK buyers still ask, though, so it's worth having the answers ready with the numbers attached.\n\nStart with what stayed the same. The legal right to buy never depended on nationality, and the purchase costs, tax, notary and registration fees are identical for UK and EU buyers. Say it clearly, because plenty of Brits assume the door half closed.\n\nWhat changed sits downstream, in the owning. Non resident income tax on rental income rose from 19 to 24 percent for Brits, and rental expenses can no longer be deducted first, though tax paid in Spain can be offset against UK tax. So if the pitch involves yield, model the 24.\n\nTime is capped at 90 days in any 180 without a residence permit. For buyers who want more, two visas do the heavy lifting. The non lucrative visa asks for roughly 28,000 euros a year in financial means plus around 600 euros a month per family member, alongside private health insurance, a clean criminal record and a medical certificate. It's renewed after one year and then every two, there's no working in Spain under it, and keeping the residency means genuinely spending time in the country, which suits retirees far better than occasional visitors. The digital nomad visa suits remote workers earning around 2,500 euros a month, mostly from clients or employers outside Spain, with health insurance and proof of qualifications or experience alongside. The Golden Visa is closed to new applicants, though existing holders can renew, and its old appeal, residency with no minimum stay, is exactly what no current route replaces.\n\nTwo frictions to schedule around: mortgages for UK nationals involve more paperwork and can take longer, and NIE appointments can be slower for Brits.\n\nTurn these five points into your standard UK buyer briefing.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
    "image_url": null
  },
  {
    "slug": "ag_modelo210_answer",
    "batch": 1,
    "day": 29,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "The Modelo 210 answer on the spot",
    "source_slug": "modelo210_scenarios_en",
    "source_slug2": "modelo210_en",
    "source_article": "non-resident-property-tax.txt, irnr.txt",
    "post_text": "Every foreign buyer eventually asks what the home will cost them in tax each year. Sketch the Modelo 210 answer on the spot and you've earned their trust instantly.\n\nEvery non resident owner files it, even when the property earns nothing, and the answer is small enough to memorise.\n\nThe formula runs cadastral value times 2 percent, or 1.1 percent where the municipality has had a general cadastral revision in the previous 10 tax years, times 19 percent for EU and EEA residents or 24 percent for everyone else, times days owned over 365.\n\nThe numbers calm people down. A UK owner with a cadastral value of 45,986 euros pays around 220 euros for a full year. That's it.\n\nNow the scenarios worth carrying. Buy mid year without renting, and the first return is due the following year, paid by year end, covering only the days of ownership. Sell, and the owner files for the days up to the sale, early the next year. Rent it out and the rhythm changes, because rental income is declared quarterly, by the 20th of April, July, October and January, with the annual return still covering any empty days. Booking platforms now report revenue to the Spanish tax office. And co-owners each file their own share, so two names on the deed means two returns.\n\nThe penalty ladder rewards honesty, so quote it precisely. File voluntarily before the tax office makes contact and penalties can be avoided entirely. Pay between 1 and 12 months late and the surcharge runs 1 to 12 percent of the tax owed. Beyond 12 months it's 15 percent plus interest. But if the tax office reaches the owner first, the fine can reach at least 50 percent of the tax owed.\n\nOne nuance for landlord clients: straightforward holiday lets are exempt from VAT, but hotel style services like meals or regular cleaning bring 10 percent VAT, and a sublease contract with a broker or platform makes the rental commercial at 21.\n\nPull the cadastral value from the IBI bill and run the numbers with your buyer.\n\n#Modelo210 #SpanishTax #RealEstateSpain",
    "image_url": "/photos/arch_terrace.jpg"
  },
  {
    "slug": "ag_partner_99_euros",
    "batch": 1,
    "day": 30,
    "language": "en",
    "member": "",
    "audience": "agents",
    "title": "What the holiday home costs a year",
    "post_text": "Buyers ask what the place costs to run and usually get a shrug. There's a better answer, and it's more useful than any yield conversation.\n\nFor a typical apartment of 50 to 100 square metres, based on what owners actually pay, the monthly picture looks roughly like this.\n\nCommunity fees around 50 euros, with large variations between communities. Electricity around 100. Gas around 25, and where there's no gas the electricity figure goes up instead. Water around 25. Internet around 30. Insurance around 20. IBI around 50. A renovation reserve of about 10. National tax around 15. A Spanish payment account, roughly 8 a month.\n\nThat comes to about 333 euros a month as a simple estimate.\n\nThen the two extras most buyers forget. A company to look after the property while they're not there adds 50 to 100 euros a month. An alarm, which is worth having on a home that stands empty, is about another 50. So a realistic figure for an apartment is 400 to 500 euros a month, not the 333.\n\nFor a detached house or villa in active use through the year, double that or more. Electricity alone can run 300 to 500 euros a month in summer if the air conditioning is working hard, and a pool pushes the water bill up substantially.\n\nThe value of saying this out loud at viewing stage is that it changes the conversation. A buyer who's budgeted 500 a month doesn't get a nasty surprise in year one, doesn't fall behind on IBI, and doesn't come back to you in March asking why the bills look like this.\n\nThat running cost list is the part of ownership that lands on the agent afterwards, question by question, unpaid. Bueno is one subscription at 99 euros a year covering the Spanish account, energy switching, Modelo 210 filing, insurance and multilingual support, which is what sits behind that 8 a month line. Give me a shout if you'd like the detail.\n\n#RealEstateSpain #Proptech #SpainProperty",
    "image_url": null,
    "source_article": "holiday-home-cost.txt"
  }
];
