// Attorneys stream: 15 posts, rewritten from the full blog articles (studio/articles). Generated; do not hand-edit.
export default [
 {
  "slug": "at_arras_window",
  "batch": 1,
  "day": 1,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "The arras amendment window",
  "source_slug": "arras_contract_en",
  "post_text": "The arras draft lands a couple of days before signing. That window exists for amendments, and most clients let it close unread.\n\nI treat the Contrato de Arras as the real decision point of the file. Once both parties sign, they are legally bound: a buyer who pulls out loses the 10 percent deposit, a seller who pulls out pays the buyer double it. Everything after that is execution.\n\nSo the draft deserves a full pass, not a skim. Check the property description against the Nota Simple. Fix the completion date, usually two to three months after signing, and make sure it leaves room for the mortgage and the documentation. Confirm the penalties are stated for both sides. Then the specifics: which furniture stays, which repairs the seller pays for, whether appliances are included, whether water and electricity will be switched on.\n\nIf it is not written in the arras, it was never agreed.\n\nTwo more habits. On new builds, add completion date clauses; that is where delays live. And route the 10 percent to a safeguarded account at a financial institution rather than directly to the owners, common as the direct route is.\n\nAsk clients to forward the arras draft the day it arrives, not the night before signing.\n\nGeneral information, not legal advice.\n\n#LegalSpain #SpainProperty #BuyingInSpain",
  "image_url": "/photos/cove_house.jpg",
  "source_article": "property-contracts.txt"
 },
 {
  "slug": "at_choice_of_law",
  "batch": 1,
  "day": 2,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "The choice-of-law clause",
  "source_slug": "inheritance_foreign_law_en",
  "source_slug2": "spanish_wills_en",
  "post_text": "One clause decides whether Spanish forced heirship takes your client's entire estate. Most wills written back home do not contain it.\n\nUnder the European Inheritance Regulation of 2012, anyone who dies after 17 August 2015 can choose the inheritance law of their home country over the law of their country of residence.\n\nThe condition is strict: the choice must be stated clearly in a Spanish or international will.\n\nA client resident in Spain who stays silent gets Spanish law across the entire estate, including the Law of Obligatory Heirs. Under that regime, 50 percent of the joint property goes to the spouse, one third of the rest must be split equally between the children, a second third is divided among the children as the testator chooses, and only the final third can be left freely.\n\nIt reaches non-residents too. A client with a holiday home in Spain still needs their will to state which country's law governs, or the default can catch the Spanish assets.\n\nThe pattern I keep seeing: the will predates the Spanish purchase and names no governing law. Nobody has read it since completion.\n\nThat makes this one of the cheapest pieces of preventive work in cross-border practice.\n\nAt the next completion, ask when the client's will was last reviewed and whether it names a governing law.\n\nGeneral information, not legal advice.\n\n#LegalSpain #InheritancePlanning #SpainProperty",
  "image_url": null,
  "source_article": "estate-planning.txt"
 },
 {
  "slug": "at_nonresident_seller",
  "batch": 1,
  "day": 3,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Two tax jobs on your buyer",
  "source_slug": "plusvalia_en",
  "post_text": "When the seller is a non-resident, two of their tax jobs land on your buyer. Better your client hears it from you than at the notary's table.\n\nJob one: the buyer withholds 3 percent of the purchase price and pays it to the tax authorities within one month of the sale. It is not extra tax. It is a holding against the seller's capital gains bill, 19 percent of the profit for EU and EEA residents, 24 percent for non-EU sellers. If the final liability comes in under the 3 percent, the seller claims a partial or full rebate within the year. The withholding duty still sits with the buyer, even where the seller made no profit at all.\n\nJob two: plusvalia, the municipal tax on the increase in urban land value. It is usually the seller's tax, but with a non-resident seller it falls to the buyer, with 30 days to pay the local council before a fine lands.\n\nThe amount turns on local council rates and how long the seller owned the property, up to a 20 year cap. If the land value genuinely fell, or the sale is at a loss, there is an exemption.\n\nPut a written allocation of both payments into every completion with a non-resident seller.\n\nGeneral information, not tax advice.\n\n#LegalSpain #SpanishTax #SpainProperty",
  "image_url": "/photos/arch_terrace.jpg",
  "source_article": "plusvalia.txt"
 },
 {
  "slug": "at_bank_guarantee",
  "batch": 1,
  "day": 4,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Law 57/68 bank guarantees",
  "source_slug": "bank_guarantee_en",
  "post_text": "Off plan, your client can pay up to 80 percent of the price in instalments before the escritura is ever signed. One instrument protects that money, and some developers hope nobody asks for it.\n\nSince Law 57/68, any developer taking a deposit and staged payments towards construction must do two things.\n\nFirst, open a specific bank account for those payments. Not a personal account, not one previously held. Money in it can be used only for the construction of that property.\n\nSecond, provide a guarantee to refund every amount paid, plus interest, if the property is not started or not finished by the agreed completion date. And the guarantee must carry no expiry date. It stays valid until the property is fully finished and deemed safe to live in.\n\nThe asymmetry worth explaining to clients: the guarantee is issued at no cost to the buyer and can be expensive for the developer. Which is exactly why some try to work around it, occasionally by offering better conditions instead.\n\nMy reading of that trade: a discount on a home that never gets built is not a discount.\n\nBefore the first instalment moves, verify the guarantee exists, covers refund plus interest, and has no expiry date. If the developer resists, that is your answer.\n\nGeneral information, not legal advice.\n\n#LegalSpain #SpainProperty #OffPlan",
  "image_url": null,
  "source_article": "bank-guarantees.txt"
 },
 {
  "slug": "at_partner_unbillable_email",
  "batch": 1,
  "day": 5,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "The unbillable email",
  "source_slug": "bueno_facts",
  "post_text": "There is a kind of email that lands in property law inboxes long after completion, and it is not about the law.\n\nIt is about a letter from the town hall the client cannot read. A utility contract that will not switch over. A question about whether the non-resident tax was ever filed.\n\nNone of it is legal work. Most of it is barely billable. But the client has exactly one professional they trust in Spain, so it lands in your inbox. Answering properly takes hours nobody pays for. Leaving them stranded damages a relationship you spent months building.\n\nThis is the gap we built Bueno for. One platform for foreign property owners in Spain: a Spanish IBAN account and card, property admin tools, energy switching, Modelo 210 filing, home insurance, and human support in the client's own language. One subscription, 99 euros a year.\n\nThe client stays cared for after completion. You keep the relationship and the referrals. Your hours go back to actual legal work.\n\nIf those emails sound familiar, I would genuinely like to compare notes.\n\n#LegalSpain #SpainProperty #PropertyLaw",
  "image_url": "/photos/couple_beach.jpg"
 },
 {
  "slug": "at_tourist_ban_ruling",
  "batch": 1,
  "day": 6,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "The 3/5 tourist-let ruling",
  "source_slug": "community_rental_ban_en",
  "post_text": "A 48 to 3 vote in Marbella settled how tourist rentals end in Spanish community buildings. If you advise landlord owners, the thresholds are now concrete.\n\nThe background: in 2019, Article 17.12 of the Horizontal Property Law was amended by royal decree, giving owner communities the power to condition and limit tourist rentals in their building. Judges then split on whether limiting included banning outright, and the law never fixed a voting threshold. Majority or unanimity? Nobody could say.\n\nThe Supreme Court has answered both. Prohibition is a form of limitation. And three fifths of the vote, 60 percent, is enough. No unanimity required.\n\nThe case behind it: a Marbella community voted 48 to 3 to ban tourist flats after complaints of noise, illegal substances and damage to common spaces. Two companies owning six tourist apartments in the building took it to court and lost.\n\nTwo defence lines survive for existing operators. The ruling is not retroactive, so the problems must still be ongoing and affecting residents. And a ban must be properly justified and implemented under the Horizontal Property Law's requirements, not simply voted through.\n\nFor any client buying with rental plans, the community's rules and voting arithmetic are now core due diligence.\n\nCheck the community's position before the arras on every buy-to-let file.\n\nGeneral information, not legal advice.\n\n#LegalSpain #HolidayRental #SpainProperty",
  "image_url": null,
  "source_article": "supreme-court-tourist-ban.txt"
 },
 {
  "slug": "at_succession_tax",
  "batch": 1,
  "day": 7,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Succession tax's six-month lock",
  "source_slug": "inheritance_tax_en",
  "post_text": "Spanish heirs pay the tax before they touch the inheritance. The estate stays locked until the bill is settled, and the clock runs six months.\n\nSuccession tax in Spain falls on the beneficiary, not the estate. And the estate cannot be released until the beneficiary has paid.\n\nRates are progressive, from 7.65 percent to 36.5 percent, and they vary sharply by region; Andalucia sits among the lowest in the country. The relationship between the deceased and the beneficiary, and the value inherited, shape the final figure, so the same estate can produce very different bills in different regions.\n\nThe deadline is 6 months, though an extension is possible. Miss it and 5 percent is added every 3 months, up to a maximum of 20 percent on top.\n\nThe scope is wider than clients expect. Residents and non-residents alike pay on assets located in Spain. Assets outside Spain escape Spanish inheritance tax, with one exception worth flagging to families: they are caught if the beneficiary is a Spanish resident.\n\nFor foreign families, those six months must cover two legal systems, paperwork in a language they do not read, and grief. The time disappears fast.\n\nWhen a client with Spanish property dies, open the file in week one, not month four.\n\nGeneral information, not tax advice.\n\n#LegalSpain #InheritanceTax #SpanishTax",
  "image_url": "/photos/poolside.jpg",
  "source_article": "estate-planning.txt"
 },
 {
  "slug": "at_notary_role",
  "batch": 1,
  "day": 8,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "The notary is not their lawyer",
  "source_slug": "escritura_notary_en",
  "source_slug2": "land_registry_en",
  "post_text": "Foreign buyers keep arriving at the escritura convinced they already have a lawyer in the room. They do not, and someone has to tell them.\n\nIn Spain the notary is impartial by design. At the escritura publica they prepare and oversee the deed, read it out to buyer and seller together, and confirm both fully understand it before anyone signs. If the buyer's Spanish is weak, the notary may require a translator or a Spanish speaking legal adviser.\n\nThe mortgage track has its own sequence. The FEIN, which lays out the loan's terms and conditions, must be signed at least 10 days before the mortgage deed; those 10 days are a legal requirement. And the buyer meets the notary at least 24 hours before signing day, to go through the mortgage conditions first.\n\nWhat the notary never does is represent one side. They advise both parties impartially and confirm the sale is legal. Clients raised in other systems mistake that neutrality for protection, and the gap between the two is exactly where an adviser belongs.\n\nSigning is not the finish line either. Registration at the Registro de la Propiedad is a separate step afterwards, and someone has to own it.\n\nExplain the notary's role at the first meeting, and diarise the FEIN clock and the registration before signing day.\n\nGeneral information, not legal advice.\n\n#LegalSpain #SpainProperty #BuyingInSpain",
  "image_url": null,
  "source_article": "buying-10-steps.txt, property-contracts.txt"
 },
 {
  "slug": "at_rural_diligence",
  "batch": 1,
  "day": 9,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Rural registry vs reality",
  "source_slug": "rural_property_en",
  "post_text": "Rural files fail checks that urban files pass. The registries say one thing, the ground says another, and your client is already in love with the finca.\n\nStart with title. If the Title Deed does not exist, or is outdated or inaccurate, the purchase should not proceed. The vendor updates the missing details at the Land Registry, at their own expense, and you check the registry before anything moves.\n\nThen reconcile paper with terrain. The Land Registry and the Cadastral Registry frequently disagree with real life on plot size, property description and boundaries, and any discrepancy brings legal and financial consequences. Confirm too that the vendor is actually the registered owner; a Nota Simple settles it.\n\nThe build itself deserves suspicion. Some owners register a casa de aperos, a shed, to get around planning restrictions, then put up a villa. An independent surveyor can confirm whether the Town Hall granted planning permission. Without it, the advice is to walk away. Pre 1956 constructions are usually legal, since no building licence was required, but often cannot be extended.\n\nFinally, the rural extras: easements such as right of way, right of view and the right to extract water, and septic tanks, where a renovation can force a modern replacement costing thousands.\n\nBring an independent surveyor into every rural file before the arras.\n\nGeneral information, not legal advice.\n\n#LegalSpain #RuralSpain #SpainProperty",
  "image_url": "/photos/coast_bay.jpg",
  "source_article": "rural-property.txt"
 },
 {
  "slug": "at_partner_after_closing",
  "batch": 1,
  "day": 10,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "After the file closes",
  "source_slug": "bueno_facts",
  "post_text": "The deed is signed, the file closes, and your foreign client's life in Spain actually begins. That is usually the moment their support ends.\n\nAfter completion the questions do not stop. They change. An IBI bill arriving at a mailbox nobody checks. A utility contract in a language the client cannot read. Insurance, tax filings, letters from the town hall.\n\nSo the client turns to the one professional they trust in Spain: their lawyer. And you answer, because leaving them stranded is not who you are. But it is not legal work, and nobody is paying for those hours.\n\nThat ongoing after-sales care is what Bueno does. One platform, one annual subscription of 99 euros: a Spanish IBAN account, property tools, energy switching, Modelo 210 filing, home insurance, and human support in the client's own language. Our customers span more than 28 countries, with Norway, Sweden, Germany, the UK and France the biggest, which tends to match a Spanish practice's foreign client base rather well.\n\nYou hand over the admin. You keep the client.\n\nIf you would like to see how the handover works, my messages are open.\n\n#LegalSpain #SpainProperty #ClientCare",
  "image_url": null
 },
 {
  "slug": "at_gift_tax",
  "batch": 1,
  "day": 11,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Gift tax's 30-day clock",
  "source_slug": "gift_tax_en",
  "post_text": "Inheritance gives a beneficiary six months and a possible extension. A gift gives the recipient 30 days. Clients funding a child's purchase rarely know the difference.\n\nGift tax in Spain falls on the person receiving, not the person giving. If your client plans to pass money or an asset to family, the family member faces the bill, and payment is due within 30 days of the gift being made.\n\nCompare the inheritance track. There, the beneficiary usually has 6 months to pay, an extension is possible, and even the penalty regime is gradual: 5 percent added every 3 months, up to a maximum of 20 percent. Gifts get no such grace. One month, and the clock starts the moment the gift is made.\n\nGeography moves the number as much as timing does. Gift tax rates vary from region to region in Spain, so an identical gift can produce a very different bill depending on where the people and assets involved sit.\n\nThe scenario I flag most is a parent passing funds so a child can buy in Spain. The transfer happens quickly, and nobody has told the recipient that a Spanish deadline started running.\n\nTiming and region decide most of the cost here, which makes this a conversation for before the transfer, never after.\n\nWhen a client mentions gifting funds for a Spanish purchase, put the 30 day clock on the table first.\n\nGeneral information, not tax advice.\n\n#LegalSpain #SpanishTax #GiftTax",
  "image_url": "/photos/golden_coast.jpg",
  "source_article": "estate-planning.txt"
 },
 {
  "slug": "at_community_debts",
  "batch": 1,
  "day": 12,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Debts that stay with the flat",
  "source_slug": "hoa_disagree_vote_en",
  "post_text": "In Spain, community fee debts do not follow the debtor. They attach to the property, and your buyer collects them with the keys.\n\nThat is the rule of the community regime: debts of community contributions belong to the flat, not the owner, so a seller's arrears become your client's liability the moment title passes.\n\nThe protection is cheap and early. Get the Nota Simple before the offer and the arras are signed. Any outstanding fees it reveals can be deducted from the selling price and settled before the deeds are exchanged. Skip the check, and your client may simply be liable.\n\nWorth reading in the same pass: the voting arithmetic your client is buying into. Most decisions pass by majority, votes are weighted by property size, and proxy voting is allowed on important matters. One person holding several flats carries a bigger share of every decision. And if a client later disputes a resolution, there are only two grounds to have a vote revoked: it is contrary to the law, or it is detrimental to the community. Preference changes nothing.\n\nThe far end of non-payment is real: late payment fees and interest, a court demand with the legal costs falling on the debtor, and ultimately forcible sale of the property at auction.\n\nMake the Nota Simple the first document on every apartment file, before the arras.\n\nGeneral information, not legal advice.\n\n#LegalSpain #SpainProperty #CommunityFees",
  "image_url": null,
  "source_article": "hoa-rules.txt, community-fees.txt"
 },
 {
  "slug": "at_spanish_wills",
  "batch": 1,
  "day": 13,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Spain's default heirship ladder",
  "source_slug": "spanish_wills_en",
  "post_text": "No will, and Spanish law hands your client's estate down a fixed ladder: children, then parents, then spouse, then wider relatives, then the state itself.\n\nSpain runs on forced heirship, the Law of Obligatory Heirs, Legitima. The mechanics are precise. 50 percent of the joint property goes to the spouse. The rest of the estate divides into thirds: one third split equally between the children, a second third shared among the children as the testator chooses, and only the final third left freely to anyone at all.\n\nDie without a will and the strict order above applies instead, children first, natural and adopted alike. Where no rightful relatives exist, the estate passes to the state.\n\nNotice who is missing from both routes: stepchildren, unmarried partners, friends. None of them inherit unless a will names them, and under Spanish law even then only from that free third. For remarried clients, that gap is enormous.\n\nSome autonomous regions apply their own rules on top, so the map shifts with the address.\n\nForeign owners tend to assume their home arrangements travel with them. They do not, unless a Spanish will, or clear wishes stated in an international one, says so.\n\nAsk every foreign owner client one question: does your family fit Spain's default order? Most do not.\n\nGeneral information, not legal advice.\n\n#LegalSpain #InheritancePlanning #SpainProperty",
  "image_url": "/photos/terrace_sunset.jpg",
  "source_article": "estate-planning.txt"
 },
 {
  "slug": "at_extension_legalisation",
  "batch": 1,
  "day": 14,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "Legalise extensions before sale",
  "source_slug": "extension_deeds_en",
  "post_text": "That pool, extra floor or enclosed porch is legally an extension. If it never reached the deeds, it surfaces at the worst moment for your client: the sale.\n\nThe proper sequence runs like this. Structural work, new rooms or floors, a garage, covering a porch, basement excavation, needs the Obra Mayor licence. Even non-structural jobs, painting, replacing tiles, swapping windows in the same position and size, need the Obra Menor. A technical architect drafts the plans, the project is filed at the town hall, and where communal spaces are shared, the neighbours must authorise it, with the community's certificate signed before a notary.\n\nCost and timing: ICIO tax of 2 to 5 percent of construction cost, plus a smaller urban development licensing fee. Processing runs from a few weeks to several months.\n\nWhen work finishes, the architect issues the Certificado Final de Obra, and the extension is declared before a notary and written into the land registry.\n\nBuilt without a licence? The antiquity certificate can legalise it retrospectively, with an architect confirming the age on site: works completed after August 2014 must be 15 years old, against 4 years for earlier ones, and regions vary.\n\nUnregistered extensions stall sales, because notaries and buyers will ask, and the alternative is infraction risk and demolition.\n\nWalk selling clients through their deeds before they list. Legalise first, market second.\n\nGeneral information, not legal advice.\n\n#LegalSpain #SpainProperty #SpanishHomeOwners",
  "image_url": null,
  "source_article": "extension-deeds.txt"
 },
 {
  "slug": "at_partner_referral_logic",
  "batch": 1,
  "day": 15,
  "language": "en",
  "member": "",
  "audience": "attorneys",
  "title": "The referral logic of care",
  "source_slug": "bueno_facts",
  "post_text": "Where does a foreign client's next referral come from? Rarely from the contract you drafted. Almost always from how looked after they felt two years later.\n\nHere is the quiet logic of a cross-border practice. The legal work ends at completion. The client's need for help does not. Account setup, utility contracts, IBI, the Modelo 210, letters in Spanish they cannot read.\n\nIf that stretch goes badly, the client does not blame the utility company. They just stop feeling looked after, and the recommendations quietly stop with it.\n\nBueno exists for exactly that stretch. We take over the ongoing admin in the client's own language, on one platform, for 99 euros a year, licensed by the Bank of Spain via SEFIDE EDE S.L.U.\n\nThe division of labour is clean. You remain the legal name they trust in Spain. We handle the small stuff between transactions. And a client who feels cared for is far more likely to send the next buyer back to you.\n\nNothing dramatic. Just after-sales care, done properly.\n\nIf that division of labour sounds useful for your clients, I am easy to find.\n\n#LegalSpain #SpainProperty #ReferralNetwork",
  "image_url": "/photos/sunset_village.jpg"
 }
];
