// Agents stream: 30 posts, rewritten from the full blog articles (studio/articles). Generated; do not hand-edit.
export default [
 {
  "slug": "ag_epc_advertising",
  "batch": 1,
  "day": 1,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "EPC fines start at the advert",
  "source_slug": "epc_certificates_en",
  "source_slug2": "lost_documents_en",
  "source_article": "epc.txt, lost-documents.txt",
  "post_text": "The EPC fine in Spain starts at the advert, not the sale. 300 to 600 euros for marketing a property without one, before a single viewing happens.\n\nIf you publish listings, the sequence matters more than the rating.\n\nThe certificate must exist before the property is listed, and a copy goes into the notarial deed when it sells. Notaries may refuse to complete without it. So a missing EPC is not a completion problem, it is a marketing problem that surfaces on day one and again at the finish line.\n\nThe fines scale with the offence. Advertising without a valid certificate runs 300 to 600 euros. Failing to provide one at all, or falsifying it, runs 1,000 to 6,000. Each autonomous region manages its own inspections and penalties.\n\nThe fix is genuinely small. A certified technician inspects insulation, windows, heating, cooling and lighting, then issues the A to G rating. Budget 100 to 300 euros and less than a week, start to finish. The certificate lasts ten years and must be registered with the regional authority, which the technician will usually handle. A strong rating can also support the price and opens access to green funding and subsidies.\n\nIf the seller has lost theirs, the issuing technician or any licensed assessor replaces it for roughly 60 to 150 euros. No drama, just lead time.\n\nMy rule: no certificate on file, no listing goes live. Build it into your intake checklist.\n\nGeneral information, not legal advice.\n\n#SpainProperty #RealEstateSpain #EPC",
  "image_url": "/photos/sunset_village.jpg"
 },
 {
  "slug": "ag_nota_simple_twice",
  "batch": 1,
  "day": 2,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The Nota Simple sizes the mortgage",
  "source_slug": "nota_simple_en",
  "source_slug2": "land_registry_en",
  "source_article": "nota-simple.txt, land-registry.txt",
  "post_text": "The Nota Simple can quietly shrink your buyer's mortgage. If the cadastral value on it sits 10k under the price, the bank may lend 10k less.\n\nThat detail from the Land Registry catches foreign buyers off guard, and it is exactly the kind of thing an agent can flag early.\n\nThe document itself costs around 10 euros online and can arrive the same day. In person at the registry it is under 4 euros. You supply the property details or its identifier, the IDUFIR, which the seller or the agent usually has to hand. Anyone with a legitimate interest in buying can request one.\n\nWhat it shows: the registered owner and when they bought, the property description and square metres, boundaries, the land classification, and any charges. Mortgages, unpaid taxes, debts. In Spain those debts sit on the property, so your buyer inherits whatever that page reveals.\n\nTwo moments matter. Before the arras, because any debt or discrepancy is far easier to resolve before 10 percent changes hands. And at mortgage time, because when the registered cadastral value comes in below the offer, the bank looks at that lower figure, not the price your buyer agreed.\n\nIf the document shows something unexpected, the next call is a property lawyer, not the seller.\n\nOrder it for every serious buyer before the arras is drafted. Ten euros of paper beats six weeks of surprises.\n\nGeneral information, not legal advice.\n\n#NotaSimple #BuyingInSpain #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_arras_window",
  "batch": 1,
  "day": 3,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The arras amendment window",
  "source_slug": "arras_contract_en",
  "source_article": "property-contracts.txt",
  "post_text": "The arras draft arrives a couple of days before signing. That window exists so someone can request amendments. Most foreign buyers never use it.\n\nIf you sell to foreign buyers, this contract is where the deal is really made.\n\nWhat must be inside, checked line by line: an accurate description of the property, address, size and layout. The price. A completion date, usually two to three months out, and it has to leave enough time for the buyer's documentation and any mortgage. The penalties if either side pulls out. And the specifics: furniture the sellers leave, repairs they agreed to fund, whether appliances are included, whether water and electricity will be switched on. If it is not written here, it was never agreed.\n\nThe stakes are real on both sides. Once signed, a buyer who withdraws loses the 10 percent deposit. A seller who withdraws pays double. That is why the draft goes out a couple of days early, so the buyer or their representative can read it and push back.\n\nTwo more habits worth building. The 10 percent sometimes goes straight to the owners, which is common, but a safeguarded account at a financial institution is the safer route, so raise it. And on a new build, add completion date clauses of their own.\n\nSend the draft to your buyer the day it lands, with one line: read this now, not at the table.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
  "image_url": "/photos/pool_dusk.jpg"
 },
 {
  "slug": "ag_offer_accepted",
  "batch": 1,
  "day": 4,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "An accepted offer binds nobody",
  "source_slug": "offer_accepted_en",
  "source_article": "offer-accepted.txt",
  "post_text": "In Spain an accepted offer is a gentleman's agreement. Either side can still walk away without penalty. What binds is the arras, and it can arrive within days.\n\nThat speed is the part foreign buyers never see coming.\n\nThe sequence: the property comes off the market, the buyer signs an offer contract, usually at the agency, and transfers 1,000 to 2,000 euros. That sum comes off the fees if the sale proceeds and is returned if it falls through. Nothing yet stops the seller changing their mind.\n\nThen the arras. Ten percent of the price, terms formally agreed, completion date fixed. Pull out as buyer and the deposit is gone. Pull out as seller and you repay double. It can be a matter of days between acceptance and this signature, which is a huge commitment on a short runway.\n\nBetween those two points sits the due diligence: the Nota Simple, confirming the registered owner, checking for debts tied to the property, verifying planning permissions and correct registration. And the money has to be ready to move through a Spanish account, because the transaction and everything after it runs through one.\n\nFrom deposit to keys usually takes six to ten weeks. The buyers who sail through are the ones whose NIE, account and funds existed before the offer did.\n\nSo ask the qualifying questions at the first viewing, not at the accepted offer.\n\nGeneral information, not legal advice.\n\n#SpainProperty #RealEstateSpain #BuyingInSpain",
  "image_url": null
 },
 {
  "slug": "ag_partner_week_after_keys",
  "batch": 1,
  "day": 5,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The week after the keys",
  "source_slug": "bueno_facts",
  "post_text": "The week after the keys are handed over is when an agent's real second job begins. Nobody pays for that job.\n\nCompletion goes perfectly. Everyone shakes hands at the notary. And then the messages start. Can you help me open an account? Who do I call about the electricity? What is this IBI letter? How do I file that non-resident tax?\n\nNone of it earns the agent anything. All of it eats the hours that should go into the next sale. And saying no feels wrong, because this is the client who will send you their friends.\n\nThat gap is exactly what we built Bueno for. One platform for foreign owners in Spain: an account, property tools, energy switching, Modelo 210 filing, insurance, with human support in the client's own language.\n\nThe client stays looked after. You stay the person who introduced them to something that works. And your week goes back to selling.\n\nIf this sounds familiar, my inbox is open.\n\n#RealEstateSpain #Proptech #SpainProperty",
  "image_url": "/photos/marina.jpg"
 },
 {
  "slug": "ag_tourist_licence_first",
  "batch": 1,
  "day": 6,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Licence first, yield second",
  "source_slug": "tourist_license_en",
  "source_article": "legally-renting.txt",
  "post_text": "A tourist licence already issued is a selling point you can price. An area where none are granted is a yield pitch you should never make.\n\nAny rental contract under three months makes your buyer a tourist landlord, and that requires a licence. Two types exist: individual for private owners, collective for companies owning or managing several properties.\n\nThe application is a project, not a form. The property has to meet hygiene, safety and quality standards. It needs habitability and energy efficiency certificates. Some areas require registration with the local tourism agency. Then the application, with ID and proof of payment, goes to the tourist office, and approval takes one to six months depending on region and demand.\n\nAvailability is the real filter. In Barcelona, renting out short term private rooms is illegal, and licences for entire homes are now very hard to come by. Valencia is generally only granting them to ground floor properties in popular areas. Catalunya runs dedicated teams hunting illegal lets.\n\nGetting it wrong costs real money: fines typically run 4,000 to 60,000 euros, rising sharply for repeat infractions, and reach 111,000 in Ibiza. A licence also unlocks proper rental insurance and legitimate advertising, which is why listings that already hold one command attention.\n\nBefore the words rental income leave your mouth, confirm licences are actually being issued in that exact area. One call protects the sale and the relationship after it.\n\nGeneral information, not legal advice.\n\n#HolidayRental #SpainProperty #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_seller_debt_certificate",
  "batch": 1,
  "day": 7,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Community debt comes off the price",
  "source_slug": "community_fees_en",
  "source_slug2": "hoa_disagree_vote_en",
  "source_article": "community-fees.txt",
  "post_text": "Unpaid community fees can follow the keys, not the seller. The clean fix: find the debt before signing and deduct it from the purchase price.\n\nIf you sell apartments or anything with shared spaces, this check belongs in your standard process.\n\nThe numbers first, because buyers always ask. Fees fund cleaning, gardening, lifts, maintenance, a reserve pot for surprises and the safety work Spanish law requires. Some owners pay around 100 euros a quarter. High end developments with pools, security and a gym can run past 1,000. The share depends on two things: the services provided and the size of the property, and a bigger share also means more voting weight at the annual general meeting where budgets are set.\n\nNow the trap. If the previous owner fell behind, the debt can land on your buyer, because unchecked community debts may become the new owner's liability. The lawyer's job during the purchase is to confirm nothing is outstanding, and where something is, the usual mechanism is simple: the outstanding amount is deducted from the purchase price so it is settled before the deeds are signed.\n\nWorth telling landlord clients too: when the property is rented out, the fees stay the owner's responsibility, never the tenant's. And communities do escalate, from late fees and interest to court demands and, after years, a forced auction.\n\nMake the community debt check, and the price deduction, a fixed step in every shared building sale.\n\nGeneral information, not legal advice.\n\n#SpainProperty #CommunityFees #RealEstateSpain",
  "image_url": "/photos/cove_house.jpg"
 },
 {
  "slug": "ag_3pct_withholding",
  "batch": 1,
  "day": 8,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The 3 percent withholding",
  "source_slug": "plusvalia_en",
  "source_article": "plusvalia.txt",
  "post_text": "When the seller is a non-resident, your buyer picks up two of the seller's tax jobs, each with its own deadline. Most discover this at the notary's table.\n\nIf you list homes owned by foreigners, this is worth explaining at the mandate, not the completion.\n\nJob one: the 3 percent withholding. The buyer holds back 3 percent of the purchase price and pays it to the tax authorities within one month of the sale. It is not an extra tax. It is a holding against the seller's capital gains bill, which runs 19 percent of the profit for EU and EEA residents and 24 percent for everyone else. If the final tax comes to less than the amount withheld, the seller is entitled to a rebate of the difference within the year.\n\nJob two: plusvalia, the municipal tax on the increase in urban land value. Normally the seller pays it, but when the seller is a non-resident, the buyer pays it instead, with 30 days from the transfer to get it to the local council before fines start. The amount depends on local rates and the years of ownership, up to a 20 year cap, and if the land value genuinely fell, there is an exemption.\n\nNone of this needs drama. It needs a written agreement before completion on who handles which payment.\n\nRaise it the moment you learn the seller lives abroad.\n\nGeneral information, not tax advice.\n\n#SpanishTax #SpainProperty #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_law5768_guarantee",
  "batch": 1,
  "day": 9,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Law 57/68 off plan guarantees",
  "source_slug": "bank_guarantee_en",
  "source_slug2": "arras_contract_en",
  "source_article": "bank-guarantees.txt, property-contracts.txt",
  "post_text": "Off plan in Spain can mean staged payments of up to 80 percent before the escritura is signed. Law 57/68 is what stands between that money and disaster.\n\nIf you sell new developments to foreign buyers, this law answers their biggest fear, so make it part of the pitch.\n\nSince 1968, a developer taking a deposit and staged payments must do two things. First, open a specific bank account for those payments. Not a personal account, not one previously held, and the money in it can only be used for the construction of that property. Second, provide a guarantee that refunds every payment plus interest if the build is not started, or not finished, by the agreed completion date.\n\nOne detail carries most of the weight: the guarantee must have no expiry date. It stays valid until the property is fully finished and deemed safe to live in. A guarantee that lapses mid build protects nobody.\n\nThe economics explain the behaviour you will meet. The guarantee costs the buyer nothing but is expensive for developers, which is why some try to work around it, sometimes by dangling better conditions instead. The rule to give any client: do not proceed without the guarantee, whatever the sweetener.\n\nAnd a practical pairing: the guarantee bites on the agreed completion date, so on a new build the arras deserves its own completion date clauses.\n\nA developer who resists the guarantee has answered your due diligence for you. Walk.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
  "image_url": "/photos/arch_terrace.jpg"
 },
 {
  "slug": "ag_partner_utility_bill_text",
  "batch": 1,
  "day": 10,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The utility bill text message",
  "source_slug": "bueno_facts",
  "post_text": "A photo of a utility bill, in Spanish, with the message: what is this? If you sell to foreign buyers, that text will look familiar.\n\nIt arrives months after completion. The deal is closed, the commission is paid, and yet here you are, translating a bill on a Sunday because the client has nobody else to ask.\n\nI understand why agents keep answering. That client trusted you with the biggest purchase of their life. The relationship is the asset. But translating paperwork is not your job, and every one of those messages is time taken from the buyers who are.\n\nThis is the exact problem Bueno exists for. One platform for foreign property owners in Spain: a Spanish account, property management tools, energy switching, non-resident tax filing, home insurance, and human support in the client's own language. When the confusing letter arrives, they ask us, not you.\n\nYou made the introduction, so you still get the credit. You just stop doing the unpaid work behind it.\n\nIf your phone knows this story too, my inbox is open.\n\n#RealEstateSpain #Proptech #ExpatSpain",
  "image_url": null
 },
 {
  "slug": "ag_three_fifths_ruling",
  "batch": 1,
  "day": 11,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The three fifths tourist let ruling",
  "source_slug": "community_rental_ban_en",
  "source_slug2": "rental_rule_changes_en",
  "source_article": "supreme-court-tourist-ban.txt, rental-rule-changes.txt",
  "post_text": "The Supreme Court settled it: limiting tourist flats includes banning them, and three fifths of owners is enough. No unanimity required.\n\nIf you sell apartments as rental investments, this ruling rewrote your due diligence.\n\nThe background: in 2019, article 17.12 of the Horizontal Property Law was amended to let owner communities condition and limit tourist rentals. Two ambiguities followed. Judges across Spain disagreed on whether limiting included banning outright, and the law never set a voting threshold, so nobody knew if a majority sufficed or unanimity was needed.\n\nThe Supreme Court answered both. Prohibition is a form of limitation, and three fifths of the vote, 60 percent, is enough.\n\nThe case that carried it came from Marbella. Residents complained about noise, illegal substances and damage to common spaces from tourist flats. The community voted 48 to 3 to ban them, and the two companies owning the six apartments involved lost in court.\n\nTwo safeguards survive for owners. A ban cannot be retroactive; the problems must still be ongoing and affecting residents. And it must be properly justified and implemented under the law's requirements, not just voted through.\n\nThe connection that matters commercially: the new national rental register can certify whether the building allows tourist lets, and a community ban means no registration code, before any other paperwork starts.\n\nBefore pitching short term yield on any apartment, read the statutes and ask when the community last voted.\n\nGeneral information, not legal advice.\n\n#HolidayRental #RealEstateSpain #SpainProperty",
  "image_url": "/photos/couple_beach.jpg"
 },
 {
  "slug": "ag_fx_completion_funds",
  "batch": 1,
  "day": 12,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Completion money, on time",
  "source_slug": "currency_transfer_en",
  "source_slug2": "sepa_swift_en",
  "source_article": "currency-transfer.txt, sepa-swift.txt",
  "post_text": "Completion funds that arrive late can cost your buyer the 10 percent deposit. The deadline is fixed in the arras. The exchange rate is not.\n\nWhich is why the transfer plan belongs in your post arras conversation, not in the panicked week before the notary.\n\nRoute first. SEPA covers euro payments across the EU, EEA and the UK using nothing more than an IBAN, and it is faster and cheaper than the alternative. SWIFT routes money through correspondent banks, each of which needs paying, which makes it slower and more expensive. Most UK banks send European transfers as SEPA by default, but the instruction that matters is simple: send euros, on the SEPA network.\n\nTiming second. Exchange rates change throughout the day, and on a purchase sized sum a small difference is real money. Rather than guessing, the buyer can set rate alerts and transfer when the level works in their favour, with completion as the hard stop.\n\nProvider third. Whoever moves the money should hold client funds in segregated accounts, separate from the business's own money, be upfront about fees, and handle regular automated payments if the buyer will later move a pension or pay a mortgage from abroad.\n\nOne local quirk to mention too: many Spanish direct debits only run through Spanish accounts, so the banking setup is part of the same conversation.\n\nAdd one line to your post arras email: plan your transfer timeline today.\n\nGeneral information, not legal advice.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_rural_land_checks",
  "batch": 1,
  "day": 13,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Four checks for rural land",
  "source_slug": "rural_property_en",
  "source_article": "rural-property.txt",
  "post_text": "Rural property in Spain fails checks that urban flats pass. Four of them decide whether your finca sale survives due diligence.\n\nOne: the title deed. If it does not exist, or is outdated or inaccurate, the sale should wait. The vendor updates the missing details at the Land Registry, at their expense, and the buyer's lawyer checks the registry before anything proceeds.\n\nTwo: paper versus ground. The Land Registry and the Cadastral Registry frequently disagree with real life on plot size, description and boundaries, and any discrepancy brings legal and financial consequences. Rural land also carries easements urban homes rarely see: rights of way, rights of view, rights to extract water. Your buyer should know who can cross the land before it is theirs. And confirm the vendor really is the registered owner, which a Nota Simple settles.\n\nThree: is the build legal. Some owners register a casa de aperos, a shed, to get around planning restrictions, then build a villa on it. A surveyor can confirm whether the property has Town Hall permission. If it does not, the advice is blunt: walk away and avoid the legal battle. Pre 1956 constructions are usually legal without a licence but often cannot be extended.\n\nFour: water out, not just in. Rural homes often run on septic tanks that cost money to empty, and a renovation can force a modern replacement costing thousands.\n\nRecommend an independent rural surveyor before any offer. Every time.\n\nGeneral information, not legal advice.\n\n#RuralSpain #SpainProperty #RealEstateSpain",
  "image_url": "/photos/poolside.jpg"
 },
 {
  "slug": "ag_notary_role",
  "batch": 1,
  "day": 14,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The notary is not their lawyer",
  "source_slug": "escritura_notary_en",
  "source_slug2": "land_registry_en",
  "source_article": "property-contracts.txt, land-registry.txt",
  "post_text": "Foreign buyers assume the notary is on their side. In Spain the notary is impartial by design. Nobody at that table represents your buyer unless someone fixes it early.\n\nWorth explaining at the first meeting, because it changes who your client hires.\n\nWhat the notary does at the escritura publica: prepares and oversees the deed, reads it out to buyer and seller together, and checks both fully understand before anyone signs. If the buyer's Spanish is weak, the notary may require a translator or a Spanish speaking legal adviser in the room. With a mortgage there is more structure still: the FEIN with the loan conditions must be signed at least 10 days before the mortgage deed, and the buyer meets the notary at least 24 hours ahead so the conditions are explained first.\n\nWhat the notary does not do: represent anyone. They act as an impartial adviser to both parties and confirm the sale is legal. That is the whole job. The checks beyond legality belong to the legal adviser your buyer may not have hired yet.\n\nAnd signing is not the finish. The property and its new owners still need registering at the Land Registry, and only once registered is ownership officially recognised. Cities can have many offices, Valencia has 18, and the right one appears in the first line of the Nota Simple.\n\nTell every foreign buyer at viewing one: bring your own adviser to the table.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_partner_aftersales_list",
  "batch": 1,
  "day": 15,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "What after-sales actually contains",
  "source_slug": "bueno_facts",
  "post_text": "Ask an agent what after-sales means in Spain and you get a list nobody ever wrote down. We wrote it down.\n\nOpening a Spanish account. Utilities into the client's name. The first IBI letter. The Modelo 210 return nobody warned them about. Home insurance. And a steady stream of paperwork that arrives in Spanish at a house that is empty most of the year.\n\nThat is the real content of after-sales for a foreign owner. None of it is the agent's job. All of it lands on the agent anyway, because the agent is the only person in Spain the client knows.\n\nWe built Bueno to be the other person they know. One annual subscription that bundles the account, property management tools, energy switching, non-resident tax filing and insurance, with multilingual human support behind all of it.\n\nThe agent hands the client over after completion, the client is cared for in their own language, and the list above stops arriving by text message.\n\nIf you recognise that list, my inbox is open.\n\n#RealEstateSpain #Proptech #SpainProperty",
  "image_url": "/photos/coast_bay.jpg"
 },
 {
  "slug": "ag_ibi_attaches",
  "batch": 1,
  "day": 16,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "IBI stays with the house",
  "source_slug": "ibi_deep_en",
  "source_article": "ibi-tax.txt",
  "post_text": "Unpaid IBI can stay attached to the property through a sale. Which makes the seller's arrears your buyer's problem, unless someone checks.\n\nTwo sides of this tax matter to an agent.\n\nThe buyer side first. When ownership changes, the land registry updates and the council knows who to bill. But arrears do not reset. Unpaid IBI can remain attached to the home, with charges placed against it, and it surfaces exactly when someone tries to sell. Checking the position before purchase is basic protection your foreign buyer will not know to request.\n\nThen the owner side, which becomes the same client's problem within a year. The bill is the cadastral value, an official valuation based on location, size, age and characteristics, usually below market value, multiplied by the municipal rate. Across Spain that rate averages 0.3 to 1.1 percent. Santander, Zaragoza and Madrid sit low; parts of Catalunya and the Costa Blanca run higher.\n\nBills land between May and October in many municipalities, and some councils no longer post abroad. Then the sequence runs: reminder letter, surcharges starting around 5 percent and climbing to 20 or more, then debt collection, which can mean money seized from the owner's Spanish account.\n\nThe fix costs nothing: a direct debit with the town hall and electronic notifications, set up while the keys are still warm.\n\nCheck the IBI position before every sale, and hand over the direct debit tip with the keys.\n\nGeneral information, not tax advice.\n\n#IBI #SpanishTax #SpainProperty",
  "image_url": null
 },
 {
  "slug": "ag_true_buying_costs",
  "batch": 1,
  "day": 17,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The real price is 12 to 14 more",
  "source_slug": "buying_fees_en",
  "source_slug2": "buying_cost_stages_en",
  "source_article": "buying-fees.txt, cost-of-buying-expats.txt",
  "post_text": "Same home, different region, thousands apart in tax. The 12 to 14 percent on top of the asking price is not a flat number, and your buyer should see the breakdown early.\n\nHere is where it goes, in the order the money leaves.\n\nA reservation fee of 1,000 to 6,000 euros secures the bid while the arras is drawn up, refunded if the sale falls through in that window. Then the 10 percent arras deposit.\n\nThe tax layer is the regional one. On resales, transfer tax runs from 4 percent in the Basque Country to 6 in Madrid and 10 in Valencia and Catalonia. New builds skip it and pay 10 percent VAT plus a document fee of roughly 0.5 to 1.5 percent. That spread is why the same budget stretches differently a few kilometres apart.\n\nThe fixed layer: notary fees around 1,000 euros on a 250,000 euro purchase, land registry fees of 400 to 700 set by the government, a lawyer at a few thousand euros or a gestor at a few hundred.\n\nBorrowing adds bank setup fees of up to 2 percent of the loan, and valuation reports of 250 to 600 euros that should be the bank's cost but sometimes land on the buyer.\n\nAnd on used homes there is often room to haggle, which is where the costs get clawed back.\n\nGive every buyer a written, region specific cost sheet at the first serious conversation.\n\nGeneral information, not tax advice.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
  "image_url": "/photos/golden_coast.jpg"
 },
 {
  "slug": "ag_100pct_tax_calm",
  "batch": 1,
  "day": 18,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The 100 percent tax, calmly",
  "source_slug": "noneu_tax_proposal_en",
  "source_article": "noneu-100-tax.txt",
  "post_text": "Your UK buyer read about a 100 percent tax on non EU purchases and froze. What the proposal actually says is calmer than the headline.\n\nFirst, the status. It is one of twelve measures announced by the Prime Minister to tackle the housing crisis, and it remains a proposal being studied, with no set mechanism or date. Nothing has changed at the notary. In Valencia today, residents, non-residents and Spanish citizens alike pay the same 10 percent transfer tax.\n\nWho it would target: non-EU residents, meaning anyone spending under 183 days a year in Spain. That includes UK and US buyers of second homes.\n\nThe context your buyer half read: property prices have almost doubled in a decade, rents in Madrid and Barcelona rose by as much as 33 percent in five years, and the Golden Visa closed on April 3rd 2025, ending residency through 500,000 euro property purchases.\n\nNow the scale, which is the useful part. In 2023, foreigners bought 15 percent of Spanish properties, 87,000 out of 583,000 sales. Non-EU residents accounted for 27,000, around 5 percent, mostly from the US, UK, Morocco, Venezuela and Mexico, and mostly coastal holiday homes rather than the city centres where the crisis bites hardest.\n\nSo the honest line for a worried buyer: watch the legislation, plan on today's rules, and do not restructure around a draft that does not exist yet.\n\nSave these numbers. You will need them at a viewing soon.\n\nGeneral information, not tax advice.\n\n#SpainProperty #RealEstateSpain #BuyingInSpain",
  "image_url": null
 },
 {
  "slug": "ag_scam_red_flags",
  "batch": 1,
  "day": 19,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Scam red flags for foreign buyers",
  "source_slug": "scams_en",
  "source_slug2": "land_registry_en",
  "source_article": "scams.txt",
  "post_text": "Scammers pick foreign buyers because distance, language and urgency do half the work. Your clients are the exact demographic, and you are the first line of defence.\n\nThe listing that does not exist. A real property, reposted at an irresistible price, then a reservation fee requested before any viewing, sometimes with the line that this is normal in Spain. It is not. Someone should always view in person, and no money moves without legal confirmation.\n\nThe bait and switch. The perfect listing was just sold, but here is a similar one, more expensive and not quite right. Check how long a property has been on the market, be wary of listings reposted unusually often, and hold the budget.\n\nThe hijacked email. Criminals impersonate agents, lawyers, even notaries, intercept a thread and alter the payment instructions, usually with a same day deadline. The counter: verify bank details verbally or in person before sending, and treat any change of payment instructions as an alarm, not an update.\n\nThe licence that does not exist. Buyers get told a property has a tourist licence or sits where one is obtainable. Check whether short term rentals are permitted in that area, and whether an existing licence actually transfers between owners.\n\nThe fake demand. Urgent letters about unpaid taxes or community fees. Verify with the community administrator or tax authority before paying anything.\n\nSend your buyers this list before their first deposit. Honest sellers never mind the extra day.\n\nGeneral information, not legal advice.\n\n#PropertyScams #SpainProperty #RealEstateSpain",
  "image_url": "/photos/terrace_sunset.jpg"
 },
 {
  "slug": "ag_partner_saying_no",
  "batch": 1,
  "day": 20,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Why saying no costs referrals",
  "source_slug": "bueno_facts",
  "post_text": "No agent loses referrals by closing a bad deal. They lose them in the year after a good one.\n\nThink about where recommendations actually come from. Not the signing day. They come from how the client feels twelve months later, when they mention their Spanish house at a dinner back home.\n\nIf that year was full of confusing letters, an account they could not open, taxes they did not know existed, the story they tell is complicated. Not your fault, but attached to your name, because you were their introduction to Spain.\n\nSo agents keep helping for free. Every reply protects the referral, and every reply costs an hour of selling time. Saying no is cheaper today and expensive forever.\n\nWe built Bueno to break that trade. The client gets a platform that handles the account, taxes, energy, insurance and paperwork, with human support in their own language. Their year goes smoothly, the dinner story is a good one, and your name stays attached to it.\n\nIf that trade off sounds familiar, my inbox is open.\n\n#RealEstateSpain #Proptech #SpainProperty",
  "image_url": null
 },
 {
  "slug": "ag_market_calendar",
  "batch": 1,
  "day": 21,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The market calendar as a tool",
  "source_slug": "market_seasons_en",
  "source_article": "market-seasons.txt",
  "post_text": "In Spain the calendar is a pricing tool. Spring sells, autumn competes, winter negotiates, and August simply stops.\n\nForeign clients do not know this rhythm, which makes it easy value for you to hand over.\n\nSpring is prime selling season. Buyers want to have exchanged well before the warm weather, and homes show at their best, gardens and balconies in bloom. Curbside appeal is not a small thing in listing photos.\n\nSummer brings tourists who combine the holiday with a property hunt, so visibility is high. But August is its own rule: many estate agents, lawyers and banks are on holiday, and several Spanish companies close for almost the entire month. A completion scheduled across it will stall.\n\nAutumn runs hot for a different reason. Tourists head home wanting their own slice of Spain, and families push to finalise before the new school year. That competition can drive up prices, especially in popular coastal towns, which favours your sellers and squeezes your buyers.\n\nWinter is the buyer's window. Few people make a big financial decision with Christmas around the corner, so sellers are more willing to negotiate and prices can sit lower than at other points in the year.\n\nTwo local quirks: the Fallas in Valencia in March and Seville's feria in May both create noticeable spikes in interest around them.\n\nThe practical translation: sellers aim for late summer or early autumn, buyers hunt in winter, and every timeline you draft routes around August.\n\nGeneral information, not legal advice.\n\n#SpainProperty #RealEstateSpain #BuyingInSpain",
  "image_url": "/photos/sunset_village.jpg"
 },
 {
  "slug": "ag_resale_questions",
  "batch": 1,
  "day": 22,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "New build or resale, wrong question",
  "source_slug": "new_build_vs_resale_en",
  "source_slug2": "renovation_permits_en",
  "source_article": "key-questions.txt, new-build-vs-resale.txt, renovation.txt",
  "post_text": "New build or resale is the wrong question. The right one: what becomes your buyer's problem the day the property is in their name?\n\nWith a resale in Spain, hidden defects and illegal renovations transfer with the keys. Once the home is in the buyer's name, they are the buyer's issues, and they can be very expensive to resolve.\n\nWhich is why the questions matter more than the finish. How long has it been on the market. Why is the owner selling. Has it been renovated before. What do community fees, utilities and insurance actually cost. Does it need maintenance or repairs. Are there outstanding debts, which the Nota Simple will confirm anyway. What are the neighbours like.\n\nAn agent who asks these out loud, in front of the client, is doing visible due diligence. That is what foreign buyers remember and repeat.\n\nThree details that surprise people. The tax differs by type: resales carry transfer tax, new builds carry VAT instead, and IBI is based on the cadastral value, varying by region and by whether the home is a new build. Community fees can run higher on new developments with modern pools and common areas, so check the expected figure before commitment. And renovation plans need permits from the town hall for each aspect of the work, so their legal viability should be confirmed before the purchase, not after.\n\nRecommend an expert inspection before any resale offer. Standard for you, a revelation for them.\n\nGeneral information, not legal advice.\n\n#SpainProperty #BuyingInSpain #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_nie_timing",
  "batch": 1,
  "day": 23,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "NIE timing breaks timelines",
  "source_slug": "nie_application_en",
  "source_slug2": "nie_realities_en",
  "source_article": "nie-application.txt, buying-documents.txt",
  "post_text": "For a property purchase, the NIE document your buyer shows must be recently issued. The initial one is only valid three months for that purpose. Timing is everything.\n\nIf you sell to foreign buyers, this is where timelines quietly break, in both directions. Apply too late and the purchase cannot complete, because completion does not happen without a NIE. Apply too early and the document ages out of its three month window before the deal reaches the notary. Time the application to the buying window, not to convenience.\n\nThe process has friction worth warning about. The fee, around 11 euros, is paid first at a bank branch using form 790, and the stamped proof goes to the appointment, because the police station rarely takes payment. The application itself is the EX-18, submitted in Spanish in two copies; the English version is a guide, not a valid submission. Add a passport with at least a year left, two photocopies, two photos, and a translated letter explaining the reason, a purchase agreement works. Non EU citizens bring their visa or landing card.\n\nWithout an appointment, the queue starts early and many stations stop letting people in around 13:30. Brits can wait longer than EU applicants, and the alternatives are the Spanish consulate at home or a lawyer applying on the buyer's behalf.\n\nAsk about the NIE before your client books the viewing trip, and diarise the three month window against the likely completion date.\n\nGeneral information, not legal advice.\n\n#NIE #BuyingInSpain #RealEstateSpain",
  "image_url": "/photos/pool_dusk.jpg"
 },
 {
  "slug": "ag_paperwork_sequence",
  "batch": 1,
  "day": 24,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Paperwork before the search",
  "source_slug": "buying_documents_en",
  "source_article": "buying-documents.txt",
  "post_text": "The buyers who complete on time in Spain did their paperwork before the search. Here is the sequence worth handing every foreign lead.\n\nStart with identity and money. A passport or ID card with at least six months left. The NIE, applied for early, because Brits can wait longer for appointments and the consulate route takes several weeks. Proof of financial solvency ready to show: tax returns, payslips or income certificates, and recent bank statements, because Spanish banks are required to lend only to people who can demonstrably repay.\n\nThen the account. Taxes and fees in the purchase are paid through a Spanish bank account, and many utility providers only work with Spanish accounts, so this is infrastructure, not admin. A non-resident certificate is sometimes requested for banking, available from the police station or the requesting bank.\n\nThen, per property: the Nota Simple, a few euros in person and a little more online. It shows the debts associated with the property, and in Spain those transfer to the new owner, so this page is what your buyer is really buying.\n\nWhen the offer lands, the sequence runs: offer contract with a reserve fee of roughly 1,000 to 2,000 euros, refundable if the sale falls through, then the arras draft a few days before signing, with 10 percent due at signature.\n\nTurn this into a one page checklist and send it with your first reply to every foreign enquiry.\n\nGeneral information, not legal advice.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_partner_handover_service",
  "batch": 1,
  "day": 25,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Handover as a service",
  "source_slug": "bueno_facts",
  "post_text": "What if after-sales was something you could hand a client, instead of something that happens to you?\n\nMost agents treat the period after completion as weather. The calls come, you answer them, that is the job.\n\nThere is another way to frame it: the handover itself is a service. At the keys, alongside the manuals and the contact list, you introduce the client to the platform that will run their Spanish admin. An account, property tools, energy switching, the Modelo 210 filing, insurance, and support in their own language.\n\nThat is what Bueno is built to be. For the client, the scary part of owning abroad, the paperwork in a language they do not read, has an owner from day one. For you, the introduction becomes part of your offer. You are not leaving them after completion, you are handing them to specialists, and that is one more reason to choose you over the agency that just says goodbye at the notary.\n\nCurious what that handover could look like in your agency? My inbox is open.\n\n#RealEstateSpain #Proptech #SpainProperty",
  "image_url": "/photos/marina.jpg"
 },
 {
  "slug": "ag_unregistered_extensions",
  "batch": 1,
  "day": 26,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Extensions not on the deeds",
  "source_slug": "extension_deeds_en",
  "source_article": "extension-deeds.txt",
  "post_text": "That pool the seller added without paperwork? Notaries and buyers will demand it on the deeds, and the risk scale ends at demolition. Check at listing, not at completion.\n\nThe definition is broader than sellers think. Pools, extra floors, bigger rooms and an enclosed porch all count as extensions. Structural work needs the Obra Mayor licence. Even non structural jobs, painting, retiling, replacing windows in the same size and position, need the Obra Menor.\n\nThe proper route runs like this: a licensed technical architect drafts the plans and project documentation, the file goes to the town hall with proof of ownership, ID and NIE, and processing takes anywhere from a few weeks to several months. If the property shares communal spaces, the neighbours must approve, and the community's certificate is signed before a notary. Budget the ICIO tax at 2 to 5 percent of construction cost plus a smaller urban development fee. When the work finishes, the architect issues the Certificado Final de Obra and the extension is declared before a notary into the land registry.\n\nFor work done without a licence, the antiquity certificate can legalise retrospectively, with a catch worth memorising: extensions completed after August 2014 must be 15 years old, versus 4 years for earlier ones, and an architect confirms the age on site.\n\nWalk every new listing against its deeds, and start sellers legalising the day you take the mandate.\n\nGeneral information, not legal advice.\n\n#SpainProperty #SellingInSpain #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_rental_registration_2025",
  "batch": 1,
  "day": 27,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The 2025 rental registration number",
  "source_slug": "rental_rule_changes_en",
  "source_article": "rental-rule-changes.txt",
  "post_text": "Every rental advert in Spain now points to a registration number, and the platforms themselves must check it. The responsibility stopped being only the landlord's.\n\nIf you or your clients market rentals, this system is the new baseline.\n\nThe scheme, rolling out from January 2025 with a voluntary phase first: every property advertised for tourist or short term rental needs its own identification number from a single national register, displayed on the advert. Platforms are required to ensure listings carry it. Short term has its own definition too, more than a month and less than a year, so the register captures far more than holiday flats.\n\nRegistration runs through the central electronic office of the Colegio de Registradores. It asks for proof of ownership and proof of compliance with local and regional rules, and the register can certify whether the residents' association allows tourist rental. A building that voted to ban tourist lets means no code, before any other paperwork starts.\n\nThe number lasts 12 months. Renewal means listing the leases from the past year and, for short lets, a declaracion responsable justifying why they were short term: work, an academic year, medical treatment.\n\nContext worth having: various sources suggest up to 90 percent of properties that should hold a tourist licence do not, which is exactly what this register exists to surface.\n\nTwo habits to build now: check the community statutes before promising rental income, and put the renewal date in the calendar.\n\nGeneral information, not legal advice.\n\n#HolidayRental #SpainProperty #RealEstateSpain",
  "image_url": "/photos/cove_house.jpg"
 },
 {
  "slug": "ag_brexit_briefing",
  "batch": 1,
  "day": 28,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "Brexit answers for UK buyers",
  "source_slug": "brexit_buying_en",
  "source_slug2": "buyer_visas_en",
  "source_article": "brexit-impact.txt, buyer-visas.txt",
  "post_text": "Brexit did not change the price of a Spanish home by one euro. Your UK buyers still ask. Here are the answers, with the numbers attached.\n\nWhat stayed the same: the legal right to buy never depended on nationality, and the purchase costs, tax, notary and registration fees are identical for UK and EU buyers. Say it clearly, because plenty of Brits assume the door half closed.\n\nWhat changed sits downstream, in the owning. Non resident income tax on rental income rose from 19 to 24 percent for Brits, and rental expenses can no longer be deducted first, though tax paid in Spain can be offset against UK tax. If the pitch involves yield, model the 24.\n\nTime is capped at 90 days in any 180 without a residence permit. For buyers who want more, two visas do the heavy lifting. The non lucrative visa asks for roughly 28,000 euros a year in financial means plus around 600 euros a month per family member, renewed after one year and then every two, with no working in Spain. The digital nomad visa suits remote workers earning around 2,500 euros a month, mostly from outside Spain. The Golden Visa is closed to new applicants, though existing holders can renew.\n\nTwo frictions to schedule around: mortgages for UK nationals involve more paperwork and can take longer, and NIE appointments can be slower for Brits.\n\nTurn these five points into your standard UK buyer briefing.\n\nGeneral information, not legal advice.\n\n#BuyingInSpain #SpainProperty #RealEstateSpain",
  "image_url": null
 },
 {
  "slug": "ag_modelo210_answer",
  "batch": 1,
  "day": 29,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "The Modelo 210 answer on the spot",
  "source_slug": "modelo210_scenarios_en",
  "source_slug2": "modelo210_en",
  "source_article": "non-resident-property-tax.txt, irnr.txt",
  "post_text": "What will this home cost me in tax each year? The agent who can sketch the Modelo 210 answer on the spot earns a foreign buyer's trust instantly.\n\nEvery non resident owner files it, even when the property earns nothing. The answer is small enough to memorise.\n\nThe formula: cadastral value times 2 percent, or 1.1 percent where the municipality has had a general cadastral revision in the previous 10 tax years, times 19 percent for EU and EEA residents or 24 percent for everyone else, times days owned over 365.\n\nThe numbers calm people down. A UK owner with a cadastral value of 45,986 euros pays around 220 euros for a full year.\n\nThe scenarios worth carrying. Buy mid year without renting: the first return is due the following year, paid by year end, covering only the days of ownership. Sell: the owner files for the days up to the sale, early the next year. Rent it out and the rhythm changes: rental income is declared quarterly, by the 20th of April, July, October and January, with the annual return still covering any empty days. Booking platforms now report revenue to the Spanish tax office. And co-owners each file their own share, so two names on the deed means two returns.\n\nMiss the deadline and the fine can reach at least 50 percent of the tax owed.\n\nPull the cadastral value from the IBI bill and run the numbers with your buyer.\n\nGeneral information, not tax advice.\n\n#Modelo210 #SpanishTax #RealEstateSpain",
  "image_url": "/photos/arch_terrace.jpg"
 },
 {
  "slug": "ag_partner_99_euros",
  "batch": 1,
  "day": 30,
  "language": "en",
  "member": "",
  "audience": "agents",
  "title": "What 99 euros a year buys",
  "source_slug": "bueno_facts",
  "post_text": "What does a client actually get for 99 euros a year? A fair question. Here is the honest answer.\n\nOne annual subscription. Inside it: a Spanish IBAN account, the Bueno Account, with a Bueno Visa Card. Property management tools. Energy switching through Bueno Energy. Non resident tax filing, the Modelo 210 that catches so many owners out. Home insurance. And multilingual human support, which is the part clients end up valuing most, because it means the confusing letter in Spanish has someone to go to.\n\nWe are licensed by the Bank of Spain via SEFIDE EDE S.L.U., and we serve customers across 28 plus countries, with Norway, Sweden, Germany, the UK and France as the main markets. There is a good chance your buyers already come from one of them.\n\nFor you, the maths is simple: everything on that list is a call you no longer take, from a client who still feels looked after because of you.\n\nWant to see it before recommending it? My inbox is open.\n\n#RealEstateSpain #Proptech #SpainProperty",
  "image_url": null
 }
];
