// Attorneys stream: 15 posts, article-sourced, human voice, audience-woven, no disclaimers. Generated; do not hand-edit.
export default [
  {
    "slug": "at_arras_window",
    "batch": 1,
    "day": 1,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "The arras amendment window",
    "source_slug": "arras_contract_en",
    "post_text": "The arras draft usually lands a couple of days before signing, and that's the only window anyone on the file gets to amend it.\n\nMost buyers let it close unread. Which is a problem, because the Contrato de Arras is the real decision point of a Spanish purchase. Once both parties sign, they're legally bound. A buyer who pulls out loses the 10 percent deposit. A seller who pulls out pays the buyer double it. Everything after that is execution.\n\nSo when the buyer on your file is foreign, the draft deserves a full pass, not a skim. Remember most agencies work from a standard contract and amend it, so the details are only as good as whoever checks them. Check the property description against the Nota Simple, address, size and layout. Fix the completion date, usually two to three months after signing, and make sure it leaves room for the mortgage and the documentation. Confirm the penalties are stated for both sides. Then get specific. Which furniture stays, which repairs the seller pays for, whether appliances are included, whether water and electricity will be switched on.\n\nIf it isn't written in the arras, it was never agreed.\n\nTwo more habits worth keeping. On new builds, add completion date clauses, because that's where delays live. And route the 10 percent to a safeguarded account at a financial institution rather than directly to the owners, common as the direct route is.\n\nOne earlier number worth knowing too. If the offer went through an agency, the client's likely already transferred around 2,000 euros to secure it, refundable if the offer's declined, or set against agency fees of 3 to 5 percent of the price. Worth checking early who's actually paying those fees, because in Spain it can be either side.\n\nMy ask of clients is simple. Forward the arras draft the day it arrives, not the night before signing.\n\n#LegalSpain #SpainProperty #BuyingInSpain",
    "image_url": "/photos/cove_house.jpg",
    "source_article": "property-contracts.txt"
  },
  {
    "slug": "at_choice_of_law",
    "batch": 1,
    "day": 2,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "The choice-of-law clause",
    "source_slug": "inheritance_foreign_law_en",
    "source_slug2": "spanish_wills_en",
    "post_text": "There's a single clause that decides whether Spanish forced heirship swallows your client's entire estate, and most wills written back home don't contain it.\n\nThe clause is a choice of law. Under the European Inheritance Regulation of 2012, anyone who dies after 17 August 2015 can choose the inheritance law of their home country over the law of their country of residence. The condition's strict, though. The choice must be stated clearly in a Spanish or international will.\n\nStay silent, and a client resident in Spain gets Spanish law across the entire estate, including the Law of Obligatory Heirs. That regime sends 50 percent of the joint property to the spouse, splits one third of the rest equally between the children, divides a second third among the children as the testator chooses, and leaves only the final third free.\n\nPut plainly, without the clause your client can leave no more than a third to anyone who isn't a spouse or child, and every child takes a share whether the client wants that or not. Spain doesn't even require a will, precisely because forced heirship fills the silence.\n\nIt reaches non-residents too. A client with a holiday home in Spain still needs their will to state which country's law governs, or the default can catch the Spanish assets.\n\nThe pattern I keep seeing is a will that predates the Spanish purchase, names no governing law, and hasn't been read since completion.\n\nThat's what makes this one of the cheapest pieces of preventive work in cross-border practice. At the next completion, ask when the client's will was last reviewed and whether it names a governing law.\n\n#LegalSpain #InheritancePlanning #SpainProperty",
    "image_url": null,
    "source_article": "estate-planning.txt"
  },
  {
    "slug": "at_nonresident_seller",
    "batch": 1,
    "day": 3,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Two tax jobs on your buyer",
    "source_slug": "plusvalia_en",
    "post_text": "Your buyer inherits two of the seller's tax jobs the moment that seller is a non-resident. Better they hear it from you than at the notary's table.\n\nThe first job is the withholding. The buyer holds back 3 percent of the purchase price and pays it to the tax authorities within one month of the sale. It isn't extra tax, it's a holding against the seller's capital gains bill, which runs at 19 percent of the profit for EU and EEA residents and 24 percent for non-EU sellers. If the final liability comes in under the 3 percent, the seller claims a partial or full rebate within the year. But the withholding duty sits with the buyer either way, even if the seller didn't make a profit at all.\n\nThe second is plusvalia, the municipal tax on the increase in urban land value. The council's logic is that the land under the property grew more valuable as public investment rose around it, transport, hospitals, supermarkets, parks. It's usually the seller's tax. With a non-resident seller it falls to the buyer, who then has 30 days to pay the local council before a fine lands.\n\nHow much? That turns on local council rates and how long the seller owned the property, up to a 20 year cap, plus the property's location and the size of the urban area. And there are outs. If the land value genuinely fell, if the infrastructure hasn't grown since the purchase, or if the sale is at a loss, there's an exemption.\n\nWorth filing away for the same client's estate planning too. Plusvalia also triggers on inheritance and donation, and there it's the receiver who pays.\n\nMy habit on these files is boring but useful. Put a written allocation of both payments into every completion with a non-resident seller.\n\n#LegalSpain #SpanishTax #SpainProperty",
    "image_url": "/photos/arch_terrace.jpg",
    "source_article": "plusvalia.txt"
  },
  {
    "slug": "at_bank_guarantee",
    "batch": 1,
    "day": 4,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Law 57/68 bank guarantees",
    "source_slug": "bank_guarantee_en",
    "post_text": "Off plan, your client can hand over up to 80 percent of the price in instalments before the escritura is ever signed, and one instrument stands between that money and a building that never happens.\n\nSome developers quietly hope nobody asks for it.\n\nThe risk is exactly what it sounds like. The building company closes, disappears, or the construction itself goes wrong, and the staged payments went out against a home that only ever existed as a showroom and digital renders. Before 1968, Spanish law gave buyers no protection here at all, and the stories from that era are grim.\n\nSince Law 57/68, any developer taking a deposit and staged payments towards construction has two obligations. They must open a specific bank account for those payments, not a personal account, not one previously held, and the money in it can only be used for the construction of that property. And they must provide a guarantee to refund every amount paid, plus interest, if the property isn't started or isn't finished by the agreed completion date.\n\nThat guarantee can't carry an expiry date. It stays valid until the property is fully finished and deemed safe to live in.\n\nNow the asymmetry worth explaining when the buyer on your file goes off plan. The guarantee comes at no cost to the buyer, and it can be expensive for the developer. Which is exactly why some try to work around it, occasionally by offering better conditions instead. My reading of that trade hasn't changed. A discount on a home that never gets built isn't a discount.\n\nSo before the first instalment moves, verify the guarantee exists, covers refund plus interest, and has no expiry date. If the developer resists, you've got your answer.\n\n#LegalSpain #SpainProperty #OffPlan",
    "image_url": null,
    "source_article": "bank-guarantees.txt"
  },
  {
    "slug": "at_partner_unbillable_email",
    "batch": 1,
    "day": 5,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "The unbillable email",
    "source_slug": "bueno_facts",
    "post_text": "A letter from the town hall the client can't read. A utility contract that won't switch over. A question about whether the non-resident tax was ever filed. You know these emails.\n\nThey land in property law inboxes long after completion, and not one of them is about the law. Most of them are barely billable either. But the client has exactly one professional they trust in Spain, so they arrive in yours. Answering properly takes hours nobody pays for, and leaving the client stranded damages a relationship you spent months building. There isn't a good option, which is why the emails keep getting answered.\n\nThat's the gap we built Bueno for. It's one platform for foreign property owners in Spain, covering a Spanish IBAN account and card, property admin tools, energy switching, Modelo 210 filing, home insurance, and human support in the client's own language. One subscription, 99 euros a year.\n\nThe client stays cared for after completion. You keep the relationship and the referrals. And your hours go back to actual legal work.\n\nIf those emails sound familiar, I'd genuinely like to compare notes.\n\n#LegalSpain #SpainProperty #PropertyLaw",
    "image_url": "/photos/couple_beach.jpg"
  },
  {
    "slug": "at_tourist_ban_ruling",
    "batch": 1,
    "day": 6,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "The 3/5 tourist-let ruling",
    "source_slug": "community_rental_ban_en",
    "post_text": "It took a 48 to 3 vote in Marbella to settle how tourist rentals end in Spanish community buildings. If you advise landlord owners, the thresholds aren't fuzzy anymore.\n\nSome background first. In 2019, Article 17.12 of the Horizontal Property Law was amended by royal decree, giving owner communities the power to condition and limit tourist rentals in their building. Judges then split on whether limiting included banning outright, and the law never fixed a voting threshold, so nobody could say whether a majority or unanimity was needed.\n\nThe Supreme Court has now answered both questions. Prohibition is a form of limitation. And three fifths of the vote, 60 percent, is enough. No unanimity required.\n\nThe case behind it went like this. A Marbella community voted 48 to 3 to ban tourist flats after complaints of noise, illegal substances and damage to common spaces. Two companies owning six tourist apartments in the building took it to court and lost.\n\nThe court's reasoning is worth keeping for the file. It looked past the bare legality of renting to the broader context and its social implications, and held that an individual owner's right to rent out property has to be balanced against the collective interest of the community.\n\nExisting operators aren't defenceless, though. The ruling isn't retroactive, so the problems must still be ongoing and affecting residents. And a ban must be properly justified and implemented under the Horizontal Property Law's requirements, not simply voted through.\n\nFor any client buying with rental plans, the community's rules and voting arithmetic are now core due diligence. Check them before the arras on every buy-to-let file.\n\n#LegalSpain #HolidayRental #SpainProperty",
    "image_url": null,
    "source_article": "supreme-court-tourist-ban.txt"
  },
  {
    "slug": "at_succession_tax",
    "batch": 1,
    "day": 7,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Succession tax's six-month lock",
    "source_slug": "inheritance_tax_en",
    "post_text": "In Spain the heirs pay the tax before they ever touch the inheritance, and the estate stays locked until the bill's settled. The clock gives them six months.\n\nThat ordering surprises the foreign families on your files every time. Succession tax here falls on the beneficiary, not the estate, and the estate can't be released until the beneficiary has paid.\n\nRates are progressive, from 7.65 percent to 36.5 percent, and they vary sharply by region. Andalucia sits among the lowest in the country. The relationship between the deceased and the beneficiary, and the value inherited, shape the final figure, so the same estate can produce very different bills in different regions.\n\nThe deadline's 6 months, though an extension is possible. Miss it and 5 percent is added every 3 months, up to a maximum of 20 percent on top.\n\nAnd the scope runs wider than clients expect. Residents and non-residents alike pay on assets located in Spain. Assets outside Spain escape Spanish inheritance tax, with one exception worth flagging to families. They're caught if the beneficiary is a Spanish resident.\n\nFor foreign families, those six months have to cover two legal systems, paperwork in a language they don't read, and grief. The time disappears fast.\n\nSo when a client with Spanish property dies, open the file in week one, not month four.\n\n#LegalSpain #InheritanceTax #SpanishTax",
    "image_url": "/photos/poolside.jpg",
    "source_article": "estate-planning.txt"
  },
  {
    "slug": "at_notary_role",
    "batch": 1,
    "day": 8,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "The notary is not their lawyer",
    "source_slug": "escritura_notary_en",
    "source_slug2": "land_registry_en",
    "post_text": "Foreign buyers walk into the escritura convinced they've already got a lawyer in the room. They don't, and someone has to tell them.\n\nThe notary's impartial by design. At the escritura publica they prepare and oversee the deed, read it out to buyer and seller together, and confirm both fully understand it before anyone signs. If the buyer's Spanish is weak, the notary may require a translator or a Spanish speaking legal adviser.\n\nThe mortgage track runs on its own sequence. The FEIN, which lays out the loan's terms and conditions, must be signed at least 10 days before the mortgage deed, and those 10 days are a legal requirement. The buyer also meets the notary at least 24 hours before signing day, to go through the mortgage conditions first.\n\nNo mortgage, no FEIN. A cash buyer signs a Contrato de Compraventa instead, drawn up by a legal representative or sometimes the estate agency, stating the exact price and confirming neither party signs without understanding what they've agreed to.\n\nWhat the notary never does is represent one side. They advise both parties impartially and confirm the sale is legal. Clients raised in other systems mistake that neutrality for protection, and the gap between the two is exactly where an adviser belongs.\n\nSigning isn't the finish line either. The escritura is when the remaining funds move and the keys change hands, but registration at the Registro de la Propiedad is a separate step afterwards, and someone has to own it. In practice that's usually the lawyer or the agent, often along with setting up the utility supplies.\n\nSo explain the notary's role at the first meeting, and diarise the FEIN clock and the registration before signing day.\n\n#LegalSpain #SpainProperty #BuyingInSpain",
    "image_url": null,
    "source_article": "buying-10-steps.txt, property-contracts.txt"
  },
  {
    "slug": "at_rural_diligence",
    "batch": 1,
    "day": 9,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Rural registry vs reality",
    "source_slug": "rural_property_en",
    "post_text": "Your client's already in love with the finca. Meanwhile the registries say one thing and the ground says another, which is why rural files fail checks that urban files pass.\n\nTitle comes first. If the Title Deed doesn't exist, or it's outdated or inaccurate, the purchase shouldn't proceed. The vendor updates the missing details at the Land Registry, at their own expense, and you check the registry before anything moves.\n\nThen reconcile paper with terrain. The Land Registry and the Cadastral Registry frequently disagree with real life on plot size, property description and boundaries, and any discrepancy brings legal and financial consequences. Confirm too that the vendor's actually the registered owner. Sellers aren't always lying when the paperwork's wrong, sometimes they simply don't know, but the consequences land on your client either way. A Nota Simple settles it.\n\nThe build itself deserves suspicion. Some owners register a casa de aperos, a shed, to get around planning restrictions, then put up a villa. An independent surveyor can confirm whether the Town Hall granted planning permission, and without it, the advice is to walk away rather than inherit a legal battle. Pre 1956 constructions are usually legal, since no building licence was required, but often can't be extended.\n\nThen the rural extras. Easements come with the territory here in a way urban files rarely see, right of way, right of view, the right to extract water. Utilities too. Electricity and running water are easy to spot on a viewing, but wastewater hides. Many rural properties run on their own septic tank, which costs money to empty periodically, and a renovation will likely require installing a modern replacement costing thousands.\n\nBring an independent surveyor into every rural file before the arras.\n\n#LegalSpain #RuralSpain #SpainProperty",
    "image_url": "/photos/coast_bay.jpg",
    "source_article": "rural-property.txt"
  },
  {
    "slug": "at_partner_after_closing",
    "batch": 1,
    "day": 10,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "After the file closes",
    "source_slug": "bueno_facts",
    "post_text": "The deed gets signed, the file closes, and your foreign client's life in Spain actually begins. That's usually the exact moment their support ends.\n\nBecause the questions don't stop after completion. They just change. An IBI bill arriving at a mailbox nobody checks. A utility contract in a language the client can't read. Insurance, tax filings, letters from the town hall.\n\nSo the client turns to the one professional they trust in Spain, their lawyer. And you answer, because leaving them stranded isn't who you are. But it isn't legal work, and nobody's paying for those hours.\n\nThat ongoing after-sales care is what Bueno does. One platform, one annual subscription of 99 euros, covering a Spanish IBAN account, property tools, energy switching, Modelo 210 filing, home insurance, and human support in the client's own language. Our customers span more than 28 countries, with Norway, Sweden, Germany, the UK and France the biggest, which tends to match a Spanish practice's foreign client base rather well.\n\nYou hand over the admin. You keep the client. The relationship survives the part of ownership nobody bills for.\n\nIf you'd like to see how the handover works, my messages are open.\n\n#LegalSpain #SpainProperty #ClientCare",
    "image_url": null
  },
  {
    "slug": "at_gift_tax",
    "batch": 1,
    "day": 11,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Gift tax's 30-day clock",
    "source_slug": "gift_tax_en",
    "post_text": "An inheritance gives the beneficiary six months and maybe an extension. A gift gives the recipient 30 days, and clients funding a child's purchase rarely know there's a difference.\n\nGift tax in Spain falls on the person receiving, not the person giving. So when your client plans to pass money or an asset to family, it's the family member who faces the bill, and payment's due within 30 days of the gift being made.\n\nSet that against the inheritance track. There the beneficiary usually has 6 months to pay, an extension is possible, and even the penalty regime is gradual, 5 percent added every 3 months up to a maximum of 20 percent. Gifts don't get that grace. One month, and the clock starts the moment the gift is made.\n\nGeography moves the number as much as timing does. Gift tax rates vary from region to region in Spain, so an identical gift can produce a very different bill depending on where the people and assets involved sit.\n\nThe scenario I flag most often is a parent passing funds so a child can buy in Spain. The transfer happens quickly, and nobody's told the recipient that a Spanish deadline started running.\n\nTiming and region decide most of the cost here, so this isn't a conversation for after the transfer. It has to happen before. When a client mentions gifting funds for a Spanish purchase, put the 30 day clock on the table first.\n\n#LegalSpain #SpanishTax #GiftTax",
    "image_url": "/photos/golden_coast.jpg",
    "source_article": "estate-planning.txt"
  },
  {
    "slug": "at_community_debts",
    "batch": 1,
    "day": 12,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Debts that stay with the flat",
    "source_slug": "hoa_disagree_vote_en",
    "post_text": "Community fee debts in Spain don't follow the debtor. They attach to the flat, which means your buyer collects them with the keys.\n\nThat's how the community regime works. Debts of community contributions belong to the property, not the owner, so a seller's arrears become your client's liability the moment title passes.\n\nThe protection's cheap and early. Get the Nota Simple before the offer and the arras are signed. Any outstanding fees it reveals can be deducted from the selling price and settled before the deeds are exchanged. Skip the check, and your client may simply be liable.\n\nWorth reading in the same pass is the voting arithmetic your client's buying into. Most decisions pass by majority, votes are weighted by property size, and proxy voting is allowed on important matters, so one person holding several flats carries a bigger share of every decision. And if a client later wants a resolution overturned, there are only two grounds to have a vote revoked. It's contrary to the law, or it's detrimental to the community. Preference changes nothing.\n\nWhile you're in there, give the client the fee picture too. The bill runs from around 100 euros a quarter in modest communities to over 1,000 in high-end developments, set by the services provided and the client's share of the community. And if the plan is to rent the flat out, the fees stay the owner's obligation, never the tenant's.\n\nNon-payment doesn't end quietly either. Late payment fees and interest, then a court demand with the legal costs falling on the debtor, and ultimately forcible sale of the property at auction.\n\nMake the Nota Simple the first document on every apartment file, before the arras.\n\n#LegalSpain #SpainProperty #CommunityFees",
    "image_url": null,
    "source_article": "hoa-rules.txt, community-fees.txt"
  },
  {
    "slug": "at_spanish_wills",
    "batch": 1,
    "day": 13,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Spain's default heirship ladder",
    "source_slug": "spanish_wills_en",
    "post_text": "No will, and Spanish law walks your client's estate down a fixed ladder. Children, then parents, then spouse, then wider relatives, then the state itself.\n\nSpain runs on forced heirship, the Law of Obligatory Heirs, Legitima, and the mechanics are precise. 50 percent of the joint property goes to the spouse. The rest of the estate divides into thirds. One third's split equally between the children, a second third's shared among the children as the testator chooses, and only the final third can be left freely to anyone at all.\n\nDie without a will and the strict order above applies instead, children first, natural and adopted alike, then the parents of the deceased, then the surviving spouse, then relatives like nieces and nephews. Where no rightful relatives exist, the estate passes to the state.\n\nNow notice who's missing from both routes. Stepchildren, unmarried partners, friends. None of them inherit unless a will names them, and under Spanish law even then only from that free third. For remarried clients, that gap's enormous.\n\nSome autonomous regions apply their own rules on top, so the map shifts with the address.\n\nForeign owners tend to assume their home arrangements travel with them. They don't, unless a Spanish will, or clear wishes stated in an international one, says so.\n\nWhich leaves one question worth asking every foreign owner client. Does your family fit Spain's default order? Most don't.\n\n#LegalSpain #InheritancePlanning #SpainProperty",
    "image_url": "/photos/terrace_sunset.jpg",
    "source_article": "estate-planning.txt"
  },
  {
    "slug": "at_extension_legalisation",
    "batch": 1,
    "day": 14,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "Legalise extensions before sale",
    "source_slug": "extension_deeds_en",
    "post_text": "That pool, extra floor or enclosed porch is legally an extension, and if it never reached the deeds it'll surface at the worst possible moment for your client. The sale.\n\nThe proper sequence isn't complicated, just slow. Structural work, new rooms or floors, a garage, covering a porch, basement excavation, all of it needs the Obra Mayor licence. Even non-structural jobs, painting, replacing tiles, swapping windows in the same position and size, need the Obra Menor. A technical architect drafts the plans, the project's filed at the town hall, and where communal spaces are shared the neighbours must authorise it, with the community's certificate signed before a notary.\n\nThe town hall file itself is a checklist worth handing over early. Proof of the architect's registration, the project proposal and reports, proof of tax and fee payment, the title deed, ID and the NIE.\n\nOn cost and timing, expect ICIO tax of 2 to 5 percent of construction cost, plus a smaller urban development licensing fee, and processing that runs from a few weeks to several months.\n\nWhen the work finishes, the architect issues the Certificado Final de Obra, and the extension's declared before a notary and written into the land registry.\n\nBuilt without a licence? The antiquity certificate can legalise it retrospectively, with an architect confirming the age on site. Works completed after August 2014 must be 15 years old, against 4 years for earlier ones, and regions vary. And in community properties there's a second catch. Even for work finished years ago, the neighbours' consent is still needed before the deeds can be updated.\n\nUnregistered extensions stall sales, because notaries and buyers will ask, and the alternative is infraction risk and demolition. So walk selling clients through their deeds before they list. Legalise first, market second.\n\n#LegalSpain #SpainProperty #SpanishHomeOwners",
    "image_url": null,
    "source_article": "extension-deeds.txt"
  },
  {
    "slug": "at_partner_referral_logic",
    "batch": 1,
    "day": 15,
    "language": "en",
    "member": "",
    "audience": "attorneys",
    "title": "The referral logic of care",
    "source_slug": "bueno_facts",
    "post_text": "Where does a foreign client's next referral come from? Rarely from the contract you drafted. Almost always from how looked after they felt two years later.\n\nThe quiet logic of a cross-border practice runs like that. The legal work ends at completion, but the client's need for help doesn't. Account setup, utility contracts, IBI, the Modelo 210, letters in Spanish they can't read.\n\nAnd if that stretch goes badly, the client doesn't blame the utility company. They just stop feeling looked after, and the recommendations quietly stop with it.\n\nBueno exists for exactly that stretch. We take over the ongoing admin in the client's own language, on one platform, for 99 euros a year, licensed by the Bank of Spain via SEFIDE EDE S.L.U.\n\nThe division of labour stays clean. You remain the legal name they trust in Spain. We handle the small stuff between transactions. And a client who feels cared for is far more likely to send the next buyer back to you.\n\nNothing dramatic. Just after-sales care, done properly.\n\nIf that division of labour sounds useful for your clients, I'm easy to find.\n\n#LegalSpain #SpainProperty #ReferralNetwork",
    "image_url": "/photos/sunset_village.jpg"
  }
];
